-- chunkname: @scripts/settings/environmental_hazards.lua

EnvironmentalHazards = {
	spike_trap = {
		enemy = {
			can_damage = true,
			can_stagger = true,
			damage_profile = "spike_trap",
			difficulty_power_level = {
				500,
				500,
				500,
				500,
				500,
				500,
				500,
				500,
			},
		},
		player = {
			action_data = {
				damage_type = "cutting",
				player_push_speed = 1,
			},
			difficulty_damage = {
				cataclysm = 30,
				cataclysm_2 = 40,
				cataclysm_3 = 50,
				easy = 7,
				hard = 15,
				harder = 18,
				hardest = 23,
				normal = 12,
			},
		},
	},
	thorn_trap = {
		enemy = {
			can_damage = true,
			can_stagger = false,
			damage_profile = "spike_trap",
			difficulty_power_level = {
				500,
				500,
				500,
				500,
				500,
				500,
				500,
				500,
			},
		},
		player = {
			action_data = {
				damage_type = "cutting",
				player_push_speed = 1,
			},
			difficulty_damage = {
				cataclysm = 8,
				cataclysm_2 = 9,
				cataclysm_3 = 10,
				easy = 3,
				hard = 5,
				harder = 6,
				hardest = 7,
				normal = 4,
			},
		},
	},
	fire = {
		enemy = {
			can_damage = true,
			can_stagger = false,
			damage_profile = "environment_fire",
			difficulty_power_level = {
				500,
				500,
				500,
				500,
				500,
				500,
				500,
				500,
			},
		},
		player = {
			action_data = {
				damage_type = "burn",
				player_push_speed = 0,
			},
			difficulty_damage = {
				cataclysm = 8,
				cataclysm_2 = 9,
				cataclysm_3 = 10,
				easy = 3,
				hard = 5,
				harder = 6,
				hardest = 7,
				normal = 4,
			},
		},
	},
	payload = {
		enemy = {
			can_damage = false,
			can_stagger = true,
			damage_profile = "payload_wagon",
			difficulty_power_level = {
				200,
				200,
				300,
				400,
				600,
				700,
				700,
				700,
				300,
			},
		},
	},
	sled = {
		enemy = {
			can_damage = true,
			can_stagger = true,
			damage_profile = "sled",
			difficulty_power_level = {
				300,
				300,
				400,
				500,
				600,
				700,
				800,
				900,
			},
		},
	},
	trail_cog = {
		enemy = {
			can_damage = true,
			can_stagger = true,
			damage_profile = "trail_cog",
			difficulty_power_level = {
				200,
				200,
				300,
				400,
				600,
				700,
				700,
				700,
			},
		},
	},
	sawblade = {
		enemy = {
			can_damage = true,
			can_stagger = true,
			damage_profile = "sawblade",
			difficulty_power_level = {
				200,
				200,
				300,
				400,
				600,
				700,
				700,
				700,
			},
			difficulty_damage = {
				60,
				90,
				100,
				125,
				150,
				190,
				220,
				250,
			},
		},
	},
	sawblade_instant_kill = {
		enemy = {
			can_damage = true,
			can_stagger = true,
			damage_profile = "sawblade_instant_kill",
			difficulty_power_level = {
				1000,
				1000,
				300,
				400,
				600,
				700,
				1000,
				1500,
			},
		},
	},
}
