-- chunkname: @scripts/settings/slot_templates.lua

SlotTypeSettings = {
	normal = {
		count = 9,
		debug_color = "lime",
		dialogue_surrounded_count = 4,
		distance = 1.85,
		priority = 2,
		queue_distance = 3,
		radius = 0.5,
		use_wait_slots = true,
	},
	medium = {
		count = 8,
		debug_color = "yellow",
		dialogue_surrounded_count = 3,
		distance = 2.2,
		priority = 1.5,
		queue_distance = 3.5,
		radius = 1,
		use_wait_slots = true,
	},
	large = {
		count = 4,
		debug_color = "red",
		dialogue_surrounded_count = 2,
		distance = 2.25,
		priority = 1,
		queue_distance = 3.5,
		radius = 1.5,
		use_wait_slots = false,
	},
}

local dummy_data = {
	disable_slot_search = true,
}

SlotTemplates = {
	normal = {
		skaven_horde = {
			abandon_slot_when_blocked = false,
			abandon_slot_when_blocked_time = 0.3,
			abandon_slot_when_staggered = false,
			abandon_slot_when_staggered_time = 0.3,
			avoid_slots_behind_overwhelmed_target = true,
			min_wait_queue_distance = 2,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_roamer = {
			abandon_slot_when_blocked = false,
			min_wait_queue_distance = 2,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		chaos_horde = {
			abandon_slot_when_blocked = false,
			abandon_slot_when_blocked_time = 0.3,
			abandon_slot_when_staggered = true,
			abandon_slot_when_staggered_time = 0.3,
			avoid_slots_behind_overwhelmed_target = true,
			min_wait_queue_distance = 3.5,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		chaos_roamer = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "medium",
		},
		chaos_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "medium",
		},
		chaos_large_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "large",
		},
		boss = dummy_data,
	},
	hard = {
		skaven_horde = {
			abandon_slot_when_blocked = false,
			abandon_slot_when_blocked_time = 0.3,
			abandon_slot_when_staggered = false,
			abandon_slot_when_staggered_time = 0.3,
			avoid_slots_behind_overwhelmed_target = true,
			min_wait_queue_distance = 2,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_roamer = {
			abandon_slot_when_blocked = false,
			min_wait_queue_distance = 2,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		chaos_horde = {
			abandon_slot_when_blocked = false,
			abandon_slot_when_blocked_time = 0.3,
			abandon_slot_when_staggered = true,
			abandon_slot_when_staggered_time = 0.3,
			avoid_slots_behind_overwhelmed_target = true,
			min_wait_queue_distance = 3.5,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		chaos_roamer = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "medium",
		},
		chaos_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "medium",
		},
		chaos_large_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "large",
		},
		boss = dummy_data,
	},
	harder = {
		skaven_horde = {
			abandon_slot_when_blocked = false,
			abandon_slot_when_blocked_time = 0.3,
			abandon_slot_when_staggered = false,
			abandon_slot_when_staggered_time = 0.3,
			avoid_slots_behind_overwhelmed_target = true,
			min_wait_queue_distance = 2,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_roamer = {
			abandon_slot_when_blocked = false,
			min_wait_queue_distance = 2,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		chaos_horde = {
			abandon_slot_when_blocked = false,
			abandon_slot_when_blocked_time = 0.3,
			abandon_slot_when_staggered = true,
			abandon_slot_when_staggered_time = 0.3,
			avoid_slots_behind_overwhelmed_target = true,
			min_wait_queue_distance = 3.5,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		chaos_roamer = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "medium",
		},
		chaos_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "medium",
		},
		chaos_large_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "large",
		},
		boss = dummy_data,
	},
	hardest = {
		skaven_horde = {
			abandon_slot_when_blocked = false,
			abandon_slot_when_blocked_time = 0.3,
			abandon_slot_when_staggered = false,
			abandon_slot_when_staggered_time = 0.3,
			avoid_slots_behind_overwhelmed_target = true,
			min_wait_queue_distance = 2,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_roamer = {
			abandon_slot_when_blocked = false,
			min_wait_queue_distance = 2,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		chaos_horde = {
			abandon_slot_when_blocked = false,
			abandon_slot_when_blocked_time = 0.3,
			abandon_slot_when_staggered = true,
			abandon_slot_when_staggered_time = 0.3,
			avoid_slots_behind_overwhelmed_target = true,
			min_wait_queue_distance = 3.5,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		chaos_roamer = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "medium",
		},
		chaos_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "medium",
		},
		chaos_large_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "large",
		},
		boss = dummy_data,
	},
	cataclysm = {
		skaven_horde = {
			abandon_slot_when_blocked = false,
			abandon_slot_when_blocked_time = 0.3,
			abandon_slot_when_staggered = false,
			abandon_slot_when_staggered_time = 0.3,
			avoid_slots_behind_overwhelmed_target = true,
			min_wait_queue_distance = 2,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_roamer = {
			abandon_slot_when_blocked = false,
			min_wait_queue_distance = 2,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_boss = dummy_data,
		chaos_horde = {
			abandon_slot_when_blocked = false,
			abandon_slot_when_blocked_time = 0.3,
			abandon_slot_when_staggered = true,
			abandon_slot_when_staggered_time = 0.3,
			avoid_slots_behind_overwhelmed_target = true,
			min_wait_queue_distance = 3.5,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		chaos_roamer = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "medium",
		},
		chaos_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "medium",
		},
		chaos_large_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "large",
		},
		boss = dummy_data,
	},
	cataclysm_2 = {
		skaven_horde = {
			abandon_slot_when_blocked = false,
			abandon_slot_when_blocked_time = 0.3,
			abandon_slot_when_staggered = false,
			abandon_slot_when_staggered_time = 0.3,
			avoid_slots_behind_overwhelmed_target = true,
			min_wait_queue_distance = 2,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_roamer = {
			abandon_slot_when_blocked = false,
			min_wait_queue_distance = 2,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		chaos_horde = {
			abandon_slot_when_blocked = false,
			abandon_slot_when_blocked_time = 0.3,
			abandon_slot_when_staggered = true,
			abandon_slot_when_staggered_time = 0.3,
			avoid_slots_behind_overwhelmed_target = true,
			min_wait_queue_distance = 3.5,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		chaos_roamer = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "medium",
		},
		chaos_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "medium",
		},
		chaos_large_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "large",
		},
		boss = dummy_data,
	},
	cataclysm_3 = {
		skaven_horde = {
			abandon_slot_when_blocked = false,
			abandon_slot_when_blocked_time = 0.3,
			abandon_slot_when_staggered = false,
			abandon_slot_when_staggered_time = 0.3,
			avoid_slots_behind_overwhelmed_target = true,
			min_wait_queue_distance = 2,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_roamer = {
			abandon_slot_when_blocked = false,
			min_wait_queue_distance = 2,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		chaos_horde = {
			abandon_slot_when_blocked = false,
			abandon_slot_when_blocked_time = 0.3,
			abandon_slot_when_staggered = true,
			abandon_slot_when_staggered_time = 0.3,
			avoid_slots_behind_overwhelmed_target = true,
			min_wait_queue_distance = 3.5,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		chaos_roamer = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "medium",
		},
		chaos_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "medium",
		},
		chaos_large_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "large",
		},
		boss = dummy_data,
	},
	versus_base = {
		skaven_horde = {
			abandon_slot_when_blocked = false,
			abandon_slot_when_blocked_time = 0.3,
			abandon_slot_when_staggered = false,
			abandon_slot_when_staggered_time = 0.3,
			avoid_slots_behind_overwhelmed_target = true,
			min_wait_queue_distance = 2,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_roamer = {
			abandon_slot_when_blocked = false,
			min_wait_queue_distance = 2,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		skaven_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		chaos_horde = {
			abandon_slot_when_blocked = false,
			abandon_slot_when_blocked_time = 0.3,
			abandon_slot_when_staggered = true,
			abandon_slot_when_staggered_time = 0.3,
			avoid_slots_behind_overwhelmed_target = true,
			min_wait_queue_distance = 3.5,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "normal",
		},
		chaos_roamer = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			prioritize_queued_units_on_death = true,
			restricted_queue_distance = true,
			slot_type = "medium",
		},
		chaos_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "medium",
		},
		chaos_large_elite = {
			avoid_slots_behind_overwhelmed_target = false,
			min_wait_queue_distance = 3,
			restricted_queue_distance = true,
			slot_type = "large",
		},
		boss = dummy_data,
	},
}

DLCUtils.map_list("slot_templates_file_names", function (file_name)
	return table.merge_recursive(SlotTemplates, require(file_name))
end)
