-- chunkname: @scripts/settings/store_bundle_featured_settings.lua

StoreBundleFeaturedSettings = {
	{
		item_key = "five_career_bundle_0001",
		name = "five_career_bundle_0001",
		show_in_slideshow = false,
		slideshow_text = "five_career_bundle_0001_subtitle",
		slideshow_texture = "store_slideshow_bundle_five_career_bundle_0001",
		store_texture = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_five_career_bundle_0001",
		store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_five_career_bundle_0001",
	},
	{
		item_key = "fall_collection_2021_bundle",
		name = "display_name_five_career_bundle_0002",
		show_in_slideshow = false,
		slideshow_text = "five_career_bundle_0001_subtitle",
		slideshow_texture = "store_slideshow_bundle_fall_collection_2021_bundle",
		store_texture = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_fall_collection_2021_bundle",
		store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_fall_collection_2021_bundle",
	},
	{
		item_key = "huntsman_bundle_0001",
		name = "display_name_huntsman_bundle_0001",
		show_in_slideshow = true,
		slideshow_text = "description_huntsman_bundle_0001",
		slideshow_texture = "store_slideshow_bundle_huntsman_bundle_0001",
		store_texture = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_huntsman_bundle_0001",
		store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_huntsman_bundle_0001",
	},
	{
		item_key = "slayer_bundle_0001",
		name = "display_name_slayer_bundle_0001",
		show_in_slideshow = true,
		slideshow_text = "description_slayer_bundle_0001",
		slideshow_texture = "store_slideshow_bundle_slayer_bundle_0001",
		store_texture = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_slayer_bundle_0001",
		store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_slayer_bundle_0001",
	},
	{
		item_key = "maidenguard_bundle_0001",
		name = "maidenguard_bundle_01",
		show_in_slideshow = false,
		slideshow_text = "maidenguard_bundle_01_desc",
		slideshow_texture = "store_slideshow_bundle_maidenguard_bundle_0001",
		store_texture = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_maidenguard_bundle_0001",
		store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_maidenguard_bundle_0001",
	},
	{
		item_key = "zealot_bundle_0001",
		name = "zealot_bundle_01",
		show_in_slideshow = false,
		slideshow_text = "zealot_bundle_01_desc",
		slideshow_texture = "store_slideshow_bundle_zealot_bundle_0001",
		store_texture = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_zealot_bundle_0001",
		store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_zealot_bundle_0001",
	},
	{
		item_key = "adept_bundle_0001",
		name = "adept_bundle_01",
		show_in_slideshow = false,
		slideshow_text = "adept_bundle_01_desc",
		slideshow_texture = "store_slideshow_bundle_adept_bundle_0001",
		store_texture = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_adept_bundle_0001",
		store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_adept_bundle_0001",
	},
}
