Currencies = Currencies or {}
CanWieldAllItemTemplates = CanWieldAllItemTemplates or {}
Currencies.shillings_01 = {
	description = "shilling_bag_1_description",
	rarity = "common",
	display_name = "shilling_bag_1_name",
	inventory_icon = "icon_shillings_01",
	slot_type = "chips",
	information_text = "information_text_shilling",
	item_type = "chips",
	icon = "icon_shillings_01",
	can_wield = CanWieldAllItemTemplates
}
Currencies.shillings_02 = {
	description = "shilling_bag_5_description",
	rarity = "common",
	display_name = "shilling_bag_5_name",
	inventory_icon = "icon_shillings_02",
	slot_type = "chips",
	information_text = "information_text_shilling",
	item_type = "chips",
	icon = "icon_shillings_02",
	can_wield = CanWieldAllItemTemplates
}
Currencies.shillings_03 = {
	description = "shilling_bag_10_description",
	rarity = "common",
	display_name = "shilling_bag_10_name",
	inventory_icon = "icon_shillings_03",
	slot_type = "chips",
	information_text = "information_text_shilling",
	item_type = "chips",
	icon = "icon_shillings_03",
	can_wield = CanWieldAllItemTemplates
}
Currencies.shillings_04 = {
	description = "shilling_bag_25_description",
	rarity = "common",
	display_name = "shilling_bag_25_name",
	inventory_icon = "icon_shillings_04",
	slot_type = "chips",
	information_text = "information_text_shilling",
	item_type = "chips",
	icon = "icon_shillings_04",
	can_wield = CanWieldAllItemTemplates
}
Currencies.shillings_05 = {
	description = "shilling_bag_50_description",
	rarity = "common",
	display_name = "shilling_bag_50_name",
	inventory_icon = "icon_shillings_05",
	slot_type = "chips",
	information_text = "information_text_shilling",
	item_type = "chips",
	icon = "icon_shillings_05",
	can_wield = CanWieldAllItemTemplates
}
Currencies.shillings_06 = {
	description = "shilling_bag_100_description",
	rarity = "common",
	display_name = "shilling_bag_100_name",
	inventory_icon = "icon_shillings_06",
	slot_type = "chips",
	information_text = "information_text_shilling",
	item_type = "chips",
	icon = "icon_shillings_06",
	can_wield = CanWieldAllItemTemplates
}
Currencies.shillings_small = {
	description = "shilling_bag_small_description",
	rarity = "common",
	display_name = "shilling_chest_small_name",
	inventory_icon = "icon_shillings_05",
	slot_type = "chips",
	information_text = "information_text_shilling",
	item_type = "chips",
	icon = "icon_shillings_05",
	can_wield = CanWieldAllItemTemplates
}
Currencies.shillings_medium = {
	description = "shilling_bag_medium_description",
	rarity = "common",
	display_name = "shilling_bag_medium_name",
	inventory_icon = "icon_shillings_06",
	slot_type = "chips",
	information_text = "information_text_shilling",
	item_type = "chips",
	icon = "icon_shillings_06",
	can_wield = CanWieldAllItemTemplates
}
Currencies.shillings_large = {
	description = "shilling_bag_large_description",
	rarity = "common",
	display_name = "shilling_bag_large_name",
	inventory_icon = "icon_shillings_06",
	slot_type = "chips",
	information_text = "information_text_shilling",
	item_type = "chips",
	icon = "icon_shillings_06",
	can_wield = CanWieldAllItemTemplates
}
