-- chunkname: @scripts/settings/dlcs/skulls_2025/item_master_list_skulls_2025.lua

ItemMasterList.dw_dual_axe_skin_06_runed_04 = {
	description = "dw_dual_axe_skin_06_runed_04_description",
	display_name = "dw_dual_axe_skin_06_runed_04_name",
	display_unit = "units/weapons/weapon_display/display_dual_axes",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_axe_03_t2_dual",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_dw_axe_03_t2/wpn_dw_axe_03_t2_runed_01",
	matching_item_key = "dr_dual_wield_axes",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_dw_axe_03_t2/wpn_dw_axe_03_t2_runed_01",
	slot_type = "weapon_skin",
	template = "dual_wield_axes_template_1",
	can_wield = {
		"dr_slayer",
	},
}
ItemMasterList.we_spear_skin_03_runed_04 = {
	description = "we_spear_skin_03_runed_04_description",
	display_name = "we_spear_skin_03_runed_04_name",
	display_unit = "units/weapons/weapon_display/display_2h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_spear_03",
	item_type = "weapon_skin",
	matching_item_key = "we_spear",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_we_spear_03/wpn_we_spear_03_runed_01",
	slot_type = "weapon_skin",
	template = "two_handed_spears_elf_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.es_halberd_skin_04_runed_04 = {
	description = "es_halberd_skin_04_runed_04_description",
	display_name = "es_halberd_skin_04_runed_04_name",
	display_unit = "units/weapons/weapon_display/display_2h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_wh_halberd_04",
	item_type = "weapon_skin",
	matching_item_key = "es_halberd",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_wh_halberd_04/wpn_wh_halberd_04_runed_01",
	slot_type = "weapon_skin",
	template = "two_handed_halberds_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.bw_flamethrower_staff_skin_02_runed_04 = {
	description = "bw_flamethrower_staff_skin_02_runed_04_description",
	display_name = "bw_flamethrower_staff_skin_02_runed_04_name",
	display_unit = "units/weapons/weapon_display/display_staff",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_brw_flame_staff_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
	matching_item_key = "bw_skullstaff_flamethrower",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_brw_flame_staff_02/wpn_brw_flame_staff_02_runed_01",
	slot_type = "weapon_skin",
	template = "staff_flamethrower_template",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.wh_repeating_crossbow_skin_03_runed_04 = {
	description = "wh_repeating_crossbow_skin_03_runed_04_description",
	display_name = "wh_repeating_crossbow_skin_03_runed_04_name",
	display_unit = "units/weapons/weapon_display/display_rifle",
	hud_icon = "weapon_generic_icon_fencing_sword",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_wh_repeater_crossbow_t3",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_repeater_crossbow_t3/wpn_wh_repeater_crossbow_t3_runed_01",
	matching_item_key = "wh_crossbow_repeater",
	rarity = "unique",
	slot_type = "weapon_skin",
	template = "repeating_crossbow_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.frame_skulls_2025 = {
	description = "frame_skulls_2025_description",
	display_name = "frame_skulls_2025_name",
	display_unit = "units/weapons/weapon_display/display_portrait_frame",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_skulls_2025",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_skulls_2025",
	can_wield = CanWieldAllItemTemplates,
	events = {
		"skulls",
	},
}
