-- chunkname: @scripts/ui/cutscene_overlay_templates/cutscene_template_tutorial.lua

local utils = require("scripts/ui/cutscene_overlay_templates/cutscene_utils")
local template_settings = {
	template_1 = {
		{
			end_timestamp = "00:03:90",
			fade_in_duration = 0.5,
			fade_out_duration = 0.4,
			font_size = 70,
			font_type = "hell_shark_header",
			font_upper_case = true,
			localize = true,
			start_timestamp = "00:00:00",
			text = "tutorial_intro_fatshark_games",
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				0,
				0,
			},
		},
		{
			end_timestamp = "00:12:80",
			fade_in_duration = 0.5,
			fade_out_duration = 0.4,
			font_size = 70,
			font_type = "hell_shark_header",
			font_upper_case = true,
			localize = true,
			start_timestamp = "00:08:90",
			text = "tutorial_intro_games_workshop",
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				0,
				0,
			},
		},
		{
			end_timestamp = "00:21:70",
			fade_in_duration = 0.5,
			fade_out_duration = 0.4,
			font_size = 60,
			font_type = "hell_shark_header",
			font_upper_case = true,
			localize = true,
			start_timestamp = "00:17:80",
			text = "tutorial_intro_end_times_adventure",
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				0,
				0,
			},
		},
		{
			end_timestamp = "00:33:21",
			fade_in_duration = 1,
			fade_out_duration = 0.51,
			image = "vermintide_2_logo_tutorial",
			start_timestamp = "00:28:70",
			image_size = {
				1920,
				1080,
			},
			offset = {
				0,
				0,
				0,
			},
		},
	},
	template_2 = {
		{
			end_timestamp = "00:03:90",
			fade_in_duration = 0.5,
			fade_out_duration = 0.4,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			localize = true,
			start_timestamp = "00:00:00",
			text = "tutorial_intro_presents",
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				-50,
				0,
			},
		},
		{
			end_timestamp = "00:12:80",
			fade_in_duration = 0.5,
			fade_out_duration = 0.4,
			font_size = 28,
			font_type = "hell_shark",
			font_upper_case = false,
			localize = true,
			start_timestamp = "00:08:90",
			text = "tutorial_intro_in_association_with",
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				50,
				0,
			},
		},
		{
			end_timestamp = "00:21:70",
			fade_in_duration = 0.4,
			fade_out_duration = 0.5,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			localize = true,
			start_timestamp = "00:17:80",
			text = "tutorial_intro_an",
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				50,
				0,
			},
		},
	},
	template_3 = {
		{
			end_timestamp = "00:03:90",
			fade_in_duration = 0.5,
			fade_out_duration = 0.4,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			localize = false,
			start_timestamp = "00:00:00",
			text = "",
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				-50,
				0,
			},
		},
		{
			end_timestamp = "00:12:80",
			fade_in_duration = 0.5,
			fade_out_duration = 0.4,
			font_size = 28,
			font_type = "hell_shark",
			font_upper_case = false,
			localize = false,
			start_timestamp = "00:08:90",
			text = "",
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				50,
				0,
			},
		},
		{
			end_timestamp = "00:21:70",
			fade_in_duration = 0.4,
			fade_out_duration = 0.5,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			localize = true,
			start_timestamp = "00:17:80",
			text = "tutorial_intro_adventure",
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				-45,
				0,
			},
		},
	},
}

utils.convert_string_timestamps_to_seconds(template_settings)

return {
	templates = template_settings,
}
