-- chunkname: @scripts/ui/cutscene_overlay_templates/cutscene_template_vermintide_2_versus_intro.lua

local utils = require("scripts/ui/cutscene_overlay_templates/cutscene_utils")
local start_layer = 700
local template_settings = {
	template_1 = {
		{
			end_timestamp = "00:18:68",
			fade_in_duration = 0.3,
			fade_out_duration = 0.3,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			horizontal_alignment = "center",
			localize = false,
			start_timestamp = "00:10:62",
			vertical_alignment = "bottom",
			word_wrap = true,
			text = Localize("carousel_intro_subtitle_01"),
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				20,
				start_layer,
			},
		},
		{
			end_timestamp = "00:39:72",
			fade_in_duration = 0.3,
			fade_out_duration = 0.3,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			horizontal_alignment = "center",
			localize = false,
			start_timestamp = "00:35:15",
			vertical_alignment = "bottom",
			word_wrap = true,
			text = Localize("carousel_intro_subtitle_02"),
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				20,
				start_layer,
			},
		},
		{
			end_timestamp = "00:46:74",
			fade_in_duration = 0.3,
			fade_out_duration = 0.3,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			horizontal_alignment = "center",
			localize = false,
			start_timestamp = "00:42:14",
			vertical_alignment = "bottom",
			word_wrap = true,
			text = Localize("carousel_intro_subtitle_03"),
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				20,
				start_layer,
			},
		},
		{
			end_timestamp = "00:54:00",
			fade_in_duration = 0.3,
			fade_out_duration = 0.3,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			horizontal_alignment = "center",
			localize = false,
			start_timestamp = "00:48:04",
			vertical_alignment = "bottom",
			word_wrap = true,
			text = Localize("carousel_intro_subtitle_04"),
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				20,
				start_layer,
			},
		},
		{
			end_timestamp = "01:00:42",
			fade_in_duration = 0.3,
			fade_out_duration = 0.3,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			horizontal_alignment = "center",
			localize = false,
			start_timestamp = "00:54:59",
			vertical_alignment = "bottom",
			word_wrap = true,
			text = Localize("carousel_intro_subtitle_05"),
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				20,
				start_layer,
			},
		},
		{
			end_timestamp = "01:18:19",
			fade_in_duration = 0.3,
			fade_out_duration = 0.3,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			horizontal_alignment = "center",
			localize = false,
			start_timestamp = "01:13:21",
			vertical_alignment = "bottom",
			word_wrap = true,
			text = Localize("carousel_intro_subtitle_06"),
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				20,
				start_layer,
			},
		},
		{
			end_timestamp = "01:21:00",
			fade_in_duration = 0.3,
			fade_out_duration = 0.3,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			horizontal_alignment = "center",
			localize = false,
			start_timestamp = "01:18:44",
			vertical_alignment = "bottom",
			word_wrap = true,
			text = Localize("carousel_intro_subtitle_07"),
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				20,
				start_layer,
			},
		},
		{
			end_timestamp = "01:23:02",
			fade_in_duration = 0.3,
			fade_out_duration = 0.3,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			horizontal_alignment = "center",
			localize = false,
			start_timestamp = "01:21:91",
			vertical_alignment = "bottom",
			word_wrap = true,
			text = Localize("carousel_intro_subtitle_08"),
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				20,
				start_layer,
			},
		},
		{
			end_timestamp = "01:24:89",
			fade_in_duration = 0.3,
			fade_out_duration = 0.3,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			horizontal_alignment = "center",
			localize = false,
			start_timestamp = "01:23:90",
			vertical_alignment = "bottom",
			word_wrap = true,
			text = Localize("carousel_intro_subtitle_09"),
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				20,
				start_layer,
			},
		},
		{
			end_timestamp = "01:26:84",
			fade_in_duration = 0.3,
			fade_out_duration = 0.3,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			horizontal_alignment = "center",
			localize = false,
			start_timestamp = "01:25:80",
			vertical_alignment = "bottom",
			word_wrap = true,
			text = Localize("carousel_intro_subtitle_10"),
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				20,
				start_layer,
			},
		},
		{
			end_timestamp = "01:30:95",
			fade_in_duration = 0.3,
			fade_out_duration = 0.3,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			horizontal_alignment = "center",
			localize = false,
			start_timestamp = "01:28:05",
			vertical_alignment = "bottom",
			word_wrap = true,
			text = Localize("carousel_intro_subtitle_11"),
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				20,
				start_layer,
			},
		},
		{
			end_timestamp = "01:36:61",
			fade_in_duration = 0.3,
			fade_out_duration = 0.3,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			horizontal_alignment = "center",
			localize = false,
			start_timestamp = "01:31:45",
			vertical_alignment = "bottom",
			word_wrap = true,
			text = Localize("carousel_intro_subtitle_12"),
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				20,
				start_layer,
			},
		},
		{
			end_timestamp = "01:45:38",
			fade_in_duration = 0.3,
			fade_out_duration = 0.3,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			horizontal_alignment = "center",
			localize = false,
			start_timestamp = "01:41:78",
			vertical_alignment = "bottom",
			word_wrap = true,
			text = Localize("carousel_intro_subtitle_13"),
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				20,
				start_layer,
			},
		},
		{
			end_timestamp = "01:48:34",
			fade_in_duration = 0.3,
			fade_out_duration = 0.3,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			horizontal_alignment = "center",
			localize = false,
			start_timestamp = "01:45:38",
			vertical_alignment = "bottom",
			word_wrap = true,
			text = Localize("carousel_intro_subtitle_14"),
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				20,
				start_layer,
			},
		},
		{
			end_timestamp = "01:56:73",
			fade_in_duration = 0.3,
			fade_out_duration = 0.3,
			font_size = 30,
			font_type = "hell_shark",
			font_upper_case = false,
			horizontal_alignment = "center",
			localize = false,
			start_timestamp = "01:52:87",
			vertical_alignment = "bottom",
			word_wrap = true,
			text = Localize("carousel_intro_subtitle_15"),
			color = Colors.get_color_table_with_alpha("white", 255),
			offset = {
				0,
				20,
				start_layer,
			},
		},
	},
}

utils.convert_string_timestamps_to_seconds(template_settings)

return {
	templates = template_settings,
}
