-- chunkname: @scripts/settings/profiles/vs_profiles.lua

local base_character_states = {
	"EnemyCharacterStateDead",
	"EnemyCharacterStateInteracting",
	"EnemyCharacterStateInspecting",
	"EnemyCharacterStateDodging",
	"EnemyCharacterStateCatapulted",
	"EnemyCharacterStateStunned",
	"EnemyCharacterStateUsingTransport",
	"EnemyCharacterStateInVortex",
	"EnemyCharacterStateLunging",
	"EnemyCharacterStateLeaping",
	"EnemyCharacterStateClimbing",
	"EnemyCharacterStateTunneling",
	"EnemyCharacterStateSpawning",
	"EnemyCharacterStateJumpAcross",
	"EnemyCharacterStateStaggered",
}
local base_camera_states = {
	"CameraStateIdle",
	"CameraStateFollow",
	"CameraStateFollowThirdPerson",
	"CameraStateFollowAttract",
	"CameraStateFollowThirdPersonLedge",
	"CameraStateFollowThirdPersonOverShoulder",
	"CameraStateFollowThirdPersonSmartClimbing",
	"CameraStateFollowThirdPersonTunneling",
	"CameraStateFollowChaosSpawnGrabbed",
	"CameraStateObserver",
	"CameraStateInteraction",
}
local VSProfiles = {
	{
		affiliation = "dark_pact",
		character_name = "vs_undecided",
		character_vo = "vs_undecided",
		dialogue_faction = "enemy",
		display_name = "vs_undecided",
		ingame_display_name = "vs_undecided",
		ingame_short_display_name = "vs_undecided",
		careers = {
			CareerSettings.vs_undecided,
		},
		base_character_states = {
			"PlayerCharacterStateDead",
		},
		base_camera_states = base_camera_states,
	},
	{
		affiliation = "dark_pact",
		aim_template = "enemy_character",
		career_voice_parameter = "dwarf_career_voice_effect",
		character_name = "vs_poison_wind_globadier",
		character_vo = "vs_poison_wind_globadier",
		default_wielded_slot = "slot_melee",
		dialogue_faction = "enemy",
		display_name = "vs_poison_wind_globadier",
		enemy_role = "area_damage",
		ingame_display_name = "vs_poison_wind_globadier",
		ingame_short_display_name = "vs_poison_wind_globadier",
		mover_profile = "filter_player_mover_pactsworn",
		player_check_for_jumps = true,
		role = "special",
		ui_portrait = "unit_frame_portrait_vs_poison_wind_globadier",
		ui_portrait_small = "portrait_enemy_globadier_versus",
		unit_name = "dwarf_ranger",
		unit_template_name = "player_unit_dark_pact",
		breed = PlayerBreeds.vs_poison_wind_globadier,
		career_voice_parameter_values = {
			0,
			100,
			50,
		},
		room_profile = RoomProfiles.dwarf_ranger,
		first_person_heights = {
			crouch = 1,
			grabbed_by_tentacle = 1.7,
			knocked_down = 0.7,
			stand = 1.5,
		},
		careers = {
			CareerSettings.vs_poison_wind_globadier,
		},
		base_character_states = base_character_states,
		base_camera_states = base_camera_states,
	},
	{
		affiliation = "dark_pact",
		aim_template = "enemy_character",
		career_voice_parameter = "victor_career_voice_effect",
		character_name = "vs_gutter_runner",
		character_vo = "vs_gutter_runner",
		dead_player_destroy_time = 0,
		default_wielded_slot = "slot_melee",
		dialogue_faction = "enemy",
		display_name = "vs_gutter_runner",
		enemy_role = "disabler",
		ingame_display_name = "vs_gutter_runner",
		ingame_short_display_name = "vs_gutter_runner",
		mover_profile = "filter_player_mover_pactsworn",
		player_check_for_jumps = true,
		role = "special",
		ui_portrait = "unit_frame_portrait_vs_gutter_runner",
		ui_portrait_small = "portrait_enemy_gutter_runner_versus",
		unit_name = "witch_hunter",
		unit_template_name = "player_unit_dark_pact",
		breed = PlayerBreeds.vs_gutter_runner,
		career_voice_parameter_values = {
			0,
			100,
			50,
		},
		room_profile = RoomProfiles.witch_hunter,
		first_person_heights = {
			crouch = 0.5,
			grabbed_by_tentacle = 1.9,
			knocked_down = 1,
			stand = 1,
		},
		careers = {
			CareerSettings.vs_gutter_runner,
		},
		base_character_states = base_character_states,
		base_camera_states = base_camera_states,
	},
	{
		affiliation = "dark_pact",
		aim_template = "enemy_character",
		career_voice_parameter = "kerillian_career_voice_effect",
		character_name = "vs_packmaster",
		character_vo = "vs_packmaster",
		default_wielded_slot = "slot_melee",
		dialogue_faction = "enemy",
		display_name = "vs_packmaster",
		enemy_role = "disabler",
		ingame_display_name = "vs_packmaster",
		ingame_short_display_name = "vs_packmaster",
		mover_profile = "filter_player_mover_pactsworn",
		player_check_for_jumps = true,
		role = "special",
		ui_portrait = "unit_frame_portrait_vs_packmaster",
		ui_portrait_small = "portrait_enemy_packmaster_versus",
		unit_name = "way_watcher",
		unit_template_name = "player_unit_dark_pact",
		breed = PlayerBreeds.vs_packmaster,
		career_voice_parameter_values = {
			0,
			100,
			50,
		},
		room_profile = RoomProfiles.wood_elf,
		first_person_heights = {
			crouch = 1,
			grabbed_by_tentacle = 1.7,
			knocked_down = 1,
			stand = 1.2,
		},
		careers = {
			CareerSettings.vs_packmaster,
		},
		base_character_states = base_character_states,
		base_camera_states = base_camera_states,
	},
	{
		affiliation = "dark_pact",
		aim_template = "enemy_character",
		career_voice_parameter = "dwarf_career_voice_effect",
		character_name = "vs_ratling_gunner",
		character_vo = "vs_ratling_gunner",
		default_wielded_slot = "slot_melee",
		dialogue_faction = "enemy",
		display_name = "vs_ratling_gunner",
		enemy_role = "area_damage",
		ingame_display_name = "vs_ratling_gunner",
		ingame_short_display_name = "vs_ratling_gunner",
		mover_profile = "filter_player_mover_pactsworn",
		player_check_for_jumps = true,
		role = "special",
		ui_portrait = "unit_frame_portrait_vs_ratling_gunner",
		ui_portrait_small = "unit_frame_portrait_enemy_ratling_gunner",
		unit_name = "dwarf_ranger",
		unit_template_name = "player_unit_dark_pact",
		breed = PlayerBreeds.vs_ratling_gunner,
		career_voice_parameter_values = {
			0,
			100,
			50,
		},
		room_profile = RoomProfiles.dwarf_ranger,
		first_person_heights = {
			crouch = 1,
			grabbed_by_tentacle = 1.7,
			knocked_down = 0.7,
			stand = 1.5,
		},
		careers = {
			CareerSettings.vs_ratling_gunner,
		},
		base_character_states = base_character_states,
		base_camera_states = base_camera_states,
	},
	{
		affiliation = "dark_pact",
		aim_template = "enemy_character",
		career_voice_parameter = "dwarf_career_voice_effect",
		character_name = "vs_warpfire_thrower",
		character_vo = "vs_warpfire_thrower",
		default_wielded_slot = "slot_melee",
		dialogue_faction = "enemy",
		display_name = "vs_warpfire_thrower",
		enemy_role = "area_damage",
		ingame_display_name = "vs_warpfire_thrower",
		ingame_short_display_name = "vs_warpfire_thrower",
		mover_profile = "filter_player_mover_pactsworn",
		player_check_for_jumps = true,
		role = "special",
		ui_portrait = "unit_frame_portrait_vs_warpfire_thrower",
		ui_portrait_small = "portrait_enemy_warpfire_versus",
		unit_name = "dwarf_ranger",
		unit_template_name = "player_unit_dark_pact",
		breed = PlayerBreeds.vs_warpfire_thrower,
		career_voice_parameter_values = {
			0,
			100,
			50,
		},
		room_profile = RoomProfiles.dwarf_ranger,
		first_person_heights = {
			crouch = 1,
			grabbed_by_tentacle = 1.7,
			knocked_down = 0.7,
			stand = 1.5,
		},
		careers = {
			CareerSettings.vs_warpfire_thrower,
		},
		base_character_states = base_character_states,
		base_camera_states = base_camera_states,
	},
	{
		affiliation = "dark_pact",
		aim_template = "enemy_character",
		career_voice_parameter = "dwarf_career_voice_effect",
		character_name = "vs_chaos_troll",
		character_vo = "vs_chaos_troll",
		default_wielded_slot = "slot_melee",
		dialogue_faction = "enemy",
		display_name = "vs_chaos_troll",
		enemy_role = "boss",
		ingame_display_name = "vs_chaos_troll",
		ingame_short_display_name = "vs_chaos_troll",
		mover_profile = "filter_player_mover_pactsworn",
		player_check_for_jumps = true,
		role = "boss",
		ui_portrait = "unit_frame_portrait_vs_chaos_troll",
		ui_portrait_small = "unit_frame_portrait_enemy_chaos_troll",
		unit_name = "dwarf_ranger",
		unit_template_name = "player_unit_dark_pact",
		breed = PlayerBreeds.vs_chaos_troll,
		career_voice_parameter_values = {
			0,
			100,
			50,
		},
		room_profile = RoomProfiles.dwarf_ranger,
		first_person_heights = {
			crouch = 1.5,
			grabbed_by_tentacle = 1.7,
			knocked_down = 0.7,
			stand = 2.7,
		},
		careers = {
			CareerSettings.vs_chaos_troll,
		},
		base_character_states = base_character_states,
		base_camera_states = base_camera_states,
	},
	{
		affiliation = "spectators",
		display_name = "spectator",
		role = "spectator",
		careers = {
			CareerSettings.spectator,
		},
		base_character_states = {
			"PlayerCharacterStateDead",
		},
		base_camera_states = {
			"CameraStateIdle",
			"CameraStateObserverSpectator",
		},
	},
}

return VSProfiles
