-- chunkname: @scripts/settings/dlcs/grudge_marks/grudge_marks_achievements_settings.lua

local settings = DLCSettings.grudge_marks

settings.achievement_template_file_names = {
	"scripts/managers/achievements/achievement_templates_grudge_marks",
}
settings.achievement_outline = {
	levels = {
		categories = {
			{
				name = "area_selection_morris_name",
				sorting = 7,
				entries = {
					"grudge_mark_kills_grind_we_thornsister",
					"grudge_mark_kills_grind_we_shade",
					"grudge_mark_kills_grind_bw_adept",
					"grudge_mark_kills_grind_wh_captain",
					"grudge_mark_kills_grind_we_waywatcher",
					"grudge_mark_kills_grind_dr_ranger",
					"grudge_mark_kills_grind_wh_bountyhunter",
					"grudge_mark_kills_grind_es_questingknight",
					"grudge_mark_kills_grind_we_maidenguard",
					"grudge_mark_kills_grind_dr_ironbreaker",
					"grudge_mark_kills_grind_es_knight",
					"grudge_mark_kills_grind_dr_engineer",
					"grudge_mark_kills_grind_es_huntsman",
					"grudge_mark_kills_grind_dr_slayer",
					"grudge_mark_kills_grind_es_mercenary",
					"grudge_mark_kills_grind_bw_scholar",
					"grudge_mark_kills_grind_bw_unchained",
					"grudge_mark_kills_grind_bw_necromancer",
					"grudge_mark_kills_grind_wh_zealot",
					"grudge_mark_kills_grind_wh_priest",
					"kill_each_monster_grudge_we_thornsister",
					"kill_each_monster_grudge_we_shade",
					"kill_each_monster_grudge_bw_adept",
					"kill_each_monster_grudge_wh_captain",
					"kill_each_monster_grudge_we_waywatcher",
					"kill_each_monster_grudge_dr_ranger",
					"kill_each_monster_grudge_wh_bountyhunter",
					"kill_each_monster_grudge_es_questingknight",
					"kill_each_monster_grudge_we_maidenguard",
					"kill_each_monster_grudge_dr_ironbreaker",
					"kill_each_monster_grudge_es_knight",
					"kill_each_monster_grudge_dr_engineer",
					"kill_each_monster_grudge_es_huntsman",
					"kill_each_monster_grudge_dr_slayer",
					"kill_each_monster_grudge_es_mercenary",
					"kill_each_monster_grudge_bw_scholar",
					"kill_each_monster_grudge_bw_unchained",
					"kill_each_monster_grudge_bw_necromancer",
					"kill_each_monster_grudge_wh_zealot",
					"kill_each_monster_grudge_wh_priest",
					"kill_grudge_each_expedition_we_thornsister",
					"kill_grudge_each_expedition_we_shade",
					"kill_grudge_each_expedition_bw_adept",
					"kill_grudge_each_expedition_wh_captain",
					"kill_grudge_each_expedition_we_waywatcher",
					"kill_grudge_each_expedition_dr_ranger",
					"kill_grudge_each_expedition_wh_bountyhunter",
					"kill_grudge_each_expedition_es_questingknight",
					"kill_grudge_each_expedition_we_maidenguard",
					"kill_grudge_each_expedition_dr_ironbreaker",
					"kill_grudge_each_expedition_es_knight",
					"kill_grudge_each_expedition_dr_engineer",
					"kill_grudge_each_expedition_es_huntsman",
					"kill_grudge_each_expedition_dr_slayer",
					"kill_grudge_each_expedition_es_mercenary",
					"kill_grudge_each_expedition_bw_scholar",
					"kill_grudge_each_expedition_bw_unchained",
					"kill_grudge_each_expedition_bw_necromancer",
					"kill_grudge_each_expedition_wh_zealot",
					"kill_grudge_each_expedition_wh_priest",
					"complete_all_career_grudge_challenges_we_thornsister",
					"complete_all_career_grudge_challenges_we_shade",
					"complete_all_career_grudge_challenges_bw_adept",
					"complete_all_career_grudge_challenges_wh_captain",
					"complete_all_career_grudge_challenges_we_waywatcher",
					"complete_all_career_grudge_challenges_dr_ranger",
					"complete_all_career_grudge_challenges_wh_bountyhunter",
					"complete_all_career_grudge_challenges_es_questingknight",
					"complete_all_career_grudge_challenges_we_maidenguard",
					"complete_all_career_grudge_challenges_dr_ironbreaker",
					"complete_all_career_grudge_challenges_es_knight",
					"complete_all_career_grudge_challenges_dr_engineer",
					"complete_all_career_grudge_challenges_es_huntsman",
					"complete_all_career_grudge_challenges_dr_slayer",
					"complete_all_career_grudge_challenges_es_mercenary",
					"complete_all_career_grudge_challenges_bw_scholar",
					"complete_all_career_grudge_challenges_bw_unchained",
					"complete_all_career_grudge_challenges_bw_necromancer",
					"complete_all_career_grudge_challenges_wh_zealot",
					"complete_all_career_grudge_challenges_wh_priest",
				},
			},
		},
	},
}
settings.achievement_events = {}
