-- chunkname: @scripts/settings/dlcs/geheimnisnacht_2025/item_master_list_geheimnisnacht_2025.lua

ItemMasterList.frame_geheimnisnacht_2025 = {
	description = "frame_geheimnisnacht_2025_description",
	display_name = "frame_geheimnisnacht_2025_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_geheimnisnacht_2025",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_geheimnisnacht_2025",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.dw_2h_pick_skin_04_runed_03 = {
	description = "dw_2h_pick_skin_04_runed_03_description",
	display_name = "dw_2h_pick_skin_04_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_2h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_pick_01_t4",
	item_type = "weapon_skin",
	matching_item_key = "dr_2h_pick",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_dw_pick_01_t4/wpn_dw_pick_01_t4_runed_01",
	slot_type = "weapon_skin",
	template = "two_handed_picks_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.we_2h_sword_skin_06_runed_03 = {
	description = "we_2h_sword_skin_06_runed_03_description",
	display_name = "we_2h_sword_skin_06_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_2h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_2h_sword_03_t2",
	item_type = "weapon_skin",
	matching_item_key = "we_2h_sword",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_we_2h_sword_03_t2/wpn_we_2h_sword_03_t2_runed_01",
	slot_type = "weapon_skin",
	template = "two_handed_swords_wood_elf_template",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.es_1h_sword_skin_02_runed_03 = {
	description = "es_1h_sword_skin_02_runed_03_description",
	display_name = "es_1h_sword_skin_02_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_1h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_sword_02_t2",
	item_type = "weapon_skin",
	matching_item_key = "es_1h_sword",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_emp_sword_02_t2/wpn_emp_sword_02_t2_runed_01",
	slot_type = "weapon_skin",
	template = "one_handed_swords_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.bw_conflagration_staff_skin_02_runed_03 = {
	description = "bw_conflagration_staff_skin_02_runed_03_description",
	display_name = "bw_conflagration_staff_skin_02_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_staff",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_brw_staff_04",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
	matching_item_key = "bw_skullstaff_geiser",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_brw_staff_04/wpn_brw_staff_04_runed_01",
	slot_type = "weapon_skin",
	template = "staff_fireball_geiser_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.wh_1h_axe_skin_04_runed_03 = {
	description = "wh_1h_axe_skin_04_runed_03_description",
	display_name = "wh_1h_axe_skin_04_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_1h_weapon",
	hud_icon = "weapon_generic_icon_axe1h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_axe_03_t2",
	item_type = "weapon_skin",
	matching_item_key = "wh_1h_axe",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_axe_03_t2/wpn_axe_03_t2_runed_01",
	slot_type = "weapon_skin",
	template = "one_hand_axe_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
