-- chunkname: @scripts/entity_system/systems/behaviour/trees/pets/pet_skeleton_behavior.lua

local ACTIONS_DEFAULT = BreedActions.pet_skeleton
local ACTIONS_ARMORED = BreedActions.pet_skeleton_armored
local ACTIONS_DUAL_WIELD = BreedActions.pet_skeleton_dual_wield
local ACTIONS_SHIELD = BreedActions.pet_skeleton_with_shield
local COMMAND_COMBAT = {
	"BTSelector",
	{
		"BTUtilityNode",
		{
			"BTMeleeOverlapAttackAction",
			condition = "ask_target_before_attacking",
			leave_hook = "command_attack_done",
			name = "running_command_attack",
			action_data = ACTIONS_ARMORED.running_command_attack,
		},
		{
			"BTMeleeOverlapAttackAction",
			condition = "ask_target_before_attacking",
			leave_hook = "command_attack_done",
			name = "command_attack",
			action_data = ACTIONS_ARMORED.command_attack,
		},
		{
			"BTClanRatFollowAction",
			condition = "has_target",
			name = "command_follow",
			action_data = ACTIONS_DEFAULT.command_follow,
		},
		condition = "pet_skeleton_is_armored",
		name = "armored_command_combat",
	},
	{
		"BTUtilityNode",
		{
			"BTMeleeOverlapAttackAction",
			condition = "ask_target_before_attacking",
			leave_hook = "command_attack_done",
			name = "running_command_attack",
			action_data = ACTIONS_DEFAULT.running_command_attack,
		},
		{
			"BTMeleeOverlapAttackAction",
			condition = "ask_target_before_attacking",
			leave_hook = "command_attack_done",
			name = "command_attack",
			action_data = ACTIONS_DUAL_WIELD.command_attack,
		},
		{
			"BTClanRatFollowAction",
			condition = "has_target",
			name = "command_follow",
			action_data = ACTIONS_DEFAULT.command_follow,
		},
		condition = "pet_skeleton_is_dual_wield",
		name = "dual_wield_command_combat",
	},
	{
		"BTUtilityNode",
		{
			"BTMeleeOverlapAttackAction",
			condition = "ask_target_before_attacking",
			leave_hook = "command_attack_done",
			name = "running_command_attack",
			action_data = ACTIONS_DEFAULT.running_command_attack,
		},
		{
			"BTMeleeOverlapAttackAction",
			condition = "ask_target_before_attacking",
			leave_hook = "command_attack_done",
			name = "command_attack",
			action_data = ACTIONS_DEFAULT.command_attack,
		},
		{
			"BTClanRatFollowAction",
			condition = "has_target",
			name = "command_follow",
			action_data = ACTIONS_DEFAULT.command_follow,
		},
		condition = "pet_skeleton_has_shield",
		name = "shield_command_combat",
	},
	{
		"BTUtilityNode",
		{
			"BTMeleeOverlapAttackAction",
			condition = "ask_target_before_attacking",
			leave_hook = "command_attack_done",
			name = "running_command_attack",
			action_data = ACTIONS_DEFAULT.running_command_attack,
		},
		{
			"BTMeleeOverlapAttackAction",
			condition = "ask_target_before_attacking",
			leave_hook = "command_attack_done",
			name = "command_attack",
			action_data = ACTIONS_DEFAULT.command_attack,
		},
		{
			"BTClanRatFollowAction",
			condition = "has_target",
			name = "command_follow",
			action_data = ACTIONS_DEFAULT.command_follow,
		},
		condition = "pet_skeleton_default",
		name = "default_command_combat",
	},
	condition = "has_command_attack",
	name = "command_combat",
}
local ARMORED_COMBAT = {
	"BTUtilityNode",
	action_data = ACTIONS_DEFAULT.utility_action,
	{
		"BTMeleeOverlapAttackAction",
		condition = "ask_target_before_attacking",
		name = "running_sweep_attack",
		action_data = ACTIONS_ARMORED.running_sweep_attack,
	},
	{
		"BTRandom",
		action_data = ACTIONS_ARMORED.moving_attack,
		{
			"BTMeleeOverlapAttackAction",
			condition = "ask_target_before_attacking",
			name = "running_special_attack_sweep",
			weight = 1,
			action_data = ACTIONS_ARMORED.moving_special_attack_sweep,
		},
		{
			"BTMeleeOverlapAttackAction",
			condition = "ask_target_before_attacking",
			name = "running_special_attack_cleave",
			weight = 1,
			action_data = ACTIONS_ARMORED.moving_special_attack_cleave,
		},
		name = "moving_attack",
	},
	{
		"BTRandom",
		action_data = ACTIONS_ARMORED.special_attack,
		{
			"BTMeleeOverlapAttackAction",
			condition = "ask_target_before_attacking",
			name = "special_attack_sweep",
			weight = 1,
			action_data = ACTIONS_ARMORED.special_attack_sweep,
		},
		{
			"BTMeleeOverlapAttackAction",
			condition = "ask_target_before_attacking",
			name = "special_attack_cleave",
			weight = 1,
			action_data = ACTIONS_ARMORED.special_attack_cleave,
		},
		name = "special_attack",
	},
	{
		"BTStormVerminPushAction",
		condition = "has_target",
		name = "push_attack",
		action_data = ACTIONS_ARMORED.push_attack,
	},
	{
		"BTMoveToGoalAction",
		condition = "wants_stand_ground",
		enter_hook = "start_stand_ground",
		name = "hold_position",
		action_data = ACTIONS_DEFAULT.follow,
	},
	{
		"BTClanRatFollowAction",
		condition = "has_target",
		name = "follow",
		action_data = ACTIONS_DEFAULT.follow,
	},
	condition = "pet_skeleton_is_armored",
	name = "armored_combat",
}
local DUAL_WIELD_COMBAT = {
	"BTUtilityNode",
	action_data = ACTIONS_DEFAULT.utility_action,
	{
		"BTMeleeOverlapAttackAction",
		condition = "ask_target_before_attacking",
		name = "running_sweep_attack",
		action_data = ACTIONS_DEFAULT.running_sweep_attack,
	},
	{
		"BTMeleeOverlapAttackAction",
		condition = "ask_target_before_attacking",
		name = "sweep_attack",
		action_data = ACTIONS_DUAL_WIELD.sweep_attack,
	},
	{
		"BTMoveToGoalAction",
		condition = "wants_stand_ground",
		enter_hook = "start_stand_ground",
		name = "hold_position",
		action_data = ACTIONS_DEFAULT.follow,
	},
	{
		"BTClanRatFollowAction",
		condition = "has_target",
		name = "follow",
		action_data = ACTIONS_DEFAULT.follow,
	},
	condition = "pet_skeleton_is_dual_wield",
	name = "dual_wield_combat",
}
local SHIELD_COMBAT = {
	"BTUtilityNode",
	action_data = ACTIONS_DEFAULT.utility_action,
	{
		"BTMeleeOverlapAttackAction",
		condition = "ask_target_before_attacking",
		name = "running_sweep_attack",
		action_data = ACTIONS_DEFAULT.running_sweep_attack,
	},
	{
		"BTRandom",
		action_data = ACTIONS_SHIELD.special_attack,
		{
			"BTMeleeOverlapAttackAction",
			condition = "ask_target_before_attacking",
			name = "sweep_attack",
			weight = 10,
			action_data = ACTIONS_DEFAULT.sweep_attack,
		},
		{
			"BTMeleeOverlapAttackAction",
			condition = "ask_target_before_attacking",
			name = "shield_bash",
			weight = 1,
			action_data = ACTIONS_SHIELD.shield_bash,
		},
		name = "special_attack",
	},
	{
		"BTCombatShoutAction",
		name = "combat_shout",
		action_data = ACTIONS_SHIELD.combat_shout,
	},
	{
		"BTMoveToGoalAction",
		condition = "wants_stand_ground",
		enter_hook = "start_stand_ground",
		name = "hold_position",
		action_data = ACTIONS_DEFAULT.follow,
	},
	{
		"BTClanRatFollowAction",
		condition = "has_target",
		name = "follow",
		action_data = ACTIONS_DEFAULT.follow,
	},
	condition = "pet_skeleton_has_shield",
	name = "shield_combat",
}
local DEFAULT_COMBAT = {
	"BTUtilityNode",
	action_data = ACTIONS_DEFAULT.utility_action,
	{
		"BTMeleeOverlapAttackAction",
		condition = "ask_target_before_attacking",
		name = "running_sweep_attack",
		action_data = ACTIONS_DEFAULT.running_sweep_attack,
	},
	{
		"BTMeleeOverlapAttackAction",
		condition = "ask_target_before_attacking",
		name = "sweep_attack",
		action_data = ACTIONS_DEFAULT.sweep_attack,
	},
	{
		"BTMoveToGoalAction",
		condition = "wants_stand_ground",
		enter_hook = "start_stand_ground",
		name = "hold_position",
		action_data = ACTIONS_DEFAULT.follow,
	},
	{
		"BTClanRatFollowAction",
		condition = "has_target",
		name = "follow",
		action_data = ACTIONS_DEFAULT.follow,
	},
	condition = "pet_skeleton_default",
	name = "default_combat",
}

BreedBehaviors.pet_skeleton = {
	"BTSelector",
	{
		"BTSpawningAction",
		condition = "spawn",
		enter_hook = "to_combat",
		name = "spawn",
		action_data = ACTIONS_DEFAULT.spawn,
	},
	{
		"BTTransportedAction",
		condition = "is_transported",
		name = "transported_idle",
	},
	{
		"BTInVortexAction",
		condition = "in_vortex",
		name = "in_vortex",
	},
	{
		"BTFallAction",
		condition = "is_falling",
		name = "falling",
	},
	{
		"BTStaggerAction",
		condition = "stagger",
		name = "stagger",
		action_data = ACTIONS_DEFAULT.stagger,
	},
	{
		"BTBlockedAction",
		condition = "blocked",
		name = "blocked",
		action_data = ACTIONS_DEFAULT.blocked,
	},
	{
		"BTSelector",
		{
			"BTTeleportAction",
			condition = "at_teleport_smartobject",
			name = "teleport",
		},
		{
			"BTClimbAction",
			condition = "at_climb_smartobject",
			name = "climb",
		},
		{
			"BTJumpAcrossAction",
			condition = "at_jump_smartobject",
			name = "jump_across",
		},
		{
			"BTSmashDoorAction",
			condition = "at_door_smartobject",
			name = "smash_door",
			action_data = ACTIONS_DEFAULT.smash_door,
		},
		condition = "at_smartobject",
		name = "smartobject",
	},
	{
		"BTTeleportToCommanderAction",
		condition = "should_teleport_to_commander",
		name = "teleport_out_of_range",
	},
	{
		"BTSelector",
		action_data = ACTIONS_DEFAULT.utility_action,
		{
			"BTIdleAction",
			condition = "commander_disabled",
			enter_hook = "disable_perception",
			leave_hook = "start_disabled_resume_timer",
			name = "commander_disabled_idle",
			action_data = ACTIONS_DEFAULT.commander_disabled,
		},
		{
			"BTFallbackIdleAction",
			leave_hook = "enable_perception",
			name = "commander_disabled_idle_resume",
			action_data = ACTIONS_DEFAULT.commander_disabled_resume,
		},
		condition = "commander_disabled_or_resuming",
		name = "commander_disabled",
	},
	{
		"BTChargeAttackAction",
		condition = "has_charge_target",
		leave_hook = "remove_charge_target",
		name = "ability_charge_attack",
		action_data = ACTIONS_ARMORED.ability_charge,
	},
	COMMAND_COMBAT,
	{
		"BTSelector",
		ARMORED_COMBAT,
		DUAL_WIELD_COMBAT,
		SHIELD_COMBAT,
		DEFAULT_COMBAT,
		{
			"BTCombatIdleAction",
			name = "idle",
			action_data = ACTIONS_DEFAULT.idle,
		},
		condition = "confirmed_enemy_sighting_within_commander_sticky",
		name = "in_combat",
	},
	{
		"BTSelector",
		{
			"BTMoveToGoalAction",
			condition = "has_goal_destination",
			name = "hold_position",
			action_data = ACTIONS_DEFAULT.follow,
		},
		{
			"BTFallbackIdleAction",
			name = "fallback_idle",
			action_data = ACTIONS_DEFAULT.fallback_idle,
		},
		condition = "wants_stand_ground",
		enter_hook = "start_stand_ground",
		name = "stand_ground",
	},
	{
		"BTSelector",
		{
			"BTMoveToGoalAction",
			condition = "has_goal_destination",
			name = "hold_position",
			action_data = ACTIONS_DEFAULT.follow,
		},
		{
			"BTFallbackIdleAction",
			name = "fallback_idle",
			action_data = ACTIONS_DEFAULT.fallback_idle,
		},
		enter_hook = "start_follow_commander",
		leave_hook = "stop_follow_commander",
		name = "follow",
	},
	name = "pet_skeleton",
}
