-- chunkname: @scripts/settings/dlcs/morris_2024/item_master_list_morris_2024.lua

ItemMasterList.we_dual_dagger_skin_02_runed_06 = {
	description = "chaos_wastes_weapon_skin_runed_06_description",
	display_name = "we_dual_dagger_skin_02_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_1h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_dagger_01_t2_dual_runed_06",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_dagger_01_t2/wpn_we_dagger_01_t2_runed_01",
	matching_item_key = "we_dual_wield_daggers",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_we_dagger_01_t2/wpn_we_dagger_01_t2_runed_01",
	slot_type = "weapon_skin",
	template = "dual_wield_daggers_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.es_longbow_skin_05_runed_06 = {
	description = "es_longbow_skin_05_runed_06_description",
	display_name = "es_longbow_skin_05_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_bow",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_bow_05_runed_06",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_emp_bow_05/wpn_emp_bow_05_runed_01",
	matching_item_key = "es_longbow",
	rarity = "unique",
	slot_type = "weapon_skin",
	template = "longbow_empire_template",
	can_wield = {
		"es_huntsman",
	},
}
ItemMasterList.dw_handgun_skin_02_runed_06 = {
	description = "dw_handgun_skin_02_runed_06_description",
	display_name = "dw_handgun_skin_02_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_rifle",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_handgun_01_t2_runed_06",
	item_type = "weapon_skin",
	matching_item_key = "dr_handgun",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_dw_handgun_01_t2/wpn_dw_handgun_01_t2_runed_01",
	slot_type = "weapon_skin",
	template = "handgun_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
}
ItemMasterList.bw_conflagration_staff_skin_02_runed_06 = {
	description = "bw_conflagration_staff_skin_02_runed_06_description",
	display_name = "bw_conflagration_staff_skin_02_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_staff",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_brw_staff_04_runed_06",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
	matching_item_key = "bw_skullstaff_geiser",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_brw_staff_04/wpn_brw_staff_04_runed_01",
	slot_type = "weapon_skin",
	template = "staff_fireball_geiser_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.wh_2h_sword_skin_02_runed_06 = {
	description = "wh_2h_sword_skin_02_runed_06_description",
	display_name = "wh_2h_sword_skin_02_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_2h_weapon",
	hud_icon = "weapon_generic_icon_sword",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_empire_2h_sword_02_t2_runed_06",
	item_type = "weapon_skin",
	matching_item_key = "wh_2h_sword",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_empire_2h_sword_02_t2/wpn_2h_sword_02_t2_runed_01",
	slot_type = "weapon_skin",
	template = "two_handed_swords_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.we_hagbane_skin_04_runed_06 = {
	description = "we_hagbane_skin_04_runed_06_description",
	display_name = "we_hagbane_skin_04_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_bow",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_bow_short_04_runed_06",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_bow_short_04/wpn_we_bow_short_04_runed_01",
	matching_item_key = "we_shortbow_hagbane",
	rarity = "unique",
	slot_type = "weapon_skin",
	template = "shortbow_hagbane_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.es_2h_sword_exe_skin_04_runed_06 = {
	description = "es_2h_sword_exe_skin_04_runed_06_description",
	display_name = "es_2h_sword_exe_skin_04_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_2h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_sword_exe_04_t1_runed_06",
	item_type = "weapon_skin",
	matching_item_key = "es_2h_sword_executioner",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_emp_sword_exe_04_t1/wpn_emp_sword_exe_04_t1_runed_01",
	slot_type = "weapon_skin",
	template = "two_handed_swords_executioner_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.dw_1h_hammer_skin_02_runed_06 = {
	description = "dw_1h_hammer_skin_02_runed_06_description",
	display_name = "dw_1h_hammer_skin_02_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_1h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_hammer_01_t2_runed_06",
	item_type = "weapon_skin",
	matching_item_key = "dr_1h_hammer",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_dw_hammer_01_t2/wpn_dw_hammer_01_t2_runed_01",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_template_2",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.bw_spear_staff_skin_04_runed_06 = {
	description = "bw_spear_staff_skin_04_runed_06_description",
	display_name = "bw_spear_staff_skin_04_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_staff",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_brw_spear_staff_04_runed_06",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
	matching_item_key = "bw_skullstaff_spear",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_brw_spear_staff_04/wpn_brw_spear_staff_04_runed_01",
	slot_type = "weapon_skin",
	template = "staff_spark_spear_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.wh_repeating_crossbow_skin_03_runed_06 = {
	description = "wh_repeating_crossbow_skin_03_runed_06_description",
	display_name = "wh_repeating_crossbow_skin_03_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_rifle",
	hud_icon = "weapon_generic_icon_fencing_sword",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_wh_repeater_crossbow_t3_runed_06",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_repeater_crossbow_t3/wpn_wh_repeater_crossbow_t3_runed_01",
	matching_item_key = "wh_crossbow_repeater",
	rarity = "unique",
	slot_type = "weapon_skin",
	template = "repeating_crossbow_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.we_spear_skin_04_runed_06 = {
	description = "we_spear_skin_04_runed_06_description",
	display_name = "we_spear_skin_04_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_2h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_spear_04_runed_06",
	item_type = "weapon_skin",
	matching_item_key = "we_spear",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_we_spear_04/wpn_we_spear_04_runed_01",
	slot_type = "weapon_skin",
	template = "two_handed_spears_elf_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.es_blunderbuss_skin_04_runed_06 = {
	description = "es_blunderbuss_skin_04_runed_06_description",
	display_name = "es_blunderbuss_skin_04_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_rifle",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_empire_blunderbuss_t2_runed_06",
	item_type = "weapon_skin",
	matching_item_key = "es_blunderbuss",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_empire_blunderbuss_t2/wpn_empire_blunderbuss_t2_runed_01",
	slot_type = "weapon_skin",
	template = "blunderbuss_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.dw_1h_axe_shield_skin_02_runed_06 = {
	description = "dw_1h_axe_shield_skin_02_runed_06_description",
	display_name = "dw_1h_axe_shield_skin_02_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_shield",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_shield_02_axe_runed_06",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_dw_shield_02_t1/wpn_dw_shield_02_runed_01",
	matching_item_key = "dr_shield_axe",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_dw_axe_03_t2/wpn_dw_axe_03_t2_runed_01",
	slot_type = "weapon_skin",
	template = "one_hand_axe_shield_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
}
ItemMasterList.bw_1h_mace_skin_05_runed_06 = {
	description = "bw_1h_mace_skin_05_runed_06_description",
	display_name = "bw_1h_mace_skin_05_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_1h_hammer_wizard",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_brw_mace_05_runed_06",
	item_type = "weapon_skin",
	matching_item_key = "bw_1h_mace",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_brw_mace_05/wpn_brw_mace_05_runed_01",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_wizard_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.wh_brace_of_pistols_skin_05_runed_06 = {
	description = "wh_brace_of_pistols_skin_05_runed_06_description",
	display_name = "wh_brace_of_pistols_skin_05_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_pistols",
	hud_icon = "weapon_generic_icon_brace_of_pistol",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_pistol_03_t2_runed_06",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_emp_pistol_03_t2/wpn_emp_pistol_03_t2_runed_01",
	matching_item_key = "wh_brace_of_pistols",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_emp_pistol_03_t2/wpn_emp_pistol_03_t2_runed_01",
	slot_type = "weapon_skin",
	template = "brace_of_pistols_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.we_crossbow_skin_03_runed_06 = {
	description = "we_crossbow_skin_03_runed_06_description",
	display_name = "we_crossbow_skin_03_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_rifle",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_repeater_crossbow_t3_runed_06",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_repeater_crossbow_t3/wpn_we_repeater_crossbow_t3_runed_01",
	matching_item_key = "we_crossbow_repeater",
	rarity = "unique",
	slot_type = "weapon_skin",
	template = "repeating_crossbow_elf_template",
	can_wield = {
		"we_shade",
	},
}
ItemMasterList.es_repeating_handgun_skin_02_runed_06 = {
	description = "es_repeating_handgun_skin_02_runed_06_description",
	display_name = "es_repeating_handgun_skin_02_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_rifle",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_handgun_repeater_t2_runed_06",
	item_type = "weapon_skin",
	matching_item_key = "es_repeating_handgun",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_emp_handgun_repeater_t2/wpn_emp_handgun_repeater_t2_runed_01",
	slot_type = "weapon_skin",
	template = "repeating_handgun_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.dw_2h_pick_skin_03_runed_06 = {
	description = "dw_2h_pick_skin_03_runed_06_description",
	display_name = "dw_2h_pick_skin_03_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_2h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_pick_01_t3_runed_06",
	item_type = "weapon_skin",
	matching_item_key = "dr_2h_pick",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_dw_pick_01_t3/wpn_dw_pick_01_t3_runed_01",
	slot_type = "weapon_skin",
	template = "two_handed_picks_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.bw_1h_flaming_sword_skin_01_runed_06 = {
	description = "bw_1h_flaming_sword_skin_01_runed_06_description",
	display_name = "bw_1h_flaming_sword_skin_01_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_1h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_brw_flaming_sword_01_t1_runed_06",
	item_type = "weapon_skin",
	matching_item_key = "bw_flame_sword",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_brw_sword_01_t1/wpn_brw_flaming_sword_01_t1_runed_01",
	slot_type = "weapon_skin",
	template = "flaming_sword_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.wh_1h_axe_skin_02_runed_06 = {
	description = "wh_1h_axe_skin_02_runed_06_description",
	display_name = "wh_1h_axe_skin_02_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_1h_weapon",
	hud_icon = "weapon_generic_icon_axe1h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_axe_02_t2_runed_06",
	item_type = "weapon_skin",
	matching_item_key = "wh_1h_axe",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_axe_02_t2/wpn_axe_02_t2_runed_01",
	slot_type = "weapon_skin",
	template = "one_hand_axe_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.we_longbow_skin_06_runed_06 = {
	description = "we_longbow_skin_06_runed_06_description",
	display_name = "we_longbow_skin_06_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_bow",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_bow_03_t2_runed_06",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_bow_03_t2/wpn_we_bow_03_t2_runed_01",
	matching_item_key = "we_longbow",
	rarity = "unique",
	slot_type = "weapon_skin",
	template = "longbow_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.es_1h_mace_shield_skin_02_runed_06 = {
	description = "es_1h_mace_shield_skin_02_runed_06_description",
	display_name = "es_1h_mace_shield_skin_02_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_shield",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_empire_shield_02_mace_runed_06",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_empire_shield_02/wpn_emp_shield_02_runed_01",
	matching_item_key = "es_mace_shield",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_emp_mace_02_t2/wpn_emp_mace_02_t2_runed_01",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_shield_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.dw_drake_pistol_skin_03_runed_06 = {
	description = "dw_drake_pistol_skin_03_runed_06_description",
	display_name = "dw_drake_pistol_skin_03_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_pistols",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_drake_pistol_02_t1_runed_06",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_dw_drake_pistol_02_t1/wpn_dw_drake_pistol_02_t1_runed_01",
	matching_item_key = "dr_drake_pistol",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_dw_drake_pistol_02_t1/wpn_dw_drake_pistol_02_t1_runed_01",
	slot_type = "weapon_skin",
	template = "brace_of_drakefirepistols_template_1",
	can_wield = {
		"dr_ironbreaker",
	},
}
ItemMasterList.bw_flamethrower_staff_skin_05_runed_06 = {
	description = "bw_flamethrower_staff_skin_05_runed_06_description",
	display_name = "bw_flamethrower_staff_skin_05_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_staff",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_brw_flame_staff_05_runed_06",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
	matching_item_key = "bw_skullstaff_flamethrower",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_brw_flame_staff_05/wpn_brw_flame_staff_05_runed_01",
	slot_type = "weapon_skin",
	template = "staff_flamethrower_template",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.wh_fencing_sword_skin_01_runed_06 = {
	description = "wh_fencing_sword_skin_01_runed_06_description",
	display_name = "wh_fencing_sword_skin_01_runed_06_name",
	display_unit = "units/weapons/weapon_display/display_1h_weapon",
	hud_icon = "weapon_generic_icon_fencing_sword",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_fencingsword_01_t1_runed_06",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_emp_pistol_01_t1/wpn_emp_pistol_01_t1",
	matching_item_key = "wh_fencing_sword",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_fencingsword_01_t1/wpn_fencingsword_01_t1_runed_01",
	slot_type = "weapon_skin",
	template = "fencing_sword_template_1",
	can_wield = {
		"wh_bountyhunter",
		"wh_captain",
		"wh_zealot",
	},
}
