WeaveLoadoutSettings = WeaveLoadoutSettings or {}
WeaveLoadoutSettings.bw_unchained = {
	talent_tree = {
		{
			"sienna_unchained_vanguard",
			"sienna_unchained_reaper",
			"sienna_unchained_heal_share"
		},
		{
			"sienna_unchained_attack_speed_on_high_overcharge",
			"sienna_unchained_burn_push",
			"sienna_unchained_exploding_burning_enemies"
		},
		{
			"sienna_unchained_tank_unbalance",
			"sienna_unchained_linesman_unbalance",
			"sienna_unchained_power_level_unbalance"
		},
		{
			"sienna_unchained_overcharged_blocks",
			"sienna_unchained_increased_vent_speed",
			"sienna_unchained_reduced_damage_taken_after_venting"
		},
		{
			"sienna_unchained_burning_enemies_reduced_damage",
			"sienna_unchained_vent_overheat_on_low_health",
			"sienna_unchained_reduced_overcharge"
		},
		{
			"sienna_unchained_activated_ability_radius",
			"sienna_unchained_activated_ability_power_on_enemies_hit",
			"sienna_unchained_activated_ability_temp_health"
		}
	},
	properties = {
		"weave_attack_speed",
		"weave_crit_boost",
		"weave_power_vs_skaven",
		"weave_power_vs_chaos",
		"weave_power_vs_unarmoured",
		"weave_power_vs_armoured",
		"weave_power_vs_large",
		"weave_power_vs_frenzy",
		"weave_stamina",
		"weave_health",
		"weave_push_block_arc",
		"weave_block_cost",
		"weave_protection_skaven",
		"weave_protection_chaos",
		"weave_protection_aoe",
		"weave_crit_chance",
		"weave_ability_cooldown_reduction",
		"weave_curse_resistance",
		"weave_respawn_speed",
		"weave_revive_speed",
		"weave_fatigue_regen",
		"weave_movespeed"
	},
	traits = {
		"weave_melee_attack_speed_on_crit",
		"weave_melee_timed_block_cost",
		"weave_melee_counter_push_power",
		"weave_melee_reduce_cooldown_on_crit",
		"weave_melee_increase_damage_on_block",
		"weave_melee_shield_on_assist",
		"weave_ranged_replenish_ammo_headshot",
		"weave_ranged_restore_stamina_headshot",
		"weave_ranged_reduced_overcharge",
		"weave_ranged_reduce_cooldown_on_crit",
		"weave_ranged_replenish_ammo_on_crit",
		"weave_ranged_remove_overcharge_on_crit",
		"weave_ranged_increase_power_level_vs_armour_crit",
		"weave_ranged_consecutive_hits_increase_power",
		"weave_ring_not_consume_potion",
		"weave_ring_potion_spread",
		"weave_ring_all_potions",
		"weave_ring_potion_duration",
		"weave_necklace_not_consume_healing",
		"weave_necklace_heal_self_on_heal_other",
		"weave_necklace_increased_healing_received",
		"weave_necklace_no_healing_health_regen",
		"weave_necklace_damage_taken_reduction_on_heal",
		"weave_trinket_not_consume_grenade",
		"weave_trinket_increase_grenade_radius",
		"weave_trinket_grenade_damage_taken"
	}
}

return
