WeaveLoadoutSettings = WeaveLoadoutSettings or {}
WeaveLoadoutSettings.es_mercenary = {
	talent_tree = {
		{
			"markus_mercenary_reaper",
			"markus_mercenary_bloodlust_2",
			"markus_mercenary_heal_share"
		},
		{
			"markus_mercenary_increased_damage_on_enemy_proximity",
			"markus_mercenary_power_level_cleave",
			"markus_mercenary_crit_count"
		},
		{
			"markus_mercenary_linesman_unbalance",
			"markus_mercenary_smiter_unbalance",
			"markus_mercenary_power_level_unbalance"
		},
		{
			"markus_mercenary_passive_power_level_on_proc",
			"markus_mercenary_passive_improved",
			"markus_mercenary_passive_group_proc"
		},
		{
			"markus_mercenary_dodge_range",
			"markus_mercenary_passive_defence_on_proc",
			"markus_mercenary_max_ammo"
		},
		{
			"markus_mercenary_activated_ability_damage_reduction",
			"markus_mercenary_activated_ability_cooldown_no_heal",
			"markus_mercenary_activated_ability_revive"
		}
	},
	properties = {
		"weave_attack_speed",
		"weave_crit_boost",
		"weave_power_vs_skaven",
		"weave_power_vs_chaos",
		"weave_power_vs_unarmoured",
		"weave_power_vs_armoured",
		"weave_power_vs_large",
		"weave_power_vs_frenzy",
		"weave_stamina",
		"weave_health",
		"weave_push_block_arc",
		"weave_block_cost",
		"weave_protection_skaven",
		"weave_protection_chaos",
		"weave_protection_aoe",
		"weave_crit_chance",
		"weave_ability_cooldown_reduction",
		"weave_curse_resistance",
		"weave_respawn_speed",
		"weave_revive_speed",
		"weave_fatigue_regen",
		"weave_movespeed"
	},
	traits = {
		"weave_melee_attack_speed_on_crit",
		"weave_melee_timed_block_cost",
		"weave_melee_counter_push_power",
		"weave_melee_reduce_cooldown_on_crit",
		"weave_melee_increase_damage_on_block",
		"weave_melee_shield_on_assist",
		"weave_ranged_replenish_ammo_headshot",
		"weave_ranged_restore_stamina_headshot",
		"weave_ranged_reduced_overcharge",
		"weave_ranged_reduce_cooldown_on_crit",
		"weave_ranged_replenish_ammo_on_crit",
		"weave_ranged_remove_overcharge_on_crit",
		"weave_ranged_increase_power_level_vs_armour_crit",
		"weave_ranged_consecutive_hits_increase_power",
		"weave_ring_not_consume_potion",
		"weave_ring_potion_spread",
		"weave_ring_all_potions",
		"weave_ring_potion_duration",
		"weave_necklace_not_consume_healing",
		"weave_necklace_heal_self_on_heal_other",
		"weave_necklace_increased_healing_received",
		"weave_necklace_no_healing_health_regen",
		"weave_necklace_damage_taken_reduction_on_heal",
		"weave_trinket_not_consume_grenade",
		"weave_trinket_increase_grenade_radius",
		"weave_trinket_grenade_damage_taken"
	}
}

return
