WeaveLoadoutSettings = WeaveLoadoutSettings or {}
WeaveLoadoutSettings.wh_captain = {
	talent_tree = {
		{
			"victor_witchhunter_regrowth_2",
			"victor_witchhunter_reaper",
			"victor_witchhunter_heal_share"
		},
		{
			"victor_witchhunter_guaranteed_crit_on_timed_block",
			"victor_witchhunter_headshot_damage_increase",
			"victor_witchhunter_bleed_on_critical_hit"
		},
		{
			"victor_witchhunter_linesman_unbalance",
			"victor_witchhunter_finesse_unbalance",
			"victor_witchhunter_power_level_unbalance"
		},
		{
			"victor_witchhunter_improved_damage_taken_ping",
			"victor_witchhunter_attack_speed_on_enemy_pinged",
			"victor_witchhunter_critical_hit_chance_on_ping_target_killed"
		},
		{
			"victor_witchhunter_dodge_range",
			"victor_witchhunter_stamina_regen_on_push",
			"victor_witchhunter_max_ammo"
		},
		{
			"victor_captain_activated_ability_stagger_ping_debuff",
			"victor_witchhunter_activated_ability_guaranteed_crit_self_buff",
			"victor_witchhunter_activated_ability_refund_cooldown_on_enemies_hit"
		}
	},
	properties = {
		"weave_attack_speed",
		"weave_crit_boost",
		"weave_power_vs_skaven",
		"weave_power_vs_chaos",
		"weave_power_vs_unarmoured",
		"weave_power_vs_armoured",
		"weave_power_vs_large",
		"weave_power_vs_frenzy",
		"weave_stamina",
		"weave_health",
		"weave_push_block_arc",
		"weave_block_cost",
		"weave_protection_skaven",
		"weave_protection_chaos",
		"weave_protection_aoe",
		"weave_crit_chance",
		"weave_ability_cooldown_reduction",
		"weave_curse_resistance",
		"weave_respawn_speed",
		"weave_revive_speed",
		"weave_fatigue_regen",
		"weave_movespeed"
	},
	traits = {
		"weave_melee_attack_speed_on_crit",
		"weave_melee_timed_block_cost",
		"weave_melee_counter_push_power",
		"weave_melee_reduce_cooldown_on_crit",
		"weave_melee_increase_damage_on_block",
		"weave_melee_shield_on_assist",
		"weave_ranged_replenish_ammo_headshot",
		"weave_ranged_restore_stamina_headshot",
		"weave_ranged_reduced_overcharge",
		"weave_ranged_reduce_cooldown_on_crit",
		"weave_ranged_replenish_ammo_on_crit",
		"weave_ranged_remove_overcharge_on_crit",
		"weave_ranged_increase_power_level_vs_armour_crit",
		"weave_ranged_consecutive_hits_increase_power",
		"weave_ring_not_consume_potion",
		"weave_ring_potion_spread",
		"weave_ring_all_potions",
		"weave_ring_potion_duration",
		"weave_necklace_not_consume_healing",
		"weave_necklace_heal_self_on_heal_other",
		"weave_necklace_increased_healing_received",
		"weave_necklace_no_healing_health_regen",
		"weave_necklace_damage_taken_reduction_on_heal",
		"weave_trinket_not_consume_grenade",
		"weave_trinket_increase_grenade_radius",
		"weave_trinket_grenade_damage_taken"
	}
}

return
