WeaveLoadoutSettings = WeaveLoadoutSettings or {}
WeaveLoadoutSettings.dr_ironbreaker = {
	talent_tree = {
		{
			"bardin_ironbreaker_vanguard",
			"bardin_ironbreaker_bloodlust_2",
			"bardin_ironbreaker_heal_share"
		},
		{
			"bardin_ironbreaker_increased_overcharge_increased_range_power",
			"bardin_ironbreaker_power_on_nearby_allies",
			"bardin_ironbreaker_power_on_blocked_attacks"
		},
		{
			"bardin_ironbreaker_tank_unbalance",
			"bardin_ironbreaker_smiter_unbalance",
			"bardin_ironbreaker_power_level_unbalance"
		},
		{
			"bardin_ironbreaker_stamina_regen_during_gromril",
			"bardin_ironbreaker_gromril_stagger",
			"bardin_ironbreaker_max_gromril_delay"
		},
		{
			"bardin_ironbreaker_regen_stamina_on_block_broken",
			"bardin_ironbreaker_cooldown_reduction_on_kill_while_full_stamina",
			"bardin_ironbreaker_regen_stamina_on_charged_attacks"
		},
		{
			"bardin_ironbreaker_activated_ability_power_buff_allies",
			"bardin_ironbreaker_activated_ability_taunt_bosses",
			"bardin_ironbreaker_activated_ability_taunt_range_and_duration"
		}
	},
	properties = {
		"weave_attack_speed",
		"weave_crit_boost",
		"weave_power_vs_skaven",
		"weave_power_vs_chaos",
		"weave_power_vs_unarmoured",
		"weave_power_vs_armoured",
		"weave_power_vs_large",
		"weave_power_vs_frenzy",
		"weave_stamina",
		"weave_health",
		"weave_push_block_arc",
		"weave_block_cost",
		"weave_protection_skaven",
		"weave_protection_chaos",
		"weave_protection_aoe",
		"weave_crit_chance",
		"weave_ability_cooldown_reduction",
		"weave_curse_resistance",
		"weave_respawn_speed",
		"weave_revive_speed",
		"weave_fatigue_regen",
		"weave_movespeed"
	},
	traits = {
		"weave_melee_attack_speed_on_crit",
		"weave_melee_timed_block_cost",
		"weave_melee_counter_push_power",
		"weave_melee_reduce_cooldown_on_crit",
		"weave_melee_increase_damage_on_block",
		"weave_melee_shield_on_assist",
		"weave_ranged_replenish_ammo_headshot",
		"weave_ranged_restore_stamina_headshot",
		"weave_ranged_reduced_overcharge",
		"weave_ranged_reduce_cooldown_on_crit",
		"weave_ranged_replenish_ammo_on_crit",
		"weave_ranged_remove_overcharge_on_crit",
		"weave_ranged_increase_power_level_vs_armour_crit",
		"weave_ranged_consecutive_hits_increase_power",
		"weave_ring_not_consume_potion",
		"weave_ring_potion_spread",
		"weave_ring_all_potions",
		"weave_ring_potion_duration",
		"weave_necklace_not_consume_healing",
		"weave_necklace_heal_self_on_heal_other",
		"weave_necklace_increased_healing_received",
		"weave_necklace_no_healing_health_regen",
		"weave_necklace_damage_taken_reduction_on_heal",
		"weave_trinket_not_consume_grenade",
		"weave_trinket_increase_grenade_radius",
		"weave_trinket_grenade_damage_taken"
	}
}

return
