-- chunkname: @scripts/settings/dlcs/woods/item_master_list_woods.lua

ItemMasterList.skin_ww_thornsister = {
	description = "description_skin_we_thornsister",
	display_name = "skin_we_thornsister",
	hud_icon = "unit_frame_portrait_way_watcher",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ww_thornsister",
	item_preview_environment = "waystalker_skins_01",
	item_type = "skin",
	name = "skin_ww_thornsister",
	rarity = "plentiful",
	required_dlc = "woods",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_ww_waywatcher",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.skin_ww_thornsister_black_and_gold = {
	description = "description_skin_ww_thornsister_black_and_gold",
	display_name = "display_name_skin_ww_thornsister_black_and_gold",
	hud_icon = "unit_frame_portrait_way_watcher",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ww_thornsister_black_and_gold",
	item_type = "skin",
	name = "skin_skin_ww_thornsister_black_and_gold",
	rarity = "promo",
	required_dlc = "woods",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_ww_thornsister_black_and_gold",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.skin_ww_thornsister_blue = {
	description = "description_skin_ww_thornsister_blue",
	display_name = "display_name_skin_ww_thornsister_blue",
	hud_icon = "unit_frame_portrait_way_watcher",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ww_thornsister_blue",
	item_type = "skin",
	name = "skin_skin_ww_thornsister_blue",
	rarity = "promo",
	required_dlc = "woods",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_ww_thornsister_blue",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.skin_ww_thornsister_green = {
	description = "description_skin_ww_thornsister_green",
	display_name = "display_name_skin_ww_thornsister_green",
	hud_icon = "unit_frame_portrait_way_watcher",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ww_thornsister_green",
	item_type = "skin",
	name = "skin_skin_ww_thornsister_green",
	rarity = "promo",
	required_dlc = "woods",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_ww_thornsister_green",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.skin_ww_thornsister_redblack = {
	description = "description_skin_ww_thornsister_redblack",
	display_name = "display_name_skin_ww_thornsister_redblack",
	hud_icon = "unit_frame_portrait_way_watcher",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ww_thornsister_redblack",
	item_type = "skin",
	name = "skin_skin_ww_thornsister_redblack",
	rarity = "promo",
	required_dlc = "woods",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_ww_thornsister_redblack",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.skin_ww_thornsister_white = {
	description = "description_skin_ww_thornsister_white",
	display_name = "skin_ww_thornsister_white",
	hud_icon = "unit_frame_portrait_way_watcher",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ww_thornsister_white",
	item_type = "skin",
	name = "skin_ww_thornsister_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_ww_thornsister_white",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.thornsister_hat_0000 = {
	description = "description_thornsister_hat_0000",
	display_name = "display_name_thornsister_hat_0000",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_we_t_hat_01",
	item_type = "hat",
	rarity = "plentiful",
	required_dlc = "woods",
	slot_type = "hat",
	template = "ww_half_masks",
	unit = "units/beings/player/way_watcher_thornsister/headpiece/ww_t_hat_01",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.thornsister_hat_0001 = {
	description = "description_thornsister_hat_0001",
	display_name = "display_name_thornsister_hat_0001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_we_t_hat_02",
	item_type = "hat",
	rarity = "promo",
	required_dlc = "woods",
	slot_type = "hat",
	template = "ww_half_masks",
	unit = "units/beings/player/way_watcher_thornsister/headpiece/ww_t_hat_02",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.thornsister_hat_0002 = {
	description = "description_thornsister_hat_0002",
	display_name = "display_name_thornsister_hat_0002",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_we_t_hat_03",
	item_type = "hat",
	rarity = "promo",
	required_dlc = "woods",
	slot_type = "hat",
	template = "ww_half_masks",
	unit = "units/beings/player/way_watcher_thornsister/headpiece/ww_t_hat_03",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.thornsister_hat_0003 = {
	description = "description_thornsister_hat_0003",
	display_name = "display_name_thornsister_hat_0003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_we_t_hat_04",
	item_type = "hat",
	rarity = "promo",
	required_dlc = "woods",
	slot_type = "hat",
	template = "ww_half_masks",
	unit = "units/beings/player/way_watcher_thornsister/headpiece/ww_t_hat_04",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.thornsister_hat_1010 = {
	description = "description_huntsman_hat_1006",
	display_name = "display_name_huntsman_hat_1006",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_generic_hat_1010",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	template = "ww_half_masks",
	unit = "units/beings/player/way_watcher_thornsister/headpiece/ww_t_fatshark_hat_01",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.frame_0102 = {
	description = "frame_0102_description",
	display_name = "frame_0102_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_0102",
	item_type = "frame",
	rarity = "promo",
	required_dlc = "woods",
	slot_type = "frame",
	temporary_template = "frame_0102",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_0103 = {
	description = "frame_0103_description",
	display_name = "frame_0103_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_0103",
	item_type = "frame",
	rarity = "promo",
	required_dlc = "woods",
	slot_type = "frame",
	temporary_template = "frame_0103",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_0104 = {
	description = "frame_0104_description",
	display_name = "frame_0104_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_0104",
	item_type = "frame",
	rarity = "promo",
	required_dlc = "woods",
	slot_type = "frame",
	temporary_template = "frame_0104",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.we_thornsister_career_skill_weapon = {
	is_local = true,
	left_hand_unit = "units/beings/player/chr_dummy_hat",
	rarity = "plentiful",
	template = "we_thornsister_career_skill_weapon",
	can_wield = {},
}
ItemMasterList.we_javelin = {
	ammo_unit = "units/weapons/player/wpn_we_javelin_01/wpn_we_javelin_01",
	description = "we_javelin_skin_01_description",
	display_name = "we_javelin_skin_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_we_javelin_01",
	is_ammo_weapon = true,
	item_type = "we_javelin",
	left_hand_unit = "units/weapons/player/wpn_we_javelin_01/wpn_we_javelin_01",
	projectile_units_template = "javelin",
	property_table_name = "ranged",
	rarity = "plentiful",
	required_dlc = "woods",
	right_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	skin_combination_table = "we_javelin_skins",
	slot_type = "ranged",
	template = "javelin_template",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"we_thornsister",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.we_javelin_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "we_javelin",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"we_thornsister",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.we_javelin_magic = {
	ammo_unit = "units/weapons/player/wpn_we_javelin_02/wpn_we_javelin_02_magic",
	description = "we_javelin_skin_02_magic_01_description",
	display_name = "we_javelin_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_we_javelin_02_magic",
	is_ammo_weapon = true,
	item_type = "we_javelin",
	left_hand_unit = "units/weapons/player/wpn_we_javelin_02/wpn_we_javelin_02_magic",
	projectile_units_template = "javelin_02_magic",
	property_table_name = "ranged",
	rarity = "magic",
	required_dlc = "woods",
	required_unlock_item = "we_javelin",
	right_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	slot_type = "ranged",
	template = "javelin_template",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"we_thornsister",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.we_life_staff = {
	description = "we_life_staff_skin_01_description",
	display_name = "we_life_staff_skin_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_we_life_staff_01",
	item_type = "we_life_staff",
	left_hand_unit = "units/weapons/player/wpn_we_life_staff_01/wpn_we_life_staff_01",
	property_table_name = "ranged",
	rarity = "plentiful",
	required_dlc = "woods",
	skin_combination_table = "life_staff_skins",
	slot_type = "ranged",
	template = "staff_life",
	trait_table_name = "ranged_heat",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_life_staff_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "we_life_staff",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_life_staff_magic = {
	description = "we_life_staff_skin_02_magic_01_description",
	display_name = "we_life_staff_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_we_life_staff_02_magic",
	item_type = "we_life_staff",
	left_hand_unit = "units/weapons/player/wpn_we_life_staff_02/wpn_we_life_staff_02_magic",
	property_table_name = "ranged",
	rarity = "magic",
	required_dlc = "woods",
	required_unlock_item = "we_life_staff",
	slot_type = "ranged",
	template = "staff_life",
	trait_table_name = "ranged_heat",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_javelin_skin_01 = {
	ammo_unit = "units/weapons/player/wpn_we_javelin_01/wpn_we_javelin_01",
	description = "we_javelin_skin_01_description",
	display_name = "we_javelin_skin_01_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_javelin_01",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_javelin_01/wpn_we_javelin_01",
	matching_item_key = "we_javelin",
	rarity = "common",
	required_dlc = "woods",
	right_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	slot_type = "weapon_skin",
	template = "two_handed_spears_elf_template_1",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_javelin_skin_01_runed_01 = {
	ammo_unit = "units/weapons/player/wpn_we_javelin_01/wpn_we_javelin_01_runed",
	description = "we_javelin_skin_01_runed_01_description",
	display_name = "we_javelin_skin_01_runed_01_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_javelin_01_runed",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_javelin_01/wpn_we_javelin_01_runed",
	matching_item_key = "we_javelin",
	rarity = "unique",
	required_dlc = "woods",
	right_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	slot_type = "weapon_skin",
	template = "two_handed_spears_elf_template_1",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_javelin_skin_01_runed_02 = {
	ammo_unit = "units/weapons/player/wpn_we_javelin_01/wpn_we_javelin_01_runed",
	description = "we_javelin_skin_01_runed_02_description",
	display_name = "we_javelin_skin_01_runed_02_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_javelin_01_runed_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_javelin_01/wpn_we_javelin_01_runed",
	matching_item_key = "we_javelin",
	rarity = "unique",
	required_dlc = "woods",
	right_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	slot_type = "weapon_skin",
	template = "two_handed_spears_elf_template_1",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_javelin_skin_02 = {
	ammo_unit = "units/weapons/player/wpn_we_javelin_02/wpn_we_javelin_02",
	description = "we_javelin_skin_02_description",
	display_name = "we_javelin_skin_02_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_javelin_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_javelin_02/wpn_we_javelin_02",
	matching_item_key = "we_javelin",
	rarity = "rare",
	required_dlc = "woods",
	right_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	slot_type = "weapon_skin",
	template = "two_handed_spears_elf_template_1",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_javelin_skin_02_runed_01 = {
	ammo_unit = "units/weapons/player/wpn_we_javelin_02/wpn_we_javelin_02",
	description = "we_javelin_skin_02_runed_01_description",
	display_name = "we_javelin_skin_02_runed_01_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_javelin_02_runed",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_javelin_02/wpn_we_javelin_02_runed",
	matching_item_key = "we_javelin",
	rarity = "unique",
	required_dlc = "woods",
	right_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	slot_type = "weapon_skin",
	template = "two_handed_spears_elf_template_1",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_javelin_skin_02_runed_02 = {
	ammo_unit = "units/weapons/player/wpn_we_javelin_02/wpn_we_javelin_02",
	description = "we_javelin_skin_02_runed_02_description",
	display_name = "we_javelin_skin_02_runed_02_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_javelin_02_runed_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_javelin_02/wpn_we_javelin_02_runed",
	matching_item_key = "we_javelin",
	rarity = "unique",
	required_dlc = "woods",
	right_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	slot_type = "weapon_skin",
	template = "two_handed_spears_elf_template_1",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_javelin_skin_02_magic_01 = {
	ammo_unit = "units/weapons/player/wpn_we_javelin_02/wpn_we_javelin_02_magic",
	description = "we_javelin_skin_02_magic_01_description",
	display_name = "we_javelin_skin_02_magic_01_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_javelin_02_runed_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_javelin_02/wpn_we_javelin_02_magic",
	matching_item_key = "we_javelin",
	rarity = "magic",
	required_dlc = "woods",
	right_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	slot_type = "weapon_skin",
	template = "two_handed_spears_elf_template_1",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_life_staff_skin_01 = {
	description = "we_life_staff_skin_01_description",
	display_name = "we_life_staff_skin_01_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_life_staff_01",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_life_staff_01/wpn_we_life_staff_01",
	matching_item_key = "we_life_staff",
	rarity = "common",
	required_dlc = "woods",
	slot_type = "weapon_skin",
	template = "staff_life",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_life_staff_skin_01_runed_01 = {
	description = "we_life_staff_skin_01_runed_01_description",
	display_name = "we_life_staff_skin_01_runed_01_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_life_staff_01_runed",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_life_staff_01/wpn_we_life_staff_01_runed",
	matching_item_key = "we_life_staff",
	rarity = "unique",
	required_dlc = "woods",
	slot_type = "weapon_skin",
	template = "staff_life",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_life_staff_skin_01_runed_02 = {
	description = "we_life_staff_skin_01_runed_02_description",
	display_name = "we_life_staff_skin_01_runed_02_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_life_staff_01_runed_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_life_staff_01/wpn_we_life_staff_01_runed",
	matching_item_key = "we_life_staff",
	rarity = "unique",
	required_dlc = "woods",
	slot_type = "weapon_skin",
	template = "staff_life",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_life_staff_skin_02 = {
	description = "we_life_staff_skin_02_description",
	display_name = "we_life_staff_skin_02_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_life_staff_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_life_staff_02/wpn_we_life_staff_02",
	matching_item_key = "we_life_staff",
	rarity = "rare",
	required_dlc = "woods",
	slot_type = "weapon_skin",
	template = "staff_life",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_life_staff_skin_02_runed_01 = {
	description = "we_life_staff_skin_02_runed_01_description",
	display_name = "we_life_staff_skin_02_runed_01_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_life_staff_02_runed",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_life_staff_02/wpn_we_life_staff_02_runed",
	matching_item_key = "we_life_staff",
	rarity = "unique",
	required_dlc = "woods",
	slot_type = "weapon_skin",
	template = "staff_life",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_life_staff_skin_02_runed_02 = {
	description = "we_life_staff_skin_02_runed_02_description",
	display_name = "we_life_staff_skin_02_runed_02_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_life_staff_02_runed_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_life_staff_02/wpn_we_life_staff_02_runed",
	matching_item_key = "we_life_staff",
	rarity = "unique",
	required_dlc = "woods",
	slot_type = "weapon_skin",
	template = "staff_life",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_life_staff_skin_02_magic_01 = {
	description = "we_life_staff_skin_02_magic_01_description",
	display_name = "we_life_staff_skin_02_magic_01_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_life_staff_02_magic",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_life_staff_02/wpn_we_life_staff_02_magic",
	matching_item_key = "we_life_staff",
	rarity = "magic",
	required_dlc = "woods",
	slot_type = "weapon_skin",
	template = "staff_life",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.shilling_bag_woods = {
	description = "shilling_bag_100_description",
	display_name = "shilling_bag_100_name",
	information_text = "information_text_shilling",
	inventory_icon = "icon_shillings_06",
	item_type = "chips",
	rarity = "common",
	slot_type = "chips",
	can_wield = CanWieldAllItemTemplates,
	bundle = {
		BundledVirtualCurrencies = {
			SM = 100,
		},
	},
}
ItemMasterList.shilling_bag_woods_upgrade = {
	description = "shilling_bag_100_description",
	display_name = "shilling_bag_100_name",
	information_text = "information_text_shilling",
	inventory_icon = "icon_shillings_06",
	item_type = "chips",
	rarity = "common",
	slot_type = "chips",
	can_wield = CanWieldAllItemTemplates,
	bundle = {
		BundledVirtualCurrencies = {
			SM = 225,
		},
	},
}

UpdateItemMasterList({
	"we_1h_sword_magic_01",
	"we_longbow_magic_01",
	"we_spear_magic_01",
	"we_dual_wield_daggers_magic_01",
	"we_dual_wield_swords_magic_01",
	"we_dual_wield_sword_dagger_magic_01",
	"we_shortbow_magic_01",
	"we_shortbow_hagbane_magic_01",
	"we_2h_axe_magic_01",
	"we_2h_sword_magic_01",
	"we_1h_axe_magic_01",
	"we_1h_sword",
	"we_longbow",
	"we_spear",
	"we_dual_wield_daggers",
	"we_dual_wield_swords",
	"we_dual_wield_sword_dagger",
	"we_shortbow",
	"we_shortbow_hagbane",
	"we_2h_axe",
	"we_2h_sword",
	"we_1h_axe",
	"we_deus_01",
	"we_deus_01_magic",
	"vs_we_1h_sword",
	"vs_we_longbow",
	"vs_we_spear",
	"vs_we_dual_wield_daggers",
	"vs_we_dual_wield_swords",
	"vs_we_dual_wield_sword_dagger",
	"vs_we_shortbow",
	"vs_we_shortbow_hagbane",
	"vs_we_2h_axe",
	"vs_we_2h_sword",
	"vs_we_1h_axe",
	"vs_we_deus_01",
}, "we_thornsister")
