-- chunkname: @scripts/settings/dlcs/gotwf/item_master_list_gotwf_2025.lua

ItemMasterList.frame_gotwf_2025 = {
	description = "frame_gotwf_2025_description",
	display_name = "frame_gotwf_2025_name",
	display_unit = "units/weapons/weapon_display/display_portrait_frame",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_mondstille_05",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_gotwf_2025",
	can_wield = CanWieldAllItemTemplates,
	events = {
		"gotwf",
	},
}
ItemMasterList.dr_deus_01_skin_03_runed_05 = {
	description = "dr_deus_01_skin_03_runed_05_description",
	display_name = "dr_deus_01_skin_03_runed_05_name",
	hud_icon = "weapon_generic_icon_crossbow",
	information_text = "information_weapon_skin",
	inventory_icon = "icons_placeholder",
	item_type = "weapon_skin",
	matching_item_key = "dr_deus_01",
	rarity = "unique",
	required_dlc = "grass",
	slot_type = "weapon_skin",
	template = "dr_deus_01_template_1",
	can_wield = {
		"dr_ironbreaker",
	},
}
ItemMasterList.dw_1h_hammer_shield_skin_04_runed_05 = {
	description = "dw_1h_hammer_shield_skin_04_runed_05_description",
	display_name = "dw_1h_hammer_shield_skin_04_runed_05_name",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icons_placeholder",
	item_type = "weapon_skin",
	matching_item_key = "dr_shield_hammer",
	rarity = "unique",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_shield_template_2",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
}
ItemMasterList.we_deus_01_skin_02_runed_05 = {
	description = "we_deus_01_skin_02_runed_05_description",
	display_name = "we_deus_01_skin_02_runed_05_name",
	hud_icon = "weapon_generic_icon_bow",
	information_text = "information_weapon_skin",
	inventory_icon = "icons_placeholder",
	item_type = "weapon_skin",
	matching_item_key = "we_deus_01",
	rarity = "unique",
	required_dlc = "grass",
	slot_type = "weapon_skin",
	template = "we_deus_01_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.we_sword_skin_05_runed_05 = {
	description = "we_sword_skin_05_runed_05_description",
	display_name = "we_sword_skin_05_runed_05_name",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icons_placeholder",
	item_type = "weapon_skin",
	matching_item_key = "we_1h_sword",
	rarity = "unique",
	slot_type = "weapon_skin",
	template = "we_one_hand_sword_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.es_deus_01_skin_01_runed_05 = {
	description = "es_deus_01_skin_01_runed_05_description",
	display_name = "es_deus_01_skin_01_runed_05_name",
	hud_icon = "weapon_generic_icon_falken",
	information_text = "information_weapon_skin",
	inventory_icon = "icons_placeholder",
	item_type = "weapon_skin",
	matching_item_key = "es_deus_01",
	rarity = "unique",
	required_dlc = "grass",
	slot_type = "weapon_skin",
	template = "es_deus_01_template",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.es_longbow_skin_04_runed_05 = {
	description = "es_longbow_skin_04_runed_05_description",
	display_name = "es_longbow_skin_04_runed_05_name",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icons_placeholder",
	item_type = "weapon_skin",
	matching_item_key = "es_longbow",
	rarity = "unique",
	slot_type = "weapon_skin",
	template = "longbow_empire_template",
	can_wield = {
		"es_huntsman",
	},
}
ItemMasterList.bw_ghost_scythe_skin_02_runed_05 = {
	description = "bw_ghost_scythe_skin_02_runed_05_description",
	display_name = "bw_ghost_scythe_skin_02_runed_05_name",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icons_placeholder",
	item_type = "weapon_skin",
	matching_item_key = "bw_ghost_scythe",
	rarity = "unique",
	required_dlc = "shovel_upgrade",
	slot_type = "weapon_skin",
	template = "staff_scythe",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_beam_staff_skin_04_runed_05 = {
	description = "bw_beam_staff_skin_04_runed_05_description",
	display_name = "bw_beam_staff_skin_04_runed_05_name",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icons_placeholder",
	item_type = "weapon_skin",
	matching_item_key = "bw_skullstaff_beam",
	rarity = "unique",
	slot_type = "weapon_skin",
	template = "staff_blast_beam_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.wh_hammer_book_skin_02_runed_05 = {
	description = "wh_hammer_book_skin_02_runed_05_description",
	display_name = "wh_hammer_book_skin_02_runed_05_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icons_placeholder",
	item_type = "weapon_skin",
	matching_item_key = "wh_hammer_book",
	rarity = "unique",
	required_dlc = "bless",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_book_priest_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_2h_sword_skin_05_runed_05 = {
	description = "wh_2h_sword_skin_05_runed_05_description",
	display_name = "wh_2h_sword_skin_05_runed_05_name",
	hud_icon = "weapon_generic_icon_sword",
	information_text = "information_weapon_skin",
	inventory_icon = "icons_placeholder",
	item_type = "weapon_skin",
	matching_item_key = "wh_2h_sword",
	rarity = "unique",
	slot_type = "weapon_skin",
	template = "two_handed_swords_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
