-- chunkname: @scripts/settings/dlcs/gotwf/item_master_list_gotwf.lua

ItemMasterList.wh_brace_of_pistols_skin_03_runed_05 = {
	description = "wh_brace_of_pistols_skin_03_runed_05_description",
	display_name = "wh_brace_of_pistols_skin_03_runed_05_name",
	display_unit = "units/weapons/weapon_display/display_pistols",
	hud_icon = "weapon_generic_icon_brace_of_pistol",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_pistol_02_t2_runed_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_emp_pistol_02_t2/wpn_emp_pistol_02_t2_runed_01",
	matching_item_key = "wh_brace_of_pistols",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_emp_pistol_02_t2/wpn_emp_pistol_02_t2_runed_01",
	slot_type = "weapon_skin",
	template = "brace_of_pistols_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.dr_steam_pistol_skin_02_runed_05 = {
	description = "dr_steam_pistol_skin_02_runed_05_description",
	display_name = "dr_steam_pistol_skin_02_runed_05_name",
	display_unit = "units/weapons/weapon_display/display_pistols",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_steam_pistol_01_t2_runed_03",
	item_type = "weapon_skin",
	matching_item_key = "dr_steam_pistol",
	rarity = "unique",
	required_dlc = "cog",
	right_hand_unit = "units/weapons/player/wpn_dw_steam_pistol_01_t2/wpn_dw_steam_pistol_01_t2_runed_01",
	slot_type = "weapon_skin",
	template = "heavy_steam_pistol_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
	},
}
ItemMasterList.we_javelin_skin_02_runed_05 = {
	ammo_unit = "units/weapons/player/wpn_we_javelin_02/wpn_we_javelin_02",
	description = "we_javelin_skin_02_runed_05_description",
	display_name = "we_javelin_skin_02_runed_05_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_javelin_02_runed_02_03",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_javelin_02/wpn_we_javelin_02_runed",
	matching_item_key = "we_javelin",
	rarity = "unique",
	required_dlc = "woods",
	right_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	slot_type = "weapon_skin",
	template = "two_handed_spears_elf_template_1",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.bw_deus_01_skin_02_runed_05 = {
	description = "bw_deus_01_skin_02_runed_05_description",
	display_name = "bw_deus_01_skin_02_runed_05_name",
	display_unit = "units/weapons/weapon_display/display_staff",
	hud_icon = "weapon_generic_icon_staff_5",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_brw_magmastaff_t2_runed_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
	matching_item_key = "bw_deus_01",
	rarity = "unique",
	required_dlc = "grass",
	right_hand_unit = "units/weapons/player/wpn_bw_deus_02/wpn_bw_deus_02_runed",
	slot_type = "weapon_skin",
	template = "bw_deus_01_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
	right_hand_unit_override = {
		bw_necromancer = "units/weapons/player/wpn_bw_deus_02/wpn_bw_deus_02_runed_baelfire",
	},
}
ItemMasterList.es_dual_wield_hammer_sword_skin_02_runed_05 = {
	description = "es_dual_wield_hammer_sword_skin_02_runed_05_description",
	display_name = "es_dual_wield_hammer_sword_skin_02_runed_05_name",
	display_unit = "units/weapons/weapon_display/display_dual_weapons",
	hud_icon = "weapon_generic_icon_falken",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_dual_wield_hammer_sword_02_runed_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_emp_sword_06_t2/wpn_emp_sword_06_t2_runed_01",
	matching_item_key = "es_dual_wield_hammer_sword",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_emp_mace_05_t2/wpn_emp_mace_05_t2_runed_01",
	slot_type = "weapon_skin",
	template = "dual_wield_hammer_sword_template",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.wh_deus_01_skin_03_runed_05 = {
	description = "wh_deus_01_skin_03_runed_05_description",
	display_name = "wh_deus_01_skin_03_runed_05_name",
	display_unit = "units/weapons/weapon_display/display_pistols",
	hud_icon = "weapon_generic_icon_bow",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_duckfoot_t3_runed_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_deus_03/wpn_wh_deus_03_runed",
	matching_item_key = "wh_deus_01",
	rarity = "unique",
	required_dlc = "grass",
	right_hand_unit = "units/weapons/player/wpn_wh_deus_03/wpn_wh_deus_03_runed",
	slot_type = "weapon_skin",
	template = "wh_deus_01_template_1",
	can_wield = {
		"wh_bountyhunter",
		"wh_captain",
		"wh_zealot",
	},
}
ItemMasterList.dw_2h_hammer_skin_01_runed_05 = {
	description = "dw_2h_hammer_skin_01_runed_05_description",
	display_name = "dw_2h_hammer_skin_01_runed_05_name",
	display_unit = "units/weapons/weapon_display/display_2h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "dw_2h_hammer_01_t1_runed_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_2h_hammer",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_dw_2h_hammer_01_t1/wpn_dw_2h_hammer_01_t1_runed_01",
	slot_type = "weapon_skin",
	template = "two_handed_hammers_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.es_handgun_skin_02_runed_05 = {
	description = "es_handgun_skin_02_runed_05_description",
	display_name = "es_handgun_skin_02_runed_05_name",
	display_unit = "units/weapons/weapon_display/display_rifle",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "empire_handgun_02_t2_runed_02",
	item_type = "weapon_skin",
	matching_item_key = "es_handgun",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_empire_handgun_02_t2/wpn_empire_handgun_02_t2_runed_01",
	slot_type = "weapon_skin",
	template = "handgun_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.we_dual_dagger_skin_02_runed_05 = {
	description = "we_dual_dagger_skin_02_runed_05_description",
	display_name = "we_dual_dagger_skin_02_runed_05_name",
	display_unit = "units/weapons/weapon_display/display_1h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "we_dagger_01_t2_dual_runed_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_dagger_01_t2/wpn_we_dagger_01_t2_runed_01",
	matching_item_key = "we_dual_wield_daggers",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_we_dagger_01_t2/wpn_we_dagger_01_t2_runed_01",
	slot_type = "weapon_skin",
	template = "dual_wield_daggers_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.bw_1h_flaming_sword_skin_01_runed_05 = {
	description = "bw_1h_flaming_sword_skin_01_runed_05_description",
	display_name = "bw_1h_flaming_sword_skin_01_runed_05_name",
	display_unit = "units/weapons/weapon_display/display_1h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_brw_flaming_sword_01_t1_runed_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_flame_sword",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_brw_sword_01_t1/wpn_brw_flaming_sword_01_t1_runed_01",
	slot_type = "weapon_skin",
	template = "flaming_sword_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.frame_gotwf_01 = {
	description = "frame_gotwf_description",
	display_name = "frame_gotwf_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_gotwf_01",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_gotwf_01",
	can_wield = CanWieldAllItemTemplates,
}
