-- chunkname: @scripts/settings/dlcs/shovel/item_master_list_shovel.lua

ItemMasterList.skin_bw_necromancer = {
	description = "description_skin_bw_necromancer",
	display_name = "skin_bw_necromancer",
	hud_icon = "unit_frame_portrait_bright_wizard",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_bw_necromancer",
	item_type = "skin",
	name = "skin_bw_necromancer",
	rarity = "plentiful",
	required_dlc = "shovel",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_bw_necromancer",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.skin_bw_necromancer_white = {
	description = "description_skin_bw_necromancer_white",
	display_name = "skin_bw_necromancer_white",
	hud_icon = "unit_frame_portrait_witch_hunter",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_bw_necromancer_white",
	item_type = "skin",
	name = "skin_bw_necromancer_white",
	rarity = "unique",
	required_dlc = "shovel",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_bw_necromancer_white",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.skin_bw_necromancer_0001 = {
	description = "description_skin_bw_necromancer_0001",
	display_name = "skin_bw_necromancer_0001",
	hud_icon = "unit_frame_portrait_bright_wizard",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_bw_necromancer_0001",
	item_type = "skin",
	name = "skin_bw_necromancer_0001",
	rarity = "promo",
	required_dlc = "shovel_upgrade",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_bw_necromancer_0001",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.skin_bw_necromancer_0001_a = {
	description = "description_skin_bw_necromancer_0001_a",
	display_name = "skin_bw_necromancer_0001_a",
	hud_icon = "unit_frame_portrait_bright_wizard",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_bw_necromancer_0001_a",
	item_type = "skin",
	name = "skin_bw_necromancer_0001_a",
	rarity = "promo",
	required_dlc = "shovel_upgrade",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_bw_necromancer_0001_a",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.skin_bw_necromancer_0002 = {
	description = "description_skin_bw_necromancer_0002",
	display_name = "skin_bw_necromancer_0002",
	hud_icon = "unit_frame_portrait_bright_wizard",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_bw_necromancer_0002",
	item_type = "skin",
	name = "skin_bw_necromancer_0002",
	rarity = "promo",
	required_dlc = "shovel_upgrade",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_bw_necromancer_0002",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_necromancer_hat_0000 = {
	description = "description_bw_necromancer_hat_0000",
	display_name = "bw_necromancer_hat_0000",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_bw_necromancer_hat_0000",
	item_type = "hat",
	rarity = "plentiful",
	required_dlc = "shovel",
	slot_type = "hat",
	template = "bw_hat_cloak",
	unit = "units/beings/player/bright_wizard_necromancer/headpiece/bw_n_hat_01",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_necromancer_hat_0001 = {
	description = "description_bw_necromancer_hat_0001",
	display_name = "bw_necromancer_hat_0001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_bw_necromancer_hat_0001",
	item_type = "hat",
	rarity = "promo",
	required_dlc = "shovel_upgrade",
	slot_type = "hat",
	template = "bw_hair",
	unit = "units/beings/player/bright_wizard_necromancer/headpiece/bw_n_hat_02",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_necromancer_hat_0002 = {
	description = "description_bw_necromancer_hat_0002",
	display_name = "bw_necromancer_hat_0002",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_bw_necromancer_hat_0002",
	item_type = "hat",
	rarity = "promo",
	required_dlc = "shovel_upgrade",
	slot_type = "hat",
	template = "bw_hat_skinned_wide_no_hair",
	unit = "units/beings/player/bright_wizard_necromancer/headpiece/bw_n_hat_03",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_necromancer_hat_0003 = {
	description = "description_bw_necromancer_hat_0003",
	display_name = "bw_necromancer_hat_0003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_bw_necromancer_hat_0003",
	item_type = "hat",
	rarity = "promo",
	required_dlc = "shovel_upgrade",
	slot_type = "hat",
	template = "bw_hat_skinned_wide_no_head",
	unit = "units/beings/player/bright_wizard_necromancer/headpiece/bw_n_hat_04",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_necromancer_hat_1010 = {
	description = "description_huntsman_hat_1006",
	display_name = "display_name_huntsman_hat_1006",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_generic_hat_1010",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	template = "bw_hat_jaw_no_hair",
	unit = "units/beings/player/bright_wizard_necromancer/headpiece/bw_n_fatshark_hat_01",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.frame_necromancer_01 = {
	description = "frame_necromancer_03_description",
	display_name = "frame_necromancer_03_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_necromancer_01",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_necromancer_01",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_necromancer_02 = {
	description = "frame_necromancer_01_description",
	display_name = "frame_necromancer_01_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_necromancer_02",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_necromancer_02",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_necromancer_03 = {
	description = "frame_necromancer_02_description",
	display_name = "frame_necromancer_02_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_necromancer_03",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_necromancer_03",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.bw_necromancer_career_skill_weapon = {
	is_local = true,
	left_hand_unit = "units/beings/player/chr_dummy_hat",
	rarity = "plentiful",
	template = "bw_necromancer_career_skill_weapon",
	can_wield = {},
}
ItemMasterList.bw_necromancer_career_utility_weapon = {
	dont_unwield_on_pickup = true,
	gamepad_hud_icon = "hud_icon_necromancer_utility",
	hide_in_frame_ui = true,
	hud_icon = "hud_inventory_icon_necromancer_utility",
	is_local = true,
	is_not_droppable = true,
	left_hand_unit = "units/weapons/player/wpn_bw_necromancer_ability/wpn_bw_necromancer_ability",
	rarity = "plentiful",
	skip_sync = true,
	slot_type = "potion",
	template = "bw_necromancer_career_utility_weapon",
	unwield_prio = 10,
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_ghost_scythe = {
	description = "bw_ghost_scythe_skin_01_description",
	display_name = "bw_ghost_scythe_skin_01_name",
	display_unit = "units/weapons/weapon_display/display_staff",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_bw_ghost_scythe_01",
	item_type = "bw_ghost_scythe",
	property_table_name = "melee",
	rarity = "plentiful",
	required_dlc = "shovel",
	right_hand_unit = "units/weapons/player/wpn_bw_ghost_scythe_01/wpn_bw_ghost_scythe_01",
	skin_combination_table = "bw_ghost_scythe_skins",
	slot_type = "melee",
	template = "staff_scythe",
	trait_table_name = "melee",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"bw_necromancer",
	},
	right_hand_unit_override = {
		bw_adept = "units/weapons/player/wpn_bw_ghost_scythe_01/wpn_bw_ghost_scythe_01_fire",
		bw_scholar = "units/weapons/player/wpn_bw_ghost_scythe_01/wpn_bw_ghost_scythe_01_fire",
		bw_unchained = "units/weapons/player/wpn_bw_ghost_scythe_01/wpn_bw_ghost_scythe_01_fire",
	},
}
ItemMasterList.bw_ghost_scythe_magic_01 = {
	description = "bw_ghost_scythe_skin_02_magic_01_description",
	display_name = "bw_ghost_scythe_skin_02_magic_01_name",
	display_unit = "units/weapons/weapon_display/display_staff",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_bw_ghost_scythe_02_magic",
	item_type = "bw_ghost_scythe",
	property_table_name = "melee",
	rarity = "magic",
	required_dlc = "shovel",
	required_unlock_item = "bw_ghost_scythe",
	right_hand_unit = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_magic_01",
	slot_type = "melee",
	template = "staff_scythe",
	trait_table_name = "melee",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"bw_necromancer",
	},
	right_hand_unit_override = {
		bw_adept = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_magic_01_fire",
		bw_scholar = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_magic_01_fire",
		bw_unchained = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_magic_01_fire",
	},
}
ItemMasterList.bw_ghost_scythe_skin_magic_01 = {
	description = "bw_ghost_scythe_skin_02_magic_01_description",
	display_name = "bw_ghost_scythe_skin_02_magic_01_name",
	display_unit = "units/weapons/weapon_display/display_staff",
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_bw_ghost_scythe_02_magic",
	item_type = "bw_ghost_scythe",
	matching_item_key = "bw_ghost_scythe",
	rarity = "unique",
	required_dlc = "shovel",
	right_hand_unit = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_magic_01",
	slot_type = "weapon_skin",
	template = "staff_scythe",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"bw_necromancer",
	},
	right_hand_unit_override = {
		bw_adept = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_magic_01_fire",
		bw_scholar = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_magic_01_fire",
		bw_unchained = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_magic_01_fire",
	},
}
ItemMasterList.bw_ghost_scythe_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "bw_ghost_scythe",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"bw_necromancer",
	},
}
ItemMasterList.bw_ghost_scythe_skin_01 = {
	description = "bw_ghost_scythe_skin_01_description",
	display_name = "bw_ghost_scythe_skin_01_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_wpn_bw_ghost_scythe_01",
	item_type = "weapon_skin",
	matching_item_key = "bw_ghost_scythe",
	rarity = "common",
	required_dlc = "shovel",
	right_hand_unit = "units/weapons/player/wpn_bw_ghost_scythe_01/wpn_bw_ghost_scythe_01",
	slot_type = "weapon_skin",
	template = "staff_scythe",
	can_wield = {
		"bw_necromancer",
	},
	right_hand_unit_override = {
		bw_adept = "units/weapons/player/wpn_bw_ghost_scythe_01/wpn_bw_ghost_scythe_01_fire",
		bw_scholar = "units/weapons/player/wpn_bw_ghost_scythe_01/wpn_bw_ghost_scythe_01_fire",
		bw_unchained = "units/weapons/player/wpn_bw_ghost_scythe_01/wpn_bw_ghost_scythe_01_fire",
	},
}
ItemMasterList.bw_ghost_scythe_skin_01_runed_01 = {
	description = "bw_ghost_scythe_skin_01_runed_01_description",
	display_name = "bw_ghost_scythe_skin_01_runed_01_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_wpn_bw_ghost_scythe_01_runed_01",
	item_type = "weapon_skin",
	matching_item_key = "bw_ghost_scythe",
	rarity = "unique",
	required_dlc = "shovel_upgrade",
	right_hand_unit = "units/weapons/player/wpn_bw_ghost_scythe_01/wpn_bw_ghost_scythe_01_runed_01",
	slot_type = "weapon_skin",
	template = "staff_scythe",
	can_wield = {
		"bw_necromancer",
	},
	right_hand_unit_override = {
		bw_adept = "units/weapons/player/wpn_bw_ghost_scythe_01/wpn_bw_ghost_scythe_01_runed_01_fire",
		bw_scholar = "units/weapons/player/wpn_bw_ghost_scythe_01/wpn_bw_ghost_scythe_01_runed_01_fire",
		bw_unchained = "units/weapons/player/wpn_bw_ghost_scythe_01/wpn_bw_ghost_scythe_01_runed_01_fire",
	},
}
ItemMasterList.bw_ghost_scythe_skin_01_runed_02 = {
	description = "bw_ghost_scythe_skin_01_runed_02_description",
	display_name = "bw_ghost_scythe_skin_01_runed_02_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_wpn_bw_ghost_scythe_01_runed_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_ghost_scythe",
	rarity = "unique",
	required_dlc = "shovel_upgrade",
	right_hand_unit = "units/weapons/player/wpn_bw_ghost_scythe_01/wpn_bw_ghost_scythe_01",
	slot_type = "weapon_skin",
	template = "staff_scythe",
	can_wield = {
		"bw_necromancer",
	},
	right_hand_unit_override = {
		bw_adept = "units/weapons/player/wpn_bw_ghost_scythe_01/wpn_bw_ghost_scythe_01_fire",
		bw_scholar = "units/weapons/player/wpn_bw_ghost_scythe_01/wpn_bw_ghost_scythe_01_fire",
		bw_unchained = "units/weapons/player/wpn_bw_ghost_scythe_01/wpn_bw_ghost_scythe_01_fire",
	},
}
ItemMasterList.bw_ghost_scythe_skin_02 = {
	description = "bw_ghost_scythe_skin_02_description",
	display_name = "bw_ghost_scythe_skin_02_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_wpn_bw_ghost_scythe_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_ghost_scythe",
	rarity = "rare",
	required_dlc = "shovel_upgrade",
	right_hand_unit = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02",
	slot_type = "weapon_skin",
	template = "staff_scythe",
	can_wield = {
		"bw_necromancer",
	},
	right_hand_unit_override = {
		bw_adept = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_fire",
		bw_scholar = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_fire",
		bw_unchained = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_fire",
	},
}
ItemMasterList.bw_ghost_scythe_skin_02_runed_01 = {
	description = "bw_ghost_scythe_skin_02_runed_01_description",
	display_name = "bw_ghost_scythe_skin_02_runed_01_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_wpn_bw_ghost_scythe_02_runed_01",
	item_type = "weapon_skin",
	matching_item_key = "bw_ghost_scythe",
	rarity = "unique",
	required_dlc = "shovel_upgrade",
	right_hand_unit = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_runed_01",
	slot_type = "weapon_skin",
	template = "staff_scythe",
	can_wield = {
		"bw_necromancer",
	},
	right_hand_unit_override = {
		bw_adept = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_runed_01_fire",
		bw_scholar = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_runed_01_fire",
		bw_unchained = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_runed_01_fire",
	},
}
ItemMasterList.bw_ghost_scythe_skin_02_runed_02 = {
	description = "bw_ghost_scythe_skin_02_runed_02_description",
	display_name = "bw_ghost_scythe_skin_02_runed_02_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_wpn_bw_ghost_scythe_02_runed_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_ghost_scythe",
	rarity = "unique",
	required_dlc = "shovel_upgrade",
	right_hand_unit = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_runed_02",
	slot_type = "weapon_skin",
	template = "staff_scythe",
	can_wield = {
		"bw_necromancer",
	},
	right_hand_unit_override = {
		bw_adept = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_runed_02_fire",
		bw_scholar = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_runed_02_fire",
		bw_unchained = "units/weapons/player/wpn_bw_ghost_scythe_02/wpn_bw_ghost_scythe_02_runed_02_fire",
	},
}
ItemMasterList.bw_necromancy_staff_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "bw_necromancy_staff",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_necromancy_staff = {
	description = "bw_necromancy_staff_skin_01_description",
	display_name = "bw_necromancy_staff_skin_01_name",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_bw_necromancy_staff_01",
	item_type = "bw_necromancy_staff",
	left_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	property_table_name = "ranged",
	rarity = "plentiful",
	required_dlc = "shovel",
	right_hand_unit = "units/weapons/player/wpn_bw_necromancy_staff_01/wpn_bw_necromancy_staff_01",
	skin_combination_table = "bw_necromancy_staff_skins",
	slot_type = "ranged",
	template = "staff_death",
	trait_table_name = "ranged_heat",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_necromancy_staff_skin_01_runed_01 = {
	description = "bw_necromancy_staff_skin_01_runed_01_description",
	display_name = "bw_necromancy_staff_skin_01_runed_01_name",
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_bw_necromancy_staff_01_runed_01",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	matching_item_key = "bw_necromancy_staff",
	rarity = "unique",
	required_dlc = "shovel_upgrade",
	right_hand_unit = "units/weapons/player/wpn_bw_necromancy_staff_01/wpn_bw_necromancy_staff_01_runed_01",
	slot_type = "weapon_skin",
	template = "staff_death",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_necromancy_staff_skin_01_runed_02 = {
	description = "bw_necromancy_staff_skin_01_runed_02_description",
	display_name = "bw_necromancy_staff_skin_01_runed_02_name",
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_bw_necromancy_staff_01_runed_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	matching_item_key = "bw_necromancy_staff",
	rarity = "unique",
	required_dlc = "shovel_upgrade",
	right_hand_unit = "units/weapons/player/wpn_bw_necromancy_staff_01/wpn_bw_necromancy_staff_01_runed_01",
	slot_type = "weapon_skin",
	template = "staff_death",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_necromancy_staff_magic_01 = {
	description = "bw_necromancy_staff_skin_02_magic_01_description",
	display_name = "bw_necromancy_staff_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_bw_necromancy_staff_02_magic_01",
	item_type = "bw_necromancy_staff",
	left_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	property_table_name = "ranged",
	rarity = "magic",
	required_dlc = "shovel",
	required_unlock_item = "bw_necromancy_staff",
	right_hand_unit = "units/weapons/player/wpn_bw_necromancy_staff_02/wpn_bw_necromancy_staff_02_magic_01",
	slot_type = "ranged",
	template = "staff_death",
	trait_table_name = "ranged_heat",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_necromancy_staff_skin_magic_01 = {
	description = "bw_necromancy_staff_skin_02_magic_01_description",
	display_name = "bw_necromancy_staff_skin_02_magic_01_name",
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_bw_necromancy_staff_02_magic_01",
	item_type = "bw_necromancy_staff",
	left_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	matching_item_key = "bw_necromancy_staff",
	rarity = "unique",
	required_dlc = "shovel",
	right_hand_unit = "units/weapons/player/wpn_bw_necromancy_staff_02/wpn_bw_necromancy_staff_02_magic_01",
	slot_type = "weapon_skin",
	template = "staff_death",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_necromancy_staff_skin_01 = {
	description = "bw_necromancy_staff_skin_01_description",
	display_name = "bw_necromancy_staff_skin_01_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_wpn_bw_necromancy_staff_01",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	matching_item_key = "bw_necromancy_staff",
	rarity = "common",
	required_dlc = "shovel",
	right_hand_unit = "units/weapons/player/wpn_bw_necromancy_staff_01/wpn_bw_necromancy_staff_01",
	slot_type = "weapon_skin",
	template = "staff_death",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_necromancy_staff_skin_02 = {
	description = "bw_necromancy_staff_skin_02_description",
	display_name = "bw_necromancy_staff_skin_02_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_wpn_bw_necromancy_staff_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	matching_item_key = "bw_necromancy_staff",
	rarity = "rare",
	required_dlc = "shovel_upgrade",
	right_hand_unit = "units/weapons/player/wpn_bw_necromancy_staff_02/wpn_bw_necromancy_staff_02",
	slot_type = "weapon_skin",
	template = "staff_death",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_necromancy_staff_skin_02_runed_01 = {
	description = "bw_necromancy_staff_skin_02_runed_01_description",
	display_name = "bw_necromancy_staff_skin_02_runed_01_name",
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_bw_necromancy_staff_02_runed_01",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	matching_item_key = "bw_necromancy_staff",
	rarity = "unique",
	required_dlc = "shovel_upgrade",
	right_hand_unit = "units/weapons/player/wpn_bw_necromancy_staff_02/wpn_bw_necromancy_staff_02_runed_01",
	slot_type = "weapon_skin",
	template = "staff_death",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_necromancy_staff_skin_02_runed_02 = {
	description = "bw_necromancy_staff_skin_02_runed_02_description",
	display_name = "bw_necromancy_staff_skin_02_runed_02_name",
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_bw_necromancy_staff_02_runed_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	matching_item_key = "bw_necromancy_staff",
	rarity = "unique",
	required_dlc = "shovel_upgrade",
	right_hand_unit = "units/weapons/player/wpn_bw_necromancy_staff_02/wpn_bw_necromancy_staff_02_runed_01",
	slot_type = "weapon_skin",
	template = "staff_death",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.shilling_bag_shovel = {
	description = "shilling_bag_100_description",
	display_name = "shilling_bag_100_name",
	information_text = "information_text_shilling",
	inventory_icon = "icon_shillings_06",
	item_type = "chips",
	rarity = "common",
	slot_type = "chips",
	can_wield = CanWieldAllItemTemplates,
	bundle = {
		BundledVirtualCurrencies = {
			SM = 100,
		},
	},
}
ItemMasterList.shilling_bag_shovel_upgrade = {
	description = "shilling_bag_100_description",
	display_name = "shilling_bag_100_name",
	information_text = "information_text_shilling",
	inventory_icon = "icon_shillings_06",
	item_type = "chips",
	rarity = "common",
	slot_type = "chips",
	can_wield = CanWieldAllItemTemplates,
	bundle = {
		BundledVirtualCurrencies = {
			SM = 225,
		},
	},
}

UpdateItemMasterList({
	"bw_sword",
	"bw_sword_magic_01",
	"bw_skullstaff_fireball",
	"bw_skullstaff_fireball_magic_01",
	"bw_skullstaff_spear",
	"bw_skullstaff_spear_magic_01",
	"bw_skullstaff_beam",
	"bw_skullstaff_beam_magic_01",
	"bw_skullstaff_geiser",
	"bw_skullstaff_geiser_magic_01",
	"bw_1h_mace",
	"bw_1h_mace_magic_01",
	"bw_dagger",
	"bw_dagger_magic_01",
	"bw_flame_sword",
	"bw_flame_sword_magic_01",
	"bw_deus_01",
	"bw_deus_01_magic",
	"bw_1h_crowbill",
	"bw_1h_crowbill_magic_01",
	"bw_1h_flail_flaming",
	"bw_1h_flail_flaming_magic_01",
}, "bw_necromancer")
