-- chunkname: @scripts/settings/dlcs/cog/item_master_list_cog.lua

ItemMasterList.skin_dr_engineer = {
	description = "description_skin_dr_engineer_default",
	display_name = "display_name_skin_dr_engineer_default",
	hud_icon = "unit_frame_portrait_dwarf_ranger",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_engineer",
	item_type = "skin",
	name = "skin_dr_engineer",
	rarity = "plentiful",
	required_dlc = "cog",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_dr_engineer",
	can_wield = {
		"dr_engineer",
	},
}
ItemMasterList.skin_dr_engineer_black_and_gold = {
	description = "description_dr_engineer_black_and_gold",
	display_name = "display_name_dr_engineer_black_and_gold",
	hud_icon = "unit_frame_portrait_dwarf_ranger",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_engineer_black_and_gold",
	item_type = "skin",
	name = "skin_dr_engineer_black_and_gold",
	rarity = "promo",
	required_dlc = "cog",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_dr_engineer_black_and_gold",
	can_wield = {
		"dr_engineer",
	},
}
ItemMasterList.skin_dr_engineer_blue_and_gold = {
	description = "description_dr_engineer_blue_and_gold",
	display_name = "display_name_dr_engineer_blue_and_gold",
	hud_icon = "unit_frame_portrait_dwarf_ranger",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_engineer_blue_and_gold",
	item_type = "skin",
	name = "skin_dr_engineer_blue_and_gold",
	rarity = "promo",
	required_dlc = "cog",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_dr_engineer_blue_and_gold",
	can_wield = {
		"dr_engineer",
	},
}
ItemMasterList.skin_dr_engineer_brown_and_iron = {
	description = "description_dr_engineer_brown_and_iron",
	display_name = "display_name_dr_engineer_brown_and_iron",
	hud_icon = "unit_frame_portrait_dwarf_ranger",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_engineer_brown_and_iron",
	item_type = "skin",
	name = "skin_dr_engineer_brown_and_iron",
	rarity = "promo",
	required_dlc = "cog",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_dr_engineer_brown_and_iron",
	can_wield = {
		"dr_engineer",
	},
}
ItemMasterList.skin_dr_engineer_purple_and_copper = {
	description = "description_dr_engineer_purple_and_copper",
	display_name = "display_name_dr_engineer_purple_and_copper",
	hud_icon = "unit_frame_portrait_dwarf_ranger",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_engineer_purple_and_copper",
	item_type = "skin",
	name = "skin_dr_engineer_purple_and_copper",
	rarity = "promo",
	required_dlc = "cog",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_dr_engineer_purple_and_copper",
	can_wield = {
		"dr_engineer",
	},
}
ItemMasterList.skin_dr_engineer_white = {
	description = "description_skin_dr_engineer_white",
	display_name = "skin_dr_engineer_white",
	hud_icon = "unit_frame_portrait_dwarf_ranger",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_dr_engineer_white",
	item_type = "skin",
	name = "skin_dr_engineer_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_dr_engineer_white",
	can_wield = {
		"dr_engineer",
	},
}
ItemMasterList.bardin_engineer_career_skill_weapon = {
	is_local = true,
	rarity = "plentiful",
	right_hand_unit = "units/weapons/player/wpn_dw_rotary_gun_01_t1/wpn_dw_rotary_gun_01_t1",
	template = "bardin_engineer_career_skill_weapon",
	can_wield = {},
}
ItemMasterList.bardin_engineer_career_skill_weapon_heavy = {
	is_local = true,
	rarity = "plentiful",
	right_hand_unit = "units/weapons/player/wpn_dw_rotary_gun_01_t2/wpn_dw_rotary_gun_01_t2",
	template = "bardin_engineer_career_skill_weapon_special",
	can_wield = {},
}
ItemMasterList.engineer_hat_0000 = {
	description = "description_engineer_hat_0000",
	display_name = "display_name_engineer_hat_0000",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_engineer_hat_0000",
	item_type = "hat",
	rarity = "plentiful",
	required_dlc = "cog",
	slot_type = "hat",
	template = "dr_helmets",
	unit = "units/beings/player/dwarf_ranger_engineer/headpiece/dr_e_hat_01",
	can_wield = {
		"dr_engineer",
	},
}
ItemMasterList.engineer_hat_0001 = {
	description = "description_engineer_hat_0001",
	display_name = "display_name_engineer_hat_0001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_engineer_hat_0001",
	item_type = "hat",
	rarity = "promo",
	required_dlc = "cog",
	slot_type = "hat",
	template = "dr_helmets",
	unit = "units/beings/player/dwarf_ranger_engineer/headpiece/dr_e_hat_02",
	can_wield = {
		"dr_engineer",
	},
}
ItemMasterList.engineer_hat_1001 = {
	description = "description_engineer_hat_1001",
	display_name = "display_name_engineer_hat_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_engineer_hat_1001",
	item_type = "hat",
	rarity = "promo",
	required_dlc = "cog",
	slot_type = "hat",
	template = "dr_helmets_skinned_long_no_head",
	unit = "units/beings/player/dwarf_ranger_engineer/headpiece/dr_e_hat_03",
	can_wield = {
		"dr_engineer",
	},
}
ItemMasterList.frame_0099 = {
	description = "frame_0099_description",
	display_name = "frame_0099_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_0099",
	item_type = "frame",
	rarity = "promo",
	required_dlc = "cog_upgrade",
	slot_type = "frame",
	temporary_template = "frame_0099",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_0100 = {
	description = "frame_0100_description",
	display_name = "frame_0100_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_0100",
	item_type = "frame",
	rarity = "promo",
	required_dlc = "cog_upgrade",
	slot_type = "frame",
	temporary_template = "frame_0100",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_0101 = {
	description = "frame_0101_description",
	display_name = "frame_0101_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_0101",
	item_type = "frame",
	rarity = "promo",
	required_dlc = "cog_upgrade",
	slot_type = "frame",
	temporary_template = "frame_0101",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.dr_2h_cog_hammer = {
	description = "dr_cog_hammer_skin_01_description",
	display_name = "dr_cog_hammer_skin_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_dw_coghammer_01_t1",
	item_type = "dr_cog_hammer",
	property_table_name = "melee",
	rarity = "plentiful",
	required_dlc = "cog",
	right_hand_unit = "units/weapons/player/wpn_dw_coghammer_01_t1/wpn_dw_coghammer_01_t1",
	skin_combination_table = "dr_2h_cog_hammer_skins",
	slot_type = "melee",
	template = "two_handed_cog_hammers_template_1",
	trait_table_name = "melee",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
		"dr_slayer",
	},
}
ItemMasterList.dr_2h_cog_hammer_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "dr_2h_cog_hammer",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
		"dr_slayer",
	},
}
ItemMasterList.dr_2h_cog_hammer_skin_01 = {
	description = "dr_cog_hammer_skin_01_description",
	display_name = "dr_cog_hammer_skin_01_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_wpn_dw_coghammer_01_t1",
	item_type = "weapon_skin",
	matching_item_key = "dr_2h_cog_hammer",
	rarity = "common",
	required_dlc = "cog_upgrade",
	right_hand_unit = "units/weapons/player/wpn_dw_coghammer_01_t1/wpn_dw_coghammer_01_t1",
	slot_type = "weapon_skin",
	template = "two_handed_cog_hammers_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
		"dr_slayer",
	},
}
ItemMasterList.dr_2h_cog_hammer_skin_02 = {
	description = "dr_cog_hammer_skin_02_description",
	display_name = "dr_cog_hammer_skin_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_dw_coghammer_01_t2",
	item_type = "weapon_skin",
	matching_item_key = "dr_2h_cog_hammer",
	rarity = "rare",
	required_dlc = "cog_upgrade",
	right_hand_unit = "units/weapons/player/wpn_dw_coghammer_01_t2/wpn_dw_coghammer_01_t2",
	slot_type = "weapon_skin",
	template = "two_handed_cog_hammers_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
		"dr_slayer",
	},
}
ItemMasterList.dr_2h_cog_hammer_skin_01_runed_01 = {
	description = "dr_cog_hammer_skin_01_runed_01_description",
	display_name = "dr_cog_hammer_skin_01_runed_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_coghammer_01_t1_runed_01",
	item_type = "weapon_skin",
	matching_item_key = "dr_2h_cog_hammer",
	rarity = "unique",
	required_dlc = "cog_upgrade",
	right_hand_unit = "units/weapons/player/wpn_dw_coghammer_01_t1/wpn_dw_coghammer_01_t1_runed",
	slot_type = "weapon_skin",
	template = "two_handed_cog_hammers_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
		"dr_slayer",
	},
}
ItemMasterList.dr_2h_cog_hammer_skin_01_runed_02 = {
	description = "dr_cog_hammer_skin_01_runed_02_description",
	display_name = "dr_cog_hammer_skin_01_runed_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_coghammer_01_t1_runed_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_2h_cog_hammer",
	rarity = "unique",
	required_dlc = "cog_upgrade",
	right_hand_unit = "units/weapons/player/wpn_dw_coghammer_01_t1/wpn_dw_coghammer_01_t1_runed",
	slot_type = "weapon_skin",
	template = "two_handed_cog_hammers_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
		"dr_slayer",
	},
}
ItemMasterList.dr_2h_cog_hammer_skin_02_runed_01 = {
	description = "dr_cog_hammer_skin_02_runed_01_description",
	display_name = "dr_cog_hammer_skin_02_runed_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_coghammer_01_t2_runed_01",
	item_type = "weapon_skin",
	matching_item_key = "dr_2h_cog_hammer",
	rarity = "unique",
	required_dlc = "cog_upgrade",
	right_hand_unit = "units/weapons/player/wpn_dw_coghammer_01_t2/wpn_dw_coghammer_01_t2_runed",
	slot_type = "weapon_skin",
	template = "two_handed_cog_hammers_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
		"dr_slayer",
	},
}
ItemMasterList.dr_2h_cog_hammer_skin_02_runed_02 = {
	description = "dr_steam_pistol_skin_02_runed_02_description",
	display_name = "dr_steam_pistol_skin_02_runed_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_coghammer_01_t2_runed_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_2h_cog_hammer",
	rarity = "unique",
	required_dlc = "cog_upgrade",
	right_hand_unit = "units/weapons/player/wpn_dw_coghammer_01_t2/wpn_dw_coghammer_01_t2_runed",
	slot_type = "weapon_skin",
	template = "two_handed_cog_hammers_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
		"dr_slayer",
	},
}
ItemMasterList.dr_2h_cog_hammer_magic_01 = {
	description = "dr_cog_hammer_skin_02_magic_01_description",
	display_name = "dr_cog_hammer_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_dw_coghammer_01_t2_magic",
	item_type = "dr_cog_hammer",
	matching_item_key = "dr_2h_cog_hammer",
	property_table_name = "melee",
	rarity = "magic",
	required_dlc = "cog",
	required_unlock_item = "dr_2h_cog_hammer",
	right_hand_unit = "units/weapons/player/wpn_dw_coghammer_01_t2/wpn_dw_coghammer_01_t2_magic",
	slot_type = "melee",
	template = "two_handed_cog_hammers_template_1",
	trait_table_name = "melee",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
		"dr_slayer",
	},
}
ItemMasterList.dr_2h_cog_hammer_skin_02_magic_01 = {
	description = "dr_cog_hammer_skin_02_magic_01_description",
	display_name = "dr_cog_hammer_skin_02_magic_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_dw_coghammer_01_t2_magic",
	item_type = "weapon_skin",
	matching_item_key = "dr_2h_cog_hammer",
	rarity = "magic",
	required_dlc = "cog",
	required_unlock_item = "dr_2h_cog_hammer",
	right_hand_unit = "units/weapons/player/wpn_dw_coghammer_01_t2/wpn_dw_coghammer_01_t2_magic",
	slot_type = "weapon_skin",
	template = "two_handed_cog_hammers_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
		"dr_slayer",
	},
}
ItemMasterList.dr_steam_pistol = {
	description = "dr_steam_pistol_skin_01_description",
	display_name = "dr_steam_pistol_skin_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_dw_steam_pistol_01_t1",
	item_type = "dr_steam_pistol",
	property_table_name = "ranged",
	rarity = "plentiful",
	required_dlc = "cog",
	right_hand_unit = "units/weapons/player/wpn_dw_steam_pistol_01_t1/wpn_dw_steam_pistol_01_t1",
	skin_combination_table = "dr_steam_pistol_skins",
	slot_type = "ranged",
	template = "heavy_steam_pistol_template_1",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
	},
}
ItemMasterList.dr_steam_pistol_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "dr_steam_pistol",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
	},
}
ItemMasterList.dr_steam_pistol_skin_01 = {
	description = "dr_steam_pistol_skin_01_description",
	display_name = "dr_steam_pistol_skin_01_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_wpn_dw_steam_pistol_01_t1",
	item_type = "weapon_skin",
	matching_item_key = "dr_steam_pistol",
	rarity = "common",
	required_dlc = "cog",
	right_hand_unit = "units/weapons/player/wpn_dw_steam_pistol_01_t1/wpn_dw_steam_pistol_01_t1",
	slot_type = "weapon_skin",
	template = "heavy_steam_pistol_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
	},
}
ItemMasterList.dr_steam_pistol_skin_02 = {
	description = "dr_steam_pistol_skin_02_description",
	display_name = "dr_steam_pistol_skin_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_steam_pistol_01_t2",
	item_type = "weapon_skin",
	matching_item_key = "dr_steam_pistol",
	rarity = "rare",
	required_dlc = "cog_upgrade",
	right_hand_unit = "units/weapons/player/wpn_dw_steam_pistol_01_t2/wpn_dw_steam_pistol_01_t2",
	slot_type = "weapon_skin",
	template = "heavy_steam_pistol_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
	},
}
ItemMasterList.dr_steam_pistol_skin_01_runed_01 = {
	description = "dr_steam_pistol_skin_01_runed_01_description",
	display_name = "dr_steam_pistol_skin_01_runed_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_steam_pistol_01_t1_runed_01",
	item_type = "weapon_skin",
	matching_item_key = "dr_steam_pistol",
	rarity = "unique",
	required_dlc = "cog_upgrade",
	right_hand_unit = "units/weapons/player/wpn_dw_steam_pistol_01_t1/wpn_dw_steam_pistol_01_t1_runed_01",
	slot_type = "weapon_skin",
	template = "heavy_steam_pistol_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
	},
}
ItemMasterList.dr_steam_pistol_skin_01_runed_02 = {
	description = "dr_steam_pistol_skin_01_runed_02_description",
	display_name = "dr_steam_pistol_skin_01_runed_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_steam_pistol_01_t1_runed_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_steam_pistol",
	rarity = "unique",
	required_dlc = "cog_upgrade",
	right_hand_unit = "units/weapons/player/wpn_dw_steam_pistol_01_t1/wpn_dw_steam_pistol_01_t1_runed_01",
	slot_type = "weapon_skin",
	template = "heavy_steam_pistol_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
	},
}
ItemMasterList.dr_steam_pistol_skin_02_runed_01 = {
	description = "dr_steam_pistol_skin_02_runed_01_description",
	display_name = "dr_steam_pistol_skin_02_runed_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_steam_pistol_01_t2_runed_01",
	item_type = "weapon_skin",
	matching_item_key = "dr_steam_pistol",
	rarity = "unique",
	required_dlc = "cog_upgrade",
	right_hand_unit = "units/weapons/player/wpn_dw_steam_pistol_01_t2/wpn_dw_steam_pistol_01_t2_runed_01",
	slot_type = "weapon_skin",
	template = "heavy_steam_pistol_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
	},
}
ItemMasterList.dr_steam_pistol_skin_02_runed_02 = {
	description = "dr_steam_pistol_skin_02_runed_02_description",
	display_name = "dr_steam_pistol_skin_02_runed_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_steam_pistol_01_t2_runed_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_steam_pistol",
	rarity = "unique",
	required_dlc = "cog_upgrade",
	right_hand_unit = "units/weapons/player/wpn_dw_steam_pistol_01_t2/wpn_dw_steam_pistol_01_t2_runed_01",
	slot_type = "weapon_skin",
	template = "heavy_steam_pistol_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
	},
}
ItemMasterList.dr_steam_pistol_magic_01 = {
	description = "dr_steam_pistol_skin_01_magic_01_description",
	display_name = "dr_steam_pistol_skin_01_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_dw_steam_pistol_01_t2_magic",
	item_type = "dr_steam_pistol",
	property_table_name = "ranged",
	rarity = "magic",
	required_dlc = "cog",
	required_unlock_item = "dr_steam_pistol",
	right_hand_unit = "units/weapons/player/wpn_dw_steam_pistol_01_t2/wpn_dw_steam_pistol_01_t2_magic_01",
	slot_type = "ranged",
	template = "heavy_steam_pistol_template_1",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
	},
}
ItemMasterList.dr_steam_pistol_skin_02_magic_01 = {
	description = "dr_steam_pistol_skin_02_magic_01_description",
	display_name = "dr_steam_pistol_skin_02_magic_01_name",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_steam_pistol_01_t2_magic",
	item_type = "weapon_skin",
	matching_item_key = "dr_steam_pistol",
	rarity = "magic",
	required_dlc = "cog_upgrade",
	right_hand_unit = "units/weapons/player/wpn_dw_steam_pistol_01_t2/wpn_dw_steam_pistol_01_t2_magic_01",
	slot_type = "weapon_skin",
	template = "heavy_steam_pistol_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
	},
}
ItemMasterList.dr_steam_pistol_01_t2_magic_01 = {
	description = "dr_steam_pistol_01_t2_magic_01_desciption",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_wpn_dw_steam_pistol_01_t2_magic",
	item_type = "weapon_skin",
	matching_item_key = "dr_steam_pistol",
	rarity = "magic",
	required_dlc = "cog_upgrade",
	right_hand_unit = "units/weapons/player/wpn_dw_steam_pistol_01_t2/wpn_dw_steam_pistol_01_t2_magic_01",
	slot_type = "weapon_skin",
	template = "heavy_steam_pistol_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
	},
}
ItemMasterList.dr_hammer_pistol_preview = {
	description = "dr_steam_pistol_skin_01_description",
	display_name = "dr_steam_pistol_skin_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_dw_coghammer_01_t1",
	item_type = "dr_steam_pistol",
	left_hand_unit = "units/weapons/player/wpn_dw_steam_pistol_01_t1/wpn_dw_steam_pistol_01_t1",
	property_table_name = "ranged",
	rarity = "plentiful",
	required_dlc = "cog",
	right_hand_unit = "units/weapons/player/wpn_dw_coghammer_01_t1/wpn_dw_coghammer_01_t1",
	slot_type = "ranged",
	template = "dual_wield_axes_template_1",
	trait_table_name = "ranged_ammo",
	can_wield = {},
}
ItemMasterList.bardin_engineer_career_skill_weapon_preview = {
	description = "dr_steam_pistol_skin_01_description",
	display_name = "dr_steam_pistol_skin_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_dw_drake_pistol_01_t1",
	is_local = true,
	item_type = "dr_steam_pistol",
	property_table_name = "ranged",
	rarity = "plentiful",
	required_dlc = "cog",
	right_hand_unit = "units/weapons/player/wpn_dw_rotary_gun_01_t1/wpn_dw_rotary_gun_01_t1",
	slot_type = "ranged",
	template = "bardin_engineer_career_skill_weapon",
	trait_table_name = "ranged_ammo",
	can_wield = {},
}
ItemMasterList.shilling_bag_cog = {
	description = "shilling_bag_100_description",
	display_name = "shilling_bag_100_name",
	information_text = "information_text_shilling",
	inventory_icon = "icon_shillings_06",
	item_type = "chips",
	rarity = "common",
	slot_type = "chips",
	can_wield = CanWieldAllItemTemplates,
	bundle = {
		BundledVirtualCurrencies = {
			SM = 100,
		},
	},
}
ItemMasterList.shilling_bag_cog_upgrade = {
	description = "shilling_bag_100_description",
	display_name = "shilling_bag_100_name",
	information_text = "information_text_shilling",
	inventory_icon = "icon_shillings_06",
	item_type = "chips",
	rarity = "common",
	slot_type = "chips",
	can_wield = CanWieldAllItemTemplates,
	bundle = {
		BundledVirtualCurrencies = {
			SM = 225,
		},
	},
}

UpdateItemMasterList({
	"dr_1h_axe",
	"dr_1h_axe_magic_01",
	"dr_1h_hammer",
	"dr_1h_hammer_magic_01",
	"dr_2h_axe",
	"dr_2h_axe_magic_01",
	"dr_2h_hammer",
	"dr_2h_hammer_magic_01",
	"dr_drake_pistol",
	"dr_drake_pistol_magic_01",
	"dr_drakegun",
	"dr_drakegun_magic_01",
	"dr_dual_wield_hammers",
	"dr_dual_wield_hammers_magic_01",
	"dr_handgun",
	"dr_handgun_magic_01",
	"dr_rakegun",
	"dr_rakegun_magic_01",
	"dr_shield_axe",
	"dr_shield_axe_magic_01",
	"dr_shield_hammer",
	"dr_shield_hammer_magic_01",
	"dr_2h_pick",
	"dr_2h_pick_magic_01",
}, "dr_engineer")
