-- chunkname: @scripts/settings/dlcs/bless/item_master_list_bless.lua

ItemMasterList.skin_wh_priest = {
	description = "description_skin_wh_priest",
	display_name = "skin_wh_priest",
	hud_icon = "unit_frame_portrait_witch_hunter",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_wh_warriorpriest",
	item_type = "skin",
	name = "skin_wh_priest",
	rarity = "plentiful",
	required_dlc = "bless",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_wh_priest",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.skin_wh_priest_white = {
	description = "description_skin_wh_priest_white",
	display_name = "skin_wh_priest_white",
	hud_icon = "unit_frame_portrait_witch_hunter",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_wh_priest_white",
	item_type = "skin",
	name = "skin_wh_priest_white",
	rarity = "unique",
	required_dlc = "bless",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_wh_priest_white",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.skin_wh_priest_0002 = {
	description = "description_skin_wh_priest_0002",
	display_name = "skin_wh_priest_0002",
	hud_icon = "unit_frame_portrait_witch_hunter",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_wh_warriorpriest_0002",
	item_type = "skin",
	name = "skin_wh_priest_0002",
	rarity = "promo",
	required_dlc = "bless",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_wh_priest_0002",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.skin_wh_priest_0002_a = {
	description = "description_skin_wh_priest_0002_a",
	display_name = "skin_wh_priest_0002_a",
	hud_icon = "unit_frame_portrait_witch_hunter",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_wh_warriorpriest_0002_a",
	item_type = "skin",
	name = "skin_wh_priest_0002_a",
	rarity = "promo",
	required_dlc = "bless",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_wh_priest_0002_a",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.priest_hat_0000 = {
	description = "description_priest_hat_0000",
	display_name = "display_name_priest_hat_0000",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_priest_hat_0000",
	item_type = "hat",
	rarity = "plentiful",
	required_dlc = "bless",
	slot_type = "hat",
	template = "wh_hats",
	unit = "units/beings/player/chr_dummy_hat",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.priest_hat_0001 = {
	description = "description_priest_hat_0001",
	display_name = "display_name_priest_hat_0001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_priest_hat_0001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	template = "wh_hats",
	unit = "units/beings/player/witch_hunter_warrior_priest/headpiece/wh_wp_hat_01",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.priest_hat_0002 = {
	description = "description_priest_hat_0002",
	display_name = "display_name_priest_hat_0002",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_priest_hat_0002",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	template = "wh_hats",
	unit = "units/beings/player/witch_hunter_warrior_priest/headpiece/wh_wp_hat_02",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.priest_hat_0003 = {
	description = "description_priest_hat_0003",
	display_name = "display_name_priest_hat_0003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_priest_hat_0003",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	template = "wh_hats",
	unit = "units/beings/player/witch_hunter_warrior_priest/headpiece/wh_wp_hat_03",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.priest_hat_0004 = {
	description = "description_priest_hat_0004",
	display_name = "display_name_priest_hat_0004",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_priest_hat_0004",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	template = "wh_hats",
	unit = "units/beings/player/witch_hunter_warrior_priest/headpiece/wh_wp_hat_04",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.frame_0107 = {
	description = "frame_0107_description",
	display_name = "frame_0107_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_0107",
	item_type = "frame",
	rarity = "promo",
	required_dlc = "bless",
	slot_type = "frame",
	temporary_template = "frame_0107",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_0108 = {
	description = "frame_0108_description",
	display_name = "frame_0108_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_0108",
	item_type = "frame",
	rarity = "promo",
	required_dlc = "bless",
	slot_type = "frame",
	temporary_template = "frame_0108",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_0109 = {
	description = "frame_0109_description",
	display_name = "frame_0109_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_0109",
	item_type = "frame",
	rarity = "promo",
	required_dlc = "bless",
	slot_type = "frame",
	temporary_template = "frame_0109",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.wh_1h_hammer = {
	description = "wh_1h_hammer_skin_01_description",
	display_name = "wh_1h_hammer_skin_01_name",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_wh_1h_hammer_01",
	item_type = "wh_1h_hammer",
	property_table_name = "melee",
	rarity = "plentiful",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01",
	skin_combination_table = "wh_1h_hammer_skins",
	slot_type = "melee",
	template = "one_handed_hammer_priest_template",
	trait_table_name = "melee",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_1h_hammer_magic_01 = {
	description = "wh_1h_hammer_skin_02_magic_01_description",
	display_name = "wh_1h_hammer_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_1h_hammer_02_magic",
	item_type = "wh_1h_hammer",
	property_table_name = "melee",
	rarity = "magic",
	required_dlc = "bless",
	required_unlock_item = "wh_1h_hammer",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_magic",
	slot_type = "melee",
	template = "one_handed_hammer_priest_template",
	trait_table_name = "melee",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_1h_hammer_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "wh_1h_hammer",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_1h_hammer_skin_01 = {
	description = "wh_1h_hammer_skin_01_description",
	display_name = "wh_1h_hammer_skin_01_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_wpn_wh_1h_hammer_01",
	item_type = "weapon_skin",
	matching_item_key = "wh_1h_hammer",
	rarity = "common",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_1h_hammer_skin_01_runed_01 = {
	description = "wh_1h_hammer_skin_01_runed_01_description",
	display_name = "wh_1h_hammer_skin_01_runed_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_1h_hammer_01_runed",
	item_type = "weapon_skin",
	matching_item_key = "wh_1h_hammer",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01_runed",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_1h_hammer_skin_01_runed_02 = {
	description = "wh_1h_hammer_skin_01_runed_02_description",
	display_name = "wh_1h_hammer_skin_01_runed_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_1h_hammer_01_runed_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_1h_hammer",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01_runed",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_1h_hammer_skin_02 = {
	description = "wh_1h_hammer_skin_02_description",
	display_name = "wh_1h_hammer_skin_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_1h_hammer_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_1h_hammer",
	rarity = "rare",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_1h_hammer_skin_02_runed_01 = {
	description = "wh_1h_hammer_skin_02_runed_01_description",
	display_name = "wh_1h_hammer_skin_02_runed_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_1h_hammer_02_runed",
	item_type = "weapon_skin",
	matching_item_key = "wh_1h_hammer",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_runed",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_1h_hammer_skin_02_runed_02 = {
	description = "wh_1h_hammer_skin_02_runed_02_description",
	display_name = "wh_1h_hammer_skin_02_runed_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_1h_hammer_02_runed_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_1h_hammer",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_runed",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_1h_hammer_skin_02_magic_01 = {
	description = "wh_1h_hammer_skin_02_magic_01_description",
	display_name = "wh_1h_hammer_skin_02_magic_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_1h_hammer_02_magic",
	item_type = "weapon_skin",
	matching_item_key = "wh_1h_hammer",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_magic",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_2h_hammer = {
	description = "wh_2h_hammer_skin_01_description",
	display_name = "wh_2h_hammer_skin_01_name",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_wh_2h_hammer_01",
	item_type = "wh_2h_hammer",
	property_table_name = "melee",
	rarity = "plentiful",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_2h_hammer_01/wpn_wh_2h_hammer_01",
	skin_combination_table = "wh_2h_hammer_skins",
	slot_type = "melee",
	template = "two_handed_hammer_priest_template",
	trait_table_name = "melee",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_2h_hammer_magic_01 = {
	description = "wh_2h_hammer_skin_02_magic_01_description",
	display_name = "wh_2h_hammer_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_2h_hammer_02_magic",
	item_type = "wh_2h_hammer",
	property_table_name = "melee",
	rarity = "magic",
	required_dlc = "bless",
	required_unlock_item = "wh_2h_hammer",
	right_hand_unit = "units/weapons/player/wpn_wh_2h_hammer_02/wpn_wh_2h_hammer_02_magic",
	slot_type = "melee",
	template = "two_handed_hammer_priest_template",
	trait_table_name = "melee",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_2h_hammer_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "wh_2h_hammer",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_2h_hammer_skin_01 = {
	description = "wh_2h_hammer_skin_01_description",
	display_name = "wh_2h_hammer_skin_01_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_wpn_wh_2h_hammer_01",
	item_type = "weapon_skin",
	matching_item_key = "wh_2h_hammer",
	rarity = "common",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_2h_hammer_01/wpn_wh_2h_hammer_01",
	slot_type = "weapon_skin",
	template = "two_handed_hammer_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_2h_hammer_skin_01_runed_01 = {
	description = "wh_2h_hammer_skin_01_runed_01_description",
	display_name = "wh_2h_hammer_skin_01_runed_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_2h_hammer_01_runed",
	item_type = "weapon_skin",
	matching_item_key = "wh_2h_hammer",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_2h_hammer_01/wpn_wh_2h_hammer_01_runed",
	slot_type = "weapon_skin",
	template = "two_handed_hammer_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_2h_hammer_skin_01_runed_02 = {
	description = "wh_2h_hammer_skin_01_runed_02_description",
	display_name = "wh_2h_hammer_skin_01_runed_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_2h_hammer_01_runed_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_2h_hammer",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_2h_hammer_01/wpn_wh_2h_hammer_01_runed",
	slot_type = "weapon_skin",
	template = "two_handed_hammer_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_2h_hammer_skin_02 = {
	description = "wh_2h_hammer_skin_02_description",
	display_name = "wh_2h_hammer_skin_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_2h_hammer_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_2h_hammer",
	rarity = "rare",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_2h_hammer_02/wpn_wh_2h_hammer_02",
	slot_type = "weapon_skin",
	template = "two_handed_hammer_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_2h_hammer_skin_02_runed_01 = {
	description = "wh_2h_hammer_skin_02_runed_01_description",
	display_name = "wh_2h_hammer_skin_02_runed_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_2h_hammer_02_runed",
	item_type = "weapon_skin",
	matching_item_key = "wh_2h_hammer",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_2h_hammer_02/wpn_wh_2h_hammer_02_runed",
	slot_type = "weapon_skin",
	template = "two_handed_hammer_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_2h_hammer_skin_02_runed_02 = {
	description = "wh_2h_hammer_skin_02_runed_02_description",
	display_name = "wh_2h_hammer_skin_02_runed_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_2h_hammer_02_runed_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_2h_hammer",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_2h_hammer_02/wpn_wh_2h_hammer_02_runed",
	slot_type = "weapon_skin",
	template = "two_handed_hammer_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_2h_hammer_skin_02_magic_01 = {
	description = "wh_2h_hammer_skin_02_magic_01_description",
	display_name = "wh_2h_hammer_skin_02_magic_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_2h_hammer_02_magic",
	item_type = "weapon_skin",
	matching_item_key = "wh_2h_hammer",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_2h_hammer_02/wpn_wh_2h_hammer_02_magic",
	slot_type = "weapon_skin",
	template = "two_handed_hammer_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_hammer_shield = {
	description = "wh_hammer_shield_skin_01_description",
	display_name = "wh_hammer_shield_skin_01_name",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_wh_shield_01_t1",
	item_type = "wh_hammer_shield",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1",
	property_table_name = "melee",
	rarity = "plentiful",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01",
	skin_combination_table = "wh_hammer_shield_skins",
	slot_type = "melee",
	template = "one_handed_hammer_shield_priest_template",
	trait_table_name = "melee",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_shield_magic_01 = {
	description = "wh_hammer_shield_skin_02_magic_01_description",
	display_name = "wh_hammer_shield_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_shield_01_t1_magic_hammer02",
	item_type = "wh_hammer_shield",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1_magic",
	property_table_name = "melee",
	rarity = "magic",
	required_dlc = "bless",
	required_unlock_item = "wh_hammer_shield",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_magic",
	slot_type = "melee",
	template = "one_handed_hammer_shield_priest_template",
	trait_table_name = "melee",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_shield_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "wh_hammer_shield",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_shield_skin_01 = {
	description = "wh_hammer_shield_skin_01_description",
	display_name = "wh_hammer_shield_skin_01_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_wpn_wh_shield_01_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1",
	matching_item_key = "wh_hammer_shield",
	rarity = "common",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_shield_priest_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_shield_skin_01_runed_01 = {
	description = "wh_hammer_shield_skin_01_runed_01_description",
	display_name = "wh_hammer_shield_skin_01_runed_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_shield_01_t1_runed",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1_runed",
	matching_item_key = "wh_hammer_shield",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01_runed",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_shield_priest_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_shield_skin_01_runed_02 = {
	description = "wh_hammer_shield_skin_01_runed_02_description",
	display_name = "wh_hammer_shield_skin_01_runed_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_shield_01_t1_runed_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1_runed",
	matching_item_key = "wh_hammer_shield",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01_runed",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_shield_priest_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_shield_skin_02 = {
	description = "wh_hammer_shield_skin_02_description",
	display_name = "wh_hammer_shield_skin_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_shield_01_t1_hammer02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1",
	matching_item_key = "wh_hammer_shield",
	rarity = "rare",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02",
	slot_type = "weapon_skin",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_shield_skin_02_runed_01 = {
	description = "wh_hammer_shield_skin_02_runed_01_description",
	display_name = "wh_hammer_shield_skin_02_runed_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_shield_01_t1_runed_01_hammer02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1_runed",
	matching_item_key = "wh_hammer_shield",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_runed",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_shield_priest_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_shield_skin_02_runed_02 = {
	description = "wh_hammer_shield_skin_02_runed_02_description",
	display_name = "wh_hammer_shield_skin_02_runed_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_shield_01_t1_runed_02_hammer02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1_runed",
	matching_item_key = "wh_hammer_shield",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_runed",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_shield_priest_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_shield_skin_02_magic_01 = {
	description = "wh_hammer_shield_skin_02_magic_01_description",
	display_name = "wh_hammer_shield_skin_02_magic_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_shield_01_t1_magic_hammer02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1_magic",
	matching_item_key = "wh_hammer_shield",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_magic",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_shield_priest_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_flail_shield = {
	description = "wh_flail_shield_skin_01_description",
	display_name = "wh_flail_shield_skin_01_name",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_wh_flail_shield_skin_01_t1",
	item_type = "wh_flail_shield",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1",
	property_table_name = "melee",
	rarity = "plentiful",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_emp_flail_02_t1/wpn_emp_flail_02_t1",
	skin_combination_table = "wh_flail_shield_skins",
	slot_type = "melee",
	template = "one_handed_flail_shield_template",
	trait_table_name = "melee",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_flail_shield_magic_01 = {
	description = "wh_flail_shield_skin_02_magic_01_description",
	display_name = "wh_flail_shield_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_flail_shield_skin_02_magic_01_t1",
	item_type = "wh_flail_shield",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1_magic",
	property_table_name = "melee",
	rarity = "magic",
	required_dlc = "bless",
	required_unlock_item = "wh_flail_shield",
	right_hand_unit = "units/weapons/player/wpn_emp_flail_04_t1/wpn_emp_flail_04_t1_magic_01",
	slot_type = "melee",
	template = "one_handed_flail_shield_template",
	trait_table_name = "melee",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_flail_shield_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "wh_flail_shield",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_flail_shield_skin_01 = {
	description = "wh_flail_shield_skin_01_description",
	display_name = "wh_flail_shield_skin_01_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_wpn_wh_flail_shield_skin_01_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1",
	matching_item_key = "wh_flail_shield",
	rarity = "common",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_emp_flail_01_t1/wpn_emp_flail_01_t1",
	slot_type = "weapon_skin",
	template = "one_handed_flail_shield_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_flail_shield_skin_01_runed_01 = {
	description = "wh_flail_shield_skin_01_runed_01_description",
	display_name = "wh_flail_shield_skin_01_runed_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_flail_shield_skin_01_runed_01_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1_runed",
	matching_item_key = "wh_flail_shield",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_emp_flail_02_t1/wpn_emp_flail_02_t1_runed_01",
	slot_type = "weapon_skin",
	template = "one_handed_flail_shield_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_flail_shield_skin_01_runed_02 = {
	description = "wh_flail_shield_skin_01_runed_02_description",
	display_name = "wh_flail_shield_skin_01_runed_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_flail_shield_skin_01_runed_02_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1_runed",
	matching_item_key = "wh_flail_shield",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_emp_flail_02_t1/wpn_emp_flail_02_t1_runed_01",
	slot_type = "weapon_skin",
	template = "one_handed_flail_shield_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_flail_shield_skin_02 = {
	description = "wh_flail_shield_skin_02_description",
	display_name = "wh_flail_shield_skin_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_flail_shield_skin_02_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1",
	matching_item_key = "wh_flail_shield",
	rarity = "rare",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_emp_flail_05_t1/wpn_emp_flail_05_t1",
	slot_type = "weapon_skin",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_flail_shield_skin_02_runed_01 = {
	description = "wh_flail_shield_skin_02_runed_01_description",
	display_name = "wh_flail_shield_skin_02_runed_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_flail_shield_skin_02_runed_01_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1_runed",
	matching_item_key = "wh_flail_shield",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_emp_flail_05_t1/wpn_emp_flail_05_t1_runed_01",
	slot_type = "weapon_skin",
	template = "one_handed_flail_shield_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_flail_shield_skin_02_runed_02 = {
	description = "wh_flail_shield_skin_02_runed_02_description",
	display_name = "wh_flail_shield_skin_02_runed_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_flail_shield_skin_02_runed_02_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1_runed",
	matching_item_key = "wh_flail_shield",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_emp_flail_05_t1/wpn_emp_flail_05_t1_runed_01",
	slot_type = "weapon_skin",
	template = "one_handed_flail_shield_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_flail_shield_skin_02_magic_01 = {
	description = "wh_flail_shield_skin_02_magic_01_description",
	display_name = "wh_flail_shield_skin_02_magic_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_flail_shield_skin_02_magic_01_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_shield_01/wpn_wh_shield_01_t1_magic",
	matching_item_key = "wh_flail_shield",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_emp_flail_04_t1/wpn_emp_flail_04_t1_magic_01",
	slot_type = "weapon_skin",
	template = "one_handed_flail_shield_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_dual_hammer = {
	description = "wh_dual_hammer_skin_01_description",
	display_name = "wh_dual_hammer_skin_01_name",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_wh_dual_hammer_skin_01_t1",
	item_type = "wh_dual_hammer",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01",
	property_table_name = "melee",
	rarity = "plentiful",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01",
	skin_combination_table = "wh_dual_hammer_skins",
	slot_type = "melee",
	template = "dual_wield_hammers_priest_template",
	trait_table_name = "melee",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_dual_hammer_magic_01 = {
	description = "wh_dual_hammer_skin_02_magic_01_description",
	display_name = "wh_dual_hammer_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_wh_dual_hammer_skin_02_magic_01_t1",
	item_type = "wh_dual_hammer",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_magic",
	property_table_name = "melee",
	rarity = "magic",
	required_dlc = "bless",
	required_unlock_item = "wh_dual_hammer",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_magic",
	slot_type = "melee",
	template = "dual_wield_hammers_priest_template",
	trait_table_name = "melee",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_dual_hammer_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "wh_dual_hammer",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_dual_hammer_skin_01 = {
	description = "wh_dual_hammer_skin_01_description",
	display_name = "wh_dual_hammer_skin_01_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_wpn_wh_dual_hammer_skin_01_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01",
	matching_item_key = "wh_dual_hammer",
	rarity = "common",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01",
	slot_type = "weapon_skin",
	template = "dual_wield_hammers_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_dual_hammer_skin_01_runed_01 = {
	description = "wh_dual_hammer_skin_01_runed_01_description",
	display_name = "wh_dual_hammer_skin_01_runed_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_dual_hammer_skin_01_runed_01_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01_runed",
	matching_item_key = "wh_dual_hammer",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01_runed",
	slot_type = "weapon_skin",
	template = "dual_wield_hammers_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_dual_hammer_skin_01_runed_02 = {
	description = "wh_dual_hammer_skin_01_runed_02_description",
	display_name = "wh_dual_hammer_skin_01_runed_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_dual_hammer_skin_01_runed_02_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01_runed",
	matching_item_key = "wh_dual_hammer",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01_runed",
	slot_type = "weapon_skin",
	template = "dual_wield_hammers_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_dual_hammer_skin_02 = {
	description = "wh_dual_hammer_skin_02_description",
	display_name = "wh_dual_hammer_skin_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_dual_hammer_skin_02_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02",
	matching_item_key = "wh_dual_hammer",
	rarity = "rare",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02",
	slot_type = "weapon_skin",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_dual_hammer_skin_02_runed_01 = {
	description = "wh_dual_hammer_skin_02_runed_01_description",
	display_name = "wh_dual_hammer_skin_02_runed_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_dual_hammer_skin_02_runed_01_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_runed",
	matching_item_key = "wh_dual_hammer",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_runed",
	slot_type = "weapon_skin",
	template = "dual_wield_hammers_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_dual_hammer_skin_02_runed_02 = {
	description = "wh_dual_hammer_skin_02_runed_02_description",
	display_name = "wh_dual_hammer_skin_02_runed_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_dual_hammer_skin_02_runed_02_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_runed",
	matching_item_key = "wh_dual_hammer",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_runed",
	slot_type = "weapon_skin",
	template = "dual_wield_hammers_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_dual_hammer_skin_02_magic_01 = {
	description = "wh_dual_hammer_skin_02_magic_01_description",
	display_name = "wh_dual_hammer_skin_02_magic_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_dual_hammer_skin_02_magic_01_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_magic",
	matching_item_key = "wh_dual_hammer",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_magic",
	slot_type = "weapon_skin",
	template = "dual_wield_hammers_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_hammer_book = {
	description = "wh_hammer_book_skin_01_description",
	display_name = "wh_hammer_book_skin_01_name",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_wh_hammer_book_skin_01_t1",
	item_type = "wh_hammer_book",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01",
	property_table_name = "melee",
	rarity = "plentiful",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_book_02/wpn_wh_book_02",
	skin_combination_table = "wh_hammer_book_skins",
	slot_type = "melee",
	template = "one_handed_hammer_book_priest_template",
	trait_table_name = "melee",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_book_magic_01 = {
	description = "wh_hammer_book_skin_02_magic_01_description",
	display_name = "wh_hammer_book_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_wh_hammer_book_skin_02_magic_01_t1",
	item_type = "wh_hammer_book",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_magic",
	property_table_name = "melee",
	rarity = "magic",
	required_dlc = "bless",
	required_unlock_item = "wh_hammer_book",
	right_hand_unit = "units/weapons/player/wpn_wh_book_02/wpn_wh_book_02_magic",
	slot_type = "melee",
	template = "one_handed_hammer_book_priest_template",
	trait_table_name = "melee",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_book_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "wh_hammer_book",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_book_skin_01 = {
	description = "wh_hammer_book_skin_01_description",
	display_name = "wh_hammer_book_skin_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_hammer_book_skin_01_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01",
	matching_item_key = "wh_hammer_book",
	rarity = "rare",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_book_02/wpn_wh_book_02",
	slot_type = "weapon_skin",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_book_skin_01_runed_01 = {
	description = "wh_hammer_book_skin_01_runed_01_description",
	display_name = "wh_hammer_book_skin_01_runed_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_hammer_book_skin_01_runed_01_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01_runed",
	matching_item_key = "wh_hammer_book",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_book_02/wpn_wh_book_02_runed",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_book_priest_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_book_skin_01_runed_02 = {
	description = "wh_hammer_book_skin_01_runed_02_description",
	display_name = "wh_hammer_book_skin_01_runed_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_hammer_book_skin_01_runed_02_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01_runed",
	matching_item_key = "wh_hammer_book",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_book_02/wpn_wh_book_02_runed",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_book_priest_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_book_skin_02 = {
	description = "wh_hammer_book_skin_02_description",
	display_name = "wh_hammer_book_skin_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_hammer_book_skin_02_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02",
	matching_item_key = "wh_hammer_book",
	rarity = "rare",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_book_02/wpn_wh_book_02",
	slot_type = "weapon_skin",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_book_skin_02_runed_01 = {
	description = "wh_hammer_book_skin_02_runed_01_description",
	display_name = "wh_hammer_book_skin_02_runed_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_hammer_book_skin_02_runed_01_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_runed",
	matching_item_key = "wh_hammer_book",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_book_02/wpn_wh_book_02_runed",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_book_priest_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_book_skin_02_runed_02 = {
	description = "wh_hammer_book_skin_02_runed_02_description",
	display_name = "wh_hammer_book_skin_02_runed_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_hammer_book_skin_02_runed_02_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_runed",
	matching_item_key = "wh_hammer_book",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_book_02/wpn_wh_book_02_runed",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_book_priest_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_hammer_book_skin_02_magic_01 = {
	description = "wh_hammer_book_skin_02_magic_01_description",
	display_name = "wh_hammer_book_skin_02_magic_01_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_wh_hammer_book_skin_02_magic_01_t1",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_02/wpn_wh_1h_hammer_02_magic",
	matching_item_key = "wh_hammer_book",
	rarity = "unique",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_book_02/wpn_wh_book_02_magic",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_book_priest_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.shilling_bag_bless = {
	description = "shilling_bag_100_description",
	display_name = "shilling_bag_100_name",
	information_text = "information_text_shilling",
	inventory_icon = "icon_shillings_06",
	item_type = "chips",
	rarity = "common",
	slot_type = "chips",
	can_wield = CanWieldAllItemTemplates,
	bundle = {
		BundledVirtualCurrencies = {
			SM = 100,
		},
	},
}
ItemMasterList.shilling_bag_bless_upgrade = {
	description = "shilling_bag_100_description",
	display_name = "shilling_bag_100_name",
	information_text = "information_text_shilling",
	inventory_icon = "icon_shillings_06",
	item_type = "chips",
	rarity = "common",
	slot_type = "chips",
	can_wield = CanWieldAllItemTemplates,
	bundle = {
		BundledVirtualCurrencies = {
			SM = 225,
		},
	},
}
ItemMasterList.wh_priest_career_skill_weapon = {
	is_local = true,
	rarity = "plentiful",
	right_hand_unit = "units/weapons/player/wpn_wh_book_01/wpn_wh_book_01",
	template = "wh_priest_career_skill_weapon",
	can_wield = {},
}
ItemMasterList.wh_priest_career_weapon_preview = {
	description = "wh_hammer_book_description",
	display_name = "wh_hammer_book_name",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_wpn_wh_hammer_book_skin_01_t1",
	is_local = true,
	item_type = "wh_hammer_book",
	left_hand_unit = "units/weapons/player/wpn_wh_book_02/wpn_wh_book_02",
	property_table_name = "melee",
	rarity = "plentiful",
	required_dlc = "bless",
	right_hand_unit = "units/weapons/player/wpn_wh_1h_hammer_01/wpn_wh_1h_hammer_01",
	slot_type = "melee",
	template = "one_handed_hammer_book_priest_preview_template",
	trait_table_name = "melee",
	can_wield = {
		"wh_priest",
	},
}

UpdateItemMasterList({
	"bountyhunter_hat_1010",
}, "wh_priest")
