-- chunkname: @scripts/settings/dlcs/lake/item_master_list_lake.lua

ItemMasterList.skin_es_questingknight = {
	description = "description_skin_es_questing_knight_default",
	display_name = "display_name_skin_es_questing_knight_default",
	hud_icon = "unit_frame_portrait_empire_soldier",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_questingknight",
	item_type = "skin",
	name = "skin_es_questingknight",
	rarity = "plentiful",
	required_dlc = "lake_upgrade",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_es_questingknight",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.skin_es_questingknight_black_and_gold = {
	description = "description_skin_es_questingknight_black_and_gold",
	display_name = "display_name_es_questingknight_black_and_gold",
	hud_icon = "unit_frame_portrait_empire_soldier",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_questingknight_black_and_gold",
	item_type = "skin",
	name = "skin_es_questingknight_black_and_gold",
	rarity = "promo",
	required_dlc = "lake_upgrade",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_es_questingknight_black_and_gold",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.skin_es_questingknight_black_and_yellow = {
	description = "description_skin_es_questingknight_black_and_yellow",
	display_name = "display_name_es_questingknight_black_and_yellow",
	hud_icon = "unit_frame_portrait_empire_soldier",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_questingknight_black_and_yellow",
	item_type = "skin",
	name = "skin_es_questingknight_black_and_yellow",
	rarity = "promo",
	required_dlc = "lake_upgrade",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_es_questingknight_black_and_yellow",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.skin_es_questingknight_blue_and_white = {
	description = "description_skin_es_questing_knight_blue_and_white",
	display_name = "display_name_skin_es_questing_knight_blue_and_white",
	hud_icon = "unit_frame_portrait_empire_soldier",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_questingknight_blue_and_white",
	item_type = "skin",
	name = "skin_es_questingknight_blue_and_white",
	rarity = "plentiful",
	required_dlc = "lake",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_es_questingknight_blue_and_white",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.skin_es_questingknight_yellow_and_white = {
	description = "description_skin_es_questing_knight_yellow_and_white",
	display_name = "display_name_skin_es_questing_knight_yellow_and_white",
	hud_icon = "unit_frame_portrait_empire_soldier",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_questingknight_yellow_and_white",
	item_type = "skin",
	name = "skin_es_questingknight_yellow_and_white",
	rarity = "promo",
	required_dlc = "lake_upgrade",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_es_questingknight_yellow_and_white",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.skin_es_questingknight_white = {
	description = "description_skin_es_questingknight_white",
	display_name = "skin_es_questingknight_white",
	hud_icon = "unit_frame_portrait_empire_soldier",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_questingknight_white",
	item_type = "skin",
	name = "skin_es_questingknight_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_es_questingknight_white",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.markus_questingknight_career_skill_weapon = {
	is_local = true,
	rarity = "plentiful",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_ability/wpn_emp_gk_sword_ability",
	slot_type = "melee",
	template = "markus_questingknight_career_skill_weapon",
	can_wield = {},
}
ItemMasterList.questing_knight_hat_0000 = {
	description = "description_questing_knight_hat_0000",
	display_name = "display_name_questing_knight_hat_0000",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_questing_knight_hat_0000",
	item_type = "hat",
	rarity = "plentiful",
	required_dlc = "lake",
	slot_type = "hat",
	template = "es_hats_no_ear_moustache",
	unit = "units/beings/player/empire_soldier_breton/headpiece/es_gk_hat_01",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.questing_knight_hat_0001 = {
	description = "description_questing_knight_hat_0001",
	display_name = "display_name_questing_knight_hat_0001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_questing_knight_hat_0001",
	item_type = "hat",
	rarity = "promo",
	required_dlc = "lake_upgrade",
	slot_type = "hat",
	template = "es_hats_no_ear_moustache",
	unit = "units/beings/player/empire_soldier_breton/headpiece/es_gk_hat_02",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.questing_knight_hat_0003 = {
	description = "description_questing_knight_hat_0003",
	display_name = "display_name_questing_knight_hat_0003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_questing_knight_hat_0003",
	item_type = "hat",
	rarity = "promo",
	required_dlc = "lake_upgrade",
	slot_type = "hat",
	template = "es_hats_no_ear_moustache",
	unit = "units/beings/player/empire_soldier_breton/headpiece/es_gk_hat_03",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.frame_0097 = {
	description = "frame_0097_description",
	display_name = "frame_0097_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_0097",
	item_type = "frame",
	rarity = "promo",
	required_dlc = "lake_upgrade",
	slot_type = "frame",
	temporary_template = "frame_0097",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_0098 = {
	description = "frame_0098_description",
	display_name = "frame_0098_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_0098",
	item_type = "frame",
	rarity = "promo",
	required_dlc = "lake_upgrade",
	slot_type = "frame",
	temporary_template = "frame_0098",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.es_bastard_sword = {
	description = "es_bastard_sword_skin_01_description",
	display_name = "es_bastard_sword_skin_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_sword",
	inventory_icon = "icon_wpn_emp_gk_sword_01_t1",
	item_type = "es_bastard_sword",
	property_table_name = "melee",
	rarity = "plentiful",
	required_dlc = "lake",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_01_t1/wpn_emp_gk_sword_01_t1",
	skin_combination_table = "es_bastard_sword_skins",
	slot_type = "melee",
	template = "bastard_sword_template",
	trait_table_name = "melee",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
		"es_questingknight",
	},
}
ItemMasterList.es_bastard_sword_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "es_bastard_sword",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
		"es_questingknight",
	},
}
ItemMasterList.es_bastard_sword_preview = {
	description = "es_bastard_sword_skin_01_description",
	display_name = "es_bastard_sword_skin_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_sword",
	inventory_icon = "icons_placeholder",
	item_type = "es_bastard_sword",
	property_table_name = "melee",
	rarity = "plentiful",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_03_t1/wpn_emp_gk_sword_03_t1",
	slot_type = "melee",
	template = "bastard_sword_template",
	trait_table_name = "melee",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
		"es_questingknight",
	},
}
ItemMasterList.es_bastard_sword_skin_01 = {
	description = "es_bastard_sword_skin_01_description",
	display_name = "es_bastard_sword_skin_01_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_gk_sword_01_t1",
	item_type = "weapon_skin",
	matching_item_key = "es_bastard_sword",
	rarity = "common",
	required_dlc = "lake",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_01_t1/wpn_emp_gk_sword_01_t1",
	slot_type = "weapon_skin",
	template = "bastard_sword_template",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
		"es_questingknight",
	},
}
ItemMasterList.es_bastard_sword_skin_02 = {
	description = "es_bastard_sword_skin_02_description",
	display_name = "es_bastard_sword_skin_02_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_gk_sword_01_t2",
	item_type = "weapon_skin",
	matching_item_key = "es_bastard_sword",
	rarity = "rare",
	required_dlc = "lake_upgrade",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_01_t2/wpn_emp_gk_sword_01_t2",
	slot_type = "weapon_skin",
	template = "bastard_sword_template",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
		"es_questingknight",
	},
}
ItemMasterList.es_bastard_sword_skin_03 = {
	description = "es_bastard_sword_skin_03_description",
	display_name = "es_bastard_sword_skin_03_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_gk_sword_02_t1",
	item_type = "weapon_skin",
	matching_item_key = "es_bastard_sword",
	rarity = "exotic",
	required_dlc = "lake_upgrade",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_02_t1/wpn_emp_gk_sword_02_t1",
	slot_type = "weapon_skin",
	template = "bastard_sword_template",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
		"es_questingknight",
	},
}
ItemMasterList.es_bastard_sword_skin_03_runed_01 = {
	description = "es_bastard_sword_skin_03_runed_01_description",
	display_name = "es_bastard_sword_skin_03_runed_01_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_gk_sword_02_t1_runed_01",
	item_type = "weapon_skin",
	matching_item_key = "es_bastard_sword",
	rarity = "unique",
	required_dlc = "lake_upgrade",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_02_t1/wpn_emp_gk_sword_02_t1_runed_01",
	slot_type = "weapon_skin",
	template = "bastard_sword_template",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
		"es_questingknight",
	},
}
ItemMasterList.es_bastard_sword_skin_03_runed_02 = {
	description = "es_bastard_sword_skin_03_runed_02_description",
	display_name = "es_bastard_sword_skin_03_runed_02_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_gk_sword_02_t1_runed_02",
	item_type = "weapon_skin",
	matching_item_key = "es_bastard_sword",
	rarity = "unique",
	required_dlc = "lake_upgrade",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_02_t1/wpn_emp_gk_sword_02_t1_runed_01",
	slot_type = "weapon_skin",
	template = "bastard_sword_template",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
		"es_questingknight",
	},
}
ItemMasterList.es_bastard_sword_skin_04 = {
	description = "es_bastard_sword_skin_04_description",
	display_name = "es_bastard_sword_skin_04_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_gk_sword_02_t1",
	item_type = "weapon_skin",
	matching_item_key = "es_bastard_sword",
	rarity = "exotic",
	required_dlc = "lake_upgrade",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_02_t2/wpn_emp_gk_sword_02_t2",
	slot_type = "weapon_skin",
	template = "bastard_sword_template",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
		"es_questingknight",
	},
}
ItemMasterList.es_bastard_sword_skin_04_magic_01 = {
	description = "es_bastard_sword_skin_04_description",
	display_name = "es_bastard_sword_skin_04_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_gk_sword_02_t2_magic_01",
	item_type = "weapon_skin",
	matching_item_key = "es_bastard_sword",
	rarity = "magic",
	required_dlc = "lake",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_02_t2/wpn_emp_gk_sword_02_t2_magic_01",
	slot_type = "weapon_skin",
	template = "bastard_sword_template",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
		"es_questingknight",
	},
}
ItemMasterList.es_bastard_sword_magic_01 = {
	description = "es_bastard_sword_skin_05_magic_01_description",
	display_name = "es_bastard_sword_skin_05_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_sword",
	inventory_icon = "icon_wpn_emp_gk_sword_02_t2_magic_01",
	item_type = "es_bastard_sword",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "es_bastard_sword",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_02_t2/wpn_emp_gk_sword_02_t2_magic_01",
	slot_type = "melee",
	template = "bastard_sword_template",
	trait_table_name = "melee",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
		"es_questingknight",
	},
}
ItemMasterList.es_sword_shield_breton = {
	description = "es_sword_shield_breton_skin_01_description",
	display_name = "es_sword_shield_breton_skin_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_sword_and_sheild",
	inventory_icon = "icon_wpn_emp_gk_sword_01_t1_wpn_emp_gk_shield_03",
	item_type = "es_1h_sword_shield_breton",
	left_hand_unit = "units/weapons/player/wpn_emp_gk_shield_03/wpn_emp_gk_shield_03",
	property_table_name = "melee",
	rarity = "plentiful",
	required_dlc = "lake",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_01_t1/wpn_emp_gk_sword_01_t1",
	skin_combination_table = "es_sword_shield_breton_skins",
	slot_type = "melee",
	template = "one_handed_sword_shield_template_2",
	trait_table_name = "melee",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.es_sword_shield_breton_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "es_sword_shield_breton",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.es_sword_shield_breton_skin_01 = {
	description = "es_sword_shield_breton_skin_02_description",
	display_name = "es_sword_shield_breton_skin_02_name",
	display_unit = "units/weapons/weapon_display/display_shield_sword",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_gk_sword_01_t1_wpn_emp_gk_shield_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_emp_gk_shield_02/wpn_emp_gk_shield_02",
	matching_item_key = "es_sword_shield_breton",
	rarity = "common",
	required_dlc = "lake_upgrade",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_01_t1/wpn_emp_gk_sword_01_t1",
	slot_type = "weapon_skin",
	template = "one_handed_sword_shield_template_2",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.es_sword_shield_breton_skin_02 = {
	description = "es_sword_shield_breton_skin_03_description",
	display_name = "es_sword_shield_breton_skin_03_name",
	display_unit = "units/weapons/weapon_display/display_shield_sword",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_gk_sword_01_t2_wpn_emp_gk_shield_04",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_emp_gk_shield_04/wpn_emp_gk_shield_04",
	matching_item_key = "es_sword_shield_breton",
	rarity = "rare",
	required_dlc = "lake_upgrade",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_01_t2/wpn_emp_gk_sword_01_t2",
	slot_type = "weapon_skin",
	template = "one_handed_sword_shield_template_2",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.es_sword_shield_breton_skin_03 = {
	description = "es_sword_shield_breton_skin_04_description",
	display_name = "es_sword_shield_breton_skin_04_name",
	display_unit = "units/weapons/weapon_display/display_shield_sword",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_gk_sword_02_t1_wpn_emp_gk_shield_05",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_emp_gk_shield_05/wpn_emp_gk_shield_05",
	matching_item_key = "es_sword_shield_breton",
	rarity = "exotic",
	required_dlc = "lake_upgrade",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_02_t1/wpn_emp_gk_sword_02_t1",
	slot_type = "weapon_skin",
	template = "one_handed_sword_shield_template_2",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.es_sword_shield_breton_skin_03_runed_01 = {
	description = "es_sword_shield_breton_skin_03_runed_01_description",
	display_name = "es_sword_shield_breton_skin_03_runed_01_name",
	display_unit = "units/weapons/weapon_display/display_shield_sword",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_gk_sword_02_t1_runed_01_wpn_emp_gk_shield_02_runed_01",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_emp_gk_shield_02/wpn_emp_gk_shield_02_runed_01",
	matching_item_key = "es_sword_shield_breton",
	rarity = "unique",
	required_dlc = "lake_upgrade",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_02_t1/wpn_emp_gk_sword_02_t1_runed_01",
	slot_type = "weapon_skin",
	template = "one_handed_sword_shield_template_2",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.es_sword_shield_breton_skin_03_runed_02 = {
	description = "es_sword_shield_breton_skin_03_runed_02_description",
	display_name = "es_sword_shield_breton_skin_03_runed_02_name",
	display_unit = "units/weapons/weapon_display/display_shield_sword",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_gk_sword_02_t1_runed_01_wpn_emp_gk_shield_02_runed_02",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_emp_gk_shield_02/wpn_emp_gk_shield_02_runed_01",
	matching_item_key = "es_sword_shield_breton",
	rarity = "unique",
	required_dlc = "lake_upgrade",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_02_t1/wpn_emp_gk_sword_02_t1_runed_01",
	slot_type = "weapon_skin",
	template = "one_handed_sword_shield_template_2",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.es_sword_shield_breton_skin_04 = {
	description = "es_sword_shield_breton_skin_05_description",
	display_name = "es_sword_shield_breton_skin_05_name",
	display_unit = "units/weapons/weapon_display/display_shield_sword",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_gk_sword_02_t2_wpn_emp_gk_shield_01",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_emp_gk_shield_01/wpn_emp_gk_shield_01",
	matching_item_key = "es_sword_shield_breton",
	rarity = "exotic",
	required_dlc = "lake_upgrade",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_02_t2/wpn_emp_gk_sword_02_t2",
	slot_type = "weapon_skin",
	template = "one_handed_sword_shield_template_2",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.es_sword_shield_breton_skin_04_magic_01_magic_01 = {
	description = "es_sword_shield_breton_skin_05_magic_01_description",
	display_name = "es_sword_shield_breton_skin_05_magic_01_name",
	display_unit = "units/weapons/weapon_display/display_shield_sword",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_gk_sword_02_t2_wpn_emp_gk_shield_01_magic_01",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_emp_gk_shield_01/wpn_emp_gk_shield_01_magic_01",
	matching_item_key = "es_sword_shield_breton",
	rarity = "magic",
	required_dlc = "lake",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_02_t2/wpn_emp_gk_sword_02_t2_magic_01",
	slot_type = "weapon_skin",
	template = "one_handed_sword_shield_template_2",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.es_sword_shield_breton_skin_05 = {
	description = "es_sword_shield_breton_skin_01_description",
	display_name = "es_sword_shield_breton_skin_01_name",
	display_unit = "units/weapons/weapon_display/display_shield_sword",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_gk_sword_01_t1_wpn_emp_gk_shield_03",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_emp_gk_shield_03/wpn_emp_gk_shield_03",
	matching_item_key = "es_sword_shield_breton",
	rarity = "plentiful",
	required_dlc = "lake",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_01_t1/wpn_emp_gk_sword_01_t1",
	slot_type = "weapon_skin",
	template = "one_handed_sword_shield_template_2",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.es_sword_shield_breton_magic_01 = {
	description = "es_sword_shield_breton_skin_05_magic_01_description",
	display_name = "es_sword_shield_breton_skin_05_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_sword_and_sheild",
	inventory_icon = "icon_wpn_emp_gk_sword_02_t2_wpn_emp_gk_shield_01_magic_01",
	item_type = "es_1h_sword_shield_breton",
	left_hand_unit = "units/weapons/player/wpn_emp_gk_shield_01/wpn_emp_gk_shield_01_magic_01",
	property_table_name = "melee",
	rarity = "magic",
	required_dlc = "lake",
	required_unlock_item = "es_sword_shield_breton",
	right_hand_unit = "units/weapons/player/wpn_emp_gk_sword_02_t2/wpn_emp_gk_sword_02_t2_magic_01",
	slot_type = "melee",
	template = "one_handed_sword_shield_template_2",
	trait_table_name = "melee",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.shilling_bag_lake = {
	description = "shilling_bag_100_description",
	display_name = "shilling_bag_100_name",
	information_text = "information_text_shilling",
	inventory_icon = "icon_shillings_06",
	item_type = "chips",
	rarity = "common",
	slot_type = "chips",
	can_wield = CanWieldAllItemTemplates,
	bundle = {
		BundledVirtualCurrencies = {
			SM = 100,
		},
	},
}
ItemMasterList.shilling_bag_lake_upgrade = {
	description = "shilling_bag_100_description",
	display_name = "shilling_bag_100_name",
	information_text = "information_text_shilling",
	inventory_icon = "icon_shillings_06",
	item_type = "chips",
	rarity = "common",
	slot_type = "chips",
	can_wield = CanWieldAllItemTemplates,
	bundle = {
		BundledVirtualCurrencies = {
			SM = 225,
		},
	},
}

UpdateItemMasterList({
	"es_1h_sword",
	"es_1h_mace",
	"es_2h_sword_executioner",
	"es_2h_sword",
	"es_2h_hammer",
	"es_sword_shield",
	"es_mace_shield",
	"es_dual_wield_hammer_sword",
	"es_1h_sword_magic_01",
	"es_1h_mace_magic_01",
	"es_2h_sword_executioner_magic_01",
	"es_2h_sword_magic_01",
	"es_2h_hammer_magic_01",
	"es_sword_shield_magic_01",
	"es_mace_shield_magic_01",
	"es_dual_wield_hammer_sword_magic_01",
}, "es_questingknight")
