-- chunkname: @scripts/settings/breeds/breed_beastmen_minotaur.lua

local stagger_types = require("scripts/utils/stagger_types")
local default_bot_threat_difficulty_data = BotConstants and BotConstants.default.DEFAULT_BOT_THREAT_DIFFICULTY_DATA
local breed_data = {
	ai_strength = 10,
	ai_toughness = 10,
	animation_movement_template = "beastmen_minotaur",
	animation_sync_rpc = "rpc_sync_anim_state_5",
	aoe_height = 2.4,
	aoe_radius = 1,
	armor_category = 3,
	awards_positive_reinforcement_message = true,
	base_unit = "units/beings/enemies/beastmen_minotaur/chr_beastmen_minotaur",
	behavior = "minotaur",
	bone_lod_level = 0,
	boost_curve_multiplier_override = 1.5,
	boss = true,
	boss_damage_reduction = true,
	boss_staggers = true,
	bot_hitbox_radius_approximation = 0.75,
	bot_opportunity_target_melee_range = 7,
	bot_opportunity_target_melee_range_while_ranged = 5,
	bots_should_flank = true,
	catch_up_speed = 12,
	combat_music_state = "minotaur",
	death_reaction = "minotaur",
	death_sound_event = "Play_enemy_minotaur_die_vce",
	default_inventory_template = "beastmen_minotaur_dual_axes",
	detection_radius = 9999999,
	disable_crowd_dispersion = true,
	distance_sq_can_detect_target = 2025,
	distance_sq_idle_auto_detect_target = 49,
	exchange_order = 1,
	far_off_despawn_immunity = true,
	has_inventory = true,
	headshot_coop_stamina_fatigue_type = "headshot_special",
	height = 3,
	hit_effect_template = "HitEffectsChaosSpawn",
	hit_mass_count = 50,
	hit_reaction = "ai_default",
	ignore_nav_propagation_box = true,
	is_always_spawnable = true,
	is_bot_aid_threat = true,
	minion_detection_radius = 10,
	navigation_spline_distance_to_borders = 1,
	no_stagger_duration = false,
	override_mover_move_distance = 1.5,
	panic_close_detection_radius_sq = 9,
	passive_in_patrol = true,
	passive_in_patrol_start_anim = "move_fwd",
	patrol_active_perception = "perception_rat_ogre",
	patrol_active_target_selection = "pick_rat_ogre_target_with_weights",
	patrol_detection_radius = 10,
	patrol_passive_perception = "perception_rat_ogre",
	patrol_passive_target_selection = "patrol_passive_target_selection",
	patrol_walk_speed = 2.5,
	perception = "perception_rat_ogre",
	perception_continuous = "perception_continuous_rat_ogre",
	player_locomotion_constrain_radius = 1.5,
	poison_resistance = 100,
	proximity_system_check = true,
	race = "beastmen",
	radius = 2,
	reach_distance = 3,
	run_speed = 6,
	show_health_bar = true,
	slot_template = "boss",
	smart_object_template = "rat_ogre",
	smart_targeting_height_multiplier = 1.5,
	smart_targeting_outer_width = 1.4,
	smart_targeting_width = 0.6,
	stagger_resistance = 100,
	stagger_threshold_explosion = 1,
	stagger_threshold_heavy = 1,
	stagger_threshold_light = 1,
	stagger_threshold_medium = 1,
	target_selection = "pick_rat_ogre_target_idle",
	target_selection_angry = "pick_rat_ogre_target_with_weights",
	threat_value = 32,
	trigger_dialogue_on_target_switch = true,
	unit_template = "ai_unit_beastmen_minotaur",
	use_aggro = true,
	use_charge_nav_layers = false,
	use_navigation_path_splines = true,
	walk_speed = 5,
	wield_inventory_on_spawn = true,
	infighting = InfightingSettings.boss,
	perception_weights = {
		aggro_decay_per_sec = 1,
		distance_weight = 100,
		max_distance = 50,
		old_target_aggro_mul = 1,
		target_catapulted_mul = 1.5,
		target_disabled_aggro_mul = 0,
		target_disabled_mul = 0.15,
		target_outside_navmesh_mul = 0.5,
		target_staggered_you_bonus = 100,
		target_stickyness_bonus_a = 50,
		target_stickyness_bonus_b = 10,
		target_stickyness_duration_a = 5,
		target_stickyness_duration_b = 20,
		targeted_by_other_special = -10,
	},
	navigation_path_spline_config = {
		channel_smoothing_anle = 20,
		max_distance_between_gates = 5,
		max_distance_to_spline_position = 5,
		min_distance_between_gates = 0.5,
		navigation_channel_radius = 6,
		spline_distance_to_borders = 5,
		spline_recomputation_ratio = 0.5,
		turn_sampling_angle = 25,
	},
	max_health = BreedTweaks.max_health.rat_ogre,
	bloodlust_health = BreedTweaks.bloodlust_health.monster,
	stagger_duration = {
		0,
		0,
		0,
		0,
		0,
		3,
		0,
		1,
	},
	status_effect_settings = {
		category = "large",
		ignored_statuses = table.set({
			StatusEffectNames.burning_warpfire,
		}),
	},
	debug_color = {
		255,
		20,
		20,
		20,
	},
	run_on_spawn = AiBreedSnippets.on_beastmen_minotaur_spawn,
	run_on_update = AiBreedSnippets.on_beastmen_minotaur_update,
	run_on_death = AiBreedSnippets.on_beastmen_minotaur_death,
	run_on_despawn = AiBreedSnippets.on_beastmen_minotaur_death,
	blackboard_init_data = {
		ladder_distance = math.huge,
	},
	hitzone_multiplier_types = {
		head = "headshot",
	},
	hit_zones = {
		head = {
			prio = 1,
			actors = {
				"c_head",
			},
			push_actors = {
				"j_head",
				"j_spine1",
			},
		},
		neck = {
			prio = 1,
			actors = {
				"c_neck",
			},
			push_actors = {
				"j_head",
				"j_spine1",
			},
		},
		torso = {
			prio = 2,
			actors = {
				"c_spine",
				"c_spine1",
				"c_hips",
				"c_leftshoulder",
				"c_rightshoulder",
			},
			push_actors = {
				"j_spine1",
				"j_hips",
			},
		},
		left_arm = {
			prio = 3,
			actors = {
				"c_leftarm",
				"c_leftforearm",
				"c_lefthand",
			},
			push_actors = {
				"j_leftarm",
				"j_leftforearm",
				"j_lefthand",
			},
		},
		right_arm = {
			prio = 3,
			actors = {
				"c_rightarm",
				"c_rightforearm",
				"c_righthand",
			},
			push_actors = {
				"j_rightarm",
				"j_rightforearm",
				"j_righthand",
			},
		},
		left_leg = {
			prio = 3,
			actors = {
				"c_leftupleg",
				"c_leftleg",
				"c_leftfoot",
				"c_lefttoebase",
			},
			push_actors = {
				"j_leftupleg",
				"j_leftleg",
				"j_leftfoot",
			},
		},
		right_leg = {
			prio = 3,
			actors = {
				"c_rightupleg",
				"c_rightleg",
				"c_rightfoot",
				"c_righttoebase",
			},
			push_actors = {
				"j_rightupleg",
				"j_rightleg",
				"j_rightfoot",
			},
		},
		full = {
			prio = 4,
			actors = {},
		},
		afro = {
			prio = 5,
			actors = {
				"c_afro",
			},
		},
	},
	allowed_layers = {
		big_boy_destructible = 1.5,
		bot_poison_wind = 1.5,
		bot_ratling_gun_fire = 15,
		destructible_wall = 0,
		doors = 1.5,
		fire_grenade = 15,
		jumps = 1.5,
		ledges = 1.5,
		ledges_with_fence = 1.5,
		planks = 1.5,
		teleporters = 5,
		temporary_wall = 0,
	},
	nav_cost_map_allowed_layers = {
		lamp_oil_fire = 15,
		plague_wave = 1,
		stormfiend_warpfire = 1,
		troll_bile = 1,
		vortex_danger_zone = 1,
		vortex_near = 1,
		warpfire_thrower_warpfire = 1,
	},
}

Breeds.beastmen_minotaur = table.create_copy(Breeds.beastmen_minotaur, breed_data)

local pushed_data = {
	ahead_dist = 1,
	player_pushed_speed = 7,
	push_forward_offset = 1,
	push_stagger_distance = 1,
	push_width = 3,
	push_stagger_impact = {
		stagger_types.medium,
		stagger_types.medium,
		stagger_types.none,
		stagger_types.none,
	},
	push_stagger_duration = {
		1.5,
		1,
		0,
		0,
	},
}
local AttackIntensityPerDifficulty = {
	melee_slam = {
		easy = {
			normal = 5,
			running = 2,
		},
		normal = {
			normal = 5,
			running = 2,
		},
		hard = {
			normal = 5,
			running = 2,
		},
		harder = {
			normal = 5,
			running = 2,
		},
		hardest = {
			normal = 5,
			running = 2,
		},
		cataclysm = {
			normal = 5,
			running = 2,
		},
		cataclysm_2 = {
			normal = 5,
			running = 2,
		},
		cataclysm_3 = {
			normal = 5,
			running = 2,
		},
		versus_base = {
			normal = 5,
			running = 2,
		},
	},
	combo = {
		easy = {
			normal = 3,
			running = 0.5,
		},
		normal = {
			normal = 3,
			running = 0.5,
		},
		hard = {
			normal = 3,
			running = 0.5,
		},
		harder = {
			normal = 3,
			running = 0.5,
		},
		hardest = {
			normal = 3,
			running = 0.5,
		},
		cataclysm = {
			normal = 3,
			running = 0.5,
		},
		cataclysm_2 = {
			normal = 3,
			running = 0.5,
		},
		cataclysm_3 = {
			normal = 3,
			running = 0.5,
		},
		versus_base = {
			normal = 3,
			running = 0.5,
		},
	},
	shove = {
		easy = {
			normal = 1,
		},
		normal = {
			normal = 1,
		},
		hard = {
			normal = 1,
		},
		harder = {
			normal = 1,
		},
		hardest = {
			normal = 1,
		},
		cataclysm = {
			normal = 1,
		},
		cataclysm_2 = {
			normal = 1,
		},
		cataclysm_3 = {
			normal = 1,
		},
		versus_base = {
			normal = 1,
		},
	},
	jump_slam = {
		easy = {
			normal = 5,
			running = 2,
		},
		normal = {
			normal = 5,
			running = 2,
		},
		hard = {
			normal = 5,
			running = 2,
		},
		harder = {
			normal = 5,
			running = 2,
		},
		hardest = {
			normal = 5,
			running = 2,
		},
		cataclysm = {
			normal = 5,
			running = 2,
		},
		cataclysm_2 = {
			normal = 5,
			running = 2,
		},
		cataclysm_3 = {
			normal = 5,
			running = 2,
		},
		versus_base = {
			normal = 5,
			running = 2,
		},
	},
	charge = {
		easy = {
			charge = 10,
		},
		normal = {
			charge = 10,
		},
		hard = {
			charge = 10,
		},
		harder = {
			charge = 10,
		},
		hardest = {
			charge = 10,
		},
		cataclysm = {
			charge = 10,
		},
		cataclysm_2 = {
			charge = 10,
		},
		cataclysm_3 = {
			charge = 10,
		},
		versus_base = {
			charge = 10,
		},
	},
}
local action_data = {
	follow = {
		action_weight = 1,
		follow_target_function_name = "_follow_target_rat_ogre",
		move_anim = "move_start_fwd",
		considerations = UtilityConsiderations.follow,
		start_anims_name = {
			bwd = "move_start_bwd",
			fwd = "move_start_fwd",
			left = "move_start_left",
			right = "move_start_right",
		},
		start_anims_data = {
			move_start_fwd = {},
			move_start_bwd = {
				dir = -1,
				rad = math.pi,
			},
			move_start_left = {
				dir = 1,
				rad = math.pi / 2,
			},
			move_start_right = {
				dir = -1,
				rad = math.pi / 2,
			},
		},
		init_blackboard = {
			chasing_timer = -10,
		},
	},
	smash_door = {
		attack_anim = "attack_right",
		damage = 15,
		damage_type = "cutting",
		door_attack_distance = 2,
		hit_react_type = "heavy",
		move_anim = "move_fwd",
		name = "smash_door",
		unblockable = true,
		ignore_staggers = {
			false,
			true,
			true,
			true,
			false,
			true,
		},
	},
	target_rage = {
		change_target_fwd_close_dist = 15,
		rage_anim = "change_target_fwd",
		rage_time = 0.55,
		rotation_speed = 5,
	},
	charge_attack = {
		action_weight = 6,
		animation_move_speed = 9,
		attack_intensity_type = "charge",
		blocked_velocity_scale = 2,
		cancel_animation = "charge_cancel",
		cancel_slow_down_speed = 2,
		catapult_force_z = 6,
		catapult_on_push_other_targets = true,
		catapult_on_push_z = 4,
		catapult_player = true,
		charge_at_max_speed_duration = 30,
		charge_blocked_animation = "charge_blocked",
		charge_max_speed_at = 2,
		charge_rotation_speed = 7,
		charge_speed_max = 12,
		charge_speed_min = 9,
		damage = 20,
		damage_type = "cutting",
		dodge_past_push_speed = 9,
		dodge_past_sound_event = "Play_enemy_minotaur_charge_attack_miss",
		fallback_to_idle = true,
		fatigue_type = "blocked_slam",
		head_radius = 1.75,
		hit_ai_radius = 1.2,
		hit_during_impact_t = 0.5,
		hit_react_type = "heavy",
		ignore_ai_damage = true,
		ignore_ledge_death = true,
		impact_animation = "charge_impact",
		max_slowdown_angle = 40,
		max_slowdown_percentage = 0.15,
		min_slowdown_angle = 20,
		player_push_speed = 9.5,
		player_push_speed_blocked = 10,
		radius = 1.75,
		ran_past_target_duration = 0.25,
		shield_blocked_fatigue_type = "ogre_shove",
		slow_down_speed = 3,
		slow_down_start_time = 0.55,
		start_animation = "charge_start",
		target_dodged_radius = 0.75,
		target_extrapolation_length_scale = 70,
		unblockable_by_normal_blocks = true,
		wall_collision_check_range = 0.75,
		difficulty_attack_intensity = AttackIntensityPerDifficulty,
		considerations = UtilityConsiderations.minotaur_charge,
		charging_distance_thresholds = {
			far = 10,
			medium = 6,
			short = 4,
		},
		tracking_durations = {
			far = 4,
			medium = 1.5,
			short = 1,
		},
		lunge = {
			get_position_at_distance = 4,
			get_position_duration = 2,
			lean_speed = 2.3,
			max_angle_to_allow = 65,
			rotation_slow_down_speed = 2,
			rotation_speed = 6.5,
			enter_thresholds = {
				far = 15,
				medium = 9,
				short = 4,
			},
			velocity_scaling = {
				far = 1.3,
				medium = 1,
				short = 0.6,
			},
			lean_variables = {
				max = 3,
				min = 2,
			},
		},
		charging_animations = {
			far = "charge_loop",
			medium = "charge_loop",
			short = "charge_loop",
		},
		push_ai = {
			stagger_distance = 1.5,
			stagger_impact = {
				stagger_types.explosion,
				stagger_types.explosion,
				stagger_types.none,
				stagger_types.none,
				stagger_types.explosion,
			},
			stagger_duration = {
				3,
				1,
				0,
				0,
				4,
			},
		},
		difficulty_damage = {
			cataclysm = 40,
			cataclysm_2 = 40,
			cataclysm_3 = 40,
			easy = 10,
			hard = 15,
			harder = 20,
			hardest = 30,
			normal = 10,
			versus_base = 10,
		},
		ignore_staggers = {
			true,
			true,
			false,
			true,
			true,
			false,
		},
	},
	melee_slam = {
		action_weight = 1,
		attack_intensity_type = "melee_slam",
		attack_time = 1.3333333333333333,
		blocked_damage = 5,
		cooldown = -1,
		damage = 10,
		damage_type = "cutting",
		dodge_mitigation_radius_squared = 2.25,
		fatigue_type = "blocked_slam",
		forward_offset = 1.75,
		height = 2.5,
		hit_react_type = "heavy",
		player_push_speed = 8,
		player_push_speed_blocked = 4,
		radius = 1.2,
		stagger_distance = 7,
		unblockable = false,
		difficulty_attack_intensity = AttackIntensityPerDifficulty,
		considerations = UtilityConsiderations.melee_slam,
		attack_anim = {
			"attack_slam",
			"attack_slam_2",
			"attack_slam_3",
			"attack_slam_4",
		},
		blocked_difficulty_damage = BreedTweaks.difficulty_damage.boss_slam_attack_blocked,
		difficulty_damage = BreedTweaks.difficulty_damage.boss_slam_attack,
		stagger_impact = {
			stagger_types.weak,
			stagger_types.medium,
			stagger_types.none,
			stagger_types.none,
			stagger_types.weak,
		},
		bot_threats = {
			{
				duration = 0.3333333333333333,
				start_time = 0.16666666666666666,
			},
		},
		hit_player_func = function (unit, blackboard, hit_unit, damage)
			if damage then
				blackboard.has_dealt_damage = true
			end
		end,
	},
	combo_attack = {
		action_weight = 1,
		allow_friendly_fire = true,
		attack_intensity_type = "combo",
		damage = 15,
		damage_type = "cutting",
		hit_react_type = "medium",
		shield_blocked_fatigue_type = "chaos_spawn_combo",
		difficulty_attack_intensity = AttackIntensityPerDifficulty,
		considerations = UtilityConsiderations.chaos_spawn_combo,
		attacks = {
			{
				anim_driven = true,
				attack_time = 2.5,
				damage_done_time = 2.1333333333333333,
				height = 2.5,
				hit_multiple_targets = true,
				ignores_dodging = true,
				offset_forward = 1.5,
				offset_up = 0,
				player_push_speed = 7,
				player_push_speed_blocked = 7,
				push_close_units_during_attack = true,
				range = 2.5,
				rotation_speed = 5,
				rotation_time = 2,
				width = 1.5,
				attack_anim = {
					"attack_melee_combo",
				},
				push_units_in_the_way = pushed_data,
				bot_threats = {
					{
						duration = 0.3333333333333333,
						range = 3.5,
						start_time = 0.13333333333333333,
					},
					{
						duration = 0.3333333333333333,
						range = 3.5,
						start_time = 0.7333333333333333,
					},
					{
						duration = 0.3333333333333333,
						range = 3.5,
						start_time = 1.1333333333333333,
					},
					{
						duration = 0.3333333333333333,
						range = 3.5,
						start_time = 1.8333333333333333,
					},
				},
			},
		},
		difficulty_damage = BreedTweaks.difficulty_damage.boss_combo_attack,
		fatigue_type = BreedTweaks.fatigue_types.boss_combo.light_combo,
	},
	melee_shove = {
		action_weight = 1,
		allow_friendly_fire = true,
		attack_intensity_type = "shove",
		damage = 20,
		damage_type = "cutting",
		fatigue_type = "blocked_sv_sweep",
		hit_react_type = "heavy",
		ignore_ai_damage = true,
		target_running_velocity_threshold = 2,
		difficulty_attack_intensity = AttackIntensityPerDifficulty,
		considerations = UtilityConsiderations.minotaur_melee_shove,
		attacks = {
			{
				anim_driven = false,
				attack_time = 1.8333333333333333,
				catapult_player = false,
				freeze_intensity_decay_time = 15,
				height = 2,
				hit_multiple_targets = true,
				hit_only_players = false,
				ignore_targets_behind = true,
				ignores_dodging = true,
				offset_forward = 0.5,
				offset_up = 0,
				player_push_speed = 12,
				player_push_speed_blocked = 5,
				player_push_speed_blocked_z = 3,
				player_push_speed_z = 4,
				range = 2,
				rotation_speed = 8,
				rotation_time = 0.3,
				width = 0.4,
				attack_anim = {
					"attack_left",
					"attack_right",
				},
				damage_done_time = {
					attack_left = 0.5666666666666667,
					attack_right = 0.5666666666666667,
				},
				continious_overlap = {
					attack_left = {
						base_node_name = "j_leftforearm",
						start_time = 0.6,
						tip_node_name = "j_lefthand",
					},
					attack_right = {
						base_node_name = "j_rightforearm",
						start_time = 0.6,
						tip_node_name = "j_righthand",
					},
				},
				push_ai = {
					stagger_distance = 3,
					stagger_impact = {
						stagger_types.explosion,
						stagger_types.heavy,
						stagger_types.none,
						stagger_types.none,
						stagger_types.explosion,
					},
					stagger_duration = {
						4.5,
						1,
						0,
						0,
						4,
					},
				},
				bot_threat_difficulty_data = default_bot_threat_difficulty_data,
				bot_threats = {
					attack_left = {
						{
							collision_type = "cylinder",
							duration = 0.5666666666666667,
							height = 4,
							offset_forward = 0.5,
							offset_right = 0,
							offset_up = 0,
							radius = 4.5,
							start_time = 0.26666666666666666,
						},
					},
					attack_right = {
						{
							collision_type = "cylinder",
							duration = 0.5666666666666667,
							height = 4,
							offset_forward = 0.5,
							offset_right = 0,
							offset_up = 0,
							radius = 4.5,
							start_time = 0.26666666666666666,
						},
					},
				},
			},
		},
		difficulty_damage = BreedTweaks.difficulty_damage.boss_combo_attack,
	},
	headbutt_attack = {
		action_weight = 1,
		allow_friendly_fire = true,
		attack_intensity_type = "shove",
		damage = 20,
		damage_type = "cutting",
		fatigue_type = "ogre_shove",
		hit_react_type = "heavy",
		ignore_ai_damage = true,
		target_running_velocity_threshold = 2,
		difficulty_attack_intensity = AttackIntensityPerDifficulty,
		considerations = UtilityConsiderations.minotaur_melee_shove,
		attacks = {
			{
				anim_driven = false,
				attack_time = 2.3333333333333335,
				catapult_player = true,
				freeze_intensity_decay_time = 15,
				height = 2,
				hit_multiple_targets = true,
				hit_only_players = false,
				ignore_targets_behind = true,
				ignores_dodging = false,
				offset_forward = 0.5,
				offset_up = 0,
				player_push_speed = 16,
				player_push_speed_blocked = 9.6,
				player_push_speed_blocked_z = 4,
				player_push_speed_z = 4,
				range = 2,
				rotation_speed = 8,
				rotation_time = 0.5,
				width = 0.4,
				attack_anim = {
					"attack_headbutt",
				},
				damage_done_time = {
					attack_headbutt = 1.6666666666666667,
				},
				continious_overlap = {
					attack_headbutt = {
						base_node_name = "j_head_end",
						start_time = 0.6666666666666666,
						tip_node_name = "j_jaw",
					},
				},
				push_ai = {
					stagger_distance = 3,
					stagger_impact = {
						stagger_types.explosion,
						stagger_types.heavy,
						stagger_types.none,
						stagger_types.none,
						stagger_types.explosion,
					},
					stagger_duration = {
						4.5,
						1,
						0,
						0,
						4,
					},
				},
				bot_threat_difficulty_data = default_bot_threat_difficulty_data,
				bot_threats = {
					attack_headbutt = {
						{
							collision_type = "cylinder",
							duration = 0.6666666666666666,
							height = 4,
							offset_forward = 0.5,
							offset_right = 0,
							offset_up = 0,
							radius = 4.5,
							start_time = 0.4666666666666667,
						},
					},
				},
			},
		},
		difficulty_damage = BreedTweaks.difficulty_damage.boss_slam_attack,
	},
	target_unreachable = {
		move_anim = "move_start_fwd",
	},
	climb = {
		catapult_players = {
			collision_filter = "filter_player_hit_box_check",
			radius = 2,
			speed = 7,
			angle = math.pi / 6,
		},
	},
	stagger = {
		scale_animation_speeds = true,
		stagger_animation_scale = 1,
		stagger_anims = {
			{
				fwd = {},
				bwd = {},
				left = {},
				right = {},
			},
			{
				fwd = {},
				bwd = {},
				left = {},
				right = {},
			},
			{
				fwd = {},
				bwd = {},
				left = {},
				right = {},
			},
			{
				fwd = {},
				bwd = {},
				left = {},
				right = {},
			},
			{
				fwd = {},
				bwd = {},
				left = {},
				right = {},
			},
			{
				fwd = {
					"stagger_fwd_exp",
				},
				bwd = {
					"stagger_bwd_exp",
				},
				left = {
					"stagger_left_exp",
				},
				right = {
					"stagger_right_exp",
				},
			},
			{
				fwd = {},
				bwd = {},
				left = {},
				right = {},
			},
			{
				fwd = {},
				bwd = {},
				left = {},
				right = {},
			},
			{
				fwd = {},
				bwd = {},
				left = {},
				right = {},
			},
		},
	},
	walking = {
		move_anim = "walk_fwd",
	},
}

action_data.anti_ladder_melee_slam = table.clone(action_data.melee_slam)
action_data.anti_ladder_melee_slam.considerations = UtilityConsiderations.anti_ladder_melee_slam
action_data.fling_skaven = table.clone(action_data.melee_shove)
action_data.fling_skaven.self_running_speed_threshold = 2
BreedActions.beastmen_minotaur = table.create_copy(BreedActions.beastmen_minotaur, action_data)
