-- chunkname: @scripts/settings/dlcs/skulls_2023/item_master_list_skulls_2023.lua

ItemMasterList.frame_skulls_2023 = {
	description = "portrait_frame_skulls_2023_description",
	display_name = "portrait_frame_skulls_2023_name",
	display_unit = "units/weapons/weapon_display/display_portrait_frame",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_skulls_2023",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_skulls_2023",
	can_wield = CanWieldAllItemTemplates,
	events = {
		"skulls",
	},
}
ItemMasterList.es_2h_sword_exe_skin_05_runed_04 = {
	description = "es_2h_sword_exe_skin_05_runed_04_description",
	display_name = "es_2h_sword_exe_skin_05_runed_04_name",
	display_unit = "units/weapons/weapon_display/display_2h_swords_executioner",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_sword_exe_05_t1_runed_04",
	item_preview_object_set_name = "flow_rune_weapon_lights",
	item_type = "weapon_skin",
	matching_item_key = "es_2h_sword_executioner",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_emp_sword_exe_05_t1/wpn_emp_sword_exe_05_t1_runed_01",
	slot_type = "weapon_skin",
	template = "two_handed_swords_executioner_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
	events = {
		"skulls",
	},
}
ItemMasterList.bw_fireball_staff_skin_01_runed_04 = {
	description = "bw_fireball_staff_skin_01_runed_04_description",
	display_name = "bw_fireball_staff_skin_01_runed_04_name",
	display_unit = "units/weapons/weapon_display/display_staff",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_bw_fireball_staff_01_runed_04",
	item_preview_object_set_name = "flow_rune_weapon_lights",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
	matching_item_key = "bw_skullstaff_fireball",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_brw_staff_02/wpn_brw_staff_02_runed_01",
	slot_type = "weapon_skin",
	template = "staff_fireball_fireball_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
	events = {
		"skulls",
	},
}
ItemMasterList.wh_brace_of_pistols_skin_05_runed_04 = {
	description = "wh_brace_of_pistols_skin_05_runed_04_description",
	display_name = "wh_brace_of_pistols_skin_05_runed_04_name",
	display_unit = "units/weapons/weapon_display/display_pistols",
	hud_icon = "weapon_generic_icon_brace_of_pistol",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_pistol_02_t2_runed_04",
	item_preview_object_set_name = "flow_rune_weapon_lights",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_emp_pistol_03_t2/wpn_emp_pistol_03_t2_runed_01",
	matching_item_key = "wh_brace_of_pistols",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_emp_pistol_03_t2/wpn_emp_pistol_03_t2_runed_01",
	slot_type = "weapon_skin",
	template = "brace_of_pistols_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
	events = {
		"skulls",
	},
}
ItemMasterList.we_dual_dagger_skin_01_runed_04 = {
	description = "we_dual_dagger_skin_01_runed_04_description",
	display_name = "we_dual_dagger_skin_01_runed_04_name",
	display_unit = "units/weapons/weapon_display/display_1h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_dagger_01_t1_dual_runed_04",
	item_preview_object_set_name = "flow_rune_weapon_lights",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_dagger_01_t1/wpn_we_dagger_01_t1_runed_01",
	matching_item_key = "we_dual_wield_daggers",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_we_dagger_01_t1/wpn_we_dagger_01_t1_runed_01",
	slot_type = "weapon_skin",
	template = "dual_wield_daggers_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	events = {
		"skulls",
	},
}
ItemMasterList.dw_handgun_skin_02_runed_04 = {
	description = "dw_handgun_skin_02_runed_04_description",
	display_name = "dw_handgun_skin_02_runed_04_name",
	display_unit = "units/weapons/weapon_display/display_rifle",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_handgun_01_t2_runed_04",
	item_preview_object_set_name = "flow_rune_weapon_lights",
	item_type = "weapon_skin",
	matching_item_key = "dr_handgun",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_dw_handgun_02_t3/wpn_dw_handgun_02_t3_runed_01",
	slot_type = "weapon_skin",
	template = "handgun_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
	events = {
		"skulls",
	},
}
ItemMasterList.bw_beam_staff_skin_05_runed_04 = {
	description = "bw_beam_staff_skin_05_runed_04_description",
	display_name = "bw_beam_staff_skin_05_runed_04_name",
	display_unit = "units/weapons/weapon_display/display_staff",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_brw_beam_staff_05_runed_04",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
	matching_item_key = "bw_skullstaff_beam",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_brw_beam_staff_05/wpn_brw_beam_staff_05_runed_01",
	slot_type = "weapon_skin",
	template = "staff_blast_beam_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
	events = {
		"skulls",
	},
}
ItemMasterList.es_2h_hammer_skin_04_runed_04 = {
	description = "es_2h_hammer_skin_04_runed_04_description",
	display_name = "es_2h_hammer_skin_04_runed_04_name",
	display_unit = "units/weapons/weapon_display/display_2h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_empire_2h_hammer_02_t2_runed_04",
	item_type = "weapon_skin",
	matching_item_key = "es_2h_hammer",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_empire_2h_hammer_02_t2/wpn_2h_hammer_02_t2_runed_01",
	slot_type = "weapon_skin",
	template = "two_handed_hammers_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
	events = {
		"skulls",
	},
}
ItemMasterList.wh_1h_falchion_skin_02_runed_04 = {
	description = "wh_1h_falchion_skin_02_runed_04_description",
	display_name = "wh_1h_falchion_skin_02_runed_04_name",
	display_unit = "units/weapons/weapon_display/display_1h_weapon",
	hud_icon = "weapon_generic_icon_falken",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_sword_04_t2_runed_04",
	item_type = "weapon_skin",
	matching_item_key = "wh_1h_falchion",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_emp_sword_04_t2/wpn_emp_sword_04_t2_runed_01",
	slot_type = "weapon_skin",
	template = "one_hand_falchion_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
	events = {
		"skulls",
	},
}
ItemMasterList.we_shortbow_skin_04_runed_04 = {
	description = "we_shortbow_skin_04_runed_04_description",
	display_name = "we_shortbow_skin_04_runed_04_name",
	display_unit = "units/weapons/weapon_display/display_bow",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_bow_short_04_runed_04",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_bow_short_04/wpn_we_bow_short_04_runed_01",
	matching_item_key = "we_shortbow",
	rarity = "unique",
	slot_type = "weapon_skin",
	template = "shortbow_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	events = {
		"skulls",
	},
}
ItemMasterList.dw_grudge_raker_skin_02_runed_04 = {
	description = "dw_grudge_raker_skin_02_runed_04_description",
	display_name = "dw_grudge_raker_skin_02_runed_04_name",
	display_unit = "units/weapons/weapon_display/display_rifle",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_rakegun_t2_runed_04",
	item_type = "weapon_skin",
	matching_item_key = "dr_rakegun",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_dw_rakegun_t2/wpn_dw_rakegun_t2_runed_01",
	slot_type = "weapon_skin",
	template = "grudge_raker_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
	events = {
		"skulls",
	},
}
ItemMasterList.frame_skulls_2024 = {
	description = "portrait_frame_skulls_2024_description",
	display_name = "portrait_frame_skulls_2024_name",
	display_unit = "units/weapons/weapon_display/display_portrait_frame",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_skulls_2024",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_skulls_2024",
	can_wield = CanWieldAllItemTemplates,
	events = {
		"skulls",
	},
}
