-- chunkname: @scripts/unit_extensions/ai_supplementary/vortex_templates.lua

VortexTemplates = {
	standard = {
		ai_ascension_speed = 3,
		ai_attract_speed = 20,
		ai_attractable = true,
		ai_radius_change_speed = 1,
		ai_rotation_speed = 15,
		breed_name = "chaos_vortex",
		damage = 5,
		forced_standing_still = false,
		full_fx_radius = 8,
		full_inner_radius = 3.5,
		full_outer_radius = 8,
		high_cost_nav_cost_map_cost_type = "vortex_danger_zone",
		inner_fx_name = "fx/wpn_chaos_plague_vortex_small",
		inner_fx_z_scale_multiplier = 0.1,
		max_allowed_inner_radius_dist = 1.5,
		max_height = 10,
		medium_cost_nav_cost_map_cost_type = "vortex_near",
		min_fx_radius = 2,
		min_inner_radius = 0.38,
		min_outer_radius = 2,
		outer_fx_name = "fx/wpn_chaos_plague_vortex_small_outer",
		outer_fx_z_scale_multiplier = 0.1,
		player_actions_allowed = false,
		player_ascend_speed = 1,
		player_attract_speed = 15,
		player_attractable = true,
		player_eject_distance = 12,
		player_eject_height = 2.5,
		player_eject_speed = 12,
		player_ejected_bliss_time = 5,
		player_in_vortex_max_duration = 5,
		player_radius_change_speed = 1,
		player_rotation_speed = 10,
		post_vortex_buff = "vortex_base",
		random_wander = false,
		start_radius = 0.1,
		stop_and_process_player = true,
		use_nav_cost_map_volumes = true,
		windup_time = 0.5,
		ai_eject_height = {
			3,
			5,
		},
		time_of_life = {
			20,
			22,
		},
	},
	boss_sorcerer = {
		ai_ascension_speed = 3,
		ai_attract_speed = 20,
		ai_attractable = true,
		ai_radius_change_speed = 1,
		ai_rotation_speed = 15,
		breed_name = "chaos_vortex",
		damage = 5,
		forced_standing_still = true,
		full_fx_radius = 9,
		full_inner_radius = 7.5,
		full_outer_radius = 9,
		high_cost_nav_cost_map_cost_type = "vortex_danger_zone",
		inner_fx_name = "fx/wpn_chaos_plague_vortex",
		inner_fx_z_scale_multiplier = 0.1,
		max_allowed_inner_radius_dist = 1.5,
		max_height = 20,
		medium_cost_nav_cost_map_cost_type = "vortex_near",
		min_fx_radius = 7,
		min_inner_radius = 6,
		min_outer_radius = 7,
		outer_fx_name = "fx/wpn_chaos_plague_vortex_small_outer",
		outer_fx_z_scale_multiplier = 0.1,
		player_actions_allowed = false,
		player_ascend_speed = 1,
		player_attract_speed = 15,
		player_attractable = true,
		player_eject_distance = 6,
		player_eject_height = 3.5,
		player_eject_speed = 12,
		player_ejected_bliss_time = 5,
		player_in_vortex_max_duration = 5,
		player_radius_change_speed = 1,
		player_rotation_speed = 10,
		post_vortex_buff = "vortex_base",
		random_wander = false,
		start_radius = 0.1,
		stop_and_process_player = true,
		use_nav_cost_map_volumes = true,
		windup_time = 1,
		ai_eject_height = {
			3,
			4,
		},
		time_of_life = {
			7,
			8,
		},
		suck_in_ai_func = function (blackboard)
			local stat_names = {
				"halescourge_tornado_enemies",
				"halescourge_tornado_enemies_cata",
			}

			for i = 1, #stat_names do
				local current_difficulty = Managers.state.difficulty:get_difficulty()
				local allowed_difficulties = QuestSettings.allowed_difficulties[stat_names[i]]
				local allowed_difficulty = allowed_difficulties[current_difficulty]

				if allowed_difficulty and not blackboard.completed_vortex_suck_in_challenge then
					if not blackboard.num_ai_units_sucked_in then
						blackboard.num_ai_units_sucked_in = 0
					end

					local num_ai_units_sucked_in = blackboard.num_ai_units_sucked_in or 0

					blackboard.num_ai_units_sucked_in = num_ai_units_sucked_in + 1

					if blackboard.num_ai_units_sucked_in >= QuestSettings.halescourge_tornado_enemies then
						local statistics_db = Managers.player:statistics_db()

						statistics_db:increment_stat_and_sync_to_clients(stat_names[i])

						blackboard.completed_vortex_suck_in_challenge = true
					end
				end
			end
		end,
	},
	elite_mutator = {
		ai_ascension_speed = 3,
		ai_attract_speed = 20,
		ai_attractable = true,
		ai_radius_change_speed = 1,
		ai_rotation_speed = 15,
		breed_name = "chaos_vortex",
		damage = 5,
		forced_standing_still = false,
		full_fx_radius = 8,
		full_inner_radius = 3.5,
		full_outer_radius = 8,
		high_cost_nav_cost_map_cost_type = "vortex_danger_zone",
		inner_fx_name = "fx/wpn_chaos_plague_vortex_small",
		inner_fx_z_scale_multiplier = 0.1,
		max_allowed_inner_radius_dist = 1.5,
		max_height = 10,
		medium_cost_nav_cost_map_cost_type = "vortex_near",
		min_fx_radius = 2,
		min_inner_radius = 0.38,
		min_outer_radius = 2,
		outer_fx_name = "fx/wpn_chaos_plague_vortex_small_outer",
		outer_fx_z_scale_multiplier = 0.1,
		player_actions_allowed = false,
		player_ascend_speed = 1,
		player_attract_speed = 15,
		player_attractable = true,
		player_eject_distance = 20,
		player_eject_height = 2.5,
		player_eject_speed = 16,
		player_ejected_bliss_time = 5,
		player_in_vortex_max_duration = 5,
		player_radius_change_speed = 1,
		player_rotation_speed = 10,
		post_vortex_buff = "vortex_base",
		random_wander = false,
		start_radius = 0.1,
		stop_and_process_player = true,
		use_nav_cost_map_volumes = true,
		windup_time = 0.5,
		ai_eject_height = {
			3,
			5,
		},
		time_of_life = {
			20,
			22,
		},
	},
	carousel = {
		ai_ascension_speed = 3,
		ai_attract_speed = 20,
		ai_attractable = true,
		ai_radius_change_speed = 1,
		ai_rotation_speed = 15,
		breed_name = "chaos_vortex",
		damage = 5,
		forced_standing_still = false,
		full_fx_radius = 8,
		full_inner_radius = 3.5,
		full_outer_radius = 8,
		high_cost_nav_cost_map_cost_type = "vortex_danger_zone",
		inner_fx_name = "fx/wpn_chaos_plague_vortex_small",
		inner_fx_z_scale_multiplier = 0.1,
		max_allowed_inner_radius_dist = 1.5,
		max_height = 10,
		medium_cost_nav_cost_map_cost_type = "vortex_near",
		min_fx_radius = 2,
		min_inner_radius = 0.38,
		min_outer_radius = 2,
		outer_fx_name = "fx/wpn_chaos_plague_vortex_small_outer",
		outer_fx_z_scale_multiplier = 0.1,
		player_actions_allowed = false,
		player_ascend_speed = 1,
		player_attract_speed = 15,
		player_attractable = true,
		player_eject_distance = 12,
		player_eject_height = 2.5,
		player_eject_speed = 12,
		player_ejected_bliss_time = 5,
		player_in_vortex_max_duration = 5,
		player_radius_change_speed = 1,
		player_rotation_speed = 10,
		post_vortex_buff = "vortex_base",
		random_wander = false,
		start_radius = 0.1,
		stop_and_process_player = true,
		use_nav_cost_map_volumes = true,
		windup_time = 0.5,
		breed = Breeds.chaos_vortex,
		ai_eject_height = {
			3,
			5,
		},
		time_of_life = {
			5,
			8,
		},
	},
}

DLCUtils.merge("vortex_templates", VortexTemplates)
