-- chunkname: @scripts/settings/dlcs/morris/deus_terror_event_tags.lua

DeusTerrorEventTags = DeusTerrorEventTags or {
	LESS_ELITES = "DEUS_LESS_ELITES",
	LESS_HORDES = "DEUS_LESS_HORDES",
	LESS_MONSTERS = "DEUS_LESS_MONSTERS",
	LESS_SPECIALS = "DEUS_LESS_SPECIALS",
	MORE_ELITES = "DEUS_MORE_ELITES",
	MORE_HORDES = "DEUS_MORE_HORDES",
	MORE_MONSTERS = "DEUS_MORE_MONSTERS",
	MORE_SPECIALS = "DEUS_MORE_SPECIALS",
	NO_SORCERERS = "DEUS_NO_SORCERERS",
}
