DeusTerrorEventTags = DeusTerrorEventTags or {
	LESS_HORDES = "DEUS_LESS_HORDES",
	MORE_SPECIALS = "DEUS_MORE_SPECIALS",
	MORE_HORDES = "DEUS_MORE_HORDES",
	MORE_MONSTERS = "DEUS_MORE_MONSTERS",
	LESS_MONSTERS = "DEUS_LESS_MONSTERS",
	NO_SORCERERS = "DEUS_NO_SORCERERS",
	MORE_ELITES = "DEUS_MORE_ELITES",
	LESS_ELITES = "DEUS_LESS_ELITES",
	LESS_SPECIALS = "DEUS_LESS_SPECIALS"
}
