-- chunkname: @scripts/settings/equipment/item_master_list_cosmetics_2023_q1.lua

ItemMasterList.adept_hat_1005 = {
	description = "description_adept_hat_1005",
	display_name = "display_name_adept_hat_1005",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_adept_hat_1005",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 175,
	template = "bw_gates_lock_neck",
	unit = "units/beings/player/bright_wizard_adept/headpiece/bw_a_hat_15",
	can_wield = {
		"bw_adept",
	},
}
ItemMasterList.engineer_hat_1002 = {
	description = "description_engineer_hat_1002",
	display_name = "display_name_engineer_hat_1002",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_engineer_hat_1002",
	item_type = "hat",
	rarity = "promo",
	required_dlc = "cog",
	slot_type = "hat",
	steam_itemdefid = 171,
	template = "dr_helmets_beard_face_ears",
	unit = "units/beings/player/dwarf_ranger_engineer/headpiece/dr_e_hat_04",
	can_wield = {
		"dr_engineer",
	},
}
ItemMasterList.questing_knight_hat_1001 = {
	description = "description_questing_knight_hat_1001",
	display_name = "display_name_questing_knight_hat_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_questing_knight_hat_1001",
	item_type = "hat",
	rarity = "promo",
	required_dlc = "lake",
	slot_type = "hat",
	steam_itemdefid = 177,
	template = "es_hats_no_ear_moustache_skinned",
	unit = "units/beings/player/empire_soldier_breton/headpiece/es_gk_hat_04",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.priest_hat_1001 = {
	description = "description_priest_hat_1001_2023_q1",
	display_name = "display_name_priest_hat_1001_2023_q1",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_priest_hat_1001",
	item_type = "hat",
	rarity = "promo",
	required_dlc = "bless",
	slot_type = "hat",
	steam_itemdefid = 173,
	template = "wh_hats",
	unit = "units/beings/player/witch_hunter_warrior_priest/headpiece/wh_wp_hat_05",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.maidenguard_hat_1005 = {
	description = "description_maidenguard_hat_1005",
	display_name = "display_name_maidenguard_hat_1005",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_maidenguard_hat_1005",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 169,
	template = "ww_helmet_ears_skinned",
	unit = "units/beings/player/way_watcher_maiden_guard/headpiece/ww_mg_hat_16",
	can_wield = {
		"we_maidenguard",
	},
}
ItemMasterList.skin_bw_adept_1002 = {
	description = "description_skin_bw_adept_1002",
	display_name = "display_name_skin_bw_adept_1002",
	hud_icon = "unit_frame_portrait_bright_wizard",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_bw_adept_1002",
	item_type = "skin",
	name = "skin_bw_adept_1002",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 176,
	temporary_template = "skin_bw_adept_1002",
	can_wield = {
		"bw_adept",
	},
}
ItemMasterList.skin_dr_engineer_1001 = {
	description = "description_skin_dr_engineer_1001",
	display_name = "display_name_skin_dr_engineer_1001",
	hud_icon = "unit_frame_portrait_dwarf_ranger",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_dr_engineer_1001",
	item_type = "skin",
	name = "skin_dr_engineer_1001",
	rarity = "promo",
	required_dlc = "cog",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 172,
	temporary_template = "skin_dr_engineer_1001",
	can_wield = {
		"dr_engineer",
	},
}
ItemMasterList.skin_es_questingknight_1001 = {
	description = "description_skin_es_questing_knight_1001",
	display_name = "display_name_skin_es_questing_knight_1001",
	hud_icon = "unit_frame_portrait_empire_soldier",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_questingknight_1001",
	item_type = "skin",
	name = "skin_es_questingknight_1001",
	rarity = "promo",
	required_dlc = "lake",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 178,
	temporary_template = "skin_es_questingknight_1001",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.skin_wh_priest_1001 = {
	career_select_preview_animation = "career_select_04_skin_02",
	description = "description_skin_wh_priest_1001_2023_q1",
	display_name = "display_name_skin_wh_priest_1001_2023_q1",
	hud_icon = "unit_frame_portrait_witch_hunter",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_wh_priest_1001",
	item_type = "skin",
	name = "skin_wh_priest_1001",
	rarity = "promo",
	required_dlc = "bless",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 174,
	temporary_template = "skin_wh_priest_1001",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.skin_ww_maidenguard_1002 = {
	description = "description_skin_ww_maidenguard_1002",
	display_name = "display_name_skin_ww_maidenguard_1002",
	hud_icon = "unit_frame_portrait_way_watcher",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ww_maidenguard_1002",
	item_type = "skin",
	name = "skin_ww_maidenguard_1002",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 170,
	temporary_template = "skin_ww_maidenguard_1002",
	can_wield = {
		"we_maidenguard",
	},
}
ItemMasterList.engineer_bundle_0001 = {
	description = "description_engineer_bundle_0001",
	discount = 99,
	display_name = "display_name_engineer_bundle_0001",
	hud_icon = "",
	information_text = "description_engineer_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 3500,
	rarity = "promo",
	required_dlc = "cog",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 832,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_engineer_bundle_0001",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_engineer_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_engineer_bundle_0001",
	subtitle = "dr_engineer",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.maidenguard_bundle_0003 = {
	description = "description_maidenguard_bundle_0003",
	discount = 99,
	display_name = "display_name_maidenguard_bundle_0003",
	hud_icon = "",
	information_text = "description_maidenguard_bundle_0003",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 3600,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 831,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_maidenguard_bundle_0003",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_maidenguard_bundle_0003",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_maidenguard_bundle_0003",
	subtitle = "we_maidenguard",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.questing_knight_bundle_0001 = {
	description = "description_questing_knight_bundle_0001",
	discount = 99,
	display_name = "display_name_questing_knight_bundle_0001",
	hud_icon = "",
	information_text = "description_questing_knight_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 3700,
	rarity = "promo",
	required_dlc = "lake",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 835,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_questing_knight_bundle_0001",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_questing_knight_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_questing_knight_bundle_0001",
	subtitle = "es_questingknight",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.adept_bundle_0002 = {
	description = "description_adept_bundle_0002",
	discount = 99,
	display_name = "display_name_adept_bundle_0002",
	hud_icon = "",
	information_text = "description_adept_bundle_0002",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 3800,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 834,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_adept_bundle_0002",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_adept_bundle_0002",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_adept_bundle_0002",
	subtitle = "bw_adept",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.priest_bundle_0001 = {
	description = "description_priest_bundle_0001",
	discount = 99,
	display_name = "display_name_priest_bundle_0001",
	hud_icon = "",
	information_text = "description_priest_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 3900,
	rarity = "promo",
	required_dlc = "bless",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 833,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_priest_bundle_0001",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_priest_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_priest_bundle_0001",
	subtitle = "wh_priest",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.five_career_bundle_0006 = {
	description = "description_five_career_bundle_0006",
	display_name = "display_name_five_career_bundle_0006",
	hud_icon = "",
	information_text = "five_career_bundle_0006",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 4000,
	product_layout = "five_career_bundle_0006",
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 836,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_five_career_bundle_0006",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_five_career_bundle_0006",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_five_career_bundle_0006",
	subtitle = "five_career_bundle_0001_subtitle",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
