-- chunkname: @scripts/settings/equipment/item_master_list_cosmetics_2023_q2.lua

ItemMasterList.adept_hat_1003 = {
	description = "description_adept_hat_1003",
	display_name = "display_name_adept_hat_1003",
	dlc_name = "adept_hat_1003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_adept_hat_1003_3",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 179,
	template = "bw_hat_no_hair",
	unit = "units/beings/player/bright_wizard_adept/headpiece/bw_a_hat_14",
	can_wield = {
		"bw_adept",
	},
}
ItemMasterList.ironbreaker_hat_1005 = {
	description = "description_ironbreaker_hat_1005",
	display_name = "display_name_ironbreaker_hat_1005",
	dlc_name = "ironbreaker_hat_1005",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_ironbreaker_hat_1005",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 180,
	template = "dr_helmets_beard_ears",
	unit = "units/beings/player/dwarf_ranger_ironbreaker/headpiece/dr_i_hat_18",
	can_wield = {
		"dr_ironbreaker",
	},
}
ItemMasterList.huntsman_hat_1003 = {
	description = "description_huntsman_hat_1003",
	display_name = "display_name_huntsman_hat_1003",
	dlc_name = "huntsman_hat_1003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_huntsman_hat_1003",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 181,
	template = "es_hats",
	unit = "units/beings/player/empire_soldier_huntsman/headpiece/es_h_hat_14",
	can_wield = {
		"es_huntsman",
	},
}
ItemMasterList.shade_hat_1004 = {
	description = "description_shade_hat_1004",
	display_name = "display_name_shade_hat_1004",
	dlc_name = "shade_hat_1004",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_shade_hat_1004",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 182,
	template = "ww_hide_eyes_hair_hood_down",
	unit = "units/beings/player/way_watcher_shade/headpiece/ww_s_hat_15",
	can_wield = {
		"we_shade",
	},
}
ItemMasterList.bountyhunter_hat_1004 = {
	description = "description_bountyhunter_hat_1004",
	display_name = "display_name_bountyhunter_hat_1004",
	dlc_name = "bountyhunter_hat_1004",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_bountyhunter_hat_1004",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 183,
	template = "wh_face_no_hair",
	unit = "units/beings/player/witch_hunter_bounty_hunter/headpiece/wh_bh_hat_14",
	can_wield = {
		"wh_bountyhunter",
	},
}
ItemMasterList.q2_2023_hat_collection = {
	description = "description_q2_2023_hat_collection",
	display_name = "display_name_q2_2023_hat_collection",
	hud_icon = "",
	information_text = "description_q2_2023_hat_collection",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 4000,
	product_layout = "q2_2023_hat_collection",
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 837,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_q2_2023_hat_collection",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_q2_2023_hat_collection",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_q2_2023_hat_collection",
	subtitle = "five_career_bundle_0001_subtitle",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
