-- chunkname: @scripts/settings/equipment/item_master_list_versus_rewards.lua

ItemMasterList.skaven_gutter_runner_skin_0000_ektrik_01 = {
	description = "skaven_gutter_runner_skin_0000_ektrik_01_description",
	display_name = "skaven_gutter_runner_skin_0000_ektrik_01_name",
	hud_icon = "icons_placeholder",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_gutter_runner_skin_0000_ektrik_01",
	item_type = "skin",
	linked_weapon = "vs_gutter_runner_claws",
	name = "skaven_gutter_runner_skin_0000_ektrik_01",
	rarity = "common",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skaven_gutter_runner_skin_0000_ektrik_01",
	can_wield = {
		"vs_gutter_runner",
	},
}
ItemMasterList.skaven_pack_master_skin_0000_ektrik_01 = {
	description = "skaven_packmaster_skin_0000_ektrik_01_description",
	display_name = "skaven_packmaster_skin_0000_ektrik_01_name",
	hud_icon = "icons_placeholder",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_packmaster_skin_0000_ektrik_01",
	item_type = "skin",
	linked_weapon = "vs_packmaster_claw",
	name = "skaven_pack_master_skin_0000_ektrik_01",
	rarity = "common",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skaven_pack_master_skin_0000_ektrik_01",
	can_wield = {
		"vs_packmaster",
	},
}
ItemMasterList.skaven_ratling_gunner_skin_0000_ektrik_01 = {
	description = "skaven_ratling_gunner_skin_0000_ektrik_01_description",
	display_name = "skaven_ratling_gunner_skin_0000_ektrik_01_name",
	hud_icon = "icons_placeholder",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_ratling_gunner_skin_0000_ektrik_01",
	item_type = "skin",
	linked_weapon = "vs_ratling_gunner_gun",
	name = "skaven_ratling_gunner_skin_0000_ektrik_01",
	rarity = "common",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skaven_ratling_gunner_skin_0000_ektrik_01",
	can_wield = {
		"vs_ratling_gunner",
	},
}
ItemMasterList.skaven_warpfire_thrower_skin_0000_ektrik_01 = {
	description = "skaven_warpfire_thrower_skin_0000_ektrik_01_description",
	display_name = "skaven_warpfire_thrower_skin_0000_ektrik_01_name",
	hud_icon = "icons_placeholder",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_warpfire_thrower_skin_0000_ektrik_01",
	item_type = "skin",
	linked_weapon = "vs_warpfire_thrower_gun",
	name = "skaven_warpfire_thrower_skin_0000_ektrik_01",
	rarity = "common",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skaven_warpfire_thrower_skin_0000_ektrik_01",
	can_wield = {
		"vs_warpfire_thrower",
	},
}
ItemMasterList.skaven_wind_globadier_skin_0000_ektrik_01 = {
	description = "skaven_wind_globadier_skin_0000_ektrik_01_description",
	display_name = "skaven_wind_globadier_skin_0000_ektrik_01_name",
	hud_icon = "icons_placeholder",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_globadier_skin_0000_ektrik_01",
	item_type = "skin",
	linked_weapon = "vs_poison_wind_globadier_orb",
	name = "skaven_wind_globadier_skin_0000_ektrik_01",
	rarity = "common",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skaven_wind_globadier_skin_0000_ektrik_01",
	can_wield = {
		"vs_poison_wind_globadier",
	},
}
ItemMasterList.skaven_gutter_runner_skin_0000_kreepus_01 = {
	description = "skaven_gutter_runner_skin_0000_kreepus_01_description",
	display_name = "skaven_gutter_runner_skin_0000_kreepus_01_name",
	hud_icon = "icons_placeholder",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_gutter_runner_skin_0000_kreepus_01",
	item_type = "skin",
	linked_weapon = "vs_gutter_runner_claws",
	name = "skaven_gutter_runner_skin_0000_kreepus_01",
	rarity = "common",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skaven_gutter_runner_skin_0000_kreepus_01",
	can_wield = {
		"vs_gutter_runner",
	},
}
ItemMasterList.skaven_pack_master_skin_0000_kreepus_01 = {
	description = "skaven_packmaster_skin_0000_kreepus_01_description",
	display_name = "skaven_packmaster_skin_0000_kreepus_01_name",
	hud_icon = "icons_placeholder",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_packmaster_skin_0000_kreepus_01",
	item_type = "skin",
	linked_weapon = "vs_packmaster_claw",
	name = "skaven_pack_master_skin_0000_kreepus_01",
	rarity = "common",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skaven_pack_master_skin_0000_kreepus_01",
	can_wield = {
		"vs_packmaster",
	},
}
ItemMasterList.skaven_ratling_gunner_skin_0000_kreepus_01 = {
	description = "skaven_ratling_gunner_skin_0000_kreepus_01_description",
	display_name = "skaven_ratling_gunner_skin_0000_kreepus_01_name",
	hud_icon = "icons_placeholder",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_ratling_gunner_skin_0000_kreepus_01",
	item_type = "skin",
	linked_weapon = "vs_ratling_gunner_gun",
	name = "skaven_ratling_gunner_skin_0000_kreepus_01",
	rarity = "common",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skaven_ratling_gunner_skin_0000_kreepus_01",
	can_wield = {
		"vs_ratling_gunner",
	},
}
ItemMasterList.skaven_warpfire_thrower_skin_0000_kreepus_01 = {
	description = "skaven_warpfire_thrower_skin_0000_kreepus_01_description",
	display_name = "skaven_warpfire_thrower_skin_0000_kreepus_01_name",
	hud_icon = "icons_placeholder",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_warpfire_thrower_skin_0000_kreepus_01",
	item_type = "skin",
	linked_weapon = "vs_warpfire_thrower_gun",
	name = "skaven_warpfire_thrower_skin_0000_kreepus_01",
	rarity = "common",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skaven_warpfire_thrower_skin_0000_kreepus_01",
	can_wield = {
		"vs_warpfire_thrower",
	},
}
ItemMasterList.skaven_wind_globadier_skin_0000_kreepus_01 = {
	description = "skaven_wind_globadier_skin_0000_kreepus_01_description",
	display_name = "skaven_wind_globadier_skin_0000_kreepus_01_name",
	hud_icon = "icons_placeholder",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_globadier_skin_0000_kreepus_01",
	item_type = "skin",
	linked_weapon = "vs_poison_wind_globadier_orb",
	name = "skaven_wind_globadier_skin_0000_kreepus_01",
	rarity = "common",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skaven_wind_globadier_skin_0000_kreepus_01",
	can_wield = {
		"vs_poison_wind_globadier",
	},
}
ItemMasterList.skaven_gutter_runner_skin_0000_krizzor_01 = {
	description = "skaven_gutter_runner_skin_0000_krizzor_01_description",
	display_name = "skaven_gutter_runner_skin_0000_krizzor_01_name",
	hud_icon = "icons_placeholder",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_gutter_runner_skin_0000_krizzor_01",
	item_type = "skin",
	linked_weapon = "vs_gutter_runner_claws",
	name = "skaven_gutter_runner_skin_0000_krizzor_01",
	rarity = "common",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skaven_gutter_runner_skin_0000_krizzor_01",
	can_wield = {
		"vs_gutter_runner",
	},
}
ItemMasterList.skaven_pack_master_skin_0000_krizzor_01 = {
	description = "skaven_packmaster_skin_0000_krizzor_01_description",
	display_name = "skaven_packmaster_skin_0000_krizzor_01_name",
	hud_icon = "icons_placeholder",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_packmaster_skin_0000_krizzor_01",
	item_type = "skin",
	linked_weapon = "vs_packmaster_claw",
	name = "skaven_pack_master_skin_0000_krizzor_01",
	rarity = "common",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skaven_pack_master_skin_0000_krizzor_01",
	can_wield = {
		"vs_packmaster",
	},
}
ItemMasterList.skaven_ratling_gunner_skin_0000_krizzor_01 = {
	description = "skaven_ratling_gunner_skin_0000_krizzor_01_description",
	display_name = "skaven_ratling_gunner_skin_0000_krizzor_01_name",
	hud_icon = "icons_placeholder",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_ratling_gunner_skin_0000_krizzor_01",
	item_type = "skin",
	linked_weapon = "vs_ratling_gunner_gun",
	name = "skaven_ratling_gunner_skin_0000_krizzor_01",
	rarity = "common",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skaven_ratling_gunner_skin_0000_krizzor_01",
	can_wield = {
		"vs_ratling_gunner",
	},
}
ItemMasterList.skaven_warpfire_thrower_skin_0000_krizzor_01 = {
	description = "skaven_warpfire_thrower_skin_0000_krizzor_01_description",
	display_name = "skaven_warpfire_thrower_skin_0000_krizzor_01_name",
	hud_icon = "icons_placeholder",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_warpfire_thrower_skin_0000_krizzor_01",
	item_type = "skin",
	linked_weapon = "vs_warpfire_thrower_gun",
	name = "skaven_warpfire_thrower_skin_0000_krizzor_01",
	rarity = "common",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skaven_warpfire_thrower_skin_0000_krizzor_01",
	can_wield = {
		"vs_warpfire_thrower",
	},
}
ItemMasterList.skaven_wind_globadier_skin_0000_krizzor_01 = {
	description = "skaven_wind_globadier_skin_0000_krizzor_01_description",
	display_name = "skaven_wind_globadier_skin_0000_krizzor_01_name",
	hud_icon = "icons_placeholder",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_globadier_skin_0000_krizzor_01",
	item_type = "skin",
	linked_weapon = "vs_poison_wind_globadier_orb",
	name = "skaven_wind_globadier_skin_0000_krizzor_01",
	rarity = "common",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skaven_wind_globadier_skin_0000_krizzor_01",
	can_wield = {
		"vs_poison_wind_globadier",
	},
}
ItemMasterList.wh_fencing_sword_skin_07_magic_02 = {
	description = "wh_fencing_sword_skin_07_magic_02_description",
	display_name = "wh_fencing_sword_skin_07_magic_02_name",
	hud_icon = "weapon_generic_icon_fencing_sword",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wh_fencing_sword_skin_07_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_fencing_sword",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "fencing_sword_template_1",
	can_wield = {
		"wh_bountyhunter",
		"wh_captain",
		"wh_zealot",
	},
}
ItemMasterList.dw_handgun_skin_03_magic_02 = {
	description = "dw_handgun_skin_03_magic_02_description",
	display_name = "dw_handgun_skin_03_magic_02_name",
	hud_icon = "weapon_generic_icon_units/weapons/weapon_display/display_rifle",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_dw_handgun_skin_03_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_handgun",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "handgun_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
}
ItemMasterList.dw_dual_axe_skin_04_magic_02 = {
	description = "dw_dual_axe_skin_04_magic_02_description",
	display_name = "dw_dual_axe_skin_04_magic_02_name",
	hud_icon = "weapon_generic_icon_axe1h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_dw_dual_axe_skin_04_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_dual_wield_axes",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "dual_wield_axes_template_1",
	can_wield = {
		"dr_slayer",
	},
}
ItemMasterList.bw_flamethrower_staff_skin_04_magic_02 = {
	description = "bw_flamethrower_staff_skin_04_magic_02_description",
	display_name = "bw_flamethrower_staff_skin_04_magic_02_name",
	hud_icon = "weapon_generic_icon_staff_5",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_bw_flamethrower_staff_skin_04_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_skullstaff_flamethrower",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "staff_flamethrower_template",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.bw_1h_crowbill_skin_01_magic_02 = {
	description = "bw_1h_crowbill_skin_01_magic_02_description",
	display_name = "bw_1h_crowbill_skin_01_magic_02_name",
	hud_icon = "weapon_generic_icon_falken",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_bw_1h_crowbill_skin_01_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_1h_crowbill",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_crowbill",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.bw_1h_flaming_sword_skin_06_magic_02 = {
	description = "bw_1h_flaming_sword_skin_06_magic_02_description",
	display_name = "bw_1h_flaming_sword_skin_06_magic_02_name",
	hud_icon = "weapon_generic_icon_flaming_sword",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_bw_1h_flaming_sword_skin_06_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_flame_sword",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "flaming_sword_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.we_shortbow_hagbane_skin_02_magic_02 = {
	description = "we_shortbow_hagbane_skin_02_magic_02_description",
	display_name = "we_shortbow_hagbane_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_bow",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_we_shortbow_hagbane_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "we_shortbow_hagbane",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "shortbow_hagbane_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.bw_dagger_skin_02_magic_02 = {
	description = "bw_dagger_skin_02_magic_02_description",
	display_name = "bw_dagger_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_sword",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_bw_dagger_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_dagger",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_daggers_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.dw_1h_axe_shield_skin_04_magic_02 = {
	description = "dw_1h_axe_shield_skin_04_magic_02_description",
	display_name = "dw_1h_axe_shield_skin_04_magic_02_name",
	hud_icon = "weapon_generic_icon_axe_and_sheild",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_dw_1h_axe_shield_skin_04_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_shield_axe",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_hand_axe_shield_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
}
ItemMasterList.dr_dual_wield_hammers_skin_01_magic_02 = {
	description = "dr_dual_wield_hammers_skin_01_magic_02_description",
	display_name = "dr_dual_wield_hammers_skin_01_magic_02_name",
	hud_icon = "weapon_generic_icon_falken",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_dr_dual_wield_hammers_skin_01_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_dual_wield_hammers",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "dual_wield_hammers_template",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.es_2h_sword_exe_skin_03_magic_02 = {
	description = "es_2h_sword_exe_skin_03_magic_02_description",
	display_name = "es_2h_sword_exe_skin_03_magic_02_name",
	hud_icon = "weapon_generic_icon_sword",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_2h_sword_exe_skin_03_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_2h_sword_executioner",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "two_handed_swords_executioner_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.we_dual_dagger_skin_07_magic_02 = {
	description = "we_dual_dagger_skin_07_magic_02_description",
	display_name = "we_dual_dagger_skin_07_magic_02_name",
	hud_icon = "weapon_generic_icon_daggers",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_we_dual_dagger_skin_07_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "we_dual_wield_daggers",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "dual_wield_daggers_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.es_2h_heavy_spear_skin_02_magic_02 = {
	description = "es_2h_heavy_spear_skin_02_magic_02_description",
	display_name = "es_2h_heavy_spear_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_falken",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_2h_heavy_spear_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_2h_heavy_spear",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "two_handed_heavy_spears_template",
	can_wield = {
		"es_huntsman",
		"es_mercenary",
	},
}
ItemMasterList.we_1h_axe_skin_02_magic_02 = {
	description = "we_1h_axe_skin_02_magic_02_description",
	display_name = "we_1h_axe_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_falken",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_we_1h_axe_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "we_1h_axe",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "we_one_hand_axe_template",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.we_crossbow_skin_01_magic_02 = {
	description = "we_crossbow_skin_01_magic_02_description",
	display_name = "we_crossbow_skin_01_magic_02_name",
	hud_icon = "weapon_generic_icon_repeating_crossbow",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_we_crossbow_skin_01_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "we_crossbow_repeater",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "repeating_crossbow_elf_template",
	can_wield = {
		"we_shade",
	},
}
ItemMasterList.wh_2h_sword_skin_04_magic_02 = {
	description = "wh_2h_sword_skin_04_magic_02_description",
	display_name = "wh_2h_sword_skin_04_magic_02_name",
	hud_icon = "weapon_generic_icon_sword",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wh_2h_sword_skin_04_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_2h_sword",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "two_handed_swords_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.we_2h_axe_skin_03_magic_02 = {
	description = "we_2h_axe_skin_03_magic_02_description",
	display_name = "we_2h_axe_skin_03_magic_02_name",
	hud_icon = "weapon_generic_icon_elf_axe2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_we_2h_axe_skin_03_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "we_2h_axe",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "two_handed_axes_template_2",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.es_2h_hammer_skin_02_magic_02 = {
	description = "es_2h_hammer_skin_02_magic_02_description",
	display_name = "es_2h_hammer_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_2h_hammer_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_2h_hammer",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "two_handed_hammers_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.es_repeating_handgun_skin_01_magic_02 = {
	description = "es_repeating_handgun_skin_01_magic_02_description",
	display_name = "es_repeating_handgun_skin_01_magic_02_name",
	hud_icon = "weapon_generic_icon_repeating_handgun",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_repeating_handgun_skin_01_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_repeating_handgun",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "repeating_handgun_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.dr_1h_throwing_axes_skin_02_magic_02 = {
	description = "dr_1h_throwing_axes_skin_02_magic_02_description",
	display_name = "dr_1h_throwing_axes_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_falken",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_dr_1h_throwing_axes_skin_02_magic_02",
	is_ammo_weapon = true,
	item_type = "weapon_skin",
	matching_item_key = "dr_1h_throwing_axes",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_throwing_axes_template",
	can_wield = {
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.bw_1h_mace_skin_02_magic_02 = {
	description = "bw_1h_mace_skin_02_magic_02_description",
	display_name = "bw_1h_mace_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_mace",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_bw_1h_mace_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_1h_mace",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_wizard_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.wh_1h_axe_skin_06_magic_02 = {
	description = "wh_1h_axe_skin_06_magic_02_description",
	display_name = "wh_1h_axe_skin_06_magic_02_name",
	hud_icon = "weapon_generic_icon_axe1h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wh_1h_axe_skin_06_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_1h_axe",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_hand_axe_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.bw_spear_staff_skin_05_magic_02 = {
	description = "bw_spear_staff_skin_05_magic_02_description",
	display_name = "bw_spear_staff_skin_05_magic_02_name",
	hud_icon = "weapon_generic_icon_staff_5",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_bw_spear_staff_skin_05_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_skullstaff_spear",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "staff_spark_spear_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.wh_repeating_pistol_skin_05_magic_02 = {
	description = "wh_repeating_pistol_skin_05_magic_02_description",
	display_name = "wh_repeating_pistol_skin_05_magic_02_name",
	hud_icon = "weapon_generic_icon_repeating_pistol",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wh_repeating_pistol_skin_05_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_repeating_pistols",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "repeating_pistol_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.wh_crossbow_skin_06_magic_02 = {
	description = "wh_crossbow_skin_06_magic_02_description",
	display_name = "wh_crossbow_skin_06_magic_02_name",
	hud_icon = "weapon_generic_icon_crossbow",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wh_crossbow_skin_06_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_crossbow",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "crossbow_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.es_2h_sword_skin_03_magic_02 = {
	description = "es_2h_sword_skin_03_magic_02_description",
	display_name = "es_2h_sword_skin_03_magic_02_name",
	hud_icon = "weapon_generic_icon_sword",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_2h_sword_skin_03_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_2h_sword",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "two_handed_swords_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.we_shortbow_skin_02_magic_02 = {
	description = "we_shortbow_skin_02_magic_02_description",
	display_name = "we_shortbow_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_bow",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_we_shortbow_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "we_shortbow",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "shortbow_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.dw_1h_hammer_shield_skin_04_magic_02 = {
	description = "dw_1h_hammer_shield_skin_04_magic_02_description",
	display_name = "dw_1h_hammer_shield_skin_04_magic_02_name",
	hud_icon = "weapon_generic_icon_hammer_and_sheild",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_dw_1h_hammer_shield_skin_04_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_shield_hammer",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_shield_template_2",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
}
ItemMasterList.wh_brace_of_pistols_skin_05_magic_02 = {
	description = "wh_brace_of_pistols_skin_05_magic_02_description",
	display_name = "wh_brace_of_pistols_skin_05_magic_02_name",
	hud_icon = "weapon_generic_icon_brace_of_pistol",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wh_brace_of_pistols_skin_05_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_brace_of_pistols",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "brace_of_pistols_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.bw_beam_staff_skin_02_magic_02 = {
	description = "bw_beam_staff_skin_02_magic_02_description",
	display_name = "bw_beam_staff_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_staff_4",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_bw_beam_staff_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_skullstaff_beam",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "staff_blast_beam_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.dw_2h_hammer_skin_03_magic_02 = {
	description = "dw_2h_hammer_skin_03_magic_02_description",
	display_name = "dw_2h_hammer_skin_03_magic_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_dw_2h_hammer_skin_03_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_2h_hammer",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "two_handed_hammers_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.dw_2h_pick_skin_02_magic_02 = {
	description = "dw_2h_pick_skin_02_magic_02_description",
	display_name = "dw_2h_pick_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_pick",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_dw_2h_pick_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_2h_pick",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "two_handed_picks_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.we_spear_skin_02_magic_02 = {
	description = "we_spear_skin_02_magic_02_description",
	display_name = "we_spear_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_we_spear_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "we_spear",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "two_handed_spears_elf_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.we_dual_sword_skin_06_magic_02 = {
	description = "we_dual_sword_skin_06_magic_02_description",
	display_name = "we_dual_sword_skin_06_magic_02_name",
	hud_icon = "weapon_generic_icon_dual_elf_sword",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_we_dual_sword_skin_06_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "we_dual_wield_swords",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "dual_wield_swords_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.bw_1h_flail_flaming_skin_02_magic_02 = {
	description = "bw_1h_flail_flaming_skin_02_magic_02_description",
	display_name = "bw_1h_flail_flaming_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_falken",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_bw_1h_flail_flaming_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_1h_flail_flaming",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_flails_flaming_template",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.we_dual_sword_dagger_skin_07_magic_02 = {
	description = "we_dual_sword_dagger_skin_07_magic_02_description",
	display_name = "we_dual_sword_dagger_skin_07_magic_02_name",
	hud_icon = "weapon_generic_icon_elf_sword_and_dagger",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_we_dual_sword_dagger_skin_07_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "we_dual_wield_sword_dagger",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "dual_wield_sword_dagger_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.es_dual_wield_hammer_sword_skin_02_magic_02 = {
	description = "es_dual_wield_hammer_sword_skin_02_magic_02_description",
	display_name = "es_dual_wield_hammer_sword_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_falken",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_dual_wield_hammer_sword_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_dual_wield_hammer_sword",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "dual_wield_hammer_sword_template",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.wh_2h_billhook_skin_02_magic_02 = {
	description = "wh_2h_billhook_skin_02_magic_02_description",
	display_name = "wh_2h_billhook_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_falken",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wh_2h_billhook_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_2h_billhook",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "two_handed_billhooks_template",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.es_1h_flail_skin_04_magic_02 = {
	description = "es_1h_flail_skin_04_magic_02_description",
	display_name = "es_1h_flail_skin_04_magic_02_name",
	hud_icon = "weapon_generic_icon_mace",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_1h_flail_skin_04_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_1h_flail",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_flail_template_1",
	can_wield = {
		"wh_zealot",
		"wh_captain",
		"wh_bountyhunter",
	},
}
ItemMasterList.bw_conflagration_staff_skin_01_magic_02 = {
	description = "bw_conflagration_staff_skin_01_magic_02_description",
	display_name = "bw_conflagration_staff_skin_01_magic_02_name",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_bw_conflagration_staff_skin_01_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_skullstaff_geiser",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "staff_fireball_geiser_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.es_1h_sword_skin_04_magic_02 = {
	description = "es_1h_sword_skin_04_magic_02_description",
	display_name = "es_1h_sword_skin_04_magic_02_name",
	hud_icon = "weapon_generic_icon_sword",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_1h_sword_skin_04_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_1h_sword",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_swords_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.es_1h_mace_skin_05_magic_02 = {
	description = "es_1h_mace_skin_05_magic_02_description",
	display_name = "es_1h_mace_skin_05_magic_02_name",
	hud_icon = "weapon_generic_icon_mace",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_1h_mace_skin_05_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_1h_mace",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.dw_drake_pistol_skin_01_magic_02 = {
	description = "dw_drake_pistol_skin_01_magic_02_description",
	display_name = "dw_drake_pistol_skin_01_magic_02_name",
	hud_icon = "weapon_generic_icon_drakefire_pistols",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_dw_drake_pistol_skin_01_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_drake_pistol",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "brace_of_drakefirepistols_template_1",
	can_wield = {
		"dr_ironbreaker",
	},
}
ItemMasterList.dw_grudge_raker_skin_03_magic_02 = {
	description = "dw_grudge_raker_skin_03_magic_02_description",
	display_name = "dw_grudge_raker_skin_03_magic_02_name",
	hud_icon = "weapon_generic_icon_grudgeraker",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_dw_grudge_raker_skin_03_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_rakegun",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "grudge_raker_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
}
ItemMasterList.es_1h_mace_shield_skin_04_magic_02 = {
	description = "es_1h_mace_shield_skin_04_magic_02_description",
	display_name = "es_1h_mace_shield_skin_04_magic_02_name",
	hud_icon = "weapon_generic_icon_mace_and_sheild",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_1h_mace_shield_skin_04_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_mace_shield",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_shield_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.es_halberd_skin_03_magic_02 = {
	description = "es_halberd_skin_03_magic_02_description",
	display_name = "es_halberd_skin_03_magic_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_halberd_skin_03_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_halberd",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "two_handed_halberds_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.es_longbow_skin_04_magic_02 = {
	description = "es_longbow_skin_04_magic_02_description",
	display_name = "es_longbow_skin_04_magic_02_name",
	hud_icon = "weapon_generic_icon_bow",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_longbow_skin_04_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_longbow",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "longbow_empire_template",
	can_wield = {
		"es_huntsman",
	},
}
ItemMasterList.dw_crossbow_skin_03_magic_02 = {
	description = "dw_crossbow_skin_03_magic_02_description",
	display_name = "dw_crossbow_skin_03_magic_02_name",
	hud_icon = "weapon_generic_icon_crossbow",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_dw_crossbow_skin_03_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_crossbow",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "crossbow_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
}
ItemMasterList.es_handgun_skin_02_magic_02 = {
	description = "es_handgun_skin_02_magic_02_description",
	display_name = "es_handgun_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_units/weapons/weapon_display/display_rifle",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_handgun_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_handgun",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "handgun_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.dw_drakegun_skin_02_magic_02 = {
	description = "dw_drakegun_skin_02_magic_02_description",
	display_name = "dw_drakegun_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_units/weapons/weapon_display/display_rifle",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_dw_drakegun_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_drakegun",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "drakegun_template_1",
	can_wield = {
		"dr_ironbreaker",
	},
}
ItemMasterList.es_blunderbuss_skin_01_magic_02 = {
	description = "es_blunderbuss_skin_01_magic_02_description",
	display_name = "es_blunderbuss_skin_01_magic_02_name",
	hud_icon = "weapon_generic_icon_blunderbuss",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_blunderbuss_skin_01_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_blunderbuss",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "blunderbuss_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.dw_2h_axe_skin_02_magic_02 = {
	description = "dw_2h_axe_skin_02_magic_02_description",
	display_name = "dw_2h_axe_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_axe2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_dw_2h_axe_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_2h_axe",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "two_handed_axes_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.wh_repeating_crossbow_skin_02_magic_02 = {
	description = "wh_repeating_crossbow_skin_02_magic_02_description",
	display_name = "wh_repeating_crossbow_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_repeating_crossbow",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wh_repeating_crossbow_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_crossbow_repeater",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "repeating_crossbow_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.bw_fireball_staff_skin_02_magic_02 = {
	description = "bw_fireball_staff_skin_02_magic_02_description",
	display_name = "bw_fireball_staff_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_staff_2",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_bw_fireball_staff_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_skullstaff_fireball",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "staff_fireball_fireball_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.dw_1h_hammer_skin_03_magic_02 = {
	description = "dw_1h_hammer_skin_03_magic_02_description",
	display_name = "dw_1h_hammer_skin_03_magic_02_name",
	hud_icon = "weapon_generic_icon_hammer1h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_dw_1h_hammer_skin_03_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_1h_hammer",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_template_2",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.we_2h_sword_skin_08_magic_02 = {
	description = "we_2h_sword_skin_08_magic_02_description",
	display_name = "we_2h_sword_skin_08_magic_02_name",
	hud_icon = "weapon_generic_icon_elf_axe2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_we_2h_sword_skin_08_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "we_2h_sword",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "two_handed_swords_wood_elf_template",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.dw_1h_axe_skin_04_magic_02 = {
	description = "dw_1h_axe_skin_04_magic_02_description",
	display_name = "dw_1h_axe_skin_04_magic_02_name",
	hud_icon = "weapon_generic_icon_axe1h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_dw_1h_axe_skin_04_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_1h_axe",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_hand_axe_template_2",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.bw_1h_sword_skin_06_magic_02 = {
	description = "bw_1h_sword_skin_06_magic_02_description",
	display_name = "bw_1h_sword_skin_06_magic_02_name",
	hud_icon = "weapon_generic_icon_sword",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_bw_1h_sword_skin_06_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_sword",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_swords_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.es_1h_sword_shield_skin_04_magic_02 = {
	description = "es_1h_sword_shield_skin_04_magic_02_description",
	display_name = "es_1h_sword_shield_skin_04_magic_02_name",
	hud_icon = "weapon_generic_icon_sword_and_sheild",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_1h_sword_shield_skin_04_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_sword_shield",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_sword_shield_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.wh_dual_wield_axe_falchion_skin_01_magic_02 = {
	description = "wh_dual_wield_axe_falchion_skin_01_magic_02_description",
	display_name = "wh_dual_wield_axe_falchion_skin_01_magic_02_name",
	hud_icon = "weapon_generic_icon_falken",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wh_dual_wield_axe_falchion_skin_01_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_dual_wield_axe_falchion",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "dual_wield_axe_falchion_template",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.we_longbow_skin_02_magic_02 = {
	description = "we_longbow_skin_02_magic_02_description",
	display_name = "we_longbow_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_bow",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_we_longbow_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "we_longbow",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "longbow_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.wh_1h_falchion_skin_04_magic_02 = {
	description = "wh_1h_falchion_skin_04_magic_02_description",
	display_name = "wh_1h_falchion_skin_04_magic_02_name",
	hud_icon = "weapon_generic_icon_falken",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wh_1h_falchion_skin_04_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_1h_falchion",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_hand_falchion_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.we_1h_spears_shield_skin_02_magic_02 = {
	description = "we_1h_spears_shield_skin_02_magic_02_description",
	display_name = "we_1h_spears_shield_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_falken",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_we_1h_spears_shield_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "we_1h_spears_shield",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_spears_shield_template",
	can_wield = {
		"we_maidenguard",
	},
}
ItemMasterList.we_sword_skin_06_magic_02 = {
	description = "we_sword_skin_06_magic_02_description",
	display_name = "we_sword_skin_06_magic_02_name",
	hud_icon = "weapon_generic_icon_elf_sword",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_we_sword_skin_06_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "we_1h_sword",
	rarity = "unique",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "we_one_hand_sword_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.wh_1h_hammer_skin_02_magic_02 = {
	description = "wh_1h_hammer_skin_02_magic_02_description",
	display_name = "wh_1h_hammer_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wh_1h_hammer_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_1h_hammer",
	rarity = "unique",
	required_dlc = "bless",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_2h_hammer_skin_02_magic_02 = {
	description = "wh_2h_hammer_skin_02_magic_02_description",
	display_name = "wh_2h_hammer_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wh_2h_hammer_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_2h_hammer",
	rarity = "unique",
	required_dlc = "bless",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "two_handed_hammer_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_hammer_shield_skin_02_magic_02 = {
	description = "wh_hammer_shield_skin_02_magic_02_description",
	display_name = "wh_hammer_shield_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wh_hammer_shield_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_hammer_shield",
	rarity = "unique",
	required_dlc = "bless",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_shield_priest_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_dual_hammer_skin_02_magic_02 = {
	description = "wh_dual_hammer_skin_02_magic_02_description",
	display_name = "wh_dual_hammer_skin_02_magic_02_name",
	hud_icon = "hud_icon_default",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wh_dual_hammer_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_dual_hammer",
	rarity = "unique",
	required_dlc = "bless",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "dual_wield_hammers_priest_template",
	can_wield = {
		"wh_priest",
		"wh_zealot",
	},
}
ItemMasterList.wh_hammer_book_skin_02_magic_02 = {
	description = "wh_hammer_book_skin_02_magic_02_description",
	display_name = "wh_hammer_book_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wh_hammer_book_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_hammer_book",
	rarity = "unique",
	required_dlc = "bless",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_hammer_book_priest_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.wh_flail_shield_skin_02_magic_02 = {
	description = "wh_flail_shield_skin_02_magic_02_description",
	display_name = "wh_flail_shield_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wh_flail_shield_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_flail_shield",
	rarity = "unique",
	required_dlc = "bless",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_flail_shield_template",
	can_wield = {
		"wh_priest",
	},
}
ItemMasterList.we_javelin_skin_02_magic_02 = {
	description = "we_javelin_skin_02_magic_02_description",
	display_name = "we_javelin_skin_02_magic_02_name",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_we_javelin_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "we_javelin",
	rarity = "unique",
	required_dlc = "woods",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "two_handed_spears_elf_template_1",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.we_life_staff_skin_02_magic_02 = {
	description = "we_life_staff_skin_02_magic_02_description",
	display_name = "we_life_staff_skin_02_magic_02_name",
	hud_icon = "icons_placeholder",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_we_life_staff_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "we_life_staff",
	rarity = "unique",
	required_dlc = "woods",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "staff_life",
	can_wield = {
		"we_thornsister",
	},
}
ItemMasterList.es_bastard_sword_skin_04_magic_02 = {
	description = "es_bastard_sword_skin_04_magic_02_description",
	display_name = "es_bastard_sword_skin_04_magic_02_name",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_bastard_sword_skin_04_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_bastard_sword",
	rarity = "unique",
	required_dlc = "lake",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "bastard_sword_template",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
		"es_questingknight",
	},
}
ItemMasterList.es_sword_shield_breton_skin_04_magic_02 = {
	description = "es_sword_shield_breton_skin_04_magic_02_description",
	display_name = "es_sword_shield_breton_skin_04_magic_02_name",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_es_sword_shield_breton_skin_04_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_sword_shield_breton",
	rarity = "unique",
	required_dlc = "lake",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "one_handed_sword_shield_template_2",
	can_wield = {
		"es_questingknight",
	},
}
ItemMasterList.dr_2h_cog_hammer_skin_02_magic_02 = {
	description = "dr_2h_cog_hammer_skin_02_magic_02_description",
	display_name = "dr_2h_cog_hammer_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_dr_2h_cog_hammer_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_2h_cog_hammer",
	rarity = "unique",
	required_dlc = "cog",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "two_handed_cog_hammers_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
		"dr_slayer",
	},
}
ItemMasterList.dr_steam_pistol_skin_02_magic_02 = {
	description = "dr_steam_pistol_skin_02_magic_02_description",
	display_name = "dr_steam_pistol_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_dr_steam_pistol_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_steam_pistol",
	rarity = "unique",
	required_dlc = "cog",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "heavy_steam_pistol_template_1",
	can_wield = {
		"dr_engineer",
		"dr_ranger",
		"dr_ironbreaker",
	},
}
ItemMasterList.bw_ghost_scythe_skin_02_magic_02 = {
	description = "bw_ghost_scythe_skin_02_magic_02_description",
	display_name = "bw_ghost_scythe_skin_02_magic_02_name",
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_bw_ghost_scythe_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_ghost_scythe",
	rarity = "unique",
	required_dlc = "shovel",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "staff_scythe",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.bw_necromancy_staff_skin_02_magic_02 = {
	description = "bw_necromancy_staff_skin_02_magic_02_description",
	display_name = "bw_necromancy_staff_skin_02_magic_02_name",
	hud_icon = "hud_icon_default",
	inventory_icon = "icon_bw_necromancy_staff_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_necromancy_staff",
	rarity = "unique",
	required_dlc = "shovel",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "staff_death",
	can_wield = {
		"bw_necromancer",
	},
}
ItemMasterList.wh_deus_skin_02_magic_02 = {
	description = "wh_deus_skin_02_magic_02_desciption",
	display_name = "wh_deus_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_bow",
	inventory_icon = "icon_wh_deus_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "wh_deus_01",
	rarity = "unique",
	required_dlc = "grass",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "wh_deus_01_template_1",
	can_wield = {
		"wh_bountyhunter",
		"wh_captain",
		"wh_zealot",
	},
}
ItemMasterList.we_deus_skin_01_magic_02 = {
	description = "we_deus_skin_01_magic_02_description",
	display_name = "we_deus_skin_01_magic_02_name",
	hud_icon = "weapon_generic_icon_bow",
	inventory_icon = "icon_we_deus_skin_01_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "we_deus_01",
	rarity = "unique",
	required_dlc = "grass",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "we_deus_01_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"we_thornsister",
	},
}
ItemMasterList.bw_deus_skin_02_magic_02 = {
	description = "bw_deus_skin_02_magic_02_description",
	display_name = "bw_deus_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_bw_deus_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "bw_deus_01",
	rarity = "unique",
	required_dlc = "grass",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "bw_deus_01_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.es_deus_skin_02_magic_02 = {
	description = "es_deus_skin_02_magic_02_description",
	display_name = "es_deus_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_es_deus_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "es_deus_01",
	rarity = "unique",
	required_dlc = "grass",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "es_deus_01_template",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.dr_deus_skin_02_magic_02 = {
	description = "dr_deus_skin_02_magic_02_description",
	display_name = "dr_deus_skin_02_magic_02_name",
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_dr_deus_skin_02_magic_02",
	item_type = "weapon_skin",
	matching_item_key = "dr_deus_01",
	rarity = "unique",
	required_dlc = "grass",
	selection = "versus",
	slot_type = "weapon_skin",
	template = "dr_deus_01_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_engineer",
	},
}
