-- chunkname: @scripts/settings/equipment/item_master_list_paperweight.lua

ItemMasterList.we_1h_axe = {
	description = "we_1h_axe_skin_01_description",
	display_name = "we_1h_axe_skin_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_falken",
	inventory_icon = "icon_we_1h_axe_01",
	item_type = "we_1h_axe",
	property_table_name = "melee",
	rarity = "plentiful",
	required_dlc = "holly",
	right_hand_unit = "units/weapons/player/wpn_we_axe_01_t2/wpn_we_axe_01_t2",
	skin_combination_table = "we_1h_axe_skins",
	slot_type = "melee",
	template = "we_one_hand_axe_template",
	trait_table_name = "melee",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.bw_1h_crowbill = {
	description = "bw_1h_crowbill_skin_01_description",
	display_name = "bw_1h_crowbill_skin_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_falken",
	inventory_icon = "icon_bw_1h_crowbill_01",
	item_type = "bw_1h_crowbill",
	property_table_name = "melee",
	rarity = "plentiful",
	required_dlc = "holly",
	right_hand_unit = "units/weapons/player/wpn_brw_crowbill_01/wpn_brw_crowbill_01",
	skin_combination_table = "bw_1h_crowbill_skins",
	slot_type = "melee",
	template = "one_handed_crowbill",
	trait_table_name = "melee",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.wh_dual_wield_axe_falchion = {
	description = "wh_dual_wield_axe_falchion_skin_01_description",
	display_name = "wh_dual_wield_axe_falchion_skin_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_falken",
	inventory_icon = "icon_wh_dual_wield_axe_falchion_01",
	item_type = "wh_dual_wield_axe_falchion",
	left_hand_unit = "units/weapons/player/wpn_emp_sword_04_t1/wpn_emp_sword_04_t1",
	property_table_name = "melee",
	rarity = "plentiful",
	required_dlc = "holly",
	right_hand_unit = "units/weapons/player/wpn_axe_hatchet_t2/wpn_axe_hatchet_t2",
	skin_combination_table = "wh_dual_wield_axe_falchion_skins",
	slot_type = "melee",
	template = "dual_wield_axe_falchion_template",
	trait_table_name = "melee",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.dr_dual_wield_hammers = {
	description = "dr_dual_wield_hammers_skin_01_description",
	display_name = "dr_dual_wield_hammers_skin_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_falken",
	inventory_icon = "icon_dr_dual_wield_hammers_01",
	item_type = "dr_dual_wield_hammers",
	left_hand_unit = "units/weapons/player/wpn_dw_hammer_03_t1/wpn_dw_hammer_03_t1",
	property_table_name = "melee",
	rarity = "plentiful",
	required_dlc = "holly",
	right_hand_unit = "units/weapons/player/wpn_dw_hammer_03_t1/wpn_dw_hammer_03_t1",
	skin_combination_table = "dr_dual_wield_hammers_skins",
	slot_type = "melee",
	template = "dual_wield_hammers_template",
	trait_table_name = "melee",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.es_dual_wield_hammer_sword = {
	description = "es_dual_wield_hammer_sword_skin_01_description",
	display_name = "es_dual_wield_hammer_sword_skin_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_falken",
	inventory_icon = "icon_es_dual_wield_hammer_sword_01",
	item_type = "es_dual_wield_hammer_sword",
	left_hand_unit = "units/weapons/player/wpn_emp_sword_06_t1/wpn_emp_sword_06_t1",
	property_table_name = "melee",
	rarity = "plentiful",
	required_dlc = "holly",
	right_hand_unit = "units/weapons/player/wpn_emp_mace_04_t2/wpn_emp_mace_04_t2",
	skin_combination_table = "es_dual_wield_hammer_sword_skins",
	slot_type = "melee",
	template = "dual_wield_hammer_sword_template",
	trait_table_name = "melee",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.we_1h_axe_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "we_1h_axe",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"we_waywatcher",
		"we_maidenguard",
		"we_shade",
	},
}
ItemMasterList.bw_1h_crowbill_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "bw_1h_crowbill",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.dr_dual_wield_hammers_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "dr_dual_wield_hammers",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.wh_dual_wield_axe_falchion_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "wh_dual_wield_axe_falchion",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.es_dual_wield_hammer_sword_skin = {
	base_skin_item = true,
	information_text = "information_weapon_skin",
	item_type = "weapon_skin",
	matching_item_key = "es_dual_wield_hammer_sword",
	rarity = "plentiful",
	slot_type = "weapon_skin",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
