-- chunkname: @scripts/settings/equipment/item_master_list_celebrate.lua

ItemMasterList.wpn_beer_bottle = {
	description = "description_wpn_beer_bottle",
	gamepad_hud_icon = "icons_placeholder",
	hud_icon = "icons_placeholder",
	inventory_icon = "icons_placeholder",
	is_local = true,
	item_type = "potion",
	rarity = "plentiful",
	right_hand_unit = "units/weapons/player/wpn_ale/wpn_ale",
	slot_type = "potion",
	temporary_template = "beer_bottle",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_celebration_01 = {
	description = "frame_celebration_01_description",
	display_name = "frame_celebration_01_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_celebration_1",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_celebration_01",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_celebration_02 = {
	description = "frame_celebration_02_description",
	display_name = "frame_celebration_02_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_celebration_2",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_celebration_02",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_celebration_03 = {
	description = "frame_celebration_03_description",
	display_name = "frame_celebration_03_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_celebration_3",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_celebration_03",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_celebration_05 = {
	description = "frame_celebration_05_description",
	display_name = "frame_celebration_05_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_celebration_05",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_celebration_05",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_celebration_06 = {
	description = "frame_celebration_06_description",
	display_name = "frame_celebration_06_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_celebration_06",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_celebration_06",
	can_wield = CanWieldAllItemTemplates,
}
