-- chunkname: @scripts/settings/equipment/item_master_list_test_items.lua

local store_item_hidden = not Application or not Application.user_setting("show_test_item")

ItemMasterList.test_item_1001 = {
	description = "test_item_1001_desc",
	display_name = "test_item_1001",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1001",
	inventory_icon = "icon_unchained_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 1,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.test_item_1002 = {
	description = "test_item_1002_desc",
	display_name = "test_item_1002",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1002",
	inventory_icon = "icon_zealot_hat_1003",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 2,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.test_item_1003 = {
	description = "test_item_1003_desc",
	display_name = "test_item_1003",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1003",
	inventory_icon = "icon_adept_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 3,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.test_item_1004 = {
	description = "test_item_1004_desc",
	display_name = "test_item_1004",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1004",
	inventory_icon = "icon_scholar_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 4,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.test_item_1005 = {
	description = "test_item_1005_desc",
	display_name = "test_item_1005",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1005",
	inventory_icon = "icon_ranger_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 5,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.test_item_1006 = {
	description = "test_item_1006_desc",
	display_name = "test_item_1006",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1006",
	inventory_icon = "icon_ironbreaker_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 6,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.test_item_1007 = {
	description = "test_item_1007_desc",
	display_name = "test_item_1007",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1007t",
	inventory_icon = "icon_slayer_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 7,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.test_item_1008 = {
	description = "test_item_1008_desc",
	display_name = "test_item_1008",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1008",
	inventory_icon = "icon_huntsman_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 8,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.test_item_1009 = {
	description = "test_item_1009_desc",
	display_name = "test_item_1009",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1009",
	inventory_icon = "icon_mercenary_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 9,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.test_item_1010 = {
	description = "test_item_1010_desc",
	display_name = "test_item_1010",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1010t",
	inventory_icon = "icon_knight_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 10,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.test_item_1011 = {
	description = "test_item_1011_desc",
	display_name = "test_item_1011",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1011",
	inventory_icon = "icon_witchhunter_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 11,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.test_item_1012 = {
	description = "test_item_1012_desc",
	display_name = "test_item_1012",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1012",
	inventory_icon = "icon_zealot_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 12,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.test_item_1013 = {
	description = "test_item_1013_desc",
	display_name = "test_item_1013",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1013",
	inventory_icon = "icon_zealot_hat_1003",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 13,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.test_item_1014 = {
	description = "test_item_1014_desc",
	display_name = "test_item_1014",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1014",
	inventory_icon = "icon_bountyhunter_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 14,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.test_item_1015 = {
	description = "test_item_1015_desc",
	display_name = "test_item_1015",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1015",
	inventory_icon = "icon_waywatcher_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 15,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.test_bundle_1016 = {
	description = "test_bundle_1016_desc",
	display_name = "shade_bundle_01",
	hud_icon = "hud_icon_default",
	information_text = "shade_bundle_01",
	inventory_icon = "",
	item_type = "bundle",
	product_layout = "test_bundle_1016",
	rarity = "promo",
	show_discount = false,
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 16,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {},
	bundle_contains = {
		100,
		101,
		102,
	},
	steam_store_hidden = store_item_hidden,
}
