-- chunkname: @scripts/settings/equipment/item_master_list_cosmetics_2024_q3.lua

ItemMasterList.skin_bw_scholar_1003 = {
	description = "description_skin_bw_scholar_1003",
	display_name = "display_name_skin_bw_scholar_1003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_bw_scholar_1003",
	item_type = "skin",
	name = "skin_bw_scholar_1003",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 207,
	temporary_template = "skin_bw_scholar_1003",
	can_wield = {
		"bw_scholar",
		"bw_necromancer",
	},
}
ItemMasterList.skin_dr_slayer_1003 = {
	description = "description_skin_dr_slayer_1003",
	display_name = "display_name_skin_dr_slayer_1003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_dr_slayer_1003",
	item_type = "skin",
	name = "skin_dr_slayer_1003",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 204,
	temporary_template = "skin_dr_slayer_1003",
	can_wield = {
		"dr_slayer",
	},
}
ItemMasterList.skin_es_mercenary_1003 = {
	description = "description_skin_es_mercenary_1003",
	display_name = "display_name_skin_es_mercenary_1003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_mercenary_1003",
	item_type = "skin",
	name = "skin_es_mercenary_1003",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 206,
	temporary_template = "skin_es_mercenary_1003",
	can_wield = {
		"es_mercenary",
	},
}
ItemMasterList.skin_ww_thornsister_1001 = {
	description = "description_skin_ww_thornsister_1001",
	display_name = "display_name_skin_ww_thornsister_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ww_thornsister_1001",
	item_type = "skin",
	name = "skin_ww_thornsister_1001",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 205,
	temporary_template = "skin_ww_thornsister_1001",
	can_wield = {
		"we_thornsister",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.skin_wh_bountyhunter_1003 = {
	description = "description_skin_wh_bountyhunter_1003",
	display_name = "display_name_skin_wh_bountyhunter_1003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_wh_bountyhunter_1003",
	item_type = "skin",
	name = "skin_wh_bountyhunter_1003",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 208,
	temporary_template = "skin_wh_bountyhunter_1003",
	can_wield = {
		"wh_bountyhunter",
	},
}
ItemMasterList.five_career_bundle_0008 = {
	description = "description_five_career_bundle_0008",
	display_name = "display_name_five_career_bundle_0008",
	hud_icon = "",
	information_text = "five_career_bundle_0008",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 4800,
	product_layout = "five_career_bundle_0008",
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 850,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_five_career_bundle_0008",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_five_career_bundle_0008",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_five_career_bundle_0008",
	subtitle = "five_career_bundle_0001_subtitle",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
