ItemMasterList = ItemMasterList or {}
ItemMasterList.lamp_oil = {
	temporary_template = "lamp_oil",
	slot_type = "healthkit",
	rarity = "plentiful",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_oil_jug_01/wpn_oil_jug_01",
	gamepad_hud_icon = "consumables_icon_defence",
	hud_icon = "consumables_icon_defence",
	item_type = "inventory_item",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.wpn_cannon_ball_01 = {
	temporary_template = "cannon_ball",
	slot_type = "healthkit",
	rarity = "plentiful",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_cannon_ball_01/wpn_cannon_ball_01",
	gamepad_hud_icon = "consumables_icon_defence",
	hud_icon = "consumables_icon_defence",
	item_type = "inventory_item",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.healthkit_first_aid_kit_01 = {
	description = "description_healthkit_first_aid_kit_01",
	temporary_template = "first_aid_kit_02",
	slot_type = "healthkit",
	rarity = "plentiful",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_first_aid_kit_02/wpn_first_aid_kit_02",
	description_type = "healthkit",
	gamepad_hud_icon = "hud_icon_heal_01",
	hud_icon = "hud_inventory_icon_heal_01",
	item_type = "healthkit",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.wpn_grimoire_01 = {
	description = "description_wpn_grimoire_01",
	temporary_template = "wpn_grimoire_01",
	slot_type = "potion",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_grimoire_01/wpn_grimoire_01",
	description_type = "potion",
	rarity = "plentiful",
	gamepad_hud_icon = "hud_icon_grimoire",
	hud_icon = "hud_inventory_icon_grimoire",
	item_type = "potion",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.wpn_side_objective_tome_01 = {
	description = "description_wpn_side_objective_tome_01",
	temporary_template = "wpn_side_objective_tome_01",
	slot_type = "healthkit",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_side_objective_tome/wpn_side_objective_tome_01",
	description_type = "healthkit",
	rarity = "plentiful",
	gamepad_hud_icon = "hud_icon_tome",
	hud_icon = "hud_inventory_icon_tome",
	item_type = "healthkit",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.potion_healing_draught_01 = {
	description = "description_potion_healing_draught_01",
	temporary_template = "healing_draught",
	slot_type = "healthkit",
	rarity = "plentiful",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_potion_01/wpn_potion_healing_01",
	description_type = "healthkit",
	gamepad_hud_icon = "hud_icon_heal_02",
	hud_icon = "hud_inventory_icon_heal_02",
	item_type = "healthkit",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.grenade_frag_01 = {
	description = "description_grenade_frag_01",
	temporary_template = "frag_grenade_t1",
	right_hand_unit = "units/weapons/player/wpn_emp_grenade_01_t1/wpn_emp_grenade_01_t1",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_emp_grenade_01_t1/wpn_emp_grenade_lighter_01_t1",
	rarity = "plentiful",
	slot_type = "grenade",
	description_type = "grenade",
	gamepad_hud_icon = "hud_icon_bomb_01",
	hud_icon = "hud_inventory_icon_bomb",
	item_type = "grenade",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.grenade_frag_02 = {
	description = "description_grenade_frag_02",
	temporary_template = "frag_grenade_t2",
	right_hand_unit = "units/weapons/player/wpn_emp_grenade_01_t2/wpn_emp_grenade_01_t2",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_emp_grenade_01_t2/wpn_emp_grenade_lighter_01_t2",
	rarity = "plentiful",
	slot_type = "grenade",
	description_type = "grenade",
	gamepad_hud_icon = "hud_icon_bomb_01",
	hud_icon = "hud_inventory_icon_bomb",
	item_type = "grenade",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.grenade_smoke_01 = {
	description = "description_grenade_smoke_01",
	temporary_template = "smoke_grenade_t1",
	right_hand_unit = "units/weapons/player/wpn_emp_grenade_02_t1/wpn_emp_grenade_02_t1",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_emp_grenade_01_t1/wpn_emp_grenade_lighter_01_t1",
	rarity = "plentiful",
	slot_type = "grenade",
	description_type = "grenade",
	gamepad_hud_icon = "hud_icon_bomb_01",
	hud_icon = "hud_inventory_icon_bomb",
	item_type = "grenade",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.grenade_smoke_02 = {
	description = "description_grenade_smoke_02",
	temporary_template = "smoke_grenade_t2",
	right_hand_unit = "units/weapons/player/wpn_emp_grenade_02_t2/wpn_emp_grenade_02_t2",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_emp_grenade_01_t2/wpn_emp_grenade_lighter_01_t2",
	rarity = "plentiful",
	slot_type = "grenade",
	description_type = "grenade",
	gamepad_hud_icon = "hud_icon_bomb_01",
	hud_icon = "hud_inventory_icon_bomb",
	item_type = "grenade",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.grenade_fire_01 = {
	description = "description_grenade_fire_01",
	temporary_template = "fire_grenade_t1",
	right_hand_unit = "units/weapons/player/wpn_emp_grenade_03_t1/wpn_emp_grenade_03_t1",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_emp_grenade_01_t1/wpn_emp_grenade_lighter_01_t1",
	rarity = "plentiful",
	slot_type = "grenade",
	description_type = "grenade",
	gamepad_hud_icon = "hud_icon_bomb_02",
	hud_icon = "hud_inventory_icon_bomb_2",
	item_type = "grenade",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.grenade_fire_02 = {
	description = "description_grenade_fire_02",
	temporary_template = "fire_grenade_t2",
	right_hand_unit = "units/weapons/player/wpn_emp_grenade_03_t2/wpn_emp_grenade_03_t2",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_emp_grenade_01_t2/wpn_emp_grenade_lighter_01_t2",
	rarity = "plentiful",
	slot_type = "grenade",
	description_type = "grenade",
	gamepad_hud_icon = "hud_icon_bomb_02",
	hud_icon = "hud_inventory_icon_bomb_2",
	item_type = "grenade",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.grain_sack = {
	temporary_template = "sack",
	slot_type = "healthkit",
	rarity = "plentiful",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_sacks/wpn_sacks_01",
	gamepad_hud_icon = "consumables_icon_defence",
	hud_icon = "consumables_icon_defence",
	item_type = "inventory_item",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.door_stick = {
	temporary_template = "door_stick",
	right_hand_unit = "units/gameplay/timed_door_base_02/wpn_timed_door_stick",
	rarity = "plentiful",
	inventory_icon = "icons_placeholder",
	slot_type = "healthkit",
	gamepad_hud_icon = "consumables_icon_defence",
	hud_icon = "consumables_icon_defence",
	item_type = "inventory_item",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.explosive_barrel = {
	temporary_template = "explosive_barrel",
	slot_type = "healthkit",
	rarity = "plentiful",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_explosive_barrel/wpn_explosive_barrel_01",
	gamepad_hud_icon = "consumables_icon_defence",
	hud_icon = "consumables_icon_defence",
	item_type = "explosive_inventory_item",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.explosive_barrel_objective = {
	temporary_template = "explosive_barrel_objective",
	slot_type = "healthkit",
	rarity = "plentiful",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_explosive_barrel/wpn_gun_powder_barrel_01",
	gamepad_hud_icon = "consumables_icon_defence",
	hud_icon = "consumables_icon_defence",
	item_type = "explosive_inventory_item",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.beer_barrel = {
	temporary_template = "explosive_barrel_objective",
	slot_type = "healthkit",
	rarity = "plentiful",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_explosive_barrel/wpn_explosive_barrel_01",
	gamepad_hud_icon = "consumables_icon_defence",
	hud_icon = "consumables_icon_defence",
	item_type = "inventory_item",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.wpn_gargoyle_head = {
	temporary_template = "gargoyle_head",
	slot_type = "healthkit",
	rarity = "plentiful",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_gargoyle_head/wpn_gargoyle_head",
	gamepad_hud_icon = "consumables_icon_defence",
	hud_icon = "consumables_icon_defence",
	item_type = "inventory_item",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.torch = {
	temporary_template = "torch",
	right_hand_unit = "units/weapons/player/wpn_torch/wpn_torch",
	rarity = "plentiful",
	inventory_icon = "icons_placeholder",
	slot_type = "healthkit",
	gamepad_hud_icon = "consumables_icon_defence",
	hud_icon = "consumables_icon_defence",
	item_type = "inventory_item",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.packmaster_claw = {
	temporary_template = "packmaster_claw",
	right_hand_unit = "units/weapons/player/wpn_packmaster_claw/wpn_packmaster_claw",
	rarity = "plentiful",
	item_type = "inventory_item",
	slot_type = "slot_packmaster_claw",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.potion_damage_boost_01 = {
	description = "description_potion_damage_boost_01",
	temporary_template = "damage_boost_potion",
	slot_type = "potion",
	rarity = "plentiful",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_potion_01/wpn_potion_strenght_01",
	description_type = "potion",
	gamepad_hud_icon = "hud_icon_potion_strength",
	hud_icon = "hud_inventory_icon_potion_strength",
	item_type = "potion",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.potion_speed_boost_01 = {
	description = "description_potion_speed_boost_01",
	temporary_template = "speed_boost_potion",
	slot_type = "potion",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_potion_01/wpn_potion_speed_01",
	description_type = "potion",
	rarity = "plentiful",
	gamepad_hud_icon = "hud_icon_potion_speed",
	hud_icon = "hud_inventory_icon_potion_speed",
	item_type = "potion",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.potion_cooldown_reduction_01 = {
	description = "description_potion_cooldown_reduction_01",
	temporary_template = "cooldown_reduction_potion",
	slot_type = "potion",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/weapons/player/wpn_potion_01/wpn_potion_extra_01",
	description_type = "potion",
	rarity = "plentiful",
	gamepad_hud_icon = "hud_icon_potion_cooldown_reduction",
	hud_icon = "hud_inventory_icon_potion_cooldown_reduction",
	item_type = "potion",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.bardin_ranger_career_skill_weapon = {
	rarity = "plentiful",
	right_hand_unit = "units/weapons/player/wpn_emp_grenade_02_t2/wpn_emp_grenade_02_t2",
	template = "bardin_ranger_career_skill_weapon",
	can_wield = {}
}
ItemMasterList.kerillian_waywatcher_career_skill_weapon = {
	template = "kerillian_waywatcher_career_skill_weapon",
	slot_to_use = "slot_ranged",
	rarity = "plentiful",
	can_wield = {}
}
ItemMasterList.sienna_scholar_career_skill_weapon = {
	template = "sienna_scholar_career_skill_weapon",
	left_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	rarity = "plentiful",
	can_wield = {}
}
ItemMasterList.victor_bountyhunter_career_skill_weapon = {
	template = "victor_bountyhunter_career_skill_weapon",
	left_hand_unit = "units/weapons/player/wpn_emp_shotgun/wpn_emp_shotgun",
	rarity = "plentiful",
	can_wield = {}
}
ItemMasterList.training_dummy = {
	temporary_template = "training_dummy",
	slot_type = "healthkit",
	rarity = "plentiful",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/gameplay/training_dummy/wpn_training_dummy",
	gamepad_hud_icon = "consumables_icon_defence",
	hud_icon = "consumables_icon_defence",
	item_type = "inventory_item",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.training_dummy_armored = {
	temporary_template = "training_dummy_armored",
	slot_type = "healthkit",
	rarity = "plentiful",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/gameplay/training_dummy/wpn_training_dummy_armored",
	gamepad_hud_icon = "consumables_icon_defence",
	hud_icon = "consumables_icon_defence",
	item_type = "inventory_item",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}
ItemMasterList.training_dummy_skaven = {
	temporary_template = "training_dummy_skaven",
	slot_type = "healthkit",
	rarity = "plentiful",
	inventory_icon = "icons_placeholder",
	left_hand_unit = "units/gameplay/training_dummy/training_dummy_skaven/wpn_training_dummy_skaven",
	gamepad_hud_icon = "consumables_icon_defence",
	hud_icon = "consumables_icon_defence",
	item_type = "inventory_item",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
		"es_huntsman",
		"es_knight",
		"es_mercenary"
	}
}

return
