-- chunkname: @scripts/settings/equipment/item_master_list_scorpion.lua

ItemMasterList.es_1h_sword_magic_01 = {
	description = "es_1h_sword_skin_04_magic_01_description",
	display_name = "es_1h_sword_skin_04_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_sword",
	inventory_icon = "icon_emp_sword_03_t2_magic_01",
	item_type = "es_1h_sword",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "es_1h_sword",
	right_hand_unit = "units/weapons/player/wpn_emp_sword_03_t2/wpn_emp_sword_03_t2_magic_01",
	slot_type = "melee",
	template = "one_handed_swords_template_1",
	trait_table_name = "melee",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.es_1h_mace_magic_01 = {
	description = "es_1h_mace_skin_05_magic_01_description",
	display_name = "es_1h_mace_skin_05_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_mace",
	inventory_icon = "icon_emp_mace_03_t2_magic_01",
	item_type = "es_1h_mace",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "es_1h_mace",
	right_hand_unit = "units/weapons/player/wpn_emp_mace_03_t2/wpn_emp_mace_03_t2_magic_01",
	slot_type = "melee",
	template = "one_handed_hammer_template_1",
	trait_table_name = "melee",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.es_2h_sword_executioner_magic_01 = {
	description = "es_2h_sword_exe_skin_03_magic_01_description",
	display_name = "es_2h_sword_exe_skin_03_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_sword",
	inventory_icon = "icon_emp_sword_exe_03_t1_magic_01",
	item_type = "es_2h_sword_executioner",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "es_2h_sword_executioner",
	right_hand_unit = "units/weapons/player/wpn_emp_sword_exe_03_t1/wpn_emp_sword_exe_03_t1_magic_01",
	slot_type = "melee",
	template = "two_handed_swords_executioner_template_1",
	trait_table_name = "melee",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.es_2h_sword_magic_01 = {
	description = "es_2h_sword_skin_03_magic_01_description",
	display_name = "es_2h_sword_skin_03_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_sword",
	inventory_icon = "icon_2h_sword_03_t1_magic_01",
	item_type = "es_2h_sword",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "es_2h_sword",
	right_hand_unit = "units/weapons/player/wpn_empire_2h_sword_03_t1/wpn_2h_sword_03_t1_magic_01",
	slot_type = "melee",
	template = "two_handed_swords_template_1",
	trait_table_name = "melee",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.es_2h_hammer_magic_01 = {
	description = "es_2h_hammer_skin_02_magic_01_description",
	display_name = "es_2h_hammer_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_2h_hammer_01_t2_magic_01",
	item_type = "es_2h_war_hammer",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "es_2h_hammer",
	right_hand_unit = "units/weapons/player/wpn_empire_2h_hammer_01_t2/wpn_2h_hammer_01_t2_magic_01",
	slot_type = "melee",
	template = "two_handed_hammers_template_1",
	trait_table_name = "melee",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.es_longbow_tutorial_magic_01 = {
	ammo_unit = "units/weapons/player/wpn_emp_arrows/wpn_es_arrow_t1",
	description = "description_plentiful_empire_soldier_es_longbow",
	display_name = "display_name_plentiful_empire_soldier_es_longbow",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_bow",
	inventory_icon = "icon_wpn_empire_bow_tutorial",
	item_type = "ww_longbow",
	left_hand_unit = "units/weapons/player/wpn_empire_bow_tutorial/wpn_empire_bow_tutorial",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "es_longbow_tutorial",
	slot_type = "ranged",
	template = "longbow_empire_tutorial_template",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"empire_soldier_tutorial",
	},
}
ItemMasterList.es_2h_hammer_tutorial_magic_01 = {
	description = "description_plentiful_empire_soldier_es_2h_war_hammer",
	display_name = "display_name_plentiful_empire_soldier_es_2h_war_hammer",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wpn_empire_2h_hammer_01_t1",
	item_type = "es_2h_war_hammer",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "es_2h_hammer_tutorial",
	right_hand_unit = "units/weapons/player/wpn_empire_2h_hammer_tutorial/wpn_empire_2h_hammer_tut_01",
	slot_type = "melee",
	template = "two_handed_hammers_template_1",
	trait_table_name = "melee",
	can_wield = {
		"empire_soldier_tutorial",
	},
}
ItemMasterList.es_sword_shield_magic_01 = {
	description = "es_1h_sword_shield_skin_04_magic_01_description",
	display_name = "es_1h_sword_shield_skin_04_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_sword_and_sheild",
	inventory_icon = "icon_emp_sword_03_t2_magic_01_emp_shield_04_magic_01",
	item_type = "es_1h_sword_shield",
	left_hand_unit = "units/weapons/player/wpn_empire_shield_04/wpn_emp_shield_04_magic_01",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "es_sword_shield",
	right_hand_unit = "units/weapons/player/wpn_emp_sword_03_t2/wpn_emp_sword_03_t2_magic_01",
	slot_type = "melee",
	template = "one_handed_sword_shield_template_1",
	trait_table_name = "melee",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.es_mace_shield_magic_01 = {
	description = "es_1h_mace_shield_skin_04_magic_01_description",
	display_name = "es_1h_mace_shield_skin_04_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_mace_and_sheild",
	inventory_icon = "icon_emp_mace_03_t2_magic_01_emp_shield_04_magic_01",
	item_type = "es_1h_mace_shield",
	left_hand_unit = "units/weapons/player/wpn_empire_shield_04/wpn_emp_shield_04_magic_01",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "es_mace_shield",
	right_hand_unit = "units/weapons/player/wpn_emp_mace_03_t2/wpn_emp_mace_03_t2_magic_01",
	slot_type = "melee",
	template = "one_handed_hammer_shield_template_1",
	trait_table_name = "melee",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.es_1h_flail_magic_01 = {
	description = "es_1h_flail_skin_04_magic_01_description",
	display_name = "es_1h_flail_skin_04_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_mace",
	inventory_icon = "icon_emp_flail_04_t1_magic_01",
	item_type = "es_flail",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "es_1h_flail",
	right_hand_unit = "units/weapons/player/wpn_emp_flail_04_t1/wpn_emp_flail_04_t1_magic_01",
	slot_type = "melee",
	template = "one_handed_flail_template_1",
	trait_table_name = "melee",
	can_wield = {
		"wh_zealot",
		"wh_captain",
		"wh_bountyhunter",
	},
}
ItemMasterList.es_halberd_magic_01 = {
	description = "es_halberd_skin_03_magic_01_description",
	display_name = "es_halberd_skin_03_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_wh_halberd_03_magic_01",
	item_type = "es_2h_halberd",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "es_halberd",
	right_hand_unit = "units/weapons/player/wpn_wh_halberd_03/wpn_wh_halberd_03_magic_01",
	slot_type = "melee",
	template = "two_handed_halberds_template_1",
	trait_table_name = "melee",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.es_longbow_magic_01 = {
	ammo_unit = "units/weapons/player/wpn_emp_arrows/wpn_es_arrow_t1",
	description = "es_longbow_skin_04_magic_01_description",
	display_name = "es_longbow_skin_04_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_bow",
	inventory_icon = "icon_emp_bow_04_magic_01",
	item_type = "ww_longbow",
	left_hand_unit = "units/weapons/player/wpn_emp_bow_04/wpn_emp_bow_04_magic_01",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "es_longbow",
	slot_type = "ranged",
	template = "longbow_empire_template",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"es_huntsman",
	},
}
ItemMasterList.es_blunderbuss_magic_01 = {
	description = "es_blunderbuss_skin_01_magic_01_description",
	display_name = "es_blunderbuss_skin_01_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_blunderbuss",
	inventory_icon = "icon_empire_blunderbuss_02_t1_magic_01",
	item_type = "es_blunderbuss",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "es_blunderbuss",
	right_hand_unit = "units/weapons/player/wpn_empire_blunderbuss_02_t1/wpn_empire_blunderbuss_02_t1_magic_01",
	slot_type = "ranged",
	template = "blunderbuss_template_1",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.es_handgun_magic_01 = {
	description = "es_handgun_skin_02_magic_01_description",
	display_name = "es_handgun_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_units/weapons/weapon_display/display_rifle",
	inventory_icon = "icon_empire_handgun_02_t2_magic_01",
	item_type = "es_handgun",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "es_handgun",
	right_hand_unit = "units/weapons/player/wpn_empire_handgun_02_t2/wpn_empire_handgun_02_t2_magic_01",
	slot_type = "ranged",
	template = "handgun_template_1",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.es_repeating_handgun_magic_01 = {
	description = "es_repeating_handgun_skin_01_magic_01_description",
	display_name = "es_repeating_handgun_skin_01_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_repeating_handgun",
	inventory_icon = "icon_emp_handgun_repeater_t1_magic_01",
	item_type = "es_repeating_handgun",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "es_repeating_handgun",
	right_hand_unit = "units/weapons/player/wpn_emp_handgun_repeater_t1/wpn_emp_handgun_repeater_t1_magic_01",
	slot_type = "ranged",
	template = "repeating_handgun_template_1",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.we_spear_magic_01 = {
	description = "we_spear_skin_02_magic_01_description",
	display_name = "we_spear_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_we_spear_02_magic_01",
	item_type = "we_2h_spear",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "we_spear",
	right_hand_unit = "units/weapons/player/wpn_we_spear_02/wpn_we_spear_02_magic_01",
	slot_type = "melee",
	template = "two_handed_spears_elf_template_1",
	trait_table_name = "melee",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.we_dual_wield_daggers_magic_01 = {
	description = "we_dual_dagger_skin_07_magic_01_description",
	display_name = "we_dual_dagger_skin_07_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_daggers",
	inventory_icon = "icon_we_dagger_03_t2_magic_01_we_dagger_03_t2_magic_01",
	item_type = "ww_dual_daggers",
	left_hand_unit = "units/weapons/player/wpn_we_dagger_03_t2/wpn_we_dagger_03_t2_magic_01",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "we_dual_wield_daggers",
	right_hand_unit = "units/weapons/player/wpn_we_dagger_03_t2/wpn_we_dagger_03_t2_magic_01",
	slot_type = "melee",
	template = "dual_wield_daggers_template_1",
	trait_table_name = "melee",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.we_dual_wield_swords_magic_01 = {
	description = "we_dual_sword_skin_06_magic_01_description",
	display_name = "we_dual_sword_skin_06_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_dual_elf_sword",
	inventory_icon = "icon_we_sword_03_t1_magic_01_e_sword_03_t1_magic_01",
	item_type = "ww_dual_swords",
	left_hand_unit = "units/weapons/player/wpn_we_sword_03_t1/wpn_we_sword_03_t1_magic_01",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "we_dual_wield_swords",
	right_hand_unit = "units/weapons/player/wpn_we_sword_03_t1/wpn_we_sword_03_t1_magic_01",
	slot_type = "melee",
	template = "dual_wield_swords_template_1",
	trait_table_name = "melee",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.we_1h_sword_magic_01 = {
	description = "we_sword_skin_06_magic_01_description",
	display_name = "we_sword_skin_06_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_elf_sword",
	inventory_icon = "icon_we_sword_03_t1_magic_01",
	item_type = "ww_1h_sword",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "we_1h_sword",
	right_hand_unit = "units/weapons/player/wpn_we_sword_03_t1/wpn_we_sword_03_t1_magic_01",
	slot_type = "melee",
	template = "we_one_hand_sword_template_1",
	trait_table_name = "melee",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.we_dual_wield_sword_dagger_magic_01 = {
	description = "we_dual_sword_dagger_skin_07_magic_01_description",
	display_name = "we_dual_sword_dagger_skin_07_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_elf_sword_and_dagger",
	inventory_icon = "icon_we_sword_03_t1_magic_01_we_dagger_03_t2_magic_01",
	item_type = "ww_sword_and_dagger",
	left_hand_unit = "units/weapons/player/wpn_we_dagger_03_t2/wpn_we_dagger_03_t2_magic_01",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "we_dual_wield_sword_dagger",
	right_hand_unit = "units/weapons/player/wpn_we_sword_03_t1/wpn_we_sword_03_t1_magic_01",
	slot_type = "melee",
	template = "dual_wield_sword_dagger_template_1",
	trait_table_name = "melee",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.we_shortbow_magic_01 = {
	ammo_unit = "units/weapons/player/wpn_we_quiver_t1/wpn_we_arrow_t1",
	description = "we_shortbow_skin_02_magic_01_description",
	display_name = "we_shortbow_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_bow",
	inventory_icon = "icon_we_bow_short_02_magic_01",
	item_type = "ww_shortbow",
	left_hand_unit = "units/weapons/player/wpn_we_bow_short_02/wpn_we_bow_short_02_magic_01",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "we_shortbow",
	slot_type = "ranged",
	template = "shortbow_template_1",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.we_shortbow_hagbane_magic_01 = {
	ammo_unit = "units/weapons/player/wpn_we_quiver_t1/wpn_we_poison_arrow_t1",
	description = "we_shortbow_hagbane_skin_02_magic_01_description",
	display_name = "we_shortbow_hagbane_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_bow",
	inventory_icon = "icon_we_bow_short_02_magic_01",
	item_type = "ww_hagbane",
	left_hand_unit = "units/weapons/player/wpn_we_bow_short_02/wpn_we_bow_short_02_magic_01",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "we_shortbow_hagbane",
	slot_type = "ranged",
	template = "shortbow_hagbane_template_1",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.we_longbow_magic_01 = {
	ammo_unit = "units/weapons/player/wpn_we_quiver_t1/wpn_we_arrow_t1",
	description = "we_longbow_skin_02_magic_01_description",
	display_name = "we_longbow_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_bow",
	inventory_icon = "icon_we_bow_01_t2_magic_01",
	item_type = "ww_longbow",
	left_hand_unit = "units/weapons/player/wpn_we_bow_01_t2/wpn_we_bow_01_t2_magic_01",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "we_longbow",
	slot_type = "ranged",
	template = "longbow_template_1",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.we_2h_axe_magic_01 = {
	description = "we_2h_axe_skin_03_magic_01_description",
	display_name = "we_2h_axe_skin_03_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_elf_axe2h",
	inventory_icon = "icon_we_2h_axe_02_t1_magic_01",
	item_type = "ww_2h_axe",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "we_2h_axe",
	right_hand_unit = "units/weapons/player/wpn_we_2h_axe_02_t1/wpn_we_2h_axe_02_t1_magic_01",
	slot_type = "melee",
	template = "two_handed_axes_template_2",
	trait_table_name = "melee",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.we_2h_sword_magic_01 = {
	description = "we_2h_sword_skin_08_magic_01_description",
	display_name = "we_2h_sword_skin_08_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_elf_axe2h",
	inventory_icon = "icon_we_2h_sword_04_t2_magic_01",
	item_type = "ww_2h_sword",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "we_2h_sword",
	right_hand_unit = "units/weapons/player/wpn_we_2h_sword_04_t2/wpn_we_2h_sword_04_t2_magic_01",
	slot_type = "melee",
	template = "two_handed_swords_wood_elf_template",
	trait_table_name = "melee",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.we_crossbow_repeater_magic_01 = {
	ammo_unit = "units/weapons/player/wpn_crossbow_quiver/wpn_crossbow_bolt_pile",
	ammo_unit_3p = "units/weapons/player/wpn_crossbow_quiver/wpn_crossbow_bolt_3p",
	description = "we_crossbow_skin_01_magic_01_description",
	display_name = "we_crossbow_skin_01_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_repeating_crossbow",
	inventory_icon = "icon_we_repeater_crossbow_t1_magic_01",
	item_type = "wh_repeating_crossbow",
	left_hand_unit = "units/weapons/player/wpn_we_repeater_crossbow_t1/wpn_we_repeater_crossbow_t1_magic_01",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "we_crossbow_repeater",
	slot_type = "ranged",
	template = "repeating_crossbow_elf_template",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"we_shade",
	},
}
ItemMasterList.bw_1h_mace_magic_01 = {
	description = "bw_1h_mace_skin_02_magic_01_description",
	display_name = "bw_1h_mace_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_mace",
	inventory_icon = "icon_brw_mace_02_magic_01",
	item_type = "bw_morningstar",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "bw_1h_mace",
	right_hand_unit = "units/weapons/player/wpn_brw_mace_02/wpn_brw_mace_02_magic_01",
	slot_type = "melee",
	template = "one_handed_hammer_wizard_template_1",
	trait_table_name = "melee",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.bw_sword_magic_01 = {
	description = "bw_1h_sword_skin_06_magic_01_description",
	display_name = "bw_1h_sword_skin_06_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_sword",
	inventory_icon = "icon_brw_sword_03_t2_magic_01",
	item_type = "bw_1h_sword",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "bw_sword",
	right_hand_unit = "units/weapons/player/wpn_brw_sword_03_t2/wpn_brw_sword_03_t2_magic_01",
	slot_type = "melee",
	template = "one_handed_swords_template_1",
	trait_table_name = "melee",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.bw_flame_sword_magic_01 = {
	description = "bw_1h_flaming_sword_skin_06_magic_01_description",
	display_name = "bw_1h_flaming_sword_skin_06_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_flaming_sword",
	inventory_icon = "icon_brw_sword_03_t2_magic_01",
	item_type = "bw_flame_sword",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "bw_flame_sword",
	right_hand_unit = "units/weapons/player/wpn_brw_sword_03_t2/wpn_brw_flaming_sword_03_t2_magic_01",
	slot_type = "melee",
	template = "flaming_sword_template_1",
	trait_table_name = "melee",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.bw_dagger_magic_01 = {
	description = "bw_dagger_skin_02_magic_01_description",
	display_name = "bw_dagger_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_sword",
	inventory_icon = "icon_brw_dagger_02_magic_01",
	item_type = "bw_1h_dagger",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "bw_dagger",
	right_hand_unit = "units/weapons/player/wpn_brw_dagger_02/wpn_brw_dagger_02_magic_01",
	slot_type = "melee",
	template = "one_handed_daggers_template_1",
	trait_table_name = "melee",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.bw_skullstaff_fireball_magic_01 = {
	description = "bw_fireball_staff_skin_02_magic_01_description",
	display_name = "bw_fireball_staff_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_staff_2",
	inventory_icon = "icon_brw_staff_05_magic_01",
	item_type = "bw_staff_firball",
	left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "bw_skullstaff_fireball",
	right_hand_unit = "units/weapons/player/wpn_brw_staff_05/wpn_brw_staff_05_magic_01",
	slot_type = "ranged",
	template = "staff_fireball_fireball_template_1",
	trait_table_name = "ranged_heat",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.bw_skullstaff_beam_magic_01 = {
	description = "bw_beam_staff_skin_02_magic_01_description",
	display_name = "bw_beam_staff_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_staff_4",
	inventory_icon = "icon_brw_beam_staff_02_magic_01",
	item_type = "bw_staff_beam",
	left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "bw_skullstaff_beam",
	right_hand_unit = "units/weapons/player/wpn_brw_beam_staff_02/wpn_brw_beam_staff_02_magic_01",
	slot_type = "ranged",
	template = "staff_blast_beam_template_1",
	trait_table_name = "ranged_heat",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.bw_skullstaff_geiser_magic_01 = {
	description = "bw_conflagration_staff_skin_01_magic_01_description",
	display_name = "bw_conflagration_staff_skin_01_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_staff_3",
	inventory_icon = "icon_brw_staff_03_magic_01",
	item_type = "bw_staff_geiser",
	left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "bw_skullstaff_geiser",
	right_hand_unit = "units/weapons/player/wpn_brw_staff_03/wpn_brw_staff_03_magic_01",
	slot_type = "ranged",
	template = "staff_fireball_geiser_template_1",
	trait_table_name = "ranged_heat",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.bw_skullstaff_spear_magic_01 = {
	description = "bw_spear_staff_skin_05_magic_01_description",
	display_name = "bw_spear_staff_skin_05_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_staff_5",
	inventory_icon = "icon_brw_spear_staff_05_magic_01",
	item_type = "bw_staff_spear",
	left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "bw_skullstaff_spear",
	right_hand_unit = "units/weapons/player/wpn_brw_spear_staff_05/wpn_brw_spear_staff_05_magic_01",
	slot_type = "ranged",
	template = "staff_spark_spear_template_1",
	trait_table_name = "ranged_heat",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.bw_skullstaff_flamethrower_magic_01 = {
	description = "bw_flamethrower_staff_skin_04_magic_01_description",
	display_name = "bw_flamethrower_staff_skin_04_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_staff_5",
	inventory_icon = "icon_brw_flame_staff_04_magic_01",
	item_type = "bw_staff_flamethrower",
	left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "bw_skullstaff_flamethrower",
	right_hand_unit = "units/weapons/player/wpn_brw_flame_staff_04/wpn_brw_flame_staff_04_magic_01",
	slot_type = "ranged",
	template = "staff_flamethrower_template",
	trait_table_name = "ranged_heat",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.dr_1h_axe_magic_01 = {
	description = "dw_1h_axe_skin_04_magic_01_description",
	display_name = "dw_1h_axe_skin_04_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_axe1h",
	inventory_icon = "icon_dw_axe_02_t2_magic_01",
	item_type = "dr_1h_axes",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "dr_1h_axe",
	right_hand_unit = "units/weapons/player/wpn_dw_axe_02_t2/wpn_dw_axe_02_t2_magic_01",
	slot_type = "melee",
	template = "one_hand_axe_template_2",
	trait_table_name = "melee",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.dr_dual_wield_axes_magic_01 = {
	description = "dw_dual_axe_skin_04_magic_01_description",
	display_name = "dw_dual_axe_skin_04_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_axe1h",
	inventory_icon = "icon_dw_axe_02_t2_magic_01_dw_axe_02_t2_magic_01",
	item_type = "dr_dual_axes",
	left_hand_unit = "units/weapons/player/wpn_dw_axe_02_t2/wpn_dw_axe_02_t2_magic_01",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "dr_dual_wield_axes",
	right_hand_unit = "units/weapons/player/wpn_dw_axe_02_t2/wpn_dw_axe_02_t2_magic_01",
	slot_type = "melee",
	template = "dual_wield_axes_template_1",
	trait_table_name = "melee",
	can_wield = {
		"dr_slayer",
	},
}
ItemMasterList.dr_2h_axe_magic_01 = {
	description = "dw_2h_axe_skin_02_magic_01_description",
	display_name = "dw_2h_axe_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_axe2h",
	inventory_icon = "icon_dw_2h_axe_01_t2_magic_01",
	item_type = "dr_2h_axes",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "dr_2h_axe",
	right_hand_unit = "units/weapons/player/wpn_dw_2h_axe_01_t2/wpn_dw_2h_axe_01_t2_magic_01",
	slot_type = "melee",
	template = "two_handed_axes_template_1",
	trait_table_name = "melee",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.dr_2h_hammer_magic_01 = {
	description = "dw_2h_hammer_skin_03_magic_01_description",
	display_name = "dw_2h_hammer_skin_03_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer2h",
	inventory_icon = "icon_dw_2h_hammer_02_t1_magic_01",
	item_type = "dr_2h_hammer",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "dr_2h_hammer",
	right_hand_unit = "units/weapons/player/wpn_dw_2h_hammer_02_t1/wpn_dw_2h_hammer_02_t1_magic_01",
	slot_type = "melee",
	template = "two_handed_hammers_template_1",
	trait_table_name = "melee",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.dr_1h_hammer_magic_01 = {
	description = "dw_1h_hammer_skin_03_magic_01_description",
	display_name = "dw_1h_hammer_skin_03_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer1h",
	inventory_icon = "icon_dw_hammer_02_t1_magic_01",
	item_type = "dr_1h_hammer",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "dr_1h_hammer",
	right_hand_unit = "units/weapons/player/wpn_dw_hammer_02_t1/wpn_dw_hammer_02_t1_magic_01",
	slot_type = "melee",
	template = "one_handed_hammer_template_2",
	trait_table_name = "melee",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.dr_shield_axe_magic_01 = {
	description = "dw_1h_axe_shield_skin_04_magic_01_description",
	display_name = "dw_1h_axe_shield_skin_04_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_axe_and_sheild",
	inventory_icon = "icon_dw_axe_02_t2_magic_01_dw_shield_04_magic_01",
	item_type = "dr_1h_axe_shield",
	left_hand_unit = "units/weapons/player/wpn_dw_shield_04_t1/wpn_dw_shield_04_magic_01",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "dr_shield_axe",
	right_hand_unit = "units/weapons/player/wpn_dw_axe_02_t2/wpn_dw_axe_02_t2_magic_01",
	slot_type = "melee",
	template = "one_hand_axe_shield_template_1",
	trait_table_name = "melee",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
}
ItemMasterList.dr_shield_hammer_magic_01 = {
	description = "dw_1h_hammer_shield_skin_04_magic_01_description",
	display_name = "dw_1h_hammer_shield_skin_04_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_hammer_and_sheild",
	inventory_icon = "icon_dw_hammer_02_t1_magic_01_dw_shield_04_magic_01",
	item_type = "dr_1h_hammer_shield",
	left_hand_unit = "units/weapons/player/wpn_dw_shield_04_t1/wpn_dw_shield_04_magic_01",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "dr_shield_hammer",
	right_hand_unit = "units/weapons/player/wpn_dw_hammer_02_t1/wpn_dw_hammer_02_t1_magic_01",
	slot_type = "melee",
	template = "one_handed_hammer_shield_template_2",
	trait_table_name = "melee",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
}
ItemMasterList.dr_crossbow_magic_01 = {
	ammo_unit = "units/weapons/player/wpn_crossbow_quiver/wpn_crossbow_bolt",
	description = "dw_crossbow_skin_03_magic_01_description",
	display_name = "dw_crossbow_skin_03_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_crossbow",
	inventory_icon = "icon_dw_xbow_02_t1_magic_01",
	item_type = "dr_crossbow",
	left_hand_unit = "units/weapons/player/wpn_dw_xbow_02_t1/wpn_dw_xbow_02_t1_magic_01",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "dr_crossbow",
	slot_type = "ranged",
	template = "crossbow_template_1",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
}
ItemMasterList.dr_rakegun_magic_01 = {
	description = "dw_grudge_raker_skin_03_magic_01_description",
	display_name = "dw_grudge_raker_skin_03_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_grudgeraker",
	inventory_icon = "icon_dw_rakegun_t3_magic_01",
	item_type = "dr_grudgeraker",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "dr_rakegun",
	right_hand_unit = "units/weapons/player/wpn_dw_rakegun_t3/wpn_dw_rakegun_t3_magic_01",
	slot_type = "ranged",
	template = "grudge_raker_template_1",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
}
ItemMasterList.dr_handgun_magic_01 = {
	description = "dw_handgun_skin_03_magic_01_description",
	display_name = "dw_handgun_skin_03_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_units/weapons/weapon_display/display_rifle",
	inventory_icon = "icon_dw_handgun_02_t1_magic_01",
	item_type = "dr_handgun",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "dr_handgun",
	right_hand_unit = "units/weapons/player/wpn_dw_handgun_02_t1/wpn_dw_handgun_02_t1_magic_01",
	slot_type = "ranged",
	template = "handgun_template_2",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
}
ItemMasterList.dr_drakegun_magic_01 = {
	description = "dw_drakegun_skin_02_magic_01_description",
	display_name = "dw_drakegun_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_units/weapons/weapon_display/display_rifle",
	inventory_icon = "icon_dw_iron_drake_02_magic_01",
	item_type = "dr_drakegun",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "dr_drakegun",
	right_hand_unit = "units/weapons/player/wpn_dw_iron_drake_02/wpn_dw_iron_drake_02_magic_01",
	slot_type = "ranged",
	template = "drakegun_template_1",
	trait_table_name = "ranged_heat",
	can_wield = {
		"dr_ironbreaker",
	},
}
ItemMasterList.dr_drake_pistol_magic_01 = {
	description = "dw_drake_pistol_skin_01_magic_01_description",
	display_name = "dw_drake_pistol_skin_01_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_drakefire_pistols",
	inventory_icon = "icon_dw_drake_pistol_01_t1_magic_01_dw_drake_pistol_01_t1_magic_01",
	item_type = "dr_drakefire_pistols",
	left_hand_unit = "units/weapons/player/wpn_dw_drake_pistol_01_t1/wpn_dw_drake_pistol_01_t1_magic_01",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "dr_drake_pistol",
	right_hand_unit = "units/weapons/player/wpn_dw_drake_pistol_01_t1/wpn_dw_drake_pistol_01_t1_magic_01",
	slot_type = "ranged",
	template = "brace_of_drakefirepistols_template_1",
	trait_table_name = "ranged_heat",
	can_wield = {
		"dr_ironbreaker",
	},
}
ItemMasterList.dr_2h_pick_magic_01 = {
	description = "dw_2h_pick_skin_02_magic_01_description",
	display_name = "dw_2h_pick_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_pick",
	inventory_icon = "icon_dw_pick_01_t2_magic_01",
	item_type = "dr_2h_picks",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "dr_2h_pick",
	right_hand_unit = "units/weapons/player/wpn_dw_pick_01_t2/wpn_dw_pick_01_t2_magic_01",
	slot_type = "melee",
	template = "two_handed_picks_template_1",
	trait_table_name = "melee",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.wh_1h_axe_magic_01 = {
	description = "wh_1h_axe_skin_06_magic_01_description",
	display_name = "wh_1h_axe_skin_06_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_axe1h",
	inventory_icon = "icon_axe_hatchet_t2_magic_01",
	item_type = "wh_1h_axes",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "wh_1h_axe",
	right_hand_unit = "units/weapons/player/wpn_axe_hatchet_t2/wpn_axe_hatchet_t2_magic_01",
	slot_type = "melee",
	template = "one_hand_axe_template_1",
	trait_table_name = "melee",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.wh_2h_sword_magic_01 = {
	description = "wh_2h_sword_skin_04_magic_01_description",
	display_name = "wh_2h_sword_skin_04_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_sword",
	inventory_icon = "icon_2h_sword_04_t2_magic_01",
	item_type = "wh_2h_sword",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "wh_2h_sword",
	right_hand_unit = "units/weapons/player/wpn_empire_2h_sword_04_t2/wpn_2h_sword_04_t2_magic_01",
	slot_type = "melee",
	template = "two_handed_swords_template_1",
	trait_table_name = "melee",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.wh_fencing_sword_magic_01 = {
	description = "wh_fencing_sword_skin_07_magic_01_description",
	display_name = "wh_fencing_sword_skin_07_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_fencing_sword",
	inventory_icon = "icon_fencingsword_04_t2_magic_01_emp_pistol_03_t2_magic_01",
	item_type = "wh_fencing_sword",
	left_hand_unit = "units/weapons/player/wpn_emp_pistol_03_t2/wpn_emp_pistol_03_t2_magic_01",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "wh_fencing_sword",
	right_hand_unit = "units/weapons/player/wpn_fencingsword_04_t2/wpn_fencingsword_04_t2_magic_01",
	slot_type = "melee",
	template = "fencing_sword_template_1",
	trait_table_name = "melee",
	can_wield = {
		"wh_bountyhunter",
		"wh_captain",
		"wh_zealot",
	},
}
ItemMasterList.wh_brace_of_pistols_magic_01 = {
	description = "wh_brace_of_pistols_skin_05_magic_01_description",
	display_name = "wh_brace_of_pistols_skin_05_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_brace_of_pistol",
	inventory_icon = "icon_emp_pistol_03_t2_magic_01_emp_pistol_03_t2_magic_01",
	item_type = "wh_brace_of_pisols",
	left_hand_unit = "units/weapons/player/wpn_emp_pistol_03_t2/wpn_emp_pistol_03_t2_magic_01",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "wh_brace_of_pistols",
	right_hand_unit = "units/weapons/player/wpn_emp_pistol_03_t2/wpn_emp_pistol_03_t2_magic_01",
	slot_type = "ranged",
	template = "brace_of_pistols_template_1",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.wh_repeating_pistols_magic_01 = {
	description = "wh_repeating_pistol_skin_05_magic_01_description",
	display_name = "wh_repeating_pistol_skin_05_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_repeating_pistol",
	inventory_icon = "icon_empire_pistol_repeater_02_t2_magic_01",
	item_type = "wh_repeating_pistol",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "wh_repeating_pistols",
	right_hand_unit = "units/weapons/player/wpn_empire_pistol_repeater_02/wpn_empire_pistol_repeater_02_t2_magic_01",
	slot_type = "ranged",
	template = "repeating_pistol_template_1",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.wh_crossbow_magic_01 = {
	ammo_unit = "units/weapons/player/wpn_crossbow_quiver/wpn_crossbow_bolt",
	description = "wh_crossbow_skin_06_magic_01_description",
	display_name = "wh_crossbow_skin_06_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_crossbow",
	inventory_icon = "icon_empire_crossbow_tier2_magic_01",
	item_type = "wh_crossbow",
	left_hand_unit = "units/weapons/player/wpn_empire_crossbow_t2/wpn_empire_crossbow_tier2_magic_01",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "wh_crossbow",
	slot_type = "ranged",
	template = "crossbow_template_1",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.wh_crossbow_repeater_magic_01 = {
	description = "wh_repeating_crossbow_skin_02_magic_01_description",
	display_name = "wh_repeating_crossbow_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_repeating_crossbow",
	inventory_icon = "icon_wh_repeater_crossbow_t2_magic_01",
	item_type = "wh_repeating_crossbow",
	left_hand_unit = "units/weapons/player/wpn_wh_repeater_crossbow_t2/wpn_wh_repeater_crossbow_t2_magic_01",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "wh_crossbow_repeater",
	slot_type = "ranged",
	template = "repeating_crossbow_template_1",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.wh_1h_falchion_magic_01 = {
	description = "wh_1h_falchion_skin_04_magic_01_description",
	display_name = "wh_1h_falchion_skin_04_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_falken",
	inventory_icon = "icon_emp_sword_05_t2_magic_01",
	item_type = "wh_1h_falchions",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "wh_1h_falchion",
	right_hand_unit = "units/weapons/player/wpn_emp_sword_05_t2/wpn_emp_sword_05_t2_magic_01",
	slot_type = "melee",
	template = "one_hand_falchion_template_1",
	trait_table_name = "melee",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.we_1h_axe_magic_01 = {
	description = "we_1h_axe_skin_02_magic_01_description",
	display_name = "we_1h_axe_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_falken",
	inventory_icon = "icon_we_axe_03_t2_magic_01",
	item_type = "we_1h_axe",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "we_1h_axe",
	right_hand_unit = "units/weapons/player/wpn_we_axe_03_t2/wpn_we_axe_03_t2_magic_01",
	slot_type = "melee",
	template = "we_one_hand_axe_template",
	trait_table_name = "melee",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.bw_1h_crowbill_magic_01 = {
	description = "bw_1h_crowbill_skin_01_magic_01_description",
	display_name = "bw_1h_crowbill_skin_01_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_falken",
	inventory_icon = "icon_brw_crowbill_01_magic_01",
	item_type = "bw_1h_crowbill",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "bw_1h_crowbill",
	right_hand_unit = "units/weapons/player/wpn_brw_crowbill_01/wpn_brw_crowbill_01_magic_01",
	slot_type = "melee",
	template = "one_handed_crowbill",
	trait_table_name = "melee",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.wh_dual_wield_axe_falchion_magic_01 = {
	description = "wh_dual_wield_axe_falchion_skin_01_magic_01_description",
	display_name = "wh_dual_wield_axe_falchion_skin_01_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_falken",
	inventory_icon = "icon_emp_sword_05_t2_magic_01_axe_hatchet_t2_magic_01",
	item_type = "wh_dual_wield_axe_falchion",
	left_hand_unit = "units/weapons/player/wpn_emp_sword_05_t2/wpn_emp_sword_05_t2_magic_01",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "wh_dual_wield_axe_falchion",
	right_hand_unit = "units/weapons/player/wpn_axe_hatchet_t2/wpn_axe_hatchet_t2_magic_01",
	slot_type = "melee",
	template = "dual_wield_axe_falchion_template",
	trait_table_name = "melee",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.dr_dual_wield_hammers_magic_01 = {
	description = "dr_dual_wield_hammers_skin_01_magic_01_description",
	display_name = "dr_dual_wield_hammers_skin_01_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_falken",
	inventory_icon = "icon_dw_hammer_02_t1_magic_01_dw_hammer_02_t1_magic_01",
	item_type = "dr_dual_wield_hammers",
	left_hand_unit = "units/weapons/player/wpn_dw_hammer_02_t1/wpn_dw_hammer_02_t1_magic_01",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "dr_dual_wield_hammers",
	right_hand_unit = "units/weapons/player/wpn_dw_hammer_02_t1/wpn_dw_hammer_02_t1_magic_01",
	slot_type = "melee",
	template = "dual_wield_hammers_template",
	trait_table_name = "melee",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.es_dual_wield_hammer_sword_magic_01 = {
	description = "es_dual_wield_hammer_sword_skin_02_magic_01_description",
	display_name = "es_dual_wield_hammer_sword_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_falken",
	inventory_icon = "icon_emp_sword_06_t2_magic_01_emp_mace_04_t3_magic_01",
	item_type = "es_dual_wield_hammer_sword",
	left_hand_unit = "units/weapons/player/wpn_emp_sword_06_t2/wpn_emp_sword_06_t2_magic_01",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "es_dual_wield_hammer_sword",
	right_hand_unit = "units/weapons/player/wpn_emp_mace_04_t3/wpn_emp_mace_04_t3_magic_01",
	slot_type = "melee",
	template = "dual_wield_hammer_sword_template",
	trait_table_name = "melee",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.bw_1h_flail_flaming_magic_01 = {
	description = "bw_1h_flail_flaming_skin_02_magic_01_description",
	display_name = "bw_1h_flail_flaming_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_falken",
	inventory_icon = "icon_brw_flaming_flail_02_magic_01",
	item_type = "bw_1h_flail_flaming",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "bw_1h_flail_flaming",
	right_hand_unit = "units/weapons/player/wpn_brw_flaming_flail_02/wpn_brw_flaming_flail_02_magic_01",
	slot_type = "melee",
	template = "one_handed_flails_flaming_template",
	trait_table_name = "melee",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.dr_1h_throwing_axes_magic_01 = {
	ammo_unit = "units/weapons/player/wpn_dw_thrown_axe_01_t2/wpn_dw_thrown_axe_01_t2_magic_01",
	description = "dr_1h_throwing_axes_skin_02_magic_01_description",
	display_name = "dr_1h_throwing_axes_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_falken",
	inventory_icon = "icon_dw_thrown_axe_01_t2_magic_01",
	is_ammo_weapon = true,
	item_type = "dr_1h_throwing_axes",
	link_pickup_template_name = "link_ammo_throwing_axe_01_t2_magic_01",
	pickup_template_name = "ammo_throwing_axe_01_t2_magic_01",
	projectile_units_template = "throwing_axe_01_t2_magic_01",
	property_table_name = "ranged",
	rarity = "magic",
	required_unlock_item = "dr_1h_throwing_axes",
	right_hand_unit = "units/weapons/player/wpn_invisible_weapon",
	slot_type = "ranged",
	template = "one_handed_throwing_axes_template",
	trait_table_name = "ranged_ammo",
	can_wield = {
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.es_2h_heavy_spear_magic_01 = {
	description = "es_2h_heavy_spear_skin_02_magic_01_description",
	display_name = "es_2h_heavy_spear_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_falken",
	inventory_icon = "icon_emp_boar_spear_02_magic_01",
	item_type = "es_2h_heavy_spear",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "es_2h_heavy_spear",
	right_hand_unit = "units/weapons/player/wpn_emp_boar_spear_02/wpn_emp_boar_spear_02_magic_01",
	slot_type = "melee",
	template = "two_handed_heavy_spears_template",
	trait_table_name = "melee",
	can_wield = {
		"es_huntsman",
		"es_mercenary",
	},
}
ItemMasterList.we_1h_spears_shield_magic_01 = {
	description = "we_1h_spears_shield_skin_02_magic_01_description",
	display_name = "we_1h_spears_shield_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_falken",
	inventory_icon = "icon_we_spear_02_magic_01_we_shield_02_magic_01",
	item_type = "we_1h_spears_shield",
	left_hand_unit = "units/weapons/player/wpn_we_shield_02/wpn_we_shield_02_magic_01",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "we_1h_spears_shield",
	right_hand_unit = "units/weapons/player/wpn_we_spear_02/wpn_we_spear_02_magic_01",
	slot_type = "melee",
	template = "one_handed_spears_shield_template",
	trait_table_name = "melee",
	can_wield = {
		"we_maidenguard",
	},
}
ItemMasterList.wh_2h_billhook_magic_01 = {
	description = "wh_2h_billhook_skin_02_magic_01_description",
	display_name = "wh_2h_billhook_skin_02_magic_01_name",
	has_power_level = true,
	hud_icon = "weapon_generic_icon_falken",
	inventory_icon = "icon_wh_billhook_02_magic_01",
	item_type = "wh_2h_billhook",
	property_table_name = "melee",
	rarity = "magic",
	required_unlock_item = "wh_2h_billhook",
	right_hand_unit = "units/weapons/player/wpn_wh_billhook_02/wpn_wh_billhook_02_magic_01",
	slot_type = "melee",
	template = "two_handed_billhooks_template",
	trait_table_name = "melee",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.frame_scorpion_complete_all_helmgart_levels_cataclysm = {
	description = "frame_scorpion_complete_all_helmgart_levels_cataclysm_description",
	display_name = "frame_scorpion_complete_all_helmgart_levels_cataclysm_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_helmgart_cataclysm",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_complete_all_helmgart_levels_cataclysm",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_complete_all_helmgart_level_achievements_cataclysm = {
	description = "frame_scorpion_complete_all_helmgart_level_achievements_cataclysm_description",
	display_name = "frame_scorpion_complete_all_helmgart_level_achievements_cataclysm_name",
	display_unit = "units/weapons/weapon_display/display_portrait_frame",
	event_item = true,
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_scorpion_complete_all_helmgart_level_achievements_cataclysm",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	store_icon_override_key = "frame_scorpion_achieve_cata",
	temporary_template = "frame_scorpion_complete_all_helmgart_level_achievements_cataclysm",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_complete_bogenhafen_cataclysm = {
	description = "frame_scorpion_complete_bogenhafen_cataclysm_description",
	display_name = "frame_scorpion_complete_bogenhafen_cataclysm_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_bogenhafen_5",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_complete_bogenhafen_cataclysm",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_complete_plaza_cataclysm = {
	description = "frame_scorpion_complete_plaza_cataclysm_description",
	display_name = "frame_scorpion_complete_plaza_cataclysm_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_ubersreik_05",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_complete_plaza_cataclysm",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_complete_crater_recruit = {
	description = "frame_scorpion_complete_crater_recruit_description",
	display_name = "frame_scorpion_complete_crater_recruit_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_crater_01",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_complete_crater_recruit",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_complete_crater_veteran = {
	description = "frame_scorpion_complete_crater_veteran_description",
	display_name = "frame_scorpion_complete_crater_veteran_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_crater_02",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_complete_crater_veteran",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_complete_crater_champion = {
	description = "frame_scorpion_complete_crater_champion_description",
	display_name = "frame_scorpion_complete_crater_champion_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_crater_03",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_complete_crater_champion",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_complete_crater_legend = {
	description = "frame_scorpion_complete_crater_legend_description",
	display_name = "frame_scorpion_complete_crater_legend_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_crater_04",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_complete_crater_legend",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_complete_crater_cataclysm = {
	description = "frame_scorpion_complete_crater_cataclysm_description",
	display_name = "frame_scorpion_complete_crater_cataclysm_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_crater_05",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_complete_crater_cataclysm",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_season_1_beasts = {
	description = "frame_scorpion_season_1_beasts_description",
	display_name = "frame_scorpion_season_1_beasts_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_season_01_ghur",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_season_1_beasts",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_season_1_death = {
	description = "frame_scorpion_season_1_death_description",
	display_name = "frame_scorpion_season_1_death_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_season_01_shyish",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_season_1_death",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_season_1_fire = {
	description = "frame_scorpion_season_1_fire_description",
	display_name = "frame_scorpion_season_1_fire_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_season_01_aqshy",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_season_1_fire",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_season_1_heavens = {
	description = "frame_scorpion_season_1_heavens_description",
	display_name = "frame_scorpion_season_1_heavens_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_season_01_azyr",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_season_1_heavens",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_season_1_life = {
	description = "frame_scorpion_season_1_life_description",
	display_name = "frame_scorpion_season_1_life_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_season_01_ghyran",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_season_1_life",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_season_1_light = {
	description = "frame_scorpion_season_1_light_description",
	display_name = "frame_scorpion_season_1_light_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_season_01_hysh",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_season_1_light",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_season_1_metal = {
	description = "frame_scorpion_season_1_metal_description",
	display_name = "frame_scorpion_season_1_metal_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_season_01_chamon",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_season_1_metal",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_season_1_shadow = {
	description = "frame_scorpion_season_1_shadow_description",
	display_name = "frame_scorpion_season_1_shadow_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_season_01_ulgu",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_season_1_shadow",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_season_1_cataclysm_1 = {
	description = "frame_scorpion_season_1_cataclysm_1_description",
	display_name = "frame_scorpion_season_1_cataclysm_1_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_season_01_cataclysm_1",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_season_1_cataclysm_1",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_season_1_cataclysm_2 = {
	description = "frame_scorpion_season_1_cataclysm_2_description",
	display_name = "frame_scorpion_season_1_cataclysm_2_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_season_01_cataclysm_2",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_season_1_cataclysm_2",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_scorpion_season_1_cataclysm_3 = {
	description = "frame_scorpion_season_1_cataclysm_3_description",
	display_name = "frame_scorpion_season_1_cataclysm_3_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_season_01_cataclysm_3",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_scorpion_season_1_cataclysm_3",
	can_wield = CanWieldAllItemTemplates,
}
