-- chunkname: @scripts/settings/equipment/item_master_list_cosmetics_2022_q1.lua

ItemMasterList.unchained_hat_1003 = {
	description = "description_unchained_hat_1003",
	display_name = "display_name_unchained_hat_1003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_unchained_hat_1003",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 146,
	store_optional_skin = "skin_bw_unchained_1001",
	template = "bw_hat_no_hair_lock_neck",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_13",
	can_wield = {
		"bw_unchained",
	},
}
ItemMasterList.ranger_hat_1005 = {
	description = "description_ranger_hat_1005",
	display_name = "display_name_ranger_hat_1005",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_ranger_hat_1005",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 148,
	store_optional_skin = "skin_dr_ranger_1001",
	template = "dr_helmets_no_ear",
	unit = "units/beings/player/dwarf_ranger_upgraded/headpiece/dr_u_hat_13",
	can_wield = {
		"dr_ranger",
	},
}
ItemMasterList.knight_hat_1003 = {
	description = "description_knight_hat_1003",
	display_name = "display_name_knight_hat_1003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_knight_hat_1003",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 144,
	store_optional_skin = "skin_es_knight_1001",
	template = "es_hats_no_ear_lock_neck",
	unit = "units/beings/player/empire_soldier_knight/headpiece/es_k_hat_14",
	can_wield = {
		"es_knight",
	},
}
ItemMasterList.witchhunter_hat_1003 = {
	description = "description_witchhunter_hat_1003",
	display_name = "display_name_witchhunter_hat_1003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_witchhunter_hat_1003",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 142,
	store_optional_skin = "skin_wh_captain_1001",
	template = "wh_hats",
	unit = "units/beings/player/witch_hunter_captain/headpiece/wh_c_hat_12",
	can_wield = {
		"wh_captain",
	},
}
ItemMasterList.waywatcher_hat_1004 = {
	description = "description_waywatcher_hat_1004",
	display_name = "display_name_waywatcher_hat_1004",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_waywatcher_hat_1004",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 140,
	store_optional_skin = "skin_ww_waywatcher_1001",
	template = "ww_helmet_jaw",
	unit = "units/beings/player/way_watcher_upgraded/headpiece/ww_u_hat_14",
	can_wield = {
		"we_waywatcher",
	},
}
ItemMasterList.skin_bw_unchained_1001 = {
	description = "description_skin_bw_unchained_1001",
	display_name = "display_name_skin_bw_unchained_1001",
	hud_icon = "unit_frame_portrait_bright_wizard",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_bw_unchained_1001",
	item_preview_environment = "unchained_skins_01",
	item_type = "skin",
	name = "skin_bw_unchained_1001",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 147,
	store_optional_hat = "unchained_hat_1003",
	temporary_template = "skin_bw_unchained_1001",
	can_wield = {
		"bw_unchained",
	},
}
ItemMasterList.skin_dr_ranger_1001 = {
	description = "description_skin_dr_ranger_1001",
	display_name = "display_name_skin_dr_ranger_1001",
	hud_icon = "career_dwarf_ranger",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_dr_ranger_1001",
	item_type = "skin",
	name = "skin_dr_ranger_1001",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 149,
	store_optional_hat = "ranger_hat_1005",
	temporary_template = "skin_dr_ranger_1001",
	can_wield = {
		"dr_ranger",
	},
}
ItemMasterList.skin_es_knight_1001 = {
	description = "description_skin_es_knight_1001",
	display_name = "display_name_skin_es_knight_1001",
	hud_icon = "unit_frame_portrait_empire_soldier",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_knight_1001",
	item_type = "skin",
	name = "skin_es_knight_1001",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 145,
	store_optional_hat = "knight_hat_1003",
	temporary_template = "skin_es_knight_1001",
	can_wield = {
		"es_knight",
	},
}
ItemMasterList.skin_ww_waywatcher_1001 = {
	description = "description_skin_ww_waywatcher_1001",
	display_name = "display_name_skin_ww_waywatcher_1001",
	hud_icon = "unit_frame_portrait_way_watcher",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ww_waywatcher_1001",
	item_preview_environment = "waystalker_skins_01",
	item_type = "skin",
	name = "skin_ww_waywatcher_1001",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 141,
	store_optional_hat = "waywatcher_hat_1004",
	temporary_template = "skin_ww_waywatcher_1001",
	can_wield = {
		"we_waywatcher",
	},
}
ItemMasterList.skin_wh_captain_1001 = {
	description = "description_skin_wh_captain_1001",
	display_name = "display_name_skin_wh_captain_1001",
	hud_icon = "unit_frame_portrait_witch_hunter",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_wh_captain_1001",
	item_type = "skin",
	name = "skin_wh_captain_1001",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 143,
	store_optional_hat = "witchhunter_hat_1003",
	temporary_template = "skin_wh_captain_1001",
	can_wield = {
		"wh_captain",
	},
}
ItemMasterList.q1_ranger_bundle = {
	description = "description_q1_ranger_bundle",
	display_name = "display_name_q1_ranger_bundle",
	hud_icon = "",
	information_text = "description_q1_ranger_bundle",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 1700,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 817,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_q1_ranger_bundle",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_q1_ranger_bundle",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_q1_ranger_bundle",
	subtitle = "dr_ranger",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.q1_waywatcher_bundle = {
	description = "description_q1_waywatcher_bundle",
	display_name = "display_name_q1_waywatcher_bundle",
	hud_icon = "",
	information_text = "description_q1_waywatcher_bundle",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 1800,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 813,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_q1_waywatcher_bundle",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_q1_waywatcher_bundle",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_q1_waywatcher_bundle",
	subtitle = "we_waywatcher",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.q1_footknight_bundle = {
	description = "description_q1_footknight_bundle",
	display_name = "display_name_q1_footknight_bundle",
	hud_icon = "",
	information_text = "description_q1_footknight_bundle",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 1900,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 815,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_q1_footknight_bundle",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_q1_footknight_bundle",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_q1_footknight_bundle",
	subtitle = "es_knight",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.q1_unchained_bundle = {
	description = "description_q1_unchained_bundle",
	display_name = "display_name_q1_unchained_bundle",
	hud_icon = "",
	information_text = "description_q1_unchained_bundle",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 2000,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 816,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_q1_unchained_bundle",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_q1_unchained_bundle",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_q1_unchained_bundle",
	subtitle = "bw_unchained",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.q1_wh_captain_bundle = {
	description = "description_q1_wh_captain_bundle",
	display_name = "display_name_q1_wh_captain_bundle",
	hud_icon = "",
	information_text = "description_q1_wh_captain_bundle",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 2100,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 814,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_q1_wh_captain_bundle",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_q1_wh_captain_bundle",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_q1_wh_captain_bundle",
	subtitle = "wh_captain",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.q1_collection_bundle = {
	description = "description_q1_collection_bundle",
	display_name = "display_name_q1_collection_bundle",
	hud_icon = "",
	information_text = "q1_collection_bundle",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 2200,
	product_layout = "q1_collection_bundle",
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 823,
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_q1_collection_bundle",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_q1_collection_bundle",
	subtitle = "five_career_bundle_0001_subtitle",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
