-- chunkname: @scripts/settings/equipment/item_master_list_eight_ball.lua

ItemMasterList.zealot_hat_1003 = {
	description = "description_zealot_hat_1003",
	display_name = "display_name_zealot_hat_1003",
	dlc_name = "vz_1003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_zealot_hat_1003",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	template = "wh_hats",
	unit = "units/beings/player/witch_hunter_zealot/headpiece/wh_z_hat_09",
	can_wield = {
		"wh_zealot",
	},
}
ItemMasterList.adept_hat_1010 = {
	description = "description_huntsman_hat_1006",
	display_name = "display_name_huntsman_hat_1006",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_generic_hat_1010",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	template = "bw_hat_jaw_no_hair",
	unit = "units/beings/player/bright_wizard_adept/headpiece/bw_a_fatshark_hat_01",
	can_wield = {
		"bw_adept",
		"bw_scholar",
		"bw_unchained",
	},
}
ItemMasterList.ranger_hat_1010 = {
	description = "description_huntsman_hat_1006",
	display_name = "display_name_huntsman_hat_1006",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_generic_hat_1010",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	template = "dr_helmets_hide_ears_skin_jaw",
	unit = "units/beings/player/dwarf_ranger_upgraded/headpiece/dr_u_fatshark_hat_01",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
		"dr_engineer",
	},
}
ItemMasterList.slayer_hat_1010 = {
	description = "description_huntsman_hat_1006",
	display_name = "display_name_huntsman_hat_1006",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_generic_hat_1010",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	template = "dr_hair_tattoo_00_hide_ears_skin_jaw",
	unit = "units/beings/player/dwarf_ranger_upgraded/headpiece/dr_u_fatshark_hat_01",
	can_wield = {
		"dr_slayer",
	},
}
ItemMasterList.huntsman_hat_1010 = {
	description = "description_huntsman_hat_1006",
	display_name = "display_name_huntsman_hat_1006",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_generic_hat_1010",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	template = "es_hats_jaw",
	unit = "units/beings/player/empire_soldier_huntsman/headpiece/es_h_fatshark_hat_01",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
		"es_questingknight",
	},
}
ItemMasterList.shade_hat_1010 = {
	description = "description_huntsman_hat_1006",
	display_name = "display_name_huntsman_hat_1006",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_shade_hat_1010",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	template = "ww_helmet_mask_jaw",
	unit = "units/beings/player/way_watcher_shade/headpiece/ww_s_fatshark_hat_01",
	can_wield = {
		"we_shade",
	},
}
ItemMasterList.waywatcher_hat_1010 = {
	description = "description_huntsman_hat_1006",
	display_name = "display_name_huntsman_hat_1006",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_waywatcher_hat_1010",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	template = "ww_helmet_mask_jaw",
	unit = "units/beings/player/way_watcher_upgraded/headpiece/ww_u_fatshark_hat_01",
	can_wield = {
		"we_waywatcher",
	},
}
ItemMasterList.maidenguard_hat_1010 = {
	description = "description_huntsman_hat_1006",
	display_name = "display_name_huntsman_hat_1006",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_maidenguard_hat_1010",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	template = "ww_masks",
	unit = "units/beings/player/way_watcher_maiden_guard/headpiece/ww_mg_fatshark_hat_01",
	can_wield = {
		"we_maidenguard",
	},
}
ItemMasterList.bountyhunter_hat_1010 = {
	description = "description_huntsman_hat_1006",
	display_name = "display_name_huntsman_hat_1006",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_generic_hat_1010",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	template = "wh_hats_face_skinned",
	unit = "units/beings/player/witch_hunter_bounty_hunter/headpiece/wh_bh_fatshark_hat_01",
	can_wield = {
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.zealot_hat_1010 = {
	description = "description_huntsman_hat_1006",
	display_name = "display_name_huntsman_hat_1006",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_generic_hat_1010",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	template = "wh_z_hats_tattoo_00_face_skinned",
	unit = "units/beings/player/witch_hunter_zealot/headpiece/wh_z_fatshark_hat_01",
	can_wield = {
		"wh_zealot",
	},
}
ItemMasterList.unchained_hat_1001 = {
	description = "description_unchained_hat_1001",
	display_name = "display_name_unchained_hat_1001",
	dlc_name = "su_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_unchained_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 107,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"bw_unchained",
	},
}
ItemMasterList.adept_hat_1001 = {
	description = "description_adept_hat_1001",
	display_name = "display_name_adept_hat_1001",
	dlc_name = "sb_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_adept_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 108,
	template = "bw_hat_no_hair",
	unit = "units/beings/player/bright_wizard_adept/headpiece/bw_a_hat_13",
	can_wield = {
		"bw_adept",
	},
}
ItemMasterList.scholar_hat_1001 = {
	description = "description_scholar_hat_1001",
	display_name = "display_name_scholar_hat_1001",
	dlc_name = "sp_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_scholar_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 109,
	template = "bw_hat_no_hair",
	unit = "units/beings/player/bright_wizard_scholar/headpiece/bw_s_hat_15",
	can_wield = {
		"bw_scholar",
	},
}
ItemMasterList.ranger_hat_1001 = {
	description = "description_ranger_hat_1001",
	display_name = "display_name_ranger_hat_1001",
	dlc_name = "br_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_ranger_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 110,
	template = "dr_helmets_hide_beard_ears_default_only",
	unit = "units/beings/player/dwarf_ranger_upgraded/headpiece/dr_u_hat_10",
	can_wield = {
		"dr_ranger",
	},
}
ItemMasterList.ironbreaker_hat_1001 = {
	description = "description_ironbreaker_hat_1001",
	display_name = "display_name_ironbreaker_hat_1001",
	dlc_name = "bi_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_ironbreaker_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 111,
	template = "dr_helmets_beard_ears",
	unit = "units/beings/player/dwarf_ranger_ironbreaker/headpiece/dr_i_hat_15",
	can_wield = {
		"dr_ironbreaker",
	},
}
ItemMasterList.slayer_hat_1001 = {
	description = "description_slayer_hat_1001",
	display_name = "display_name_slayer_hat_1001",
	dlc_name = "bs_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_slayer_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 112,
	template = "dr_hair_tattoo_05",
	unit = "units/beings/player/dwarf_ranger_slayer/headpiece/dr_s_hat_11",
	can_wield = {
		"dr_slayer",
	},
}
ItemMasterList.huntsman_hat_1001 = {
	description = "description_huntsman_hat_1001",
	display_name = "display_name_huntsman_hat_1001",
	dlc_name = "mh_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_huntsman_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 113,
	template = "es_hats_no_ear",
	unit = "units/beings/player/empire_soldier_huntsman/headpiece/es_h_hat_12",
	can_wield = {
		"es_huntsman",
	},
}
ItemMasterList.mercenary_hat_1001 = {
	description = "description_mercenary_hat_1001",
	display_name = "display_name_mercenary_hat_1001",
	dlc_name = "mm_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_mercenary_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 114,
	template = "es_hats",
	unit = "units/beings/player/empire_soldier_mercenary/headpiece/es_m_hat_11",
	can_wield = {
		"es_mercenary",
	},
}
ItemMasterList.knight_hat_1001 = {
	description = "description_knight_hat_1001",
	display_name = "display_name_knight_hat_1001",
	dlc_name = "mk_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_knight_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 115,
	template = "es_hats_no_beard_ear_nose_moustache",
	unit = "units/beings/player/empire_soldier_knight/headpiece/es_k_hat_12",
	can_wield = {
		"es_knight",
	},
}
ItemMasterList.witchhunter_hat_1001 = {
	description = "description_witchhunter_hat_1001",
	display_name = "display_name_witchhunter_hat_1001",
	dlc_name = "vw_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_witchhunter_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 106,
	template = "wh_hats_no_ears_face_skinned",
	unit = "units/beings/player/witch_hunter_captain/headpiece/wh_c_hat_14",
	can_wield = {
		"wh_captain",
	},
}
ItemMasterList.zealot_hat_1001 = {
	description = "description_zealot_hat_1001",
	display_name = "display_name_zealot_hat_1001",
	dlc_name = "vz_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_zealot_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 116,
	template = "wh_z_hats_tattoo_00",
	unit = "units/beings/player/witch_hunter_zealot/headpiece/wh_z_hat_07",
	can_wield = {
		"wh_zealot",
	},
}
ItemMasterList.bountyhunter_hat_1001 = {
	description = "description_bountyhunter_hat_1001",
	display_name = "display_name_bountyhunter_hat_1001",
	dlc_name = "vb_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_bountyhunter_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 117,
	template = "wh_hats_no_ears",
	unit = "units/beings/player/witch_hunter_bounty_hunter/headpiece/wh_bh_hat_11",
	can_wield = {
		"wh_bountyhunter",
	},
}
ItemMasterList.waywatcher_hat_1001 = {
	description = "description_waywatcher_hat_1001",
	display_name = "display_name_waywatcher_hat_1001",
	dlc_name = "kw_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_waywatcher_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 118,
	template = "ww_hat_no_face",
	unit = "units/beings/player/way_watcher_upgraded/headpiece/ww_u_hat_13",
	can_wield = {
		"we_waywatcher",
	},
}
ItemMasterList.shade_hat_1001 = {
	description = "description_shade_hat_1001",
	display_name = "display_name_shade_hat_1001",
	dlc_name = "ks_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_shade_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 119,
	template = "ww_helmet_mask",
	unit = "units/beings/player/way_watcher_shade/headpiece/ww_s_hat_12",
	can_wield = {
		"we_shade",
	},
}
ItemMasterList.maidenguard_hat_1001 = {
	description = "description_maidenguard_hat_1001",
	display_name = "display_name_maidenguard_hat_1001",
	dlc_name = "kh_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_maidenguard_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 120,
	template = "ww_helmet_mask",
	unit = "units/beings/player/way_watcher_maiden_guard/headpiece/ww_mg_hat_12",
	can_wield = {
		"we_maidenguard",
	},
}
ItemMasterList.scholar_hat_1002 = {
	description = "description_scholar_hat_1002",
	display_name = "display_name_scholar_hat_1002",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_scholar_hat_1002",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 128,
	store_optional_skin = "skin_bw_myrmidia",
	template = "bw_hat_no_hair",
	unit = "units/beings/player/bright_wizard_scholar/headpiece/bw_s_hat_16",
	can_wield = {
		"bw_scholar",
	},
}
ItemMasterList.skin_bw_myrmidia = {
	description = "description_skin_bw_myrmidia",
	display_name = "skin_bw_myrmidia",
	hud_icon = "unit_frame_portrait_bright_wizard",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_bw_myrmidia",
	item_type = "skin",
	name = "skin_bw_blazing_sun_01",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 129,
	store_optional_hat = "scholar_hat_1002",
	temporary_template = "skin_bw_default",
	can_wield = {
		"bw_scholar",
	},
}
ItemMasterList.scholar_bundle_0001 = {
	description = "pyromancer_bundle_01_desc",
	discount = 99,
	display_name = "pyromancer_bundle_01",
	hud_icon = "",
	information_text = "scholar_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 100,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 805,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_scholar_bundle_0001",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_scholar_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_scholar_bundle_0001",
	subtitle = "bw_scholar",
	template = "",
	unit = "",
	can_wield = {},
	steam_store_hidden = store_item_hidden,
	bundle_contains = {},
}
ItemMasterList.ironbreaker_hat_1004 = {
	description = "description_ironbreaker_hat_1004",
	display_name = "display_name_ironbreaker_hat_1004",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_ironbreaker_hat_1004",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 126,
	store_optional_skin = "skin_dr_irondrake",
	template = "dr_helmets_hide_beard",
	unit = "units/beings/player/dwarf_ranger_ironbreaker/headpiece/dr_i_hat_17",
	can_wield = {
		"dr_ironbreaker",
	},
}
ItemMasterList.skin_dr_irondrake = {
	description = "description_skin_dr_irondrake",
	display_name = "skin_dr_irondrake",
	hud_icon = "career_dwarf_ironbreaker",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ironbreaker_irondrake_01",
	item_type = "skin",
	name = "skin_dr_irondrake",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 127,
	store_optional_hat = "ironbreaker_hat_1004",
	temporary_template = "skin_dr_ironbreaker",
	can_wield = {
		"dr_ironbreaker",
	},
}
ItemMasterList.ironbreaker_bundle_0001 = {
	description = "ironbreaker_bundle_01_desc",
	discount = 99,
	display_name = "ironbreaker_bundle_01",
	hud_icon = "",
	information_text = "ironbreaker_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 300,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 804,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_ironbreaker_bundle_0001",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_ironbreaker_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_ironbreaker_bundle_0001",
	subtitle = "dr_ironbreaker",
	template = "",
	unit = "",
	can_wield = {},
	steam_store_hidden = store_item_hidden,
	bundle_contains = {},
}
ItemMasterList.bountyhunter_hat_1002 = {
	description = "description_bountyhunter_hat_1002",
	display_name = "display_name_bountyhunter_hat_1002",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_bountyhunter_hat_1002",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 124,
	store_optional_skin = "skin_wh_bountyhunter_1001",
	template = "wh_hats",
	unit = "units/beings/player/witch_hunter_bounty_hunter/headpiece/wh_bh_hat_12",
	can_wield = {
		"wh_bountyhunter",
	},
}
ItemMasterList.skin_wh_bountyhunter_1001 = {
	description = "description_skin_wh_bountyhunter_1001",
	display_name = "display_name_skin_wh_bountyhunter_1001",
	hud_icon = "unit_frame_portrait_witch_hunter",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_wh_bountyhunter_1001",
	item_type = "skin",
	name = "skin_wh_bountyhunter_1001",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 125,
	store_optional_hat = "bountyhunter_hat_1002",
	temporary_template = "skin_wh_bountyhunter_1001",
	can_wield = {
		"wh_bountyhunter",
	},
}
ItemMasterList.bountyhunter_bundle_0001 = {
	description = "bounty_hunter_bundle_01_desc",
	discount = 99,
	display_name = "bounty_hunter_bundle_01",
	hud_icon = "",
	information_text = "bountyhunter_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 400,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 803,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_bountyhunter_bundle_0001",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_bountyhunter_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_bountyhunter_bundle_0001",
	subtitle = "wh_bountyhunter",
	template = "",
	unit = "",
	can_wield = {},
	steam_store_hidden = store_item_hidden,
	bundle_contains = {},
}
ItemMasterList.mercenary_hat_1002 = {
	description = "description_mercenary_hat_1002",
	display_name = "display_name_mercenary_hat_1002",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_mercenary_hat_1002",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 122,
	store_optional_skin = "skin_es_mercenary_1001",
	template = "es_hats",
	unit = "units/beings/player/empire_soldier_mercenary/headpiece/es_m_hat_12",
	can_wield = {
		"es_mercenary",
	},
}
ItemMasterList.skin_es_mercenary_1001 = {
	description = "description_skin_es_mercenary_1001",
	display_name = "display_name_skin_es_mercenary_1001",
	hud_icon = "unit_frame_portrait_empire_soldier",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_mercenary_1001",
	item_type = "skin",
	name = "skin_es_mercenary_1001",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 123,
	store_optional_hat = "mercenary_hat_1002",
	temporary_template = "skin_es_mercenary_1001",
	can_wield = {
		"es_mercenary",
	},
}
ItemMasterList.mercenary_bundle_0001 = {
	description = "mercenary_bundle_01_desc",
	discount = 99,
	display_name = "mercenary_bundle_01",
	hud_icon = "",
	information_text = "mercenary_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 200,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 802,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_mercenary_bundle_0001",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_mercenary_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_mercenary_bundle_0001",
	subtitle = "es_mercenary",
	template = "",
	unit = "",
	can_wield = {},
	steam_store_hidden = store_item_hidden,
	bundle_contains = {},
}
ItemMasterList.shade_hat_1002 = {
	description = "description_shade_hat_1002",
	display_name = "display_name_shade_hat_1002",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_shade_hat_1002",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 103,
	store_optional_skin = "skin_ww_shade_1001",
	template = "ww_half_mask_full_face",
	unit = "units/beings/player/way_watcher_shade/headpiece/ww_s_hat_13",
	can_wield = {
		"we_shade",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.skin_ww_shade_1001 = {
	description = "description_skin_ww_shade_1001",
	display_name = "display_name_skin_ww_shade_1001",
	hud_icon = "unit_frame_portrait_way_watcher",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ww_shade_1001",
	item_type = "skin",
	name = "skin_ww_shade_1001",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 121,
	store_optional_hat = "shade_hat_1002",
	temporary_template = "skin_ww_shade_1001",
	can_wield = {
		"we_shade",
	},
}
ItemMasterList.shade_bundle_0001 = {
	description = "shade_bundle_01_desc",
	discount = 99,
	display_name = "shade_bundle_01",
	hud_icon = "",
	information_text = "shade_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 500,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 801,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_shade_bundle_0001",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_shade_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_shade_bundle_0001",
	subtitle = "we_shade",
	template = "",
	unit = "",
	can_wield = {},
	steam_store_hidden = store_item_hidden,
	bundle_contains = {},
}
ItemMasterList.five_career_bundle_0001 = {
	description = "five_career_bundle_0001_desc",
	discount = 99,
	display_name = "five_career_bundle_0001",
	hud_icon = "",
	information_text = "five_career_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 600,
	product_layout = "five_career_bundle_0001",
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 806,
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_five_career_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_five_career_bundle_0001",
	subtitle = "five_career_bundle_0001_subtitle",
	template = "",
	unit = "",
	can_wield = {},
	steam_store_hidden = store_item_hidden,
	bundle_contains = {},
}
ItemMasterList.adept_hat_1002 = {
	description = "description_adept_hat_1002",
	display_name = "display_name_adept_hat_1002",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_adept_hat_1002",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 130,
	store_optional_skin = "skin_bw_adept_1001",
	template = "bw_hat_no_hair",
	unit = "units/beings/player/bright_wizard_adept/headpiece/bw_a_hat_12",
	can_wield = {
		"bw_adept",
	},
}
ItemMasterList.skin_bw_adept_1001 = {
	description = "description_skin_bw_adept_1001",
	display_name = "display_name_skin_bw_adept_1001",
	hud_icon = "unit_frame_portrait_bright_wizard",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_bw_adept_1001",
	item_type = "skin",
	name = "skin_bw_adept_1001",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 131,
	store_optional_hat = "adept_hat_1002",
	temporary_template = "skin_bw_adept_1001",
	can_wield = {
		"bw_adept",
	},
}
ItemMasterList.adept_bundle_0001 = {
	description = "description_adept_bundle_0001",
	discount = 99,
	display_name = "display_name_adept_bundle_0001",
	hud_icon = "",
	information_text = "adept_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 1000,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 807,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_adept_bundle_0001",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_adept_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_adept_bundle_0001",
	subtitle = "bw_adept",
	template = "",
	unit = "",
	can_wield = {},
	steam_store_hidden = store_item_hidden,
	bundle_contains = {},
}
ItemMasterList.slayer_hat_1002 = {
	description = "description_slayer_hat_1002",
	display_name = "display_name_slayer_hat_1002",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_slayer_hat_1002",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 138,
	store_optional_skin = "skin_dr_slayer_1001",
	template = "dr_hair_tattoo_03",
	unit = "units/beings/player/dwarf_ranger_slayer/headpiece/dr_s_hat_13",
	can_wield = {
		"dr_slayer",
	},
	steam_store_hidden = store_item_hidden,
}
ItemMasterList.skin_dr_slayer_1001 = {
	description = "description_skin_dr_slayer_1001",
	display_name = "display_name_skin_dr_slayer_1001",
	hud_icon = "career_dwarf_slayer",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_dr_slayer_1001",
	item_type = "skin",
	name = "display_name_skin_dr_slayer_1001",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 139,
	store_optional_hat = "slayer_hat_1002",
	temporary_template = "skin_dr_slayer_1001",
	can_wield = {
		"dr_slayer",
	},
}
ItemMasterList.slayer_bundle_0001 = {
	description = "description_slayer_bundle_0001",
	discount = 99,
	display_name = "display_name_slayer_bundle_0001",
	hud_icon = "",
	information_text = "slayer_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 1200,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 811,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_slayer_bundle_0001",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_slayer_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_slayer_bundle_0001",
	subtitle = "dr_slayer",
	template = "",
	unit = "",
	can_wield = {},
	steam_store_hidden = store_item_hidden,
	bundle_contains = {},
}
ItemMasterList.huntsman_hat_1005 = {
	description = "description_huntsman_hat_1005",
	display_name = "display_name_huntsman_hat_1005",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_huntsman_hat_1005",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 136,
	store_optional_skin = "skin_es_longshark",
	template = "es_hats_no_ear",
	unit = "units/beings/player/empire_soldier_huntsman/headpiece/es_h_hat_16",
	can_wield = {
		"es_huntsman",
	},
	steam_store_hidden = steam_store_hidden,
}
ItemMasterList.skin_es_longshark = {
	description = "description_skin_es_longshark",
	display_name = "skin_es_longshark",
	hud_icon = "unit_frame_portrait_empire_soldier",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_longshark",
	item_type = "skin",
	name = "skin_es_longshark",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 137,
	store_optional_hat = "huntsman_hat_1005",
	temporary_template = "skin_es_huntsman",
	can_wield = {
		"es_huntsman",
	},
}
ItemMasterList.huntsman_bundle_0001 = {
	description = "description_huntsman_bundle_0001",
	discount = 99,
	display_name = "display_name_huntsman_bundle_0001",
	hud_icon = "",
	information_text = "huntsman_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 1300,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 810,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_huntsman_bundle_0001",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_huntsman_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_huntsman_bundle_0001",
	subtitle = "es_huntsman",
	template = "",
	unit = "",
	can_wield = {},
	steam_store_hidden = store_item_hidden,
	bundle_contains = {},
}
ItemMasterList.maidenguard_hat_1004 = {
	description = "description_maidenguard_hat_1004",
	display_name = "display_name_maidenguard_hat_1004",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_maidenguard_hat_1004",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 132,
	store_optional_skin = "skin_ww_moonmantle",
	template = "ww_masks",
	unit = "units/beings/player/way_watcher_maiden_guard/headpiece/ww_mg_hat_15",
	can_wield = {
		"we_maidenguard",
	},
}
ItemMasterList.skin_ww_moonmantle = {
	description = "description_skin_ww_moonmantle",
	display_name = "skin_ww_moonmantle",
	hud_icon = "unit_frame_portrait_way_watcher",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_handmaiden_moonmantle",
	item_type = "skin",
	name = "skin_ww_moonmantle",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 133,
	store_optional_hat = "maidenguard_hat_1004",
	temporary_template = "skin_ww_maidenguard",
	can_wield = {
		"we_maidenguard",
	},
}
ItemMasterList.maidenguard_bundle_0001 = {
	description = "description_maidenguard_bundle_0001",
	discount = 99,
	display_name = "display_name_maidenguard_bundle_0001",
	hud_icon = "",
	information_text = "maidenguard_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 1400,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 808,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_maidenguard_bundle_0001",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_maidenguard_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_maidenguard_bundle_0001",
	subtitle = "we_maidenguard",
	template = "",
	unit = "",
	can_wield = {},
	steam_store_hidden = store_item_hidden,
	bundle_contains = {},
}
ItemMasterList.zealot_hat_1002 = {
	description = "description_zealot_hat_1002",
	display_name = "display_name_zealot_hat_1002",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_zealot_hat_1002",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 134,
	store_optional_skin = "skin_wh_zealot_1001",
	template = "wh_z_hats_tattoo_03",
	unit = "units/beings/player/witch_hunter_zealot/headpiece/wh_z_hat_08",
	can_wield = {
		"wh_zealot",
	},
}
ItemMasterList.skin_wh_zealot_1001 = {
	description = "description_skin_wh_zealot_1001",
	display_name = "display_name_skin_wh_zealot_1001",
	hud_icon = "unit_frame_portrait_witch_hunter",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_wh_zealot_1001",
	item_type = "skin",
	name = "skin_wh_zealot_1001",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 135,
	store_optional_hat = "zealot_hat_1002",
	temporary_template = "skin_wh_zealot_1001",
	can_wield = {
		"wh_zealot",
	},
}
ItemMasterList.zealot_bundle_0001 = {
	description = "description_zealot_bundle_0001",
	discount = 99,
	display_name = "display_name_zealot_bundle_0001",
	hud_icon = "",
	information_text = "zealot_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 1500,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 809,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_zealot_bundle_0001",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_zealot_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_zealot_bundle_0001",
	subtitle = "wh_zealot",
	template = "",
	unit = "",
	can_wield = {},
	steam_store_hidden = store_item_hidden,
	bundle_contains = {},
}
ItemMasterList.fall_collection_2021_bundle = {
	description = "description_five_career_bundle_0002",
	discount = 99,
	display_name = "display_name_five_career_bundle_0002",
	hud_icon = "",
	information_text = "",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 1600,
	product_layout = "fall_collection_2021_bundle",
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 812,
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_fall_collection_2021_bundle",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_fall_collection_2021_bundle",
	subtitle = "five_career_bundle_0001_subtitle",
	template = "",
	unit = "",
	can_wield = {},
	steam_store_hidden = store_item_hidden,
	bundle_contains = {},
}
ItemMasterList.skin_bw_adept_white = {
	description = "description_skin_bw_adept_white",
	display_name = "skin_bw_adept_white",
	hud_icon = "unit_frame_portrait_bright_wizard",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_bw_adept_white",
	item_type = "skin",
	name = "skin_bw_adept_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_bw_adept_white",
	can_wield = {
		"bw_adept",
	},
}
ItemMasterList.skin_bw_scholar_white = {
	description = "description_skin_bw_scholar_white",
	display_name = "skin_bw_scholar_white",
	hud_icon = "unit_frame_portrait_bright_wizard",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_bw_scholar_white",
	item_type = "skin",
	name = "skin_bw_scholar_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_bw_scholar_white",
	can_wield = {
		"bw_scholar",
	},
}
ItemMasterList.skin_bw_unchained_white = {
	description = "description_skin_bw_unchained_white",
	display_name = "skin_bw_unchained_white",
	hud_icon = "unit_frame_portrait_bright_wizard",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_bw_unchained_white",
	item_preview_environment = "unchained_skins_01",
	item_type = "skin",
	name = "skin_bw_unchained_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_bw_unchained_white",
	can_wield = {
		"bw_unchained",
	},
}
ItemMasterList.skin_dr_ironbreaker_white = {
	description = "description_skin_dr_ironbreaker_white",
	display_name = "skin_dr_ironbreaker_white",
	hud_icon = "career_dwarf_ironbreaker",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_dr_ironbreaker_white",
	item_type = "skin",
	name = "skin_dr_ironbreaker_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_dr_ironbreaker_white",
	can_wield = {
		"dr_ironbreaker",
	},
}
ItemMasterList.skin_dr_slayer_white = {
	description = "description_skin_dr_slayer_white",
	display_name = "skin_dr_slayer_white",
	hud_icon = "career_dwarf_slayer",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_dr_slayer_white",
	item_type = "skin",
	name = "skin_dr_slayer_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_dr_slayer_white",
	can_wield = {
		"dr_slayer",
	},
}
ItemMasterList.skin_dr_ranger_white = {
	description = "description_skin_dr_ranger_white",
	display_name = "skin_dr_ranger_white",
	hud_icon = "career_dwarf_ranger",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_dr_ranger_white",
	item_type = "skin",
	name = "skin_dr_ranger_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_dr_ranger_white",
	can_wield = {
		"dr_ranger",
	},
}
ItemMasterList.skin_es_huntsman_white = {
	description = "description_skin_es_huntsman_white",
	display_name = "skin_es_huntsman_white",
	hud_icon = "unit_frame_portrait_empire_soldier",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_huntsman_white",
	item_type = "skin",
	name = "skin_es_huntsman_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_es_huntsman_white",
	can_wield = {
		"es_huntsman",
	},
}
ItemMasterList.skin_es_knight_white = {
	description = "description_skin_es_knight_white",
	display_name = "skin_es_knight_white",
	hud_icon = "unit_frame_portrait_empire_soldier",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_knight_white",
	item_type = "skin",
	name = "skin_es_knight_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_es_knight_white",
	can_wield = {
		"es_knight",
	},
}
ItemMasterList.skin_es_mercenary_white = {
	description = "description_skin_es_mercenary_white",
	display_name = "skin_es_mercenary_white",
	hud_icon = "unit_frame_portrait_empire_soldier",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_mercenary_white",
	item_type = "skin",
	name = "skin_es_mercenary_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_es_mercenary_white",
	can_wield = {
		"es_mercenary",
	},
}
ItemMasterList.skin_ww_shade_white = {
	description = "description_skin_ww_shade_white",
	display_name = "skin_ww_shade_white",
	hud_icon = "unit_frame_portrait_way_watcher",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ww_shade_white",
	item_preview_environment = "shade_skins_01",
	item_type = "skin",
	name = "skin_ww_shade_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_ww_shade_white",
	can_wield = {
		"we_shade",
	},
}
ItemMasterList.skin_ww_maidenguard_white = {
	description = "description_skin_ww_maidenguard_white",
	display_name = "skin_ww_maidenguard_white",
	hud_icon = "unit_frame_portrait_way_watcher",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ww_maidenguard_white",
	item_type = "skin",
	name = "skin_ww_maidenguard_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_ww_maidenguard_white",
	can_wield = {
		"we_maidenguard",
	},
}
ItemMasterList.skin_ww_waywatcher_white = {
	description = "description_skin_ww_waywatcher_white",
	display_name = "skin_ww_waywatcher_white",
	hud_icon = "unit_frame_portrait_way_watcher",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ww_waywatcher_white",
	item_preview_environment = "waystalker_skins_01",
	item_type = "skin",
	name = "skin_ww_waywatcher_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_ww_waywatcher_white",
	can_wield = {
		"we_waywatcher",
	},
}
ItemMasterList.skin_wh_captain_white = {
	description = "description_skin_wh_captain_white",
	display_name = "skin_wh_captain_white",
	hud_icon = "unit_frame_portrait_witch_hunter",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_wh_captain_white",
	item_type = "skin",
	name = "skin_wh_captain_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_wh_captain_white",
	can_wield = {
		"wh_captain",
	},
}
ItemMasterList.skin_wh_bountyhunter_white = {
	description = "description_skin_wh_bountyhunter_white",
	display_name = "skin_wh_bountyhunter_white",
	hud_icon = "unit_frame_portrait_witch_hunter",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_wh_bountyhunter_white",
	item_type = "skin",
	name = "skin_wh_bountyhunter_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_wh_bountyhunter_white",
	can_wield = {
		"wh_bountyhunter",
	},
}
ItemMasterList.skin_wh_zealot_white = {
	description = "description_skin_wh_zealot_white",
	display_name = "skin_wh_zealot_white",
	hud_icon = "unit_frame_portrait_witch_hunter",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_wh_zealot_white",
	item_type = "skin",
	name = "skin_wh_zealot_white",
	rarity = "unique",
	skin_type = "unit",
	slot_type = "skin",
	temporary_template = "skin_wh_zealot_white",
	can_wield = {
		"wh_zealot",
	},
}
ItemMasterList.test_item_1017 = {
	description = "test_item_1017_desc",
	display_name = "test_item_1017",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1017",
	inventory_icon = "icon_waywatcher_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 17,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = not Application or not Application.user_setting("show_test_item"),
}
ItemMasterList.test_item_1018 = {
	description = "test_item_1018_desc",
	display_name = "test_item_1018",
	hud_icon = "hud_icon_default",
	information_text = "test_item_1018",
	inventory_icon = "icon_waywatcher_hat_1001",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 18,
	template = "bw_hat",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_12",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
	steam_store_hidden = not Application or not Application.user_setting("show_test_item"),
}
