-- chunkname: @scripts/settings/equipment/item_master_list_cosmetics_2023_q4.lua

ItemMasterList.scholar_hat_1004 = {
	description = "description_scholar_hat_1004",
	display_name = "display_name_scholar_hat_1004",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_scholar_hat_1004",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 192,
	store_optional_skin = "skin_bw_scholar_1002",
	template = "bw_gates",
	unit = "units/beings/player/bright_wizard_scholar/headpiece/bw_s_hat_17",
	can_wield = {
		"bw_scholar",
	},
}
ItemMasterList.slayer_hat_1005 = {
	description = "description_slayer_hat_1005",
	display_name = "display_name_slayer_hat_1005",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_slayer_hat_1005",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 184,
	store_optional_skin = "skin_dr_slayer_1002",
	template = "dr_s_hat_15",
	unit = "units/beings/player/dwarf_ranger_slayer/headpiece/dr_s_hat_15",
	can_wield = {
		"dr_slayer",
	},
}
ItemMasterList.mercenary_hat_1003 = {
	description = "description_mercenary_hat_1003",
	display_name = "display_name_mercenary_hat_1003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_mercenary_hat_1003",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 188,
	store_optional_skin = "skin_es_mercenary_1002",
	template = "es_hats_no_ears_skinned",
	unit = "units/beings/player/empire_soldier_mercenary/headpiece/es_m_hat_13",
	can_wield = {
		"es_mercenary",
	},
}
ItemMasterList.waywatcher_hat_1005 = {
	description = "description_waywatcher_hat_1005",
	display_name = "display_name_waywatcher_hat_1005",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_waywatcher_hat_1005",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 186,
	store_optional_skin = "skin_ww_waywatcher_1002",
	template = "ww_balaclava_wide",
	unit = "units/beings/player/way_watcher_upgraded/headpiece/ww_u_hat_15",
	can_wield = {
		"we_waywatcher",
	},
}
ItemMasterList.witchhunter_hat_1004 = {
	description = "description_witchhunter_hat_1004",
	display_name = "display_name_witchhunter_hat_1004",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_witchhunter_hat_1004",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 190,
	store_optional_skin = "skin_wh_captain_1002",
	template = "wh_hats_no_ears_skinned_lock_jaw",
	unit = "units/beings/player/witch_hunter_captain/headpiece/wh_c_hat_15",
	can_wield = {
		"wh_captain",
	},
}
ItemMasterList.skin_bw_scholar_1002 = {
	description = "description_skin_bw_scholar_1002",
	display_name = "display_name_skin_bw_scholar_1002",
	hud_icon = "unit_frame_portrait_bright_wizard",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_bw_scholar_1002",
	item_type = "skin",
	name = "skin_bw_scholar_1002",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 193,
	store_optional_hat = "scholar_hat_1004",
	temporary_template = "skin_bw_scholar_1002",
	can_wield = {
		"bw_scholar",
	},
}
ItemMasterList.skin_dr_slayer_1002 = {
	description = "description_skin_dr_slayer_1002",
	display_name = "display_name_skin_dr_slayer_1002",
	hud_icon = "career_dwarf_slayer",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_dr_slayer_1002",
	item_type = "skin",
	name = "skin_dr_slayer_1002",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 185,
	store_optional_hat = "slayer_hat_1005",
	temporary_template = "skin_dr_slayer_1002",
	can_wield = {
		"dr_slayer",
	},
}
ItemMasterList.skin_es_mercenary_1002 = {
	description = "description_skin_es_mercenary_1002",
	display_name = "display_name_skin_es_mercenary_1002",
	hud_icon = "unit_frame_portrait_empire_soldier",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_mercenary_1002",
	item_type = "skin",
	name = "skin_es_mercenary_1002",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 189,
	store_optional_hat = "mercenary_hat_1003",
	temporary_template = "skin_es_mercenary_1002",
	can_wield = {
		"es_mercenary",
	},
}
ItemMasterList.skin_ww_waywatcher_1002 = {
	description = "description_skin_ww_waywatcher_1002",
	display_name = "display_name_skin_ww_waywatcher_1002",
	hud_icon = "unit_frame_portrait_way_watcher",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ww_waywatcher_1002",
	item_preview_environment = "waystalker_skins_01",
	item_type = "skin",
	name = "skin_ww_waywatcher_1002",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 187,
	store_optional_hat = "waywatcher_hat_1005",
	temporary_template = "skin_ww_waywatcher_1002",
	can_wield = {
		"we_waywatcher",
	},
}
ItemMasterList.skin_wh_captain_1002 = {
	description = "description_skin_wh_captain_1002",
	display_name = "display_name_skin_wh_captain_1002",
	hud_icon = "unit_frame_portrait_witch_hunter",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_wh_captain_1002",
	item_type = "skin",
	name = "skin_wh_captain_1002",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 191,
	store_optional_hat = "witchhunter_hat_1004",
	temporary_template = "skin_wh_captain_1002",
	can_wield = {
		"wh_captain",
	},
}
ItemMasterList.slayer_bundle_0002 = {
	description = "description_slayer_bundle_0002",
	discount = 99,
	display_name = "display_name_slayer_bundle_0002",
	hud_icon = "",
	information_text = "description_slayer_bundle_0002",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 4100,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 838,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_slayer_bundle_0002",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_slayer_bundle_0002",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_slayer_bundle_0002",
	subtitle = "dr_slayer",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.waywatcher_bundle_0001 = {
	description = "description_waywatcher_bundle_0001",
	discount = 99,
	display_name = "display_name_waywatcher_bundle_0001",
	hud_icon = "",
	information_text = "description_waywatcher_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 4200,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 839,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_waywatcher_bundle_0001",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_waywatcher_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_waywatcher_bundle_0001",
	subtitle = "we_waywatcher",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.mercenary_bundle_0002 = {
	description = "description_mercenary_bundle_0002",
	discount = 99,
	display_name = "display_name_mercenary_bundle_0002",
	hud_icon = "",
	information_text = "description_mercenary_bundle_0002",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 4300,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 840,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_mercenary_bundle_0002",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_mercenary_bundle_0002",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_mercenary_bundle_0002",
	subtitle = "es_mercenary",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.scholar_bundle_0003 = {
	description = "description_scholar_bundle_0003",
	discount = 99,
	display_name = "display_name_scholar_bundle_0003",
	hud_icon = "",
	information_text = "description_scholar_bundle_0003",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 4400,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 842,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_scholar_bundle_0003",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_scholar_bundle_0003",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_scholar_bundle_0003",
	subtitle = "bw_scholar",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.witchhunter_bundle_0001 = {
	description = "description_witchhunter_bundle_0001",
	discount = 99,
	display_name = "display_name_witchhunter_bundle_0001",
	hud_icon = "",
	information_text = "description_witchhunter_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 4500,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 841,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_witchhunter_bundle_0001",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_witchhunter_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_witchhunter_bundle_0001",
	subtitle = "wh_captain",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.five_career_bundle_0007 = {
	description = "description_five_career_bundle_0007",
	display_name = "display_name_five_career_bundle_0007",
	hud_icon = "",
	information_text = "five_career_bundle_0007",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 4600,
	product_layout = "five_career_bundle_0007",
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 843,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_five_career_bundle_0007",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_five_career_bundle_0007",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_five_career_bundle_0007",
	subtitle = "five_career_bundle_0001_subtitle",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
