-- chunkname: @scripts/settings/equipment/item_master_list_morris.lua

require("scripts/settings/dlcs/morris/tweak_data/buff_tweak_data")

local item_master_list = {
	dr_deus_01 = {
		ammo_unit = "units/weapons/player/wpn_dr_deus_projectile_01/wpn_dr_deus_projectile_01",
		ammo_unit_3p = "units/weapons/player/wpn_dr_deus_projectile_01/wpn_dr_deus_projectile_01_3p",
		description = "dr_deus_01_description",
		display_name = "dr_deus_01_name",
		has_power_level = true,
		hud_icon = "weapon_generic_icon_crossbow",
		inventory_icon = "icon_wpn_dw_trollhammer_t1",
		item_type = "dr_deus_01",
		left_hand_unit = "units/weapons/player/wpn_dr_deus_01/wpn_dr_deus_01",
		property_table_name = "ranged",
		rarity = "plentiful",
		required_dlc = "grass",
		skin_combination_table = "dr_deus_01_skins",
		slot_type = "ranged",
		template = "dr_deus_01_template_1",
		trait_table_name = "ranged_ammo",
		can_wield = {
			"dr_ironbreaker",
		},
	},
	dr_deus_01_skin = {
		base_skin_item = true,
		description = "dr_deus_01_skin_01_description",
		display_name = "dr_deus_01_skin_01_name",
		information_text = "information_weapon_skin",
		item_type = "weapon_skin",
		matching_item_key = "dr_deus_01",
		rarity = "plentiful",
		slot_type = "weapon_skin",
		can_wield = {
			"dr_ironbreaker",
		},
	},
	dr_deus_01_skin_02 = {
		ammo_unit = "units/weapons/player/wpn_dr_deus_projectile_02/wpn_dr_deus_projectile_02",
		ammo_unit_3p = "units/weapons/player/wpn_dr_deus_projectile_02/wpn_dr_deus_projectile_02_3p",
		description = "dr_deus_01_skin_02_description",
		display_name = "dr_deus_01_skin_02_name",
		display_unit = "units/weapons/weapon_display/display_drakegun",
		hud_icon = "weapon_generic_icon_crossbow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_dw_trollhammer_t2",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_dr_deus_02/wpn_dr_deus_02",
		matching_item_key = "dr_deus_01",
		rarity = "exotic",
		required_dlc = "grass",
		slot_type = "weapon_skin",
		template = "dr_deus_01_template_1",
		can_wield = {
			"dr_ironbreaker",
		},
	},
	dr_deus_01_skin_03 = {
		ammo_unit = "units/weapons/player/wpn_dr_deus_projectile_03/wpn_dr_deus_projectile_03",
		ammo_unit_3p = "units/weapons/player/wpn_dr_deus_projectile_03/wpn_dr_deus_projectile_03_3p",
		description = "dr_deus_01_skin_02_description",
		display_name = "dr_deus_01_skin_02_name",
		display_unit = "units/weapons/weapon_display/display_drakegun",
		hud_icon = "weapon_generic_icon_crossbow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_dw_trollhammer_t3",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_dr_deus_03/wpn_dr_deus_03",
		matching_item_key = "dr_deus_01",
		rarity = "exotic",
		required_dlc = "grass",
		slot_type = "weapon_skin",
		template = "dr_deus_01_template_1",
		can_wield = {
			"dr_ironbreaker",
		},
	},
	dr_deus_01_skin_01_runed = {
		ammo_unit = "units/weapons/player/wpn_dr_deus_projectile_01/wpn_dr_deus_projectile_01",
		ammo_unit_3p = "units/weapons/player/wpn_dr_deus_projectile_01/wpn_dr_deus_projectile_01_3p",
		description = "dr_deus_01_skin_01_runed_description",
		display_name = "dr_deus_01_skin_01_runed_name",
		display_unit = "units/weapons/weapon_display/display_drakegun",
		hud_icon = "weapon_generic_icon_crossbow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_dw_trollhammer_t1_runed",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_dr_deus_01/wpn_dr_deus_01_runed",
		matching_item_key = "dr_deus_01",
		rarity = "unique",
		required_dlc = "grass",
		slot_type = "weapon_skin",
		template = "dr_deus_01_template_1",
		can_wield = {
			"dr_ironbreaker",
		},
	},
	dr_deus_01_skin_02_runed = {
		ammo_unit = "units/weapons/player/wpn_dr_deus_projectile_02/wpn_dr_deus_projectile_02",
		ammo_unit_3p = "units/weapons/player/wpn_dr_deus_projectile_02/wpn_dr_deus_projectile_02_3p",
		description = "dr_deus_01_skin_02_runed_description",
		display_name = "dr_deus_01_skin_02_runed_name",
		display_unit = "units/weapons/weapon_display/display_drakegun",
		hud_icon = "weapon_generic_icon_crossbow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_dw_trollhammer_t2_runed",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_dr_deus_02/wpn_dr_deus_02_runed",
		matching_item_key = "dr_deus_01",
		rarity = "unique",
		required_dlc = "grass",
		slot_type = "weapon_skin",
		template = "dr_deus_01_template_1",
		can_wield = {
			"dr_ironbreaker",
		},
	},
	dr_deus_01_skin_03_runed = {
		ammo_unit = "units/weapons/player/wpn_dr_deus_projectile_03/wpn_dr_deus_projectile_03",
		ammo_unit_3p = "units/weapons/player/wpn_dr_deus_projectile_03/wpn_dr_deus_projectile_03_3p",
		description = "dr_deus_01_skin_02_runed_description",
		display_name = "dr_deus_01_skin_02_runed_name",
		display_unit = "units/weapons/weapon_display/display_drakegun",
		hud_icon = "weapon_generic_icon_crossbow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_dw_trollhammer_t3_runed",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_dr_deus_03/wpn_dr_deus_03_runed",
		matching_item_key = "dr_deus_01",
		rarity = "unique",
		required_dlc = "grass",
		slot_type = "weapon_skin",
		template = "dr_deus_01_template_1",
		can_wield = {
			"dr_ironbreaker",
		},
	},
	dr_deus_01_skin_magic = {
		description = "dr_deus_01_magic_description",
		hud_icon = "weapon_generic_icon_staff_3",
		inventory_icon = "icon_wpn_dw_trollhammer_t1",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_dr_deus_01/wpn_dr_deus_01_magic",
		matching_item_key = "dr_deus_01",
		rarity = "magic",
		required_dlc = "grass",
		slot_type = "weapon_skin",
		template = "dr_deus_01_template_1",
		can_wield = {
			"dr_ironbreaker",
			"dr_engineer",
		},
	},
	dr_deus_02_skin_magic = {
		description = "dr_deus_01_magic_description",
		hud_icon = "weapon_generic_icon_staff_3",
		inventory_icon = "icon_wpn_dw_trollhammer_t2",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_dr_deus_02/wpn_dr_deus_02_magic",
		matching_item_key = "dr_deus_01",
		rarity = "magic",
		required_dlc = "grass",
		slot_type = "weapon_skin",
		template = "dr_deus_01_template_1",
		can_wield = {
			"dr_ironbreaker",
			"dr_engineer",
		},
	},
	dr_deus_01_skin_01 = {
		description = "dr_deus_01_skin_01_description",
		display_name = "dr_deus_01_skin_01_name",
		hud_icon = "weapon_generic_icon_staff_3",
		inventory_icon = "icon_wpn_dw_trollhammer_t1",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_dr_deus_01/wpn_dr_deus_01",
		matching_item_key = "dr_deus_01",
		rarity = "plentiful",
		required_dlc = "grass",
		slot_type = "weapon_skin",
		template = "dr_deus_01_template_1",
		can_wield = {
			"dr_ironbreaker",
			"dr_engineer",
		},
	},
	dr_deus_01_magic = {
		ammo_unit = "units/weapons/player/wpn_dr_deus_projectile_02/wpn_dr_deus_projectile_02",
		ammo_unit_3p = "units/weapons/player/wpn_dr_deus_projectile_02/wpn_dr_deus_projectile_02_3p",
		description = "dr_deus_01_magic_description",
		display_name = "dr_deus_01_magic_name",
		has_power_level = true,
		hud_icon = "weapon_generic_icon_bow",
		inventory_icon = "icon_wpn_dw_trollhammer_t2_magic",
		item_type = "dr_deus_01",
		left_hand_unit = "units/weapons/player/wpn_dr_deus_02/wpn_dr_deus_02_magic",
		property_table_name = "ranged",
		rarity = "magic",
		required_dlc = "grass",
		required_unlock_item = "dr_deus_01",
		slot_type = "ranged",
		template = "dr_deus_01_template_1",
		trait_table_name = "ranged_ammo",
		can_wield = {
			"dr_ironbreaker",
		},
	},
	es_deus_01 = {
		description = "es_deus_01_description",
		display_name = "es_deus_01_name",
		has_power_level = true,
		hud_icon = "weapon_generic_icon_falken",
		inventory_icon = "icon_wpn_empire_spearshield_t1",
		item_type = "es_deus_01",
		left_hand_unit = "units/weapons/player/wpn_empire_shield_02/wpn_emp_shield_02",
		property_table_name = "melee",
		rarity = "plentiful",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_es_deus_spear_01/wpn_es_deus_spear_01",
		skin_combination_table = "es_deus_01_skins",
		slot_type = "melee",
		template = "es_deus_01_template",
		trait_table_name = "melee",
		can_wield = {
			"es_huntsman",
			"es_knight",
			"es_mercenary",
		},
	},
	es_deus_01_skin = {
		base_skin_item = true,
		description = "es_deus_01_skin_01_description",
		display_name = "es_deus_01_skin_01_name",
		information_text = "information_weapon_skin",
		item_type = "weapon_skin",
		matching_item_key = "es_deus_01",
		rarity = "plentiful",
		slot_type = "weapon_skin",
		can_wield = {
			"es_huntsman",
			"es_knight",
			"es_mercenary",
		},
	},
	es_deus_01_skin_01 = {
		description = "es_deus_01_skin_01_description",
		display_name = "es_deus_01_skin_01_name",
		hud_icon = "weapon_generic_icon_staff_3",
		inventory_icon = "icon_wpn_empire_spearshield_t1",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_empire_shield_02/wpn_emp_shield_02",
		matching_item_key = "es_deus_01",
		rarity = "plentiful",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_es_deus_spear_01/wpn_es_deus_spear_01",
		slot_type = "weapon_skin",
		template = "es_deus_01_template",
		can_wield = {
			"es_huntsman",
			"es_knight",
			"es_mercenary",
		},
	},
	es_deus_01_skin_02 = {
		description = "es_deus_01_skin_02_description",
		display_name = "es_deus_01_skin_02_name",
		display_unit = "units/weapons/weapon_display/display_shield_sword",
		hud_icon = "weapon_generic_iweapon_generic_icon_falkencon_bow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_empire_spearshield_t2",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_es_deus_shield_02/wpn_es_deus_shield_02",
		matching_item_key = "es_deus_01",
		rarity = "exotic",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_es_deus_spear_02/wpn_es_deus_spear_02",
		slot_type = "weapon_skin",
		template = "es_deus_01_template",
		can_wield = {
			"es_huntsman",
			"es_knight",
			"es_mercenary",
		},
	},
	es_deus_01_skin_03 = {
		description = "es_deus_01_skin_03_description",
		display_name = "es_deus_01_skin_03_name",
		display_unit = "units/weapons/weapon_display/display_shield_sword",
		hud_icon = "weapon_generic_iweapon_generic_icon_falkencon_bow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_empire_spearshield_t3",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_es_deus_shield_03/wpn_es_deus_shield_03",
		matching_item_key = "es_deus_01",
		rarity = "exotic",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_es_deus_spear_03/wpn_es_deus_spear_03",
		slot_type = "weapon_skin",
		template = "es_deus_01_template",
		can_wield = {
			"es_huntsman",
			"es_knight",
			"es_mercenary",
		},
	},
	es_deus_01_skin_01_runed = {
		description = "es_deus_01_skin_01_runed_description",
		display_name = "es_deus_01_skin_01_runed_name",
		display_unit = "units/weapons/weapon_display/display_shield_sword",
		hud_icon = "weapon_generic_icon_falken",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_empire_spearshield_t1_runed",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_empire_shield_02/wpn_emp_shield_02_runed_01",
		matching_item_key = "es_deus_01",
		rarity = "unique",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_es_deus_spear_01/wpn_es_deus_spear_01_runed",
		slot_type = "weapon_skin",
		template = "es_deus_01_template",
		can_wield = {
			"es_huntsman",
			"es_knight",
			"es_mercenary",
		},
	},
	es_deus_01_skin_02_runed = {
		description = "es_deus_01_skin_02_runed_description",
		display_name = "es_deus_01_skin_02_runed_name",
		display_unit = "units/weapons/weapon_display/display_shield_sword",
		hud_icon = "weapon_generic_icon_falken",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_empire_spearshield_t2_runed",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_es_deus_shield_02/wpn_es_deus_shield_02_runed",
		matching_item_key = "es_deus_01",
		rarity = "unique",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_es_deus_spear_02/wpn_es_deus_spear_02_runed",
		slot_type = "weapon_skin",
		template = "es_deus_01_template",
		can_wield = {
			"es_huntsman",
			"es_knight",
			"es_mercenary",
		},
	},
	es_deus_01_skin_03_runed = {
		description = "es_deus_01_skin_03_runed_description",
		display_name = "es_deus_01_skin_03_runed_name",
		display_unit = "units/weapons/weapon_display/display_shield_sword",
		hud_icon = "weapon_generic_icon_falken",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_empire_spearshield_t3_runed",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_es_deus_shield_03/wpn_es_deus_shield_03_runed",
		matching_item_key = "es_deus_01",
		rarity = "unique",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_es_deus_spear_03/wpn_es_deus_spear_03_runed",
		slot_type = "weapon_skin",
		template = "es_deus_01_template",
		can_wield = {
			"es_huntsman",
			"es_knight",
			"es_mercenary",
		},
	},
	es_deus_01_skin_magic = {
		description = "es_deus_01_magic_description",
		hud_icon = "weapon_generic_icon_staff_3",
		inventory_icon = "icon_wpn_empire_spearshield_t1",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_es_deus_shield_02/wpn_es_deus_shield_02_magic_3p",
		matching_item_key = "es_deus_01",
		rarity = "magic",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_es_deus_spear_01/wpn_es_deus_spear_01_magic",
		slot_type = "weapon_skin",
		template = "es_deus_01_template",
		can_wield = {
			"es_huntsman",
			"es_knight",
			"es_mercenary",
		},
	},
	es_deus_02_skin_magic = {
		description = "es_deus_01_magic_description",
		hud_icon = "weapon_generic_icon_staff_3",
		inventory_icon = "icon_wpn_empire_spearshield_t1",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_es_deus_shield_02/wpn_es_deus_shield_02_magic",
		matching_item_key = "es_deus_01",
		rarity = "magic",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_es_deus_spear_02/wpn_es_deus_spear_02_magic",
		slot_type = "weapon_skin",
		template = "es_deus_01_template",
		can_wield = {
			"es_huntsman",
			"es_knight",
			"es_mercenary",
		},
	},
	es_deus_01_magic = {
		description = "es_deus_01_magic_description",
		display_name = "es_deus_01_magic_name",
		has_power_level = true,
		hud_icon = "weapon_generic_icon_bow",
		inventory_icon = "icon_wpn_empire_spearshield_t1_magic",
		item_type = "es_deus_01",
		left_hand_unit = "units/weapons/player/wpn_es_deus_shield_02/wpn_es_deus_shield_02_magic",
		property_table_name = "melee",
		rarity = "magic",
		required_dlc = "grass",
		required_unlock_item = "es_deus_01",
		right_hand_unit = "units/weapons/player/wpn_es_deus_spear_02/wpn_es_deus_spear_02_magic",
		slot_type = "melee",
		template = "es_deus_01_template",
		trait_table_name = "melee",
		can_wield = {
			"es_huntsman",
			"es_knight",
			"es_mercenary",
		},
	},
	we_deus_01 = {
		ammo_unit = "units/weapons/player/wpn_we_quiver_t1/wpn_we_deus_arrow_01",
		ammo_unit_3p = "units/weapons/player/wpn_we_quiver_t1/wpn_we_deus_arrow_01_3p",
		description = "we_deus_01_description",
		display_name = "we_deus_01_name",
		has_power_level = true,
		hud_icon = "weapon_generic_icon_bow",
		inventory_icon = "icon_wpn_we_moonfire_t1",
		item_type = "we_deus_01",
		left_hand_unit = "units/weapons/player/wpn_we_deus_01/wpn_we_deus_01",
		property_table_name = "ranged",
		rarity = "plentiful",
		required_dlc = "grass",
		skin_combination_table = "we_deus_01_skins",
		slot_type = "ranged",
		template = "we_deus_01_template_1",
		trait_table_name = "ranged_energy",
		can_wield = {
			"we_shade",
			"we_maidenguard",
			"we_waywatcher",
		},
	},
	we_deus_01_skin = {
		base_skin_item = true,
		description = "we_deus_01_skin_01_description",
		display_name = "we_deus_01_skin_01_name",
		information_text = "information_weapon_skin",
		item_type = "weapon_skin",
		matching_item_key = "we_deus_01",
		rarity = "plentiful",
		slot_type = "weapon_skin",
		can_wield = {
			"we_shade",
			"we_maidenguard",
			"we_waywatcher",
		},
	},
	we_deus_01_skin_01 = {
		description = "we_deus_01_skin_01_description",
		display_name = "we_deus_01_skin_01_name",
		hud_icon = "weapon_generic_icon_bow",
		inventory_icon = "icon_wpn_we_moonfire_t1",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_we_deus_01/wpn_we_deus_01",
		matching_item_key = "we_deus_01",
		rarity = "plentiful",
		required_dlc = "grass",
		slot_type = "weapon_skin",
		template = "we_deus_01_template_1",
		can_wield = {
			"we_shade",
			"we_maidenguard",
			"we_waywatcher",
			"we_thornsister",
		},
	},
	we_deus_01_skin_02 = {
		ammo_unit = "units/weapons/player/wpn_we_quiver_t1/wpn_we_deus_arrow_02",
		ammo_unit_3p = "units/weapons/player/wpn_we_quiver_t1/wpn_we_deus_arrow_02_3p",
		description = "we_deus_01_skin_02_description",
		display_name = "we_deus_01_skin_02_name",
		display_unit = "units/weapons/weapon_display/display_bow",
		hud_icon = "weapon_generic_icon_bow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_we_moonfire_t2",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_we_deus_02/wpn_we_deus_02",
		matching_item_key = "we_deus_01",
		rarity = "exotic",
		required_dlc = "grass",
		slot_type = "weapon_skin",
		template = "we_deus_01_template_1",
		can_wield = {
			"we_shade",
			"we_maidenguard",
			"we_waywatcher",
		},
	},
	we_deus_01_skin_01_runed = {
		ammo_unit = "units/weapons/player/wpn_we_quiver_t1/wpn_we_deus_arrow_01",
		ammo_unit_3p = "units/weapons/player/wpn_we_quiver_t1/wpn_we_deus_arrow_01_3p",
		description = "we_deus_01_skin_01_runed_description",
		display_name = "we_deus_01_skin_01_runed_name",
		display_unit = "units/weapons/weapon_display/display_bow",
		hud_icon = "weapon_generic_icon_bow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_we_moonfire_t1_runed",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_we_deus_01/wpn_we_deus_01_runed",
		matching_item_key = "we_deus_01",
		rarity = "unique",
		required_dlc = "grass",
		slot_type = "weapon_skin",
		template = "we_deus_01_template_1",
		can_wield = {
			"we_shade",
			"we_maidenguard",
			"we_waywatcher",
		},
	},
	we_deus_01_skin_02_runed = {
		ammo_unit = "units/weapons/player/wpn_we_quiver_t1/wpn_we_deus_arrow_02",
		ammo_unit_3p = "units/weapons/player/wpn_we_quiver_t1/wpn_we_deus_arrow_02_3p",
		description = "we_deus_01_skin_02_runed_description",
		display_name = "we_deus_01_skin_02_runed_name",
		display_unit = "units/weapons/weapon_display/display_bow",
		hud_icon = "weapon_generic_icon_bow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_we_moonfire_t2_runed",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_we_deus_01/wpn_we_deus_02_runed",
		matching_item_key = "we_deus_01",
		rarity = "unique",
		required_dlc = "grass",
		slot_type = "weapon_skin",
		template = "we_deus_01_template_1",
		can_wield = {
			"we_shade",
			"we_maidenguard",
			"we_waywatcher",
		},
	},
	we_deus_01_skin_magic = {
		description = "we_deus_01_description",
		hud_icon = "weapon_generic_icon_bow",
		inventory_icon = "icon_wpn_we_moonfire_t1",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_we_deus_01/wpn_we_deus_01_magic",
		matching_item_key = "we_deus_01",
		rarity = "magic",
		required_dlc = "grass",
		slot_type = "weapon_skin",
		template = "we_deus_01_template_1",
		can_wield = {
			"we_shade",
			"we_maidenguard",
			"we_waywatcher",
			"we_thornsister",
		},
	},
	we_deus_01_magic = {
		ammo_unit = "units/weapons/player/wpn_we_quiver_t1/wpn_we_deus_arrow_01",
		ammo_unit_3p = "units/weapons/player/wpn_we_quiver_t1/wpn_we_deus_arrow_01_3p",
		description = "we_deus_01_magic_description",
		display_name = "we_deus_01_magic_name",
		has_power_level = true,
		hud_icon = "weapon_generic_icon_bow",
		inventory_icon = "icon_wpn_we_moonfire_t1_magic",
		item_type = "we_deus_01",
		left_hand_unit = "units/weapons/player/wpn_we_deus_01/wpn_we_deus_01_magic",
		property_table_name = "ranged",
		rarity = "magic",
		required_dlc = "grass",
		required_unlock_item = "we_deus_01",
		slot_type = "ranged",
		template = "we_deus_01_template_1",
		trait_table_name = "ranged_energy",
		can_wield = {
			"we_shade",
			"we_maidenguard",
			"we_waywatcher",
		},
	},
	we_deus_02_skin_magic = {
		ammo_unit = "units/weapons/player/wpn_we_quiver_t1/wpn_we_deus_arrow_02",
		ammo_unit_3p = "units/weapons/player/wpn_we_quiver_t1/wpn_we_deus_arrow_02_3p",
		description = "we_deus_01_magic_description",
		display_name = "we_deus_01_magic_name",
		hud_icon = "weapon_generic_icon_bow",
		inventory_icon = "icon_wpn_we_moonfire_t2_magic",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_we_deus_02/wpn_we_deus_02_magic",
		matching_item_key = "we_deus_01",
		rarity = "magic",
		required_dlc = "grass",
		required_unlock_item = "we_deus_01",
		slot_type = "weapon_skin",
		template = "we_deus_01_template_1",
		can_wield = {
			"we_shade",
			"we_maidenguard",
			"we_waywatcher",
		},
	},
	we_deus_01_skin_03 = {
		ammo_unit = "units/weapons/player/wpn_we_quiver_t1/wpn_we_deus_arrow_01",
		ammo_unit_3p = "units/weapons/player/wpn_we_quiver_t1/wpn_we_deus_arrow_01_3p",
		description = "we_deus_01_skin_03_description",
		display_name = "we_deus_01_skin_03_name",
		display_unit = "units/weapons/weapon_display/display_bow",
		hud_icon = "weapon_generic_icon_bow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_we_moonfire_t3",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_we_deus_03/wpn_we_deus_03",
		matching_item_key = "we_deus_01",
		rarity = "exotic",
		required_dlc = "grass",
		slot_type = "weapon_skin",
		template = "we_deus_01_template_1",
		can_wield = {
			"we_shade",
			"we_maidenguard",
			"we_waywatcher",
		},
	},
	we_deus_01_skin_03_runed = {
		ammo_unit = "units/weapons/player/wpn_we_quiver_t1/wpn_we_deus_arrow_01",
		ammo_unit_3p = "units/weapons/player/wpn_we_quiver_t1/wpn_we_deus_arrow_01_3p",
		description = "we_deus_01_skin_03_runed_description",
		display_name = "we_deus_01_skin_03_runed_name",
		display_unit = "units/weapons/weapon_display/display_bow",
		hud_icon = "weapon_generic_icon_bow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_we_moonfire_t3_runed",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_we_deus_03/wpn_we_deus_03_runed",
		matching_item_key = "we_deus_01",
		rarity = "unique",
		required_dlc = "grass",
		slot_type = "weapon_skin",
		template = "we_deus_01_template_1",
		can_wield = {
			"we_shade",
			"we_maidenguard",
			"we_waywatcher",
		},
	},
	bw_deus_01 = {
		description = "bw_deus_01_description",
		display_name = "bw_deus_01_name",
		has_power_level = true,
		hud_icon = "weapon_generic_icon_staff_5",
		inventory_icon = "icon_wpn_brw_magmastaff_t1",
		item_type = "bw_deus_01",
		left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
		property_table_name = "ranged",
		rarity = "plentiful",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_bw_deus_01/wpn_bw_deus_01",
		skin_combination_table = "bw_deus_01_skins",
		slot_type = "ranged",
		template = "bw_deus_01_template_1",
		trait_table_name = "ranged_heat",
		can_wield = {
			"bw_scholar",
			"bw_adept",
			"bw_unchained",
		},
	},
	bw_deus_01_skin = {
		base_skin_item = true,
		description = "bw_deus_01_skin_01_description",
		display_name = "bw_deus_01_skin_01_name",
		information_text = "information_weapon_skin",
		item_type = "weapon_skin",
		matching_item_key = "bw_deus_01",
		rarity = "plentiful",
		slot_type = "weapon_skin",
		can_wield = {
			"bw_scholar",
			"bw_adept",
			"bw_unchained",
		},
	},
	bw_deus_01_skin_01 = {
		description = "bw_deus_01_skin_01_description",
		display_name = "bw_deus_01_skin_01_name",
		hud_icon = "weapon_generic_icon_staff_3",
		inventory_icon = "icon_wpn_brw_magmastaff_t1",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
		matching_item_key = "bw_deus_01",
		rarity = "plentiful",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_bw_deus_01/wpn_bw_deus_01",
		slot_type = "weapon_skin",
		template = "bw_deus_01_template",
		can_wield = {
			"bw_scholar",
			"bw_adept",
			"bw_unchained",
		},
	},
	bw_deus_01_skin_02 = {
		description = "bw_deus_01_skin_02_description",
		display_name = "bw_deus_01_skin_02_name",
		display_unit = "units/weapons/weapon_display/display_staff",
		hud_icon = "weapon_generic_icon_staff_5",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_brw_magmastaff_t2",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
		matching_item_key = "bw_deus_01",
		rarity = "exotic",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_bw_deus_02/wpn_bw_deus_02",
		slot_type = "weapon_skin",
		template = "bw_deus_01_template_1",
		can_wield = {
			"bw_scholar",
			"bw_adept",
			"bw_unchained",
		},
		right_hand_unit_override = {
			bw_necromancer = "units/weapons/player/wpn_bw_deus_02/wpn_bw_deus_02_baelfire",
		},
	},
	bw_deus_01_skin_01_runed = {
		description = "bw_deus_01_skin_01_runed_description",
		display_name = "bw_deus_01_skin_01_runed_name",
		display_unit = "units/weapons/weapon_display/display_staff",
		hud_icon = "weapon_generic_icon_staff_5",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_brw_magmastaff_t1_runed",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
		matching_item_key = "bw_deus_01",
		rarity = "unique",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_bw_deus_01/wpn_bw_deus_01_runed",
		slot_type = "weapon_skin",
		template = "bw_deus_01_template_1",
		can_wield = {
			"bw_scholar",
			"bw_adept",
			"bw_unchained",
		},
	},
	bw_deus_01_skin_02_runed = {
		description = "bw_deus_01_skin_02_runed_description",
		display_name = "bw_deus_01_skin_02_runed_name",
		display_unit = "units/weapons/weapon_display/display_staff",
		hud_icon = "weapon_generic_icon_staff_5",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_brw_magmastaff_t2_runed",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
		matching_item_key = "bw_deus_01",
		rarity = "unique",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_bw_deus_02/wpn_bw_deus_02_runed",
		slot_type = "weapon_skin",
		template = "bw_deus_01_template_1",
		can_wield = {
			"bw_scholar",
			"bw_adept",
			"bw_unchained",
		},
		right_hand_unit_override = {
			bw_necromancer = "units/weapons/player/wpn_bw_deus_02/wpn_bw_deus_02_runed_baelfire",
		},
	},
	bw_deus_01_skin_magic = {
		description = "bw_deus_01_magic_description",
		hud_icon = "weapon_generic_icon_staff_3",
		inventory_icon = "icon_wpn_brw_magmastaff_t1",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
		matching_item_key = "bw_deus_01",
		rarity = "magic",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_bw_deus_01/wpn_bw_deus_01_magic",
		slot_type = "weapon_skin",
		template = "bw_deus_01_template",
		can_wield = {
			"bw_scholar",
			"bw_adept",
			"bw_unchained",
		},
	},
	bw_deus_02_skin_magic = {
		description = "bw_deus_01_magic_description",
		hud_icon = "weapon_generic_icon_staff_3",
		inventory_icon = "icon_wpn_brw_magmastaff_t2",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
		matching_item_key = "bw_deus_01",
		rarity = "magic",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_bw_deus_02/wpn_bw_deus_02_magic",
		slot_type = "weapon_skin",
		template = "bw_deus_01_template",
		can_wield = {
			"bw_scholar",
			"bw_adept",
			"bw_unchained",
		},
		right_hand_unit_override = {
			bw_necromancer = "units/weapons/player/wpn_bw_deus_02/wpn_bw_deus_02_magic_baelfire",
		},
	},
	bw_deus_01_magic = {
		description = "bw_deus_01_magic_description",
		display_name = "bw_deus_01_magic_name",
		has_power_level = true,
		hud_icon = "weapon_generic_icon_staff_5",
		inventory_icon = "icon_wpn_brw_magmastaff_t2_magic",
		item_type = "bw_deus_01",
		left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
		property_table_name = "ranged",
		rarity = "magic",
		required_dlc = "grass",
		required_unlock_item = "bw_deus_01",
		right_hand_unit = "units/weapons/player/wpn_bw_deus_02/wpn_bw_deus_02_magic",
		slot_type = "ranged",
		template = "bw_deus_01_template_1",
		trait_table_name = "ranged_heat",
		can_wield = {
			"bw_scholar",
			"bw_adept",
			"bw_unchained",
		},
		right_hand_unit_override = {
			bw_necromancer = "units/weapons/player/wpn_bw_deus_02/wpn_bw_deus_02_magic_baelfire",
		},
	},
	bw_deus_01_skin_03 = {
		description = "bw_deus_01_skin_03_description",
		display_name = "bw_deus_01_skin_03_name",
		display_unit = "units/weapons/weapon_display/display_staff",
		hud_icon = "weapon_generic_icon_staff_5",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_brw_magmastaff_t3",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
		matching_item_key = "bw_deus_01",
		rarity = "exotic",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_bw_deus_03/wpn_bw_deus_03",
		slot_type = "weapon_skin",
		template = "bw_deus_01_template_1",
		can_wield = {
			"bw_scholar",
			"bw_adept",
			"bw_unchained",
		},
	},
	bw_deus_01_skin_03_runed = {
		description = "bw_deus_01_skin_03_runed_description",
		display_name = "bw_deus_01_skin_03_runed_name",
		display_unit = "units/weapons/weapon_display/display_staff",
		hud_icon = "weapon_generic_icon_staff_5",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_brw_magmastaff_t3_runed",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
		matching_item_key = "bw_deus_01",
		rarity = "unique",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_bw_deus_03/wpn_bw_deus_03_runed",
		slot_type = "weapon_skin",
		template = "bw_deus_01_template_1",
		can_wield = {
			"bw_scholar",
			"bw_adept",
			"bw_unchained",
		},
	},
	wh_deus_01 = {
		description = "wh_deus_01_description",
		display_name = "wh_deus_01_name",
		has_power_level = true,
		hud_icon = "weapon_generic_icon_fencing_sword",
		inventory_icon = "icon_wpn_emp_duckfoot_t1",
		item_type = "wh_deus_01",
		left_hand_unit = "units/weapons/player/wpn_wh_deus_01/wpn_wh_deus_01",
		property_table_name = "ranged",
		rarity = "plentiful",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_wh_deus_01/wpn_wh_deus_01",
		skin_combination_table = "wh_deus_01_skins",
		slot_type = "ranged",
		template = "wh_deus_01_template_1",
		trait_table_name = "ranged_ammo",
		can_wield = {
			"wh_bountyhunter",
			"wh_captain",
			"wh_zealot",
		},
	},
	wh_deus_01_skin = {
		base_skin_item = true,
		description = "wh_deus_01_skin_01_description",
		display_name = "wh_deus_01_skin_01_name",
		information_text = "information_weapon_skin",
		item_type = "weapon_skin",
		matching_item_key = "wh_deus_01",
		rarity = "plentiful",
		slot_type = "weapon_skin",
		can_wield = {
			"wh_bountyhunter",
			"wh_captain",
			"wh_zealot",
		},
	},
	wh_deus_01_skin_01 = {
		description = "wh_deus_01_skin_01_description",
		display_name = "wh_deus_01_skin_01_name",
		hud_icon = "weapon_generic_icon_bow",
		inventory_icon = "icon_wpn_emp_duckfoot_t1",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_wh_deus_01/wpn_wh_deus_01",
		matching_item_key = "wh_deus_01",
		rarity = "plentiful",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_wh_deus_01/wpn_wh_deus_01",
		slot_type = "weapon_skin",
		template = "wh_deus_01_template_1",
		can_wield = {
			"wh_bountyhunter",
			"wh_captain",
			"wh_zealot",
		},
	},
	wh_deus_01_skin_02 = {
		description = "wh_deus_01_skin_02_description",
		display_name = "wh_deus_01_skin_02_name",
		display_unit = "units/weapons/weapon_display/display_pistols",
		hud_icon = "weapon_generic_icon_bow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_emp_duckfoot_t2",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_wh_deus_02/wpn_wh_deus_02",
		matching_item_key = "wh_deus_01",
		rarity = "exotic",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_wh_deus_02/wpn_wh_deus_02",
		slot_type = "weapon_skin",
		template = "wh_deus_01_template_1",
		can_wield = {
			"wh_bountyhunter",
			"wh_captain",
			"wh_zealot",
		},
	},
	wh_deus_01_skin_01_runed = {
		description = "wh_deus_01_skin_01_runed_description",
		display_name = "wh_deus_01_skin_01_runed_name",
		display_unit = "units/weapons/weapon_display/display_pistols",
		hud_icon = "weapon_generic_icon_bow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_emp_duckfoot_t1_runed",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_wh_deus_01/wpn_wh_deus_01_runed",
		matching_item_key = "wh_deus_01",
		rarity = "unique",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_wh_deus_01/wpn_wh_deus_01_runed",
		slot_type = "weapon_skin",
		template = "wh_deus_01_template_1",
		can_wield = {
			"wh_bountyhunter",
			"wh_captain",
			"wh_zealot",
		},
	},
	wh_deus_01_skin_02_runed = {
		description = "wh_deus_01_skin_02_runed_description",
		display_name = "wh_deus_01_skin_02_runed_name",
		display_unit = "units/weapons/weapon_display/display_pistols",
		hud_icon = "weapon_generic_icon_bow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_emp_duckfoot_t2_runed",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_wh_deus_02/wpn_wh_deus_02_runed",
		matching_item_key = "wh_deus_01",
		rarity = "unique",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_wh_deus_02/wpn_wh_deus_02_runed",
		slot_type = "weapon_skin",
		template = "wh_deus_01_template_1",
		can_wield = {
			"wh_bountyhunter",
			"wh_captain",
			"wh_zealot",
		},
	},
	wh_deus_01_magic = {
		description = "wh_deus_01_magic_description",
		display_name = "wh_deus_01_magic_name",
		has_power_level = true,
		hud_icon = "weapon_generic_icon_bow",
		inventory_icon = "icon_wpn_emp_duckfoot_t2_magic",
		item_type = "wh_deus_01",
		left_hand_unit = "units/weapons/player/wpn_wh_deus_02/wpn_wh_deus_02_magic",
		property_table_name = "ranged",
		rarity = "magic",
		required_dlc = "grass",
		required_unlock_item = "wh_deus_01",
		right_hand_unit = "units/weapons/player/wpn_wh_deus_02/wpn_wh_deus_02_magic",
		slot_type = "ranged",
		template = "wh_deus_01_template_1",
		trait_table_name = "ranged_ammo",
		can_wield = {
			"wh_bountyhunter",
			"wh_captain",
			"wh_zealot",
		},
	},
	wh_deus_01_skin_03 = {
		description = "wh_deus_01_skin_03_description",
		display_name = "wh_deus_01_skin_03_name",
		display_unit = "units/weapons/weapon_display/display_pistols",
		hud_icon = "weapon_generic_icon_bow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_emp_duckfoot_t3",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_wh_deus_03/wpn_wh_deus_03",
		matching_item_key = "wh_deus_01",
		rarity = "exotic",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_wh_deus_03/wpn_wh_deus_03",
		slot_type = "weapon_skin",
		template = "wh_deus_01_template_1",
		can_wield = {
			"wh_bountyhunter",
			"wh_captain",
			"wh_zealot",
		},
	},
	wh_deus_01_skin_03_runed = {
		description = "wh_deus_01_skin_03_runed_description",
		display_name = "wh_deus_01_skin_03_runed_name",
		display_unit = "units/weapons/weapon_display/display_pistols",
		hud_icon = "weapon_generic_icon_bow",
		information_text = "information_weapon_skin",
		inventory_icon = "icon_wpn_emp_duckfoot_t3_runed",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_wh_deus_03/wpn_wh_deus_03_runed",
		matching_item_key = "wh_deus_01",
		rarity = "unique",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_wh_deus_03/wpn_wh_deus_03_runed",
		slot_type = "weapon_skin",
		template = "wh_deus_01_template_1",
		can_wield = {
			"wh_bountyhunter",
			"wh_captain",
			"wh_zealot",
		},
	},
	wh_deus_02_skin_magic = {
		description = "wh_deus_01_magic_desciption",
		hud_icon = "weapon_generic_icon_bow",
		inventory_icon = "icon_wpn_emp_duckfoot_t1",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_wh_deus_02/wpn_wh_deus_02_magic",
		matching_item_key = "wh_deus_01",
		rarity = "magic",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_wh_deus_02/wpn_wh_deus_02_magic",
		slot_type = "weapon_skin",
		template = "wh_deus_01_template_1",
		can_wield = {
			"wh_bountyhunter",
			"wh_captain",
			"wh_zealot",
		},
	},
	wh_deus_01_skin_magic = {
		description = "wh_deus_01_magic_desciption",
		hud_icon = "weapon_generic_icon_bow",
		inventory_icon = "icon_wpn_emp_duckfoot_t1",
		item_type = "weapon_skin",
		left_hand_unit = "units/weapons/player/wpn_wh_deus_01/wpn_wh_deus_01_magic",
		matching_item_key = "wh_deus_01",
		rarity = "magic",
		required_dlc = "grass",
		right_hand_unit = "units/weapons/player/wpn_wh_deus_01/wpn_wh_deus_01_magic",
		slot_type = "weapon_skin",
		template = "wh_deus_01_template_1",
		can_wield = {
			"wh_bountyhunter",
			"wh_captain",
			"wh_zealot",
		},
	},
	wpn_deus_relic_01 = {
		gamepad_hud_icon = "options_button_icon_event",
		hud_icon = "options_button_icon_event",
		inventory_icon = "icons_placeholder",
		item_type = "inventory_item",
		rarity = "plentiful",
		right_hand_unit = "units/weapons/player/wpn_deus_relic_01/wpn_deus_relic_01",
		slot_type = "healthkit",
		temporary_template = "deus_relic",
		can_wield = CanWieldAllItemTemplates,
	},
	potion_liquid_bravado_01 = {
		description = "description_potion_liquid_bravado_01",
		description_type = "potion",
		gamepad_hud_icon = "hud_inventory_icon_deuspotion_LiquidBravado_02",
		hud_icon = "hud_inventory_icon_deuspotion_LiquidBravado",
		inventory_icon = "icons_placeholder",
		item_received_icon = "killfeed_icon_deuspotion",
		item_type = "potion",
		left_hand_unit = "units/weapons/player/wpn_deus_potion_01/wpn_deus_potion_01",
		rarity = "plentiful",
		slot_type = "potion",
		temporary_template = "liquid_bravado_potion",
		can_wield = CanWieldAllItemTemplates,
		description_values = {
			{
				value_type = "time",
				value = MorrisBuffTweakData.liquid_bravado_potion.duration,
			},
		},
	},
	potion_vampiric_draught_01 = {
		description = "description_potion_vampiric_draught_01",
		description_type = "potion",
		gamepad_hud_icon = "hud_inventory_icon_deuspotion_VampiricDraught_02",
		hud_icon = "hud_inventory_icon_deuspotion_VampiricDraught",
		inventory_icon = "icons_placeholder",
		item_received_icon = "killfeed_icon_deuspotion",
		item_type = "potion",
		left_hand_unit = "units/weapons/player/wpn_deus_potion_01/wpn_deus_potion_01",
		rarity = "plentiful",
		slot_type = "potion",
		temporary_template = "vampiric_draught_potion",
		can_wield = CanWieldAllItemTemplates,
		description_values = {
			{
				value_type = "time",
				value = MorrisBuffTweakData.vampiric_draught_potion.duration,
			},
		},
	},
	potion_moot_milk_01 = {
		description = "description_potion_moot_milk_01",
		description_type = "potion",
		gamepad_hud_icon = "hud_inventory_icon_deuspotion_MootMilk_02",
		hud_icon = "hud_inventory_icon_deuspotion_MootMilk",
		inventory_icon = "icons_placeholder",
		item_received_icon = "killfeed_icon_deuspotion",
		item_type = "potion",
		left_hand_unit = "units/weapons/player/wpn_deus_potion_01/wpn_deus_potion_01",
		rarity = "plentiful",
		slot_type = "potion",
		temporary_template = "moot_milk_potion",
		can_wield = CanWieldAllItemTemplates,
		description_values = {
			{
				value_type = "time",
				value = MorrisBuffTweakData.moot_milk_potion.duration,
			},
		},
	},
	potion_friendly_murderer_01 = {
		description = "description_potion_friendly_murderer_01",
		description_type = "potion",
		gamepad_hud_icon = "hud_inventory_icon_deuspotion_FriendlyMurderer_02",
		hud_icon = "hud_inventory_icon_deuspotion_FriendlyMurderer",
		inventory_icon = "icons_placeholder",
		item_received_icon = "killfeed_icon_deuspotion",
		item_type = "potion",
		left_hand_unit = "units/weapons/player/wpn_deus_potion_01/wpn_deus_potion_01",
		rarity = "plentiful",
		slot_type = "potion",
		temporary_template = "friendly_murderer_potion",
		can_wield = CanWieldAllItemTemplates,
		description_values = {
			{
				value_type = "time",
				value = MorrisBuffTweakData.friendly_murderer_potion.duration,
			},
		},
	},
	potion_killer_in_the_shadows_01 = {
		description = "description_potion_killer_in_the_shadows_01",
		description_type = "potion",
		gamepad_hud_icon = "hud_inventory_icon_deuspotion_KillerInTheShadows_02",
		hud_icon = "hud_inventory_icon_deuspotion_KillerInTheShadows",
		inventory_icon = "icons_placeholder",
		item_received_icon = "killfeed_icon_deuspotion",
		item_type = "potion",
		left_hand_unit = "units/weapons/player/wpn_deus_potion_01/wpn_deus_potion_01",
		rarity = "plentiful",
		slot_type = "potion",
		temporary_template = "killer_in_the_shadows_potion",
		can_wield = CanWieldAllItemTemplates,
		description_values = {
			{
				value_type = "time",
				value = MorrisBuffTweakData.killer_in_the_shadows_potion.duration,
			},
		},
	},
	potion_pockets_full_of_bombs_01 = {
		description = "description_potion_pockets_full_of_bombs_01",
		description_type = "potion",
		gamepad_hud_icon = "hud_inventory_icon_deuspotion_PocketsFullOfBombs_02",
		hud_icon = "hud_inventory_icon_deuspotion_PocketsFullOfBombs",
		inventory_icon = "icons_placeholder",
		item_received_icon = "killfeed_icon_deuspotion",
		item_type = "potion",
		left_hand_unit = "units/weapons/player/wpn_deus_potion_01/wpn_deus_potion_01",
		rarity = "plentiful",
		slot_type = "potion",
		temporary_template = "pockets_full_of_bombs_potion",
		can_wield = CanWieldAllItemTemplates,
		description_values = {
			{
				value_type = "time",
				value = MorrisBuffTweakData.pockets_full_of_bombs_potion.duration,
			},
		},
	},
	potion_hold_my_beer_01 = {
		description = "description_potion_hold_my_beer_01",
		description_type = "potion",
		gamepad_hud_icon = "hud_inventory_icon_deuspotion_HoldMyBeer_02",
		hud_icon = "hud_inventory_icon_deuspotion_HoldMyBeer",
		inventory_icon = "icons_placeholder",
		item_received_icon = "killfeed_icon_deuspotion",
		item_type = "potion",
		left_hand_unit = "units/weapons/player/wpn_deus_potion_01/wpn_deus_potion_01",
		rarity = "plentiful",
		slot_type = "potion",
		temporary_template = "hold_my_beer_potion",
		can_wield = CanWieldAllItemTemplates,
		description_values = {
			{
				value_type = "time",
				value = MorrisBuffTweakData.hold_my_beer_potion.duration,
			},
		},
	},
	potion_poison_proof_01 = {
		description = "description_potion_poison_proof_01",
		description_type = "potion",
		gamepad_hud_icon = "hud_inventory_icon_deuspotion_PoisonProof_02",
		hud_icon = "hud_inventory_icon_deuspotion_PoisonProof",
		inventory_icon = "icons_placeholder",
		item_received_icon = "killfeed_icon_deuspotion",
		item_type = "potion",
		left_hand_unit = "units/weapons/player/wpn_deus_potion_01/wpn_deus_potion_01",
		rarity = "plentiful",
		slot_type = "potion",
		temporary_template = "poison_proof_potion",
		can_wield = CanWieldAllItemTemplates,
		description_values = {
			{
				value_type = "time",
				value = MorrisBuffTweakData.poison_proof_potion.duration,
			},
		},
	},
	deus_rally_flag = {
		description = "description_deus_rally_flag_01",
		description_type = "potion",
		gamepad_hud_icon = "hud_inventory_icon_jadecenser_02",
		hud_icon = "hud_inventory_icon_jadecenser",
		inventory_icon = "hud_inventory_icon_jadecenser",
		item_received_icon = "killfeed_icon_jadecenser",
		item_type = "potion",
		left_hand_unit = "units/weapons/player/wpn_deus_folded_rally_flag_01/wpn_deus_folded_rally_flag_01",
		rarity = "plentiful",
		slot_type = "potion",
		temporary_template = "deus_rally_flag",
		can_wield = CanWieldAllItemTemplates,
	},
	holy_hand_grenade = {
		description = "description_deus_holy_hand_grenade",
		description_type = "grenade",
		gamepad_hud_icon = "hud_inventory_icon_holybomb_02",
		hud_icon = "hud_inventory_icon_holybomb",
		inventory_icon = "hud_inventory_icon_holybomb",
		item_received_icon = "killfeed_icon_holybomb",
		item_type = "grenade",
		left_hand_unit = "units/weapons/player/wpn_emp_holy_hand_grenade_01_t1/wpn_emp_holy_hand_grenade_lighter_01_t1",
		rarity = "plentiful",
		right_hand_unit = "units/weapons/player/wpn_emp_holy_hand_grenade_01_t1/wpn_emp_holy_hand_grenade_01_t1",
		slot_type = "grenade",
		temporary_template = "holy_hand_grenade",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_khorne = {
		description = "frame_deus_portrait_khorne_description",
		display_name = "frame_deus_portrait_khorne_name",
		hud_icon = "deus_portrait_khorne",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_khorne",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_khorne",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_lileath_1 = {
		description = "frame_deus_portrait_lileath_1_description",
		display_name = "frame_deus_portrait_lileath_1_name",
		hud_icon = "deus_portrait_lileath_1",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_lileath_1",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_lileath_1",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_lileath_2 = {
		description = "frame_deus_portrait_lileath_2_description",
		display_name = "frame_deus_portrait_lileath_2_name",
		hud_icon = "deus_portrait_lileath_2",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_lileath_2",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_lileath_2",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_lileath_3 = {
		description = "frame_deus_portrait_lileath_3_description",
		display_name = "frame_deus_portrait_lileath_3_name",
		hud_icon = "deus_portrait_lileath_3",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_lileath_3",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_lileath_3",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_myrmidia_1 = {
		description = "frame_deus_portrait_myrmidia_1_description",
		display_name = "frame_deus_portrait_myrmidia_1_name",
		hud_icon = "deus_portrait_myrmidia_1",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_myrmidia_1",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_myrmidia_1",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_myrmidia_2 = {
		description = "frame_deus_portrait_myrmidia_2_description",
		display_name = "frame_deus_portrait_myrmidia_2_name",
		hud_icon = "deus_portrait_myrmidia_2",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_myrmidia_2",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_myrmidia_2",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_myrmidia_3 = {
		description = "frame_deus_portrait_myrmidia_3_description",
		display_name = "frame_deus_portrait_myrmidia_3_name",
		hud_icon = "deus_portrait_myrmidia_3",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_myrmidia_3",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_myrmidia_3",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_nurgle = {
		description = "frame_deus_portrait_nurgle_description",
		display_name = "frame_deus_portrait_nurgle_name",
		hud_icon = "deus_portrait_nurgle",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_nurgle",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_nurgle",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_sigmar_1 = {
		description = "frame_deus_portrait_sigmar_1_description",
		display_name = "frame_deus_portrait_sigmar_1_name",
		hud_icon = "deus_portrait_sigmar_1",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_sigmar_1",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_sigmar_1",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_sigmar_2 = {
		description = "frame_deus_portrait_sigmar_2_description",
		display_name = "frame_deus_portrait_sigmar_2_name",
		hud_icon = "deus_portrait_sigmar_2",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_sigmar_2",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_sigmar_2",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_sigmar_3 = {
		description = "frame_deus_portrait_sigmar_3_description",
		display_name = "frame_deus_portrait_sigmar_3_name",
		hud_icon = "deus_portrait_sigmar_3",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_sigmar_3",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_sigmar_3",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_slaanesh = {
		description = "frame_deus_portrait_slaanesh_description",
		display_name = "frame_deus_portrait_slaanesh_name",
		hud_icon = "deus_portrait_slaanesh",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_slaanesh",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_slaanesh",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_taal_1 = {
		description = "frame_deus_portrait_taal_1_description",
		display_name = "frame_deus_portrait_taal_1_name",
		hud_icon = "deus_portrait_taal_1",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_taal_1",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_taal_1",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_taal_2 = {
		description = "frame_deus_portrait_taal_2_description",
		display_name = "frame_deus_portrait_taal_2_name",
		hud_icon = "deus_portrait_taal_2",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_taal_2",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_taal_2",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_taal_3 = {
		description = "frame_deus_portrait_taal_3_description",
		display_name = "frame_deus_portrait_taal_3_name",
		hud_icon = "deus_portrait_taal_3",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_taal_3",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_taal_3",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_tzeentch = {
		description = "frame_deus_portrait_tzeentch_description",
		display_name = "frame_deus_portrait_tzeentch_name",
		hud_icon = "deus_portrait_tzeentch",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_tzeentch",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_tzeentch",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_valaya_1 = {
		description = "frame_deus_portrait_valaya_1_description",
		display_name = "frame_deus_portrait_valaya_1_name",
		hud_icon = "deus_portrait_valaya_1",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_valaya_1",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_valaya_1",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_valaya_2 = {
		description = "frame_deus_portrait_valaya_2_description",
		display_name = "frame_deus_portrait_valaya_2_name",
		hud_icon = "deus_portrait_valaya_2",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_valaya_2",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_valaya_2",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_valaya_3 = {
		description = "frame_deus_portrait_valaya_3_description",
		display_name = "frame_deus_portrait_valaya_3_name",
		hud_icon = "deus_portrait_valaya_3",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_valaya_3",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_valaya_3",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_citadel = {
		description = "frame_deus_portrait_citadel_description",
		display_name = "frame_deus_portrait_citadel_name",
		hud_icon = "deus_portrait_citadel",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_citadel",
		item_type = "frame",
		rarity = "promo",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_citadel",
		can_wield = CanWieldAllItemTemplates,
	},
	frame_deus_portrait_chaos_gods = {
		description = "frame_deus_portrait_chaos_gods_description",
		display_name = "frame_deus_portrait_chaos_gods_name",
		hud_icon = "deus_portrait_dlc",
		information_text = "information_text_frame",
		inventory_icon = "deus_icon_portrait_dlc",
		item_type = "frame",
		rarity = "promo",
		required_dlc = "grass",
		slot_type = "frame",
		temporary_template = "frame_deus_portrait_chaos_gods",
		can_wield = CanWieldAllItemTemplates,
	},
	shilling_bag_grass = {
		description = "shilling_bag_100_description",
		display_name = "shilling_bag_100_name",
		information_text = "information_text_shilling",
		inventory_icon = "icon_shillings_06",
		item_type = "chips",
		rarity = "common",
		slot_type = "chips",
		can_wield = CanWieldAllItemTemplates,
		bundle = {
			BundledVirtualCurrencies = {
				SM = 150,
			},
		},
	},
}

table.merge(ItemMasterList, item_master_list)

if DLCSettings.cog then
	UpdateItemMasterList({
		"dr_deus_01",
		"dr_deus_01_magic",
	}, "dr_engineer")
end
