-- chunkname: @scripts/settings/equipment/item_master_list_cosmetics_2024_q2.lua

ItemMasterList.skaven_gutter_runner_skin_1001 = {
	description = "description_skaven_gutter_runner_skin_1001",
	display_name = "display_name_skaven_gutter_runner_skin_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_gutter_runner_skin_1001",
	item_type = "skin",
	linked_weapon = "vs_gutter_runner_claws_1001",
	name = "skaven_gutter_runner_skin_1001",
	parent = "skaven_gutter_runner_skin_1001_bundle",
	rarity = "unique",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 200,
	steam_store_hidden = true,
	temporary_template = "skaven_gutter_runner_skin_1001",
	can_wield = {
		"vs_gutter_runner",
	},
}
ItemMasterList.skaven_pack_master_skin_1001 = {
	description = "description_skaven_pack_master_skin_1001",
	display_name = "display_name_skaven_pack_master_skin_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_packmaster_skin_1001",
	item_type = "skin",
	linked_weapon = "vs_packmaster_claw_skin_1001",
	name = "skaven_pack_master_skin_1001",
	parent = "skaven_packmaster_skin_1001_bundle",
	rarity = "unique",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 198,
	steam_store_hidden = true,
	temporary_template = "skaven_pack_master_skin_1001",
	can_wield = {
		"vs_packmaster",
	},
}
ItemMasterList.skaven_wind_globadier_skin_1001 = {
	description = "description_skaven_wind_globadier_skin_1001",
	display_name = "display_name_skaven_wind_globadier_skin_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_globadier_skin_1001",
	item_type = "skin",
	linked_weapon = "vs_poison_wind_globadier_orb_1001",
	name = "skaven_wind_globadier_skin_1001",
	parent = "skaven_globadier_skin_1001_bundle",
	rarity = "unique",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 202,
	steam_store_hidden = true,
	temporary_template = "skaven_wind_globadier_skin_1001",
	can_wield = {
		"vs_poison_wind_globadier",
	},
}
ItemMasterList.skaven_warpfire_thrower_skin_1001 = {
	description = "description_skaven_warpfire_thrower_skin_1001",
	display_name = "display_name_skaven_warpfire_thrower_skin_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_warpfire_thrower_skin_1001",
	item_type = "skin",
	linked_weapon = "vs_warpfire_thrower_gun_skin_1001",
	name = "skaven_warpfire_thrower_skin_1001",
	parent = "skaven_warpfire_thrower_skin_1001_bundle",
	rarity = "unique",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 194,
	steam_store_hidden = true,
	temporary_template = "skaven_warpfire_thrower_skin_1001",
	can_wield = {
		"vs_warpfire_thrower",
	},
}
ItemMasterList.skaven_ratling_gunner_skin_1001 = {
	description = "description_skaven_ratling_gunner_skin_1001",
	display_name = "display_name_skaven_ratling_gunner_skin_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_ratling_gunner_skin_1001",
	item_type = "skin",
	linked_weapon = "vs_ratling_gunner_gun_1001",
	name = "skaven_ratling_gunner_skin_1001",
	parent = "skaven_ratling_gunner_skin_1001_bundle",
	rarity = "unique",
	selection = "versus",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 196,
	steam_store_hidden = true,
	temporary_template = "skaven_ratling_gunner_skin_1001",
	can_wield = {
		"vs_ratling_gunner",
	},
}
ItemMasterList.vs_gutter_runner_claws_1001 = {
	description = "description_vs_gutter_runner_claws_1001",
	display_name = "display_name_vs_gutter_runner_claws_1001",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icons_placeholder",
	item_type = "we_dual_wield_daggers",
	left_hand_unit = "units/weapons/player/dark_pact/wpn_skaven_gutter_runner_claws_1001/wpn_skaven_gutter_runner_claws_left_1001",
	parent = "skaven_gutter_runner_skin_1001_bundle",
	property_table_name = "melee",
	rarity = "default",
	right_hand_unit = "units/weapons/player/dark_pact/wpn_skaven_gutter_runner_claws_1001/wpn_skaven_gutter_runner_claws_right_1001",
	selection = "versus",
	slot_type = "melee",
	steam_itemdefid = 201,
	steam_store_hidden = true,
	template = "vs_gutter_runner_claws",
	trait_table_name = "melee",
	can_wield = {
		"vs_gutter_runner",
	},
	mechanisms = {
		"versus",
	},
}
ItemMasterList.vs_packmaster_claw_skin_1001 = {
	description = "description_vs_packmaster_claw_1001",
	display_name = "display_name_vs_packmaster_claw_1001",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icons_placeholder",
	item_type = "we_spear",
	parent = "skaven_packmaster_skin_1001_bundle",
	property_table_name = "melee",
	rarity = "default",
	right_hand_unit = "units/weapons/player/dark_pact/wpn_skaven_packmaster_claw_1001/wpn_skaven_packmaster_claw_1001",
	selection = "versus",
	slot_type = "melee",
	steam_itemdefid = 199,
	steam_store_hidden = true,
	template = "vs_packmaster_claw",
	trait_table_name = "melee",
	can_wield = {
		"vs_packmaster",
	},
	mechanisms = {
		"versus",
	},
}
ItemMasterList.vs_warpfire_thrower_gun_skin_1001 = {
	description = "description_vs_warpfire_thrower_gun_1001",
	display_name = "display_name_vs_warpfire_thrower_gun_1001",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icons_placeholder",
	item_type = "dr_drakegun",
	left_hand_unit = "units/weapons/player/dark_pact/wpn_skaven_warpfiregun_1001/wpn_skaven_warpfiregun_1001",
	parent = "skaven_warpfire_thrower_skin_1001_bundle",
	property_table_name = "melee",
	rarity = "default",
	selection = "versus",
	slot_type = "melee",
	steam_itemdefid = 195,
	steam_store_hidden = true,
	template = "vs_warpfire_thrower_gun",
	trait_table_name = "melee",
	can_wield = {
		"vs_warpfire_thrower",
	},
	mechanisms = {
		"versus",
	},
}
ItemMasterList.vs_poison_wind_globadier_orb_1001 = {
	description = "description_vs_poison_wind_globadier_orb_1001",
	display_name = "display_name_vs_poison_wind_globadier_orb_1001",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icons_placeholder",
	item_type = "dr_1h_axes",
	parent = "skaven_globadier_skin_1001_bundle",
	property_table_name = "melee",
	rarity = "default",
	right_hand_unit = "units/weapons/player/dark_pact/wpn_poison_wind_globe_1001/wpn_poison_wind_globe_1001",
	selection = "versus",
	slot_type = "melee",
	steam_itemdefid = 203,
	steam_store_hidden = true,
	template = "vs_poison_wind_globadier_orb",
	trait_table_name = "melee",
	can_wield = {
		"vs_poison_wind_globadier",
	},
	mechanisms = {
		"versus",
	},
}
ItemMasterList.vs_ratling_gunner_gun_1001 = {
	description = "description_vs_ratling_gunner_gun_1001",
	display_name = "display_name_vs_ratling_gunner_gun_1001",
	has_power_level = true,
	hud_icon = "hud_icon_default",
	inventory_icon = "icons_placeholder",
	item_type = "dr_drakegun",
	left_hand_unit = "units/weapons/player/dark_pact/wpn_skaven_ratlinggun_1001/wpn_skaven_ratlinggun_1001",
	parent = "skaven_ratling_gunner_skin_1001_bundle",
	property_table_name = "melee",
	rarity = "default",
	selection = "versus",
	slot_type = "melee",
	steam_itemdefid = 197,
	steam_store_hidden = true,
	template = "vs_ratling_gunner_gun",
	trait_table_name = "melee",
	can_wield = {
		"vs_ratling_gunner",
	},
	mechanisms = {
		"versus",
	},
}
ItemMasterList.skaven_warpfire_thrower_skin_1001_bundle = {
	description = "description_skaven_warpfire_thrower_skin_1001",
	display_name = "display_name_skaven_warpfire_thrower_skin_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_warpfire_thrower_skin_1001",
	item_type = "cosmetic_bundle",
	name = "skaven_warpfire_thrower_skin_1001",
	rarity = "promo",
	selection = "versus",
	slot_type = "cosmetic_bundle",
	steam_itemdefid = 844,
	temporary_template = "",
	can_wield = {
		"vs_warpfire_thrower",
	},
	bundle_contains = {},
}
ItemMasterList.skaven_ratling_gunner_skin_1001_bundle = {
	description = "description_skaven_ratling_gunner_skin_1001",
	display_name = "display_name_skaven_ratling_gunner_skin_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_ratling_gunner_skin_1001",
	item_type = "cosmetic_bundle",
	name = "skaven_ratling_gunner_skin_1001_bundle",
	rarity = "promo",
	selection = "versus",
	slot_type = "cosmetic_bundle",
	steam_itemdefid = 845,
	temporary_template = "",
	can_wield = {
		"vs_ratling_gunner",
	},
	bundle_contains = {},
}
ItemMasterList.skaven_packmaster_skin_1001_bundle = {
	description = "description_skaven_pack_master_skin_1001",
	display_name = "display_name_skaven_pack_master_skin_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_packmaster_skin_1001",
	item_type = "cosmetic_bundle",
	name = "skaven_pack_master_skin_1001",
	rarity = "promo",
	selection = "versus",
	slot_type = "cosmetic_bundle",
	steam_itemdefid = 846,
	temporary_template = "",
	can_wield = {
		"vs_packmaster",
	},
	bundle_contains = {},
}
ItemMasterList.skaven_gutter_runner_skin_1001_bundle = {
	description = "description_skaven_gutter_runner_skin_1001",
	display_name = "display_name_skaven_gutter_runner_skin_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_gutter_runner_skin_1001",
	item_type = "cosmetic_bundle",
	name = "skaven_gutter_runner_skin_1001",
	rarity = "promo",
	selection = "versus",
	slot_type = "cosmetic_bundle",
	steam_itemdefid = 847,
	temporary_template = "",
	can_wield = {
		"vs_gutter_runner",
	},
	bundle_contains = {},
}
ItemMasterList.skaven_globadier_skin_1001_bundle = {
	description = "description_skaven_wind_globadier_skin_1001",
	display_name = "display_name_skaven_wind_globadier_skin_1001",
	hud_icon = "hud_icon_default",
	information_text = "information_text_character_skin",
	inventory_icon = "skaven_globadier_skin_1001",
	item_type = "cosmetic_bundle",
	name = "skaven_wind_globadier_skin_1001",
	rarity = "promo",
	selection = "versus",
	slot_type = "cosmetic_bundle",
	steam_itemdefid = 848,
	temporary_template = "",
	can_wield = {
		"vs_poison_wind_globadier",
	},
}
ItemMasterList.skaven_skins_bundle_0001 = {
	description = "description_skaven_skins_bundle_0001",
	display_name = "display_name_skaven_skins_bundle_0001",
	hud_icon = "",
	information_text = "skaven_skins_bundle_0001",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 4700,
	product_layout = "skaven_skins_bundle_0001",
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 849,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_skaven_skins_bundle_0001",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_skaven_skins_bundle_0001",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_skaven_skins_bundle_0001",
	subtitle = "five_career_bundle_0001_subtitle",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
