-- chunkname: @scripts/settings/equipment/item_master_list_cosmetics_2022_q2.lua

ItemMasterList.scholar_hat_1003 = {
	description = "description_scholar_hat_1003",
	display_name = "display_name_scholar_hat_1003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_scholar_hat_1003",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 152,
	store_optional_skin = "skin_bw_scholar_1001",
	template = "bw_hat_no_ears_hair",
	unit = "units/beings/player/bright_wizard_scholar/headpiece/bw_s_hat_14",
	can_wield = {
		"bw_scholar",
	},
}
ItemMasterList.ironbreaker_hat_1002 = {
	description = "description_ironbreaker_hat_1002",
	display_name = "display_name_ironbreaker_hat_1002",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_ironbreaker_hat_1002",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 105,
	store_optional_skin = "skin_dr_ironbreaker_1001",
	template = "dr_helmets_hide_beard_ears_default_only",
	unit = "units/beings/player/dwarf_ranger_ironbreaker/headpiece/dr_i_hat_16",
	can_wield = {
		"dr_ironbreaker",
	},
}
ItemMasterList.huntsman_hat_1002 = {
	description = "description_huntsman_hat_1002",
	display_name = "display_name_huntsman_hat_1002",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_huntsman_hat_1002",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 150,
	store_optional_skin = "skin_es_huntsman_1001",
	template = "es_hats_no_ear",
	unit = "units/beings/player/empire_soldier_huntsman/headpiece/es_h_hat_13",
	can_wield = {
		"es_huntsman",
	},
}
ItemMasterList.zealot_hat_1007 = {
	description = "description_zealot_hat_1007",
	display_name = "display_name_zealot_hat_1007",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_zealot_hat_1007",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 157,
	store_optional_skin = "skin_wh_flagellant",
	template = "wh_z_hat_10",
	unit = "units/beings/player/witch_hunter_zealot/headpiece/wh_z_hat_10",
	can_wield = {
		"wh_zealot",
	},
}
ItemMasterList.maidenguard_hat_1002 = {
	description = "description_maidenguard_hat_1002",
	display_name = "display_name_maidenguard_hat_1002",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_maidenguard_hat_1002",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 155,
	store_optional_skin = "skin_ww_maidenguard_1001",
	template = "ww_helmet_jaw",
	unit = "units/beings/player/way_watcher_maiden_guard/headpiece/ww_mg_hat_13",
	can_wield = {
		"we_maidenguard",
	},
}
ItemMasterList.skin_bw_scholar_1001 = {
	description = "description_skin_bw_scholar_1001",
	display_name = "display_name_skin_bw_scholar_1001",
	hud_icon = "unit_frame_portrait_bright_wizard",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_bw_scholar_1001",
	item_type = "skin",
	name = "skin_bw_scholar_1001",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 153,
	store_optional_hat = "scholar_hat_1003",
	temporary_template = "skin_bw_scholar_1001",
	can_wield = {
		"bw_scholar",
	},
}
ItemMasterList.skin_dr_ironbreaker_1001 = {
	description = "description_skin_dr_ironbreaker_1001",
	display_name = "display_name_skin_dr_ironbreaker_1001",
	hud_icon = "career_dwarf_ironbreaker",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_dr_ironbreaker_1001",
	item_type = "skin",
	name = "skin_dr_ironbreaker_1001",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 154,
	store_optional_hat = "ironbreaker_hat_1002",
	temporary_template = "skin_dr_ironbreaker_1001",
	can_wield = {
		"dr_ironbreaker",
	},
}
ItemMasterList.skin_es_huntsman_1001 = {
	description = "description_skin_huntsman_1001",
	display_name = "display_name_skin_huntsman_1001",
	hud_icon = "unit_frame_portrait_empire_soldier",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_huntsman_1001",
	item_type = "skin",
	name = "skin_es_huntsman_1001",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 151,
	store_optional_hat = "huntsman_hat_1002",
	temporary_template = "skin_es_huntsman",
	can_wield = {
		"es_huntsman",
	},
}
ItemMasterList.skin_ww_maidenguard_1001 = {
	description = "description_skin_ww_maidenguard_1001",
	display_name = "display_name_skin_ww_maidenguard_1001",
	hud_icon = "unit_frame_portrait_way_watcher",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ww_maidenguard_1001",
	item_type = "skin",
	name = "skin_ww_maidenguard_1001",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 156,
	store_optional_hat = "maidenguard_hat_1002",
	temporary_template = "skin_ww_maidenguard_1001",
	can_wield = {
		"we_maidenguard",
	},
}
ItemMasterList.skin_wh_flagellant = {
	description = "description_skin_wh_flagellant",
	display_name = "skin_wh_flagellant",
	hud_icon = "unit_frame_portrait_witch_hunter",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_wh_flagellant",
	item_type = "skin",
	name = "skin_wh_flagellant",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 158,
	store_optional_hat = "zealot_hat_1007",
	temporary_template = "skin_wh_zealot",
	can_wield = {
		"wh_zealot",
	},
}
ItemMasterList.ironbreaker_bundle_0002 = {
	description = "description_ironbreaker_bundle_0002",
	discount = 99,
	display_name = "display_name_ironbreaker_bundle_0002",
	hud_icon = "",
	information_text = "description_ironbreaker_bundle_0002",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 2300,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 820,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_ironbreaker_bundle_0002",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_ironbreaker_bundle_0002",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_ironbreaker_bundle_0002",
	subtitle = "dr_ironbreaker",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.maidenguard_bundle_0002 = {
	description = "description_maidenguard_bundle_0002",
	discount = 99,
	display_name = "display_name_maidenguard_bundle_0002",
	hud_icon = "",
	information_text = "description_maidenguard_bundle_0002",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 2400,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 821,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_maidenguard_bundle_0002",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_maidenguard_bundle_0002",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_maidenguard_bundle_0002",
	subtitle = "we_maidenguard",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.huntsman_bundle_0002 = {
	description = "description_huntsman_bundle_0002",
	discount = 99,
	display_name = "display_name_huntsman_bundle_0002",
	hud_icon = "",
	information_text = "description_huntsman_bundle_0002",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 2500,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 818,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_huntsman_bundle_0002",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_huntsman_bundle_0002",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_huntsman_bundle_0002",
	subtitle = "es_huntsman",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.scholar_bundle_0002 = {
	description = "description_scholar_bundle_0002",
	discount = 99,
	display_name = "display_name_scholar_bundle_0002",
	hud_icon = "",
	information_text = "description_scholar_bundle_0002",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 2600,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 819,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_scholar_bundle_0002",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_scholar_bundle_0002",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_scholar_bundle_0002",
	subtitle = "bw_scholar",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.zealot_bundle_0002 = {
	description = "description_zealot_bundle_0002",
	discount = 99,
	display_name = "display_name_zealot_bundle_0002",
	hud_icon = "",
	information_text = "description_zealot_bundle_0002",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 2700,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 822,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_zealot_bundle_0002",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_zealot_bundle_0002",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_zealot_bundle_0002",
	subtitle = "wh_zealot",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.five_career_bundle_0004 = {
	description = "description_five_career_bundle_0004",
	display_name = "display_name_five_career_bundle_0004",
	hud_icon = "",
	information_text = "five_career_bundle_0004",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 2800,
	product_layout = "five_career_bundle_0004",
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 824,
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_five_career_bundle_0004",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_five_career_bundle_0004",
	subtitle = "five_career_bundle_0001_subtitle",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
