-- chunkname: @scripts/settings/equipment/item_master_list_cosmetics_2022_q3.lua

ItemMasterList.unchained_hat_1004 = {
	description = "description_unchained_hat_1004",
	display_name = "display_name_unchained_hat_1004",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_unchained_hat_1004",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 159,
	template = "bw_face",
	unit = "units/beings/player/bright_wizard_unchained/headpiece/bw_u_hat_14",
	can_wield = {
		"bw_unchained",
	},
}
ItemMasterList.ranger_hat_1006 = {
	description = "description_ranger_hat_1006",
	display_name = "display_name_ranger_hat_1006",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_ranger_hat_1006",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 161,
	template = "dr_helmets_hide_head_beard",
	unit = "units/beings/player/dwarf_ranger_upgraded/headpiece/dr_u_hat_15",
	can_wield = {
		"dr_ranger",
	},
}
ItemMasterList.knight_hat_1002 = {
	description = "description_knight_hat_1002",
	display_name = "display_name_knight_hat_1002",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_knight_hat_1002",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 165,
	template = "es_hats_no_ear_moustache",
	unit = "units/beings/player/empire_soldier_knight/headpiece/es_k_hat_13",
	can_wield = {
		"es_knight",
	},
}
ItemMasterList.shade_hat_1003 = {
	description = "description_shade_hat_1003",
	display_name = "display_name_shade_hat_1003",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_shade_hat_1003",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 167,
	template = "ww_hat_no_hood",
	unit = "units/beings/player/way_watcher_shade/headpiece/ww_s_hat_14",
	can_wield = {
		"we_shade",
	},
}
ItemMasterList.bountyhunter_hat_1005 = {
	description = "description_bountyhunter_hat_1005",
	display_name = "display_name_bountyhunter_hat_1005",
	hud_icon = "hud_icon_default",
	information_text = "information_text_hat",
	inventory_icon = "icon_bountyhunter_hat_1005",
	item_type = "hat",
	rarity = "promo",
	slot_type = "hat",
	steam_itemdefid = 163,
	template = "wh_hats",
	unit = "units/beings/player/witch_hunter_bounty_hunter/headpiece/wh_bh_hat_15",
	can_wield = {
		"wh_bountyhunter",
	},
}
ItemMasterList.skin_bw_unchained_1002 = {
	description = "description_skin_bw_unchained_1002",
	display_name = "display_name_skin_bw_unchained_1002",
	hud_icon = "unit_frame_portrait_bright_wizard",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_bw_unchained_1002",
	item_preview_environment = "unchained_skins_01",
	item_type = "skin",
	name = "skin_bw_unchained_1002",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 160,
	store_optional_hat = "unchained_hat_1004",
	temporary_template = "skin_bw_unchained_1002",
	can_wield = {
		"bw_unchained",
	},
}
ItemMasterList.skin_dr_ranger_1002 = {
	description = "description_skin_dr_ranger_1002",
	display_name = "display_name_skin_dr_ranger_1002",
	hud_icon = "career_dwarf_ranger",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_dr_ranger_1002",
	item_type = "skin",
	name = "skin_dr_ranger_1002",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 162,
	store_optional_hat = "ranger_hat_1006",
	temporary_template = "skin_dr_ranger_1002",
	can_wield = {
		"dr_ranger",
	},
}
ItemMasterList.skin_es_knight_1002 = {
	description = "description_skin_es_knight_1002",
	display_name = "display_name_skin_es_knight_1002",
	hud_icon = "unit_frame_portrait_empire_soldier",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_es_knight_1002",
	item_type = "skin",
	name = "skin_es_knight_1002",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 166,
	store_optional_hat = "knight_hat_1002",
	temporary_template = "skin_es_knight_1002",
	can_wield = {
		"es_knight",
	},
}
ItemMasterList.skin_ww_shade_1002 = {
	description = "description_skin_ww_shade_1002",
	display_name = "display_name_skin_ww_shade_1002",
	hud_icon = "unit_frame_portrait_way_watcher",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_ww_shade_1002",
	item_type = "skin",
	name = "skin_ww_shade_1002",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 168,
	store_optional_hat = "shade_hat_1003",
	temporary_template = "skin_ww_shade_1002",
	can_wield = {
		"we_shade",
	},
}
ItemMasterList.skin_wh_bountyhunter_1002 = {
	description = "description_skin_wh_bountyhunter_1002",
	display_name = "display_name_skin_wh_bountyhunter_1002",
	hud_icon = "unit_frame_portrait_witch_hunter",
	information_text = "information_text_character_skin",
	inventory_icon = "icon_skin_wh_bountyhunter_1002",
	item_type = "skin",
	name = "skin_wh_bountyhunter_1002",
	rarity = "promo",
	skin_type = "unit",
	slot_type = "skin",
	steam_itemdefid = 164,
	store_optional_hat = "bountyhunter_hat_1005",
	temporary_template = "skin_wh_bountyhunter_1002",
	can_wield = {
		"wh_bountyhunter",
	},
}
ItemMasterList.ranger_bundle_0002 = {
	description = "description_ranger_bundle_0002",
	discount = 99,
	display_name = "display_name_ranger_bundle_0002",
	hud_icon = "",
	information_text = "description_ranger_bundle_0002",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 2900,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 826,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_ranger_bundle_0002",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_ranger_bundle_0002",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_ranger_bundle_0002",
	subtitle = "dr_ranger",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.shade_bundle_0002 = {
	description = "description_shade_bundle_0002",
	discount = 99,
	display_name = "display_name_shade_bundle_0002",
	hud_icon = "",
	information_text = "description_shade_bundle_0002",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 3000,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 829,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_shade_bundle_0002",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_shade_bundle_0002",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_shade_bundle_0002",
	subtitle = "we_shade",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.knight_bundle_0002 = {
	description = "description_knight_bundle_0002",
	discount = 99,
	display_name = "display_name_knight_bundle_0002",
	hud_icon = "",
	information_text = "description_knight_bundle_0002",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 3100,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 828,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_knight_bundle_0002",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_knight_bundle_0002",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_knight_bundle_0002",
	subtitle = "es_knight",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.unchained_bundle_0002 = {
	description = "description_unchained_bundle_0002",
	discount = 99,
	display_name = "display_name_unchained_bundle_0002",
	hud_icon = "",
	information_text = "description_unchained_bundle_0002",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 3200,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 825,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_unchained_bundle_0002",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_unchained_bundle_0002",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_unchained_bundle_0002",
	subtitle = "bw_unchained",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.bountyhunter_bundle_0002 = {
	description = "description_bountyhunter_bundle_0002",
	discount = 99,
	display_name = "display_name_bountyhunter_bundle_0002",
	hud_icon = "",
	information_text = "description_bountyhunter_bundle_0002",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 3300,
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 827,
	store_bundle_big_image = "gui/1080p/single_textures/store/slideshow/store_slideshow_bundle_bountyhunter_bundle_0002",
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_bountyhunter_bundle_0002",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_bountyhunter_bundle_0002",
	subtitle = "wh_bountyhunter",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
ItemMasterList.five_career_bundle_0005 = {
	description = "description_five_career_bundle_0005",
	display_name = "display_name_five_career_bundle_0005",
	hud_icon = "",
	information_text = "five_career_bundle_0005",
	inventory_icon = "",
	item_type = "bundle",
	optional_item_name = true,
	prio = 3400,
	product_layout = "five_career_bundle_0005",
	rarity = "promo",
	show_old_price = true,
	slot_type = "bundle",
	steam_itemdefid = 830,
	store_texture = "gui/1080p/single_textures/store_bundle/store_item_icon_five_career_bundle_0005",
	store_texture_package = "resource_packages/store/bundle_icons/store_item_icon_five_career_bundle_0005",
	subtitle = "five_career_bundle_0001_subtitle",
	template = "",
	unit = "",
	can_wield = {},
	bundle_contains = {},
}
