-- chunkname: @scripts/settings/equipment/light_weight_projectiles.lua

LightWeightProjectiles = {}
LightWeightProjectiles.ratling_gunner = {
	damage_profile = "ratling_gunner",
	hit_effect = "ratling_gunner",
	impact_push_speed = 1.5,
	light_weight_projectile_effect = "ratling_gun_bullet",
	projectile_max_range = 50,
	projectile_speed = 80,
	spread = math.degrees_to_radians(7),
	attack_power_level = {
		20,
		40,
		120,
		200,
		250,
		250,
		250,
		250,
		40,
	},
}
LightWeightProjectiles.ratling_gunner_vs = {
	damage_profile = "ratling_gunner_vs",
	hit_effect = "ratling_gunner",
	impact_push_speed = 1.3,
	light_weight_projectile_effect = "ratling_gun_bullet_vs",
	projectile_max_range = 50,
	projectile_speed = 80,
	spread = math.degrees_to_radians(1.2),
	attack_power_level = {
		13,
		26,
		90,
		130,
		160,
		160,
		160,
		160,
		40,
	},
}
LightWeightProjectiles.stormfiend_boss = {
	damage_profile = "stormfiend_boss",
	hit_effect = "ratling_gunner",
	impact_push_speed = 3,
	light_weight_projectile_effect = "stormfiend_gun_bullet",
	projectile_max_range = 50,
	projectile_speed = 80,
	spread = math.degrees_to_radians(4.5),
	attack_power_level = {
		20,
		40,
		60,
		80,
		120,
		120,
		120,
		120,
		40,
	},
}
LightWeightProjectiles.stormfiend_boss_narrow = {
	damage_profile = "stormfiend_boss_narrow",
	hit_effect = "ratling_gunner",
	impact_push_speed = 2.5,
	light_weight_projectile_effect = "stormfiend_gun_bullet",
	projectile_max_range = 50,
	projectile_speed = 80,
	spread = math.degrees_to_radians(4),
	attack_power_level = {
		40,
		80,
		120,
		160,
		180,
		180,
		180,
		180,
	},
}
LightWeightProjectiles.stormfiend_boss_dual_intro = {
	damage_profile = "stormfiend_boss_dual_intro",
	hit_effect = "ratling_gunner",
	impact_push_speed = 2.5,
	light_weight_projectile_effect = "stormfiend_gun_bullet",
	projectile_max_range = 50,
	projectile_speed = 80,
	spread = math.degrees_to_radians(4),
	attack_power_level = {
		40,
		80,
		120,
		160,
		180,
		180,
		180,
		180,
	},
}
LightWeightProjectiles.ratling_gunner_backdrop = {
	damage_profile = "ratling_gunner_backdrop",
	hit_effect = "autocannon",
	impact_push_speed = 2.5,
	light_weight_projectile_effect = "autocannon_backdrop_bullet",
	projectile_max_range = 500,
	projectile_speed = 80,
	spread = math.degrees_to_radians(2.5),
	attack_power_level = {
		200,
		300,
		450,
		600,
		650,
		650,
		650,
		650,
	},
}

DLCUtils.merge("light_weight_projectiles", LightWeightProjectiles)
