-- chunkname: @scripts/settings/dlcs/geheimnisnacht_2021/item_master_list_geheimnisnacht_2021.lua

ItemMasterList.wpn_geheimnisnacht_2021_side_objective = {
	description = "description_wpn_chaos_artifact",
	gamepad_hud_icon = "hud_icon_geheimnisnacht_2021",
	hud_icon = "hud_inventory_icon_geheimnisnacht_2021",
	inventory_icon = "icons_placeholder",
	is_local = true,
	is_not_droppable = true,
	item_type = "potion",
	left_hand_unit = "units/weapons/player/pup_ritual_site_01/wpn_ritual_site_01",
	rarity = "plentiful",
	slot_type = "potion",
	temporary_template = "wpn_geheimnisnacht_2021_side_objective",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.es_2h_sword_skin_02_runed_03 = {
	description = "es_2h_sword_skin_02_runed_03_description",
	display_name = "es_2h_sword_skin_02_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_2h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_2h_sword_01_t2_runed_03",
	item_type = "weapon_skin",
	matching_item_key = "es_2h_sword",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_empire_2h_sword_01_t2/wpn_2h_sword_01_t2_runed_01",
	slot_type = "weapon_skin",
	template = "two_handed_swords_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.dw_2h_axe_skin_05_runed_03 = {
	description = "dw_2h_axe_skin_05_runed_03_description",
	display_name = "dw_2h_axe_skin_05_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_2h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_2h_axe_03_t1_runed_03",
	item_type = "weapon_skin",
	matching_item_key = "dr_2h_axe",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_dw_2h_axe_03_t1/wpn_dw_2h_axe_03_t1_runed_01",
	slot_type = "weapon_skin",
	template = "two_handed_axes_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_slayer",
		"dr_ranger",
	},
}
ItemMasterList.bw_dagger_skin_04_runed_03 = {
	description = "bw_dagger_skin_04_runed_03_description",
	display_name = "bw_dagger_skin_04_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_1h_weapon",
	hud_icon = "weapon_generic_icon_daggers",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_brw_dagger_04_runed_03",
	item_type = "weapon_skin",
	matching_item_key = "bw_dagger",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_brw_dagger_04/wpn_brw_dagger_04_runed_01",
	slot_type = "weapon_skin",
	template = "one_handed_daggers_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.we_2h_axe_skin_07_runed_03 = {
	description = "we_2h_axe_skin_07_runed_03_description",
	display_name = "we_2h_axe_skin_07_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_2h_weapon",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_2h_axe_04_t1_runed_03",
	item_type = "weapon_skin",
	matching_item_key = "we_2h_axe",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_we_2h_axe_04_t1/wpn_we_2h_axe_04_t1_runed_01",
	slot_type = "weapon_skin",
	template = "two_handed_axes_template_2",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.es_1h_flail_skin_02_runed_03 = {
	description = "es_1h_flail_skin_02_runed_03_description",
	display_name = "es_1h_flail_skin_02_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_1h_weapon",
	hud_icon = "weapon_generic_icon_mace",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_flail_02_t1_runed_03",
	item_type = "weapon_skin",
	matching_item_key = "es_1h_flail",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_emp_flail_02_t1/wpn_emp_flail_02_t1_runed_01",
	slot_type = "weapon_skin",
	template = "one_handed_flail_template_1",
	can_wield = {
		"wh_zealot",
		"wh_captain",
		"wh_bountyhunter",
	},
}
ItemMasterList.frame_0105 = {
	description = "frame_0105_description",
	display_name = "frame_0105_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_0105",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_0105",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_0106 = {
	description = "frame_0106_description",
	display_name = "frame_0106_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_0106",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_0106",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.dw_1h_axe_shield_skin_05_runed_03 = {
	description = "dw_1h_axe_shield_skin_05_runed_03_description",
	display_name = "dw_1h_axe_shield_skin_05_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_shield",
	event_quest_requirement = "event_geheimnisnacht_2022_disrupt_bardin",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_1h_axe_shield_skin_05_runed_03",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_dw_shield_05_t1/wpn_dw_shield_05_runed_01",
	matching_item_key = "dr_shield_axe",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_dw_axe_03_t2/wpn_dw_axe_03_t2_runed_01",
	slot_type = "weapon_skin",
	template = "one_hand_axe_shield_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
}
ItemMasterList.bw_1h_flaming_sword_skin_01_runed_03 = {
	description = "bw_1h_flaming_sword_skin_01_runed_03_description",
	display_name = "bw_1h_flaming_sword_skin_01_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_1h_weapon",
	event_quest_requirement = "event_geheimnisnacht_2022_disrupt_sienna",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_brw_flaming_sword_01_t1_runed_01",
	item_type = "weapon_skin",
	matching_item_key = "bw_flame_sword",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_brw_sword_01_t1/wpn_brw_flaming_sword_01_t1_runed_01",
	slot_type = "weapon_skin",
	template = "flaming_sword_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.we_dual_sword_dagger_skin_02_runed_03 = {
	description = "we_dual_sword_dagger_skin_02_runed_03_description",
	display_name = "we_dual_sword_dagger_skin_02_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_dual_weapons",
	event_quest_requirement = "event_geheimnisnacht_2022_disrupt_kerillian",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_sword_01_t2_dagger_dual_runed_01",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_dagger_01_t2/wpn_we_dagger_01_t2_runed_01",
	matching_item_key = "we_dual_wield_sword_dagger",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_we_sword_01_t2/wpn_we_sword_01_t2_runed_01",
	slot_type = "weapon_skin",
	template = "dual_wield_sword_dagger_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.wh_fencing_sword_skin_01_runed_03 = {
	description = "wh_fencing_sword_skin_01_runed_03_description",
	display_name = "wh_fencing_sword_skin_01_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_1h_weapon",
	event_quest_requirement = "event_geheimnisnacht_2022_disrupt_victor",
	hud_icon = "weapon_generic_icon_fencing_sword",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_fencingsword_01_t1_runed_01",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_emp_pistol_02_t2/wpn_emp_pistol_02_t2_runed_01",
	matching_item_key = "wh_fencing_sword",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_fencingsword_01_t1/wpn_fencingsword_01_t1_runed_01",
	slot_type = "weapon_skin",
	template = "fencing_sword_template_1",
	can_wield = {
		"wh_bountyhunter",
		"wh_captain",
		"wh_zealot",
	},
}
ItemMasterList.es_1h_sword_shield_skin_03_runed_03 = {
	description = "es_1h_sword_shield_skin_03_runed_03_description",
	display_name = "es_1h_sword_shield_skin_03_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_shield",
	event_quest_requirement = "event_geheimnisnacht_2022_disrupt_markus,",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_empire_shield_03_sword_runed_01",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_empire_shield_03/wpn_emp_shield_03_runed_01",
	matching_item_key = "es_sword_shield",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_emp_sword_02_t2/wpn_emp_sword_02_t2_runed_01",
	slot_type = "weapon_skin",
	template = "one_handed_sword_shield_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.we_longbow_skin_06_runed_03 = {
	description = "we_longbow_skin_06_runed_03_description",
	display_name = "we_longbow_skin_06_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_bow",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_we_bow_03_t2_runed_03",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_we_bow_03_t2/wpn_we_bow_03_t2_runed_01",
	matching_item_key = "we_longbow",
	rarity = "unique",
	slot_type = "weapon_skin",
	template = "longbow_template_1",
	can_wield = {
		"we_shade",
		"we_maidenguard",
		"we_waywatcher",
	},
}
ItemMasterList.wh_crossbow_skin_04_runed_03 = {
	description = "wh_crossbow_skin_04_runed_03_description",
	display_name = "wh_crossbow_skin_04_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_rifle",
	hud_icon = "weapon_generic_icon_crossbow",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_crossbow_03_t2_runed_03",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_emp_crossbow_03_t2/wpn_emp_crossbow_03_t2_runed_01",
	matching_item_key = "wh_crossbow",
	rarity = "unique",
	slot_type = "weapon_skin",
	template = "crossbow_template_1",
	can_wield = {
		"wh_zealot",
		"wh_bountyhunter",
		"wh_captain",
	},
}
ItemMasterList.bw_spear_staff_skin_04_runed_03 = {
	description = "bw_spear_staff_skin_04_runed_03_description",
	display_name = "bw_spear_staff_skin_04_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_staff",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_brw_spear_staff_04_runed_03",
	item_type = "weapon_skin",
	left_hand_unit = "units/weapons/player/wpn_fireball/wpn_fireball",
	matching_item_key = "bw_skullstaff_spear",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_brw_spear_staff_04/wpn_brw_spear_staff_04_runed_01",
	slot_type = "weapon_skin",
	template = "staff_spark_spear_template_1",
	can_wield = {
		"bw_scholar",
		"bw_adept",
		"bw_unchained",
	},
}
ItemMasterList.dw_handgun_skin_02_runed_03 = {
	description = "dw_handgun_skin_02_runed_03_description",
	display_name = "dw_handgun_skin_02_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_rifle",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_dw_handgun_01_t2_runed_03",
	item_type = "weapon_skin",
	matching_item_key = "dr_handgun",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_dw_handgun_01_t2/wpn_dw_handgun_01_t2_runed_01",
	slot_type = "weapon_skin",
	template = "handgun_template_1",
	can_wield = {
		"dr_ironbreaker",
		"dr_ranger",
	},
}
ItemMasterList.es_repeating_handgun_skin_02_runed_03 = {
	description = "es_repeating_handgun_skin_02_runed_03_description",
	display_name = "es_repeating_handgun_skin_02_runed_03_name",
	display_unit = "units/weapons/weapon_display/display_rifle",
	hud_icon = "weapon_generic_icon_staff_3",
	information_text = "information_weapon_skin",
	inventory_icon = "icon_wpn_emp_handgun_repeater_t2_runed_03",
	item_type = "weapon_skin",
	matching_item_key = "es_repeating_handgun",
	rarity = "unique",
	right_hand_unit = "units/weapons/player/wpn_emp_handgun_repeater_t2/wpn_emp_handgun_repeater_t2_runed_01",
	slot_type = "weapon_skin",
	template = "repeating_handgun_template_1",
	can_wield = {
		"es_huntsman",
		"es_knight",
		"es_mercenary",
	},
}
ItemMasterList.frame_geheimnisnacht_04 = {
	description = "frame_0112_description",
	display_name = "frame_0112_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_geheimnisnacht_04",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_geheimnisnacht_04",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_geheimnisnacht_05 = {
	description = "frame_0113_description",
	display_name = "frame_0113_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_geheimnisnacht_05",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_geheimnisnacht_05",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_0110 = {
	description = "frame_0110_description",
	display_name = "frame_0110_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_0110",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_0110",
	can_wield = CanWieldAllItemTemplates,
}
ItemMasterList.frame_0111 = {
	description = "frame_0111_description",
	display_name = "frame_0111_name",
	hud_icon = "unit_frame_02",
	information_text = "information_text_frame",
	inventory_icon = "icon_portrait_frame_0111",
	item_type = "frame",
	rarity = "promo",
	slot_type = "frame",
	temporary_template = "frame_0111",
	can_wield = CanWieldAllItemTemplates,
}
